add AI4Chem example IFM(nips2023)
PaddlePaddle/PaddleScience pull request #1002
Opened 2024-10-10 08:16 UTC by huhaohao525

### PR types

New features

### PR changes

Others : Add new AI4Chem example.

### Describe

Add new AI4Chem example including code and docs.

2024-10-10 08:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleScience?pullRequest=1002) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleScience?pullRequest=1002) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleScience?pullRequest=1002) it.</sub>

2024-10-10 09:32 UTC, HydrogenSulfate requested changes
感谢提交PR，有一些修改建议如下

2024-10-10 09:32 UTC, HydrogenSulfate commented on examples/ifm/ifm.py
> +
删除这两行，固定种子和创建logger，在yaml设置了default字段之后会自动完成

2024-10-10 09:32 UTC, HydrogenSulfate commented on examples/ifm/ifm.py
> +    print(f"inputs is: {inputs}, iters_per_epoch: {iters_per_epoch}")
print建议改为logger.info

2024-10-10 09:32 UTC, HydrogenSulfate commented on examples/ifm/ifm.py
> +        inputs=inputs,
inputs作为参数名不太合适，是否可以改成更符合语义的，比如num_inputs?

2024-10-10 09:32 UTC, HydrogenSulfate commented on examples/ifm/ifm.py
> +        outputs=len(tasks),
同理，是否能改为num_outputs或者其他符合语义的变量名

2024-10-10 09:32 UTC, HydrogenSulfate commented on examples/ifm/conf/ifm.yaml
> +
这几行是否可以删除？

2024-10-10 09:32 UTC, HydrogenSulfate commented on examples/ifm/conf/ifm.yaml
> +    'hidden_unit3': 512 #3
hidden_unit1~3是否可以合并成：hidden_units: [512, 512, 512]？

2024-10-10 09:32 UTC, HydrogenSulfate commented on examples/ifm/conf/ifm.yaml
> +
可以将HYPER_OPT的参数通过引用语法`${...}`写到`MODEL`字段下，这样不用在python代码中进行处理，参考：<https://github.com/PaddlePaddle/PaddleScience/blob/83f67393d8aeef613d7e4da39ee7f76825c124da/examples/allen_cahn/conf/allen_cahn_piratenet.yaml#L51-L60>

2024-10-10 09:32 UTC, HydrogenSulfate commented on examples/ifm/ifm.py
> +    )
这里建议通过yaml里的引用语法简化一下
```suggestion
    hyper_paras = cfg.HYPER_OPT[cfg.data_label]

    hidden_units = [
        hyper_paras["hidden_unit1"],
        hyper_paras["hidden_unit2"],
        hyper_paras["hidden_unit3"],
    ]
    # set model
    model = ppsci.arch.IFMMLP(
        # **cfg.MODEL,
        input_keys=("x",),
        output_keys=("pred",),
        hidden_units=hidden_units,
        embed_name=cfg.MODEL.embed_name,
        inputs=inputs,
        outputs=len(tasks),
        d_out=hyper_paras["d_out"],
        sigma=hyper_paras["sigma"],
        dp_ratio=hyper_paras["dropout"],
        reg=reg,
        first_omega_0=hyper_paras["omega0"],
        hidden_omega_0=hyper_paras["omega1"],
    )
```

2024-10-10 09:32 UTC, HydrogenSulfate commented on examples/ifm/ifm.py
> +        seed=cfg.seed,
seed设置这行可以删除

2024-10-24 02:57 UTC, HydrogenSulfate commented on ppsci/arch/ifm_mlp.py
> +    reg (bool): Regularization flag.
参数相比Args，要增加四个空格的缩进

2024-10-24 02:57 UTC, HydrogenSulfate commented on examples/ifm/ednn_utils.py
> +
examples/ifm/ednn_utils.py里的init_parameter_uniform函数是不是可以删除？

2024-12-27 11:17 UTC, leeleolay commented
<img width="776" alt="image" src="https://github.com/user-attachments/assets/572f043d-94be-439d-8be5-6c1c6d1bbc5b" />
这里测试有报错，辛苦确认一下

2024-12-30 01:35 UTC, huhaohao525 commented
@leeleolay 已添加pgl依赖

2025-01-15 09:02 UTC, HydrogenSulfate approved these changes
LGTM

2025-01-15 09:20 UTC, merged