Paddle 适配 deepali
PaddlePaddle/PaddleScience pull request #1006
Opened 2024-10-29 01:01 UTC by co63oc

### PR types

Others 
### PR changes

Others 
### Describe

Paddle 适配 deepali
RFC https://github.com/PaddlePaddle/community/pull/978

torch中单测为89个，修改后paddle单测数量85个，3个单测使用torch_function paddle没有对应实现, 1个单测使用 torchinfo取消测试
torch单测运行
![image](https://github.com/user-attachments/assets/e63f5583-bb4d-4335-9ab2-37813f7b634e)

paddle单测运行
![image](https://github.com/user-attachments/assets/52aaaaf2-b488-4174-91fc-9a95335761e9)

2024-10-29 06:49 UTC, HydrogenSulfate requested changes
感谢提交PR，代码和docstring中有少量pytorch的部分，还请更改成paddle，有不支持的实现可以raise NotImplementedError即可
![image](https://github.com/user-attachments/assets/7aa24cd9-bf2b-4208-ae4c-711355ddc211)
![image](https://github.com/user-attachments/assets/36f38632-fc76-4984-9de7-46a92ce2814f)

2024-10-29 06:49 UTC, HydrogenSulfate commented on jointContribution/deepali/src/deepali/networks/resnet.py
> +                )
paddlenlp是一个非常大的包，只是这里一处初始化而引入paddlenlp是没有必要的，建议改为`ppsci.utils.initializer.kaiming_normal_`

2024-10-29 07:41 UTC, co63oc commented
> 感谢提交PR，代码和docstring中有少量pytorch的部分，还请更改成paddle，有不支持的实现可以raise NotImplementedError即可 
已修改

2024-10-29 07:41 UTC, co63oc commented on jointContribution/deepali/src/deepali/networks/resnet.py
> +                )
已修改

2024-10-29 07:57 UTC, HydrogenSulfate commented
> > 感谢提交PR，代码和docstring中有少量pytorch的部分，还请更改成paddle，有不支持的实现可以raise NotImplementedError即可
> > 已修改

好的辛苦，我们内部先测试一下

2024-10-29 08:15 UTC, HydrogenSulfate commented on jointContribution/deepali/src/deepali/utils/simpleitk/torch.py
这个文件是否可以改名叫paddle.py?

2024-10-29 08:15 UTC, HydrogenSulfate commented on jointContribution/deepali/src/deepali/losses/base.py
> +    the main loop which performs individual gradient steps using an instance of ``torch.optim.Optimizer``.
看起来还有一些pytorch的内容，可以再检查一下

2024-10-29 08:29 UTC, co63oc commented on jointContribution/deepali/src/deepali/utils/simpleitk/torch.py
已修改

2024-10-29 08:29 UTC, co63oc commented on jointContribution/deepali/src/deepali/losses/base.py
> +    the main loop which performs individual gradient steps using an instance of ``torch.optim.Optimizer``.
已修改

2024-10-30 06:00 UTC, HydrogenSulfate commented
![image](https://github.com/user-attachments/assets/d831feda-9cd7-4336-83be-9fe68ec8e938)
paddle目前的规则是不会在整型和浮点数之间做类型提升，所以还麻烦在所有相关的代码中，把所有可能是int64类型的Tensor手动astype到另一个对象的dtype上

2024-10-30 07:20 UTC, co63oc commented
>  paddle目前的规则是不会在整型和浮点数之间做类型提升，所以还麻烦在所有相关的代码中，把所有可能是int64类型的Tensor手动astype到另一个对象的dtype上 

测试develop版本可以
```
import paddle
spacing=paddle.ones([1,2]).astype(paddle.float32)
ret = spacing.less_equal(y=paddle.to_tensor(0)).astype("bool").any()
print(ret)
```
![image](https://github.com/user-attachments/assets/838c7b2a-7ff7-4ee1-93b3-7a4215d0bbd0)

2024-10-30 09:42 UTC, HydrogenSulfate commented
> > paddle目前的规则是不会在整型和浮点数之间做类型提升，所以还麻烦在所有相关的代码中，把所有可能是int64类型的Tensor手动astype到另一个对象的dtype上
> 
> 测试develop版本可以，只是提示信息
> 
> ```
> import paddle
> spacing=paddle.ones([1,2]).astype(paddle.float32)
> ret = spacing.less_equal(y=paddle.to_tensor(0)).astype("bool").any()
> print(ret)
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/4617245/381433862-838c7b2a-7ff7-4ee1-93b3-7a4215d0bbd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyODE1OTcsIm5iZiI6MTczMDI4MTI5NywicGF0aCI6Ii80NjE3MjQ1LzM4MTQzMzg2Mi04MzhjN2IyYS03ZmY3LTRlZTEtOTNiMy03YTQyMTVkMGJiZDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMzBUMDk0MTM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjVkZWQ0NjczZDgzZjIyYTAyY2NmMGQ4ODU0ZjlmZTRmMTY5ZDQwY2M1MzQ4NWU2YmFlZTQ5OWE0MWM2OWRmZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.w2BoDqO1LeuukFNC8k50Z-B-RxEArv4M2ugKfridI5k)
> 
> 文档说明是到2.6版本 ![image](https://private-user-images.githubusercontent.com/4617245/381434601-6cb20511-6cf4-455a-b993-f8f9d7541c50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyODE1OTcsIm5iZiI6MTczMDI4MTI5NywicGF0aCI6Ii80NjE3MjQ1LzM4MTQzNDYwMS02Y2IyMDUxMS02Y2Y0LTQ1NWEtYjk5My1mOGY5ZDc1NDFjNTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMzBUMDk0MTM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzQ2NzFhMWI0ZjcxMDJhYmJlYjk0OGM5NDA0MWVhOTkwMjdhZDcxNGJlM2IzOTQwNjlkZDFmY2Q1ZjcwZThiMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ._18KGYY7LA2BMq1kYekpNKAa14GJugG2ip7Yrh_2wf0)
> 
> develop版本安装是用的命令
> 
> ```
> python -m pip install --pre paddlepaddle-gpu -i https://www.paddlepaddle.org.cn/packages/nightly/cu118/
> ```
> 
> 其他地方有碰到类似问题，可能文档没有更新，测试有部分支持，也有部分不支持，但是不确定是哪部分不支持，需要按测试结果修改

好的，在develop上测试确实已经没有类型的问题，但是还有两个data_ptr的问题可以看一下：
![image](https://github.com/user-attachments/assets/367fe49b-5d4b-47be-8306-f9728cf3c9e3)

2024-10-30 09:50 UTC, lijialin03 reviewed
辛苦提交代码，我们在运行单测的时候遇到一点奇怪的报错，麻烦可以提供一下单测运行时的软件包版本吗，pip list之类的，谢谢

2024-10-30 11:57 UTC, lijialin03 commented on jointContribution/deepali/src/deepali/data/image.py
> +            size = tuple(grids[0].shape)
比如这几行，参考原代码都是.size()

2024-10-30 12:21 UTC, lijialin03 commented on jointContribution/deepali/src/deepali/core/affine.py
> +    matrix[..., J, J] = scales_
这里无法直接赋值，需要改成
```
for j in J:
        matrix[..., j, j] = scales_[..., j]
```

2024-10-30 12:21 UTC, lijialin03 commented on jointContribution/deepali/src/deepali/core/affine.py
> +    matrix[..., K[0], K[1]] = paddle.tan(x=angles_)
同上，需要改成
```
for j in J:
        matrix[..., j, j] = 1
    tan_values = paddle.tan(x=angles_)
    for i in range(len(K[0])):
        matrix[..., K[0][i], K[1][i]] = tan_values[..., i]
```

2024-10-30 12:21 UTC, lijialin03 commented on jointContribution/deepali/src/deepali/losses/functional.py
> +        loss = loss.mul(mask)
需要做强制转换，如loss = loss.mul(mask.astype(loss.dtype))

2024-10-30 22:36 UTC, co63oc commented on jointContribution/deepali/src/deepali/spatial/parametric.py
> +        return isinstance(self.params, paddle.base.framework.EagerParamBase.from_tensor)
from_tensor已有，关联PR https://github.com/PaddlePaddle/Paddle/pull/60316/
![image](https://github.com/user-attachments/assets/b6da2563-f716-4f9f-a441-9be506bd430f)

2024-10-30 22:37 UTC, co63oc commented
> 辛苦提交代码，我们在运行单测的时候遇到一点奇怪的报错，麻烦可以提供一下单测运行时的软件包版本吗，pip list之类的，谢谢
pip list
[pip.txt](https://github.com/user-attachments/files/17579781/pip.txt)

2024-10-30 22:44 UTC, co63oc commented on jointContribution/deepali/src/deepali/spatial/bspline.py
> +            new_size = tuple(grid.shape)
![image](https://github.com/user-attachments/assets/54264cb0-b6f9-4713-b039-44c274564792)
是有这问题，但是这里代码是比较两种size，两处都有转化，所以逻辑没有影响

2024-10-30 23:15 UTC, co63oc commented on jointContribution/deepali/src/deepali/core/affine.py
> +    matrix[..., J, J] = scales_
测试没有出现错误，有没有测试的代码发下

2024-10-30 23:15 UTC, co63oc commented on jointContribution/deepali/src/deepali/core/affine.py
> +    matrix[..., K[0], K[1]] = paddle.tan(x=angles_)
测试没有出现错误，有没有测试的代码发下

2024-10-30 23:15 UTC, co63oc commented on jointContribution/deepali/src/deepali/losses/functional.py
> +        loss = loss.mul(mask)
测试没有出现错误，有没有测试的代码发下

2024-10-30 23:19 UTC, co63oc commented
> 
> 好的，在develop上测试确实已经没有类型的问题，但是还有两个data_ptr的问题可以看一下

本地测试没有错误，这里的逻辑是用cpu分配tensor，然后使用不同的cuda设备，验证是否新建数据，截图的结果是没有新建数据，暂时不确定是什么问题

2024-10-30 23:19 UTC, co63oc commented on jointContribution/deepali/src/deepali/data/image.py
> +    def _torch_function_grid(
已修改

2024-10-30 23:20 UTC, co63oc commented on jointContribution/deepali/src/deepali/data/image.py
> +            size = tuple(grids[0].shape)
已修改，暂时没有单测测试

2024-10-31 00:13 UTC, co63oc commented on jointContribution/deepali/src/deepali/data/image.py
> +            size = tuple(grids[0].shape)
size问题已在原代码中用 grep -Inr '\.size()' src/ tests/ 搜索对比修改

2024-10-31 00:16 UTC, co63oc commented on jointContribution/deepali/src/deepali/spatial/bspline.py
> +            new_size = tuple(grid.shape)
size问题已在原代码中用 grep -Inr '.size()' src/ tests/ 搜索对比修改

2024-10-31 06:13 UTC, lijialin03 commented on jointContribution/deepali/src/deepali/spatial/parametric.py
> +        return isinstance(self.params, paddle.base.framework.EagerParamBase.from_tensor)
这边判断参数的type，对应torch中的Parameter，为paddle.create_parameter的type，应该是
![image](https://github.com/user-attachments/assets/3382b9aa-a908-4f47-a4e0-cdf022d248f8)

2024-10-31 06:15 UTC, lijialin03 commented on jointContribution/deepali/src/deepali/core/affine.py
> +    matrix[..., J, J] = scales_
是使用了这个PR的代码 https://github.com/PaddlePaddle/PaddleScience/pull/1004#event-14949548477 但是需要修改，我看看能不能写个最小复现代码

2024-10-31 07:24 UTC, lijialin03 commented on jointContribution/deepali/src/deepali/core/affine.py
> +    matrix[..., J, J] = scales_
```
scales_=paddle.to_tensor([[1., 1., 1.]],dtype=paddle.float32)
J = tuple(range(D))
D = tuple(scales_.shape)[-1]
matrix = paddle.zeros(
    shape=tuple(scales_.shape)[:-1] + (D, D), dtype=scales_.dtype
)
matrix[..., J, J] = scales_
```

2024-10-31 07:36 UTC, lijialin03 commented on jointContribution/deepali/src/deepali/losses/functional.py
> +        loss = loss.mul(mask)
```
mask=paddle.full(shape=[1, 1, 29, 35, 35],fill_value=False,dtype=bool)
loss=paddle.full(shape=[1, 3, 29, 35, 35],fill_value=1.0,dtype=paddle.float32)
paddle.multiply(loss,mask)
```
这边mask没有规定不能是bool类型，所以有可能出现不能自动类型转换的bug
![image](https://github.com/user-attachments/assets/cfdc17e6-8867-4b45-898f-c40c8b43561e)

2024-10-31 07:38 UTC, lijialin03 commented on jointContribution/deepali/src/deepali/core/affine.py
> +    matrix[..., K[0], K[1]] = paddle.tan(x=angles_)
问题原理同上，就不放代码了

2024-10-31 08:01 UTC, co63oc commented on jointContribution/deepali/src/deepali/spatial/parametric.py
> +        return isinstance(self.params, paddle.base.framework.EagerParamBase.from_tensor)
已修改

2024-10-31 08:01 UTC, co63oc commented on jointContribution/deepali/src/deepali/core/affine.py
> +    matrix[..., J, J] = scales_
已修改

2024-10-31 08:02 UTC, co63oc commented on jointContribution/deepali/src/deepali/core/affine.py
> +    matrix[..., J, J] = scales_
使用测试代码运行有Affine should be shape 4,4错误，尝试改用torch也有同样错误 
![image](https://github.com/user-attachments/assets/d896c9bb-3480-4708-a83e-9e9a1354e535)

2024-10-31 08:02 UTC, co63oc commented on jointContribution/deepali/src/deepali/core/affine.py
> +    matrix[..., K[0], K[1]] = paddle.tan(x=angles_)
已修改

2024-10-31 08:02 UTC, co63oc commented on jointContribution/deepali/src/deepali/losses/functional.py
> +        loss = loss.mul(mask)
已修改

2024-10-31 08:14 UTC, lijialin03 commented on jointContribution/deepali/src/deepali/core/affine.py
> +    matrix[..., J, J] = scales_
是的，实测在文件data/tensor.py中将def tensor的代码改为以下代码即可：
```
def tensor(self: T) -> paddle.Tensor:
        r"""Convert to plain paddle.Tensor."""
        return paddle.to_tensor(self, stop_gradient=False)
```

2024-10-31 08:25 UTC, lijialin03 commented on jointContribution/deepali/src/deepali/core/affine.py
> +    matrix[..., J, J] = scales_
好的，这个应该是deepali不支持保存这样的数据，不用管它了

2024-10-31 09:03 UTC, lijialin03 commented on jointContribution/deepali/src/deepali/core/affine.py
> +    matrix[..., J, J] = scales_
这个是由于使用nibabel.Nifti1Image保存，要求dataobj是3D或4D，而早期的deepali版本中使用SimpleITK而不是nibabel来保存，因此没有这个限制。因此不在这里进行更改，与原代码保持一致。

2024-10-31 09:10 UTC, co63oc commented on jointContribution/deepali/src/deepali/core/affine.py
> +    matrix[..., J, J] = scales_
好的

2024-11-01 11:16 UTC, lijialin03 reviewed
又看了一下发现代码中没有删除之前使用simpleitk来write的代码，因此稍作修改（下面以***** 开头的3个comment）后可以继续运行测试代码，发现还有一些问题，辛苦再修改一下～
在将问题全部修改后，简单看了一下在测试代码上运行的结果与测试代码本身的结果的均值和方法对比如下图，可以认为修改后的代码运行无误
![image](https://github.com/user-attachments/assets/7de933cc-46d1-4af4-b581-ff352c945eac)

2024-11-01 11:16 UTC, lijialin03 commented on jointContribution/deepali/src/deepali/data/image.py
> +        write_image(self.tensor(), self.grid(), path, compress=compress)
***** 暂时注释掉，改为老版写法：
```
def write(self: TImage, path: PathStr, compress: bool = True) -> None:
        """Write image data to file."""
        if sitk is None:
            raise RuntimeError(f"{type(self).__name__}.write() requires SimpleITK")
        image = self.sitk()
        path = unlink_or_mkdir(path)
        sitk.WriteImage(image, str(path), compress)
```

2024-11-01 11:16 UTC, lijialin03 commented on jointContribution/deepali/src/deepali/data/image.py
> +
***** import处添加(需要安装SimpleITK包)：
```
try:
    import SimpleITK as sitk
    from ..utils.simpleitk.imageio import read_image
    from ..utils.simpleitk.paddle import image_from_tensor
    from ..utils.simpleitk.paddle import tensor_from_image
except ImportError:
    sitk = None
from deepali.core.pathlib import unlink_or_mkdir
```

2024-11-01 13:03 UTC, co63oc commented on jointContribution/deepali/src/deepali/core/bspline.py
> +        temp[indices] = conv1d(output, kernel_1, dim=dim, padding=1)
done

2024-11-01 13:04 UTC, co63oc commented on jointContribution/deepali/src/deepali/data/image.py
> +        write_image(self.tensor(), self.grid(), path, compress=compress)
done

2024-11-01 13:05 UTC, co63oc commented on jointContribution/deepali/src/deepali/data/image.py
> +
测试read_image导入是
from deepali.utils.imageio import read_image

2024-11-01 13:06 UTC, co63oc commented
> 又看了一下发现代码中没有删除之前使用simpleitk来write的代码，因此稍作修改（下面以***** 开头的3个comment，提交代码时麻烦将老版的write和import部分代码保留但注释掉）后可以继续运行测试代码，发现还有一些问题，辛苦再修改一下～ 在将问题全部修改后，简单看了一下在测试代码上运行的结果与测试代码本身的结果的均值和方法对比如下图，可以认为修改后的代码运行无误 

已修改，没有提示错误，但是也没有日志输出，不确定什么问题

2024-11-04 02:23 UTC, lijialin03 commented on jointContribution/deepali/src/deepali/data/image.py
> +
好的，打log看这两个API在测试这个案例上好像结果没区别，不过deepali.utils.imageio里这个确实全很多，就这个吧，谢谢

2024-11-04 02:27 UTC, lijialin03 commented
> > 又看了一下发现代码中没有删除之前使用simpleitk来write的代码，因此稍作修改（下面以***** 开头的3个comment，提交代码时麻烦将老版的write和import部分代码保留但注释掉）后可以继续运行测试代码，发现还有一些问题，辛苦再修改一下～ 在将问题全部修改后，简单看了一下在测试代码上运行的结果与测试代码本身的结果的均值和方法对比如下图，可以认为修改后的代码运行无误
> 
> 已修改，没有提示错误，但是也没有日志输出，不确定什么问题

确实没有log，测试用的PR本身输出的是文件，log是手动添加的打印: )，测试过最新代码，结果同上面log截图

2024-11-04 02:27 UTC, lijialin03 approved these changes

2024-11-04 02:50 UTC, HydrogenSulfate submitted a review, later dismissed
LGTM，这个仓库能暂时先放到<https://atomgit.com/>上吗？后续我们看下github上放到哪里比较合适

2024-11-04 02:50 UTC, HydrogenSulfate commented on jointContribution/deepali/README.md
> +```
README 稍微改一下，然后文档末尾加一个简单的几行代码示例吧

```suggestion
# deepali(Paddle Backend)

> [!IMPORTANT]
> This branch(paddle) experimentally supports [Paddle backend](https://www.paddlepaddle.org.cn/en/install/quick?docurl=/documentation/docs/en/develop/install/pip/linux-pip_en.html)
> as almost all the core code has been completely rewritten using the Paddle API.
>
> It is recommended to install **nightly-build(develop)** Paddle before running any code in this branch.

Install:

``` shell
# paddlepaddle develop
python -m pip install --pre paddlepaddle-gpu -i https://www.paddlepaddle.org.cn/packages/nightly/cu118/

# setup config file is pyproject.toml
pip install .

# test
pytest tests/
```
```

2024-11-04 02:53 UTC, luotao1 commented
> 这个仓库能暂时先放到https://atomgit.com/上吗

@HydrogenSulfate 没地方放的话，可以考虑先放这里：https://github.com/PfCCLab

2024-11-04 04:02 UTC, co63oc commented on jointContribution/deepali/README.md
> +```
done

2024-11-04 04:02 UTC, co63oc commented
> LGTM，这个仓库能暂时先放到https://atomgit.com/上吗？后续我们看下github上放到哪里比较合适

已放到atomgit
https://atomgit.com/co63oc/deepali/

2024-11-04 05:02 UTC, HydrogenSulfate commented on jointContribution/deepali/README.md
> +    ).item()
```suggestion
assert paddle.allclose(
    x=kernel, y=B.cubic_bspline_interpolation_weights(5, derivative=0)
).item()
```

2024-11-04 22:42 UTC, co63oc commented
已放到 https://github.com/PFCCLab/deepali/ ，仓库为私有仓库

2024-11-06 09:53 UTC, closed without merging