AI4S-论文复现-CFDGCN
PaddlePaddle/PaddleScience pull request #211
Opened 2023-01-13 07:25 UTC by DrownFish19

### PR types
Others

### PR changes
Others

### Describe

#### AI4S-论文复现-CFDGCN

复现论文题目：Combining Differentiable PDE Solvers and Graph Neural Networks for Fluid Flow Prediction
AIStudio 地址：https://aistudio.baidu.com/aistudio/projectdetail/5216848

2023-01-13 07:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleScience?pullRequest=211) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleScience?pullRequest=211) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleScience?pullRequest=211) it.</sub>

2023-01-13 08:20 UTC, jkrescue approved these changes

2023-07-04 03:46 UTC, HydrogenSulfate requested changes

2023-07-04 03:46 UTC, HydrogenSulfate commented on jointContribution/AI4S-论文复现-CFDGCN/main.py
> +        print('------', flush=True)
在已经有logger的情况下，可以把所有的print尽量替换成logger

2023-07-04 03:46 UTC, HydrogenSulfate commented on jointContribution/AI4S-论文复现-CFDGCN/main.py
> +        print("train_loss:{},step:{}".format(avg_loss, self.global_step), flush=True)
同上

2023-07-04 03:46 UTC, HydrogenSulfate commented on jointContribution/AI4S-论文复现-CFDGCN/main.py
> +        # print("batch_val_loss:{}".format(loss.item()), flush=True)
删除无用注释

2023-07-04 03:46 UTC, HydrogenSulfate commented on jointContribution/AI4S-论文复现-CFDGCN/main.py
> +        # print("batch_train_loss:{}".format(loss.item()), flush=True)
删除注释

2023-07-04 03:46 UTC, HydrogenSulfate commented on jointContribution/AI4S-论文复现-CFDGCN/main.py
> +    paddle.seed(args.seed)
还需固定numpy和random的种子

2023-07-04 03:46 UTC, HydrogenSulfate commented on jointContribution/AI4S-论文复现-CFDGCN/mesh_utils.py
> +UnionTensor = Union[paddle.Tensor, np.ndarray]
改成 `GenericTensor`

2023-07-04 03:46 UTC, HydrogenSulfate commented on jointContribution/AI4S-论文复现-CFDGCN/mesh_utils.py
> +# import torch_geometric
删除无用注释

2023-07-04 03:46 UTC, HydrogenSulfate commented on jointContribution/AI4S-论文复现-CFDGCN/mesh_utils.py
> +                    # marker_dict[marker_tag] = np.array(marker_elems, dtype=np.long).transpose()
删除无用注释

2023-07-04 03:46 UTC, HydrogenSulfate commented on jointContribution/AI4S-论文复现-CFDGCN/mesh_utils.py
> +# def regular_grid_mesh(output_filename='regular_grid_mesh.su2', num_x=21, num_y=21,
删除注释

2023-07-04 03:46 UTC, HydrogenSulfate commented on jointContribution/AI4S-论文复现-CFDGCN/mesh_utils.py
> +        # inner_elems = [e for e in elems if len([i for i in e if i in airfoil_inds]) >= 2]
删除注释

2023-07-04 03:46 UTC, HydrogenSulfate commented on jointContribution/AI4S-论文复现-CFDGCN/mesh_utils.py
> +    # elems = elems[:, keep_inds]
删除注释

2023-07-04 03:46 UTC, HydrogenSulfate commented on jointContribution/AI4S-论文复现-CFDGCN/mesh_utils.py
> +    # g = GraphUNet(2, 2, 2, 2, pool_ratios=0.5)
删除注释

2023-07-04 03:46 UTC, HydrogenSulfate commented on jointContribution/AI4S-论文复现-CFDGCN/mesh_utils.py
> +        import pickle
import内容统一放在代码的开头位置，除非引入了第三方依赖会导致报错，否则不推荐在代码中间进行import

2023-07-04 03:46 UTC, HydrogenSulfate commented on jointContribution/AI4S-论文复现-CFDGCN/models.py
> +        # self.convs.append(GATConv(channels[0], channels[1], num_heads=4))
删除注释

2023-07-04 03:46 UTC, HydrogenSulfate commented on jointContribution/AI4S-论文复现-CFDGCN/models.py
> +        self.mesh_file = meshes_temp_dir + '/' + str(os.getpid()) + '_mesh.su2'
用os.path.join进行路径拼接

2023-07-04 03:46 UTC, HydrogenSulfate commented on jointContribution/AI4S-论文复现-CFDGCN/models.py
> +
删除冗余空行

2023-07-04 03:46 UTC, HydrogenSulfate commented on jointContribution/AI4S-论文复现-CFDGCN/models.py
> +        # self.sim_info['nodes'] = nodes[:, :2]
删除注释

2023-07-04 03:46 UTC, HydrogenSulfate commented on jointContribution/AI4S-论文复现-CFDGCN/models.py
> +        """
docstring风格不正确，改成和其他docstring一样的风格

2023-07-04 03:46 UTC, HydrogenSulfate commented on jointContribution/AI4S-论文复现-CFDGCN/models.py
> +        #                     coarse_batch.cpu(), fine.batch.cpu(), k=3)
删除注释

2023-07-04 03:46 UTC, HydrogenSulfate commented on jointContribution/AI4S-论文复现-CFDGCN/run.sh
脚本末尾加上换行

2023-07-04 03:46 UTC, HydrogenSulfate commented on jointContribution/AI4S-论文复现-CFDGCN/su2paddle/__init__.py
使用绝对路径进行导入，不要使用相对路径导入

2023-07-04 03:46 UTC, HydrogenSulfate commented on jointContribution/AI4S-论文复现-CFDGCN/su2paddle/su2_function.py
> +from .su2_function_mpi import RunCode, non_busy_post, non_busy_wait
使用绝对路径进行导入，不要使用相对路径导入

2023-07-04 03:46 UTC, HydrogenSulfate commented on jointContribution/AI4S-论文复现-CFDGCN/su2paddle/su2_function.py
> +        """
统一docstring风格

2023-07-04 03:46 UTC, HydrogenSulfate commented on jointContribution/AI4S-论文复现-CFDGCN/su2paddle/su2_function.py
> +        assert _global_max_ppe > 0, 'Before running SU2Function, a (single) call to activate_su2_mpi is needed.'
对于参数的检查，用raise Error，不要用 assert

2023-07-04 03:46 UTC, HydrogenSulfate commented on jointContribution/AI4S-论文复现-CFDGCN/su2paddle/su2_function.py
> +        print("forward tensor", x[0], x[1], x[2], x[3], flush=True)
删除调试代码，否则每次都会打印forward tensor

2023-07-04 03:46 UTC, HydrogenSulfate commented on jointContribution/AI4S-论文复现-CFDGCN/su2paddle/su2_function.py
> +        x = tuple([i.numpy() for i in x])
`x = tuple(i.numpy() for i in x)`

2023-07-04 03:46 UTC, HydrogenSulfate commented on jointContribution/AI4S-论文复现-CFDGCN/su2paddle/su2_function.py
> +        assert num_diff_inputs > 0 and num_diff_outputs > 0, \
asert -> raise

2023-07-04 03:46 UTC, HydrogenSulfate commented on jointContribution/AI4S-论文复现-CFDGCN/su2paddle/su2_function_mpi.py
> +    """
docstring风格问题

2023-07-04 03:46 UTC, HydrogenSulfate commented on jointContribution/AI4S-论文复现-CFDGCN/su2paddle/su2_function_mpi.py
> +        import paddle
import移动至最上方

2023-07-04 03:46 UTC, HydrogenSulfate commented on jointContribution/AI4S-论文复现-CFDGCN/su2paddle/su2_function_mpi.py
> +    """
docstring风格统一

2023-07-04 03:46 UTC, HydrogenSulfate commented on jointContribution/AI4S-论文复现-CFDGCN/su2paddle/su2_function_mpi.py
> +        import paddle
同上

2023-07-04 03:46 UTC, HydrogenSulfate commented on jointContribution/AI4S-论文复现-CFDGCN/su2paddle/su2_numpy.py
> +        """
docstring风格统一

2023-07-04 03:46 UTC, HydrogenSulfate commented on jointContribution/AI4S-论文复现-CFDGCN/su2paddle/su2_numpy.py
> +        assert num_zones == 1, 'Only supports 1 zone for now.'
assert -> raise

2023-07-04 03:46 UTC, HydrogenSulfate commented on jointContribution/AI4S-论文复现-CFDGCN/su2paddle/su2_numpy.py
> +from .su2_function_mpi import RunCode
绝对路径导入

2023-07-04 03:46 UTC, HydrogenSulfate commented on jointContribution/AI4S-论文复现-CFDGCN/su2paddle/su2_numpy.py
> +        """
docstring风格统一

2023-07-04 03:46 UTC, HydrogenSulfate commented on jointContribution/AI4S-论文复现-CFDGCN/su2paddle/su2_numpy.py
> +                            .format(len(inputs), self.forward_config, self.num_diff_inputs))
字符串格式化全部使用f-string，不推荐使用{}.format

2023-07-04 03:46 UTC, HydrogenSulfate commented on jointContribution/AI4S-论文复现-CFDGCN/su2paddle/su2_numpy.py
> +        """
docstring风格统一

2023-10-20 09:57 UTC, DrownFish19 commented on jointContribution/AI4S-论文复现-CFDGCN/su2paddle/__init__.py
不推荐使用绝对路径进行导入

2023-10-30 03:36 UTC, HydrogenSulfate requested changes

2023-10-30 03:54 UTC, HydrogenSulfate requested changes

2023-10-30 03:54 UTC, HydrogenSulfate commented on docs/zh/examples/cfdgcn.md
> +```
标注一下哪些是GCN运行所需的命令，哪些是CFD-GCN所需的命令

2023-10-30 03:54 UTC, HydrogenSulfate commented on docs/zh/examples/cfdgcn.md
> +```
同上标注一下

2023-10-30 03:54 UTC, HydrogenSulfate commented on docs/zh/examples/cfdgcn.md
> +```
按照运行顺序，这里的说明应该放到 4.快速运行 的上方？

2023-10-30 03:54 UTC, HydrogenSulfate commented on jointContribution/CFDGCN/su2paddle/su2_numpy.py
> +            _type_: A tuple of tensors with the batch of differentiable outputs.
_type_ 改为具体类型

2023-10-30 03:54 UTC, HydrogenSulfate commented on jointContribution/CFDGCN/su2paddle/su2_numpy.py
> +            _type_: The gradients of the loss with respect to the forward inputs.
同上，改为具体类型

2023-10-30 03:54 UTC, HydrogenSulfate commented on jointContribution/CFDGCN/main.py
> +        )
改用osp.join代替/拼接路径

2023-10-30 03:54 UTC, HydrogenSulfate commented on jointContribution/CFDGCN/models.py
> +            _type_: _description_
_type_补全

2023-11-03 08:10 UTC, HydrogenSulfate requested changes

2023-11-03 08:10 UTC, HydrogenSulfate commented on jointContribution/CFDGCN/mesh_utils.py
> +        dist = dist / dist.max() if max is None else max
分母位置可以加一下括号，否则不太能看出来这里的if-else是针对分母还是整个右值

2023-11-03 08:10 UTC, HydrogenSulfate commented on jointContribution/CFDGCN/mesh_utils.py
> +def is_ccw(points, ret_val=False):
改为is_counter_clock_wise或者在docstring中说明该函数的作用，否则缩写不太能让人明白这是什么函数

2023-11-03 08:10 UTC, HydrogenSulfate commented on jointContribution/CFDGCN/mesh_utils.py
> +def is_cw(points, triangles, ret_val=False):
同ccw

2023-11-03 08:10 UTC, HydrogenSulfate commented on jointContribution/CFDGCN/mesh_utils.py
> +        # plt.show()
删除注释

2023-11-03 08:10 UTC, HydrogenSulfate commented on jointContribution/CFDGCN/mesh_utils.py
> +    import time
import移动到文件开头处

2023-11-03 08:10 UTC, HydrogenSulfate commented on jointContribution/CFDGCN/mesh_utils.py
> +    plt.show()
所有函数定义需移动到__main__上方

2023-11-03 08:10 UTC, HydrogenSulfate commented on jointContribution/CFDGCN/su2paddle/su2_function_mpi.py
> +        elif run_type == RunCode.RUN_ADJOINT:
elif 之后加上同级的 else: raise NotImplementedError 的逻辑

2023-11-03 08:10 UTC, HydrogenSulfate commented on jointContribution/CFDGCN/su2paddle/su2_numpy.py
> +# TODO Outdated, update to match the Torch version (su2_function.py)
TODO Outdated表示什么意思呢，如果已经完成的TODO，则可以删除

2023-11-03 08:11 UTC, HydrogenSulfate commented
辛苦大佬所有文件的import方式统一修改下（typing、Image 这种除外）

2023-11-03 08:47 UTC, DrownFish19 commented on jointContribution/CFDGCN/main.py
> +            )
这里不推荐raise，如果类型都没有匹配，默认使用SGD。同时，这里加上了warning，给用户一个提示

2023-11-03 08:49 UTC, DrownFish19 commented on jointContribution/CFDGCN/main.py
> +
不推荐删除，给用户加载模型的一个示例，对用户更友好

2023-11-03 09:30 UTC, DrownFish19 commented on jointContribution/CFDGCN/data.py
> +        # data_means, data_stds = self.normalization_factors
这个注释不推荐删除，有两种normalization方式

2023-11-03 09:39 UTC, HydrogenSulfate requested changes
把meshes上传了一下：https://paddle-org.bj.bcebos.com/paddlescience/datasets/CFDGCN/meshes.tar

把PR里meshes删掉后，在文档中再添加一下 数据准备章节 就行，其他应该没啥问题了

``` sh
wget https://paddle-org.bj.bcebos.com/paddlescience/datasets/CFDGCN/meshes.tar
tar -xf meshes.tar
```

2023-11-03 09:39 UTC, HydrogenSulfate commented on docs/zh/examples/cfdgcn.md
> +### 4.2 aistudio
==> AIStudio 上运行

2023-11-03 09:39 UTC, HydrogenSulfate commented on docs/zh/examples/cfdgcn.md
> +#### 5.2 Dataset与Dataloader修改
==> #### 5.1.1

2023-11-03 09:39 UTC, HydrogenSulfate commented on docs/zh/examples/cfdgcn.md
> +### 5.3 knn_interpolate方法实现
`#### 5.1.2`

2023-11-03 09:39 UTC, HydrogenSulfate commented on docs/zh/examples/cfdgcn.md
> +### 5.4 SU2项目和paddle的结合使用
`### 5.2`

2023-11-03 09:39 UTC, HydrogenSulfate commented on jointContribution/CFDGCN/mesh_utils.py
> +        dist = (dist / dist.max()) if max is None else max
这里的括号是跟没加等价的，但是否符合代码运行的逻辑呢？从参数命名来看，代码逻辑好像是：如果max没有就除以dist.max，否则除以传入的参数max，这导致括号可能需要将分母扩上

2023-11-03 11:17 UTC, DrownFish19 commented on jointContribution/CFDGCN/mesh_utils.py
> +        dist = (dist / dist.max()) if max is None else max
参考原代码进行了修改，如下：
```python
        max_value = dist.max() if max is None else max
        dist = dist / max_value
```

2023-11-06 12:57 UTC, HydrogenSulfate approved these changes
LGTM

2023-11-06 12:57 UTC, merged