add laplace2d example
PaddlePaddle/PaddleScience pull request #230
Opened 2023-03-22 10:54 UTC by zhiminzhang0830

### PR types

New features
### PR changes

Others
### Describe

add laplace2d example

2023-03-31 03:16 UTC, HydrogenSulfate requested changes

2023-03-31 03:17 UTC, HydrogenSulfate commented on examples/laplace/laplace2d_newAPI_python_function.py
> +            | np.isclose(y, 1),
这里能否放在一行上

2023-03-31 03:37 UTC, zhiminzhang0830 commented on examples/laplace/laplace2d_newAPI_python_function.py
> +    # eval_solver.eval()
done

2023-03-31 03:37 UTC, zhiminzhang0830 commented on examples/laplace/laplace2d_newAPI_python_function.py
> +            | np.isclose(y, 1),
放到一行后，pre-commit改成了这种格式

2023-04-02 06:21 UTC, HydrogenSulfate requested changes

2023-04-02 06:21 UTC, HydrogenSulfate commented on examples/laplace/laplace2d_v2.py
> +    def u_compute_func(d):
```python
def u_compute_func(d):
    x, y = d["x"], d["y"]
    return np.cos(x) * np.cosh(y)
```
改为
```python
def u_solution_func(d):
    """compute ground truth for u as label data """
    x, y = d["x"], d["y"]
    return np.cos(x) * np.cosh(y)
```

2023-04-02 06:21 UTC, HydrogenSulfate commented on examples/laplace/laplace2d_v2.py
> +            | np.isclose(y, 1.0),
改为
```python
criteria=lambda x, y: (np.isclose(x, 0.0) | np.isclose(x, 1.0) | 
                       np.isclose(y, 0.0) | np.isclose(y, 1.0)),

```

2023-04-02 06:21 UTC, HydrogenSulfate commented on examples/laplace/laplace2d_v2.py
> +    )()
恒定学习率现已[支持直接传入浮点数](https://github.com/PaddlePaddle/PaddleScience/commit/4479f23ed1c841849c904b275750f018c2af6e16)
不再需要ConstLR这个类
所以lr_scheduler相关代码可删除（给Solver初始化时用None代替）

2023-04-02 06:21 UTC, HydrogenSulfate commented on examples/laplace/laplace2d_v2.py
> +        lr_scheduler,
改为0.001即可

2023-04-02 06:21 UTC, HydrogenSulfate commented on examples/laplace/laplace2d_v2.py
> +            {"u": u_compute_func},
改为`u_solution_func`

2023-04-02 06:21 UTC, HydrogenSulfate commented on examples/laplace/laplace2d_v2.py
> +    }
改为`eval_dataloader`

2023-04-02 06:21 UTC, HydrogenSulfate commented on examples/laplace/laplace2d_v2.py
> +        "Residual": ppsci.validate.GeometryValidator(
`Residual`改为`MSE_Metric`

2023-04-02 06:21 UTC, HydrogenSulfate commented on examples/laplace/laplace2d_v2.py
> +            name="Residual",
`Residual`改为`MSE_Metric`

2023-04-02 06:21 UTC, HydrogenSulfate commented on ppsci/validate/geo_validator.py
> +                    )
```python
 label[key] = np.full(
    (next(iter(input.values())).shape[0], 1), float(label[key]), "float32"
)
```
显式指定一下dtype

2023-04-02 06:22 UTC, HydrogenSulfate commented
把官方分支的develop merge一下，再开始修改

2023-04-03 03:17 UTC, zhiminzhang0830 commented
@HydrogenSulfate done

2023-04-03 04:02 UTC, HydrogenSulfate requested changes
TODO: 加入手动visualize过程

2023-04-03 04:02 UTC, HydrogenSulfate commented on examples/laplace/laplace2d_v2.py
> +    }
constraint、validator、visualize建议先构建对象，然后用dict封装，参考
https://github.com/PaddlePaddle/PaddleScience/pull/240/files#diff-9919bdd8d653428feb65643b2ffb05b9a85aeeaf0608ae15413a606c3635d030R120-R127
这样可以避免写两次同样的name

2023-04-03 05:12 UTC, zhiminzhang0830 commented on examples/laplace/laplace2d_v2.py
> +    output_dir = "output/laplace2d"
done

2023-04-03 05:12 UTC, zhiminzhang0830 commented on examples/laplace/laplace2d_v2.py
> +        pretrained_model_path=f"./{output_dir}/checkpoints/latest",
done

2023-04-03 05:12 UTC, zhiminzhang0830 commented on ppsci/equation/pde/laplace.py
done

2023-04-03 05:12 UTC, zhiminzhang0830 commented on examples/laplace/laplace2d_v2.py
> +    }
done

2023-04-03 06:10 UTC, HydrogenSulfate requested changes

2023-04-03 06:10 UTC, HydrogenSulfate commented on examples/laplace/laplace2d_v2.py
> +        {"laplace": lambda out: 0.0},
改成`"laplace": 0`

2023-04-03 06:11 UTC, HydrogenSulfate requested changes

2023-04-03 06:11 UTC, HydrogenSulfate commented on examples/laplace/laplace2d_v2.py
> +
这里的换行删除

2023-04-03 13:21 UTC, HydrogenSulfate approved these changes

2023-04-03 13:24 UTC, HydrogenSulfate requested changes

2023-04-03 13:24 UTC, HydrogenSulfate commented on ppsci/data/dataset/array_dataset.py
> +
删除多余空行

2023-04-03 13:24 UTC, HydrogenSulfate commented on ppsci/data/dataset/array_dataset.py
删除多余空行

2023-04-03 13:24 UTC, HydrogenSulfate commented on ppsci/solver/solver.py
> +        self.global_step = 0
下面已经有 `self.global_step = 0` 的代码

2023-04-04 02:10 UTC, HydrogenSulfate approved these changes
LGTM

2023-04-04 03:29 UTC, merged