3d cylinder merge
PaddlePaddle/PaddleScience pull request #249
Opened 2023-04-07 14:01 UTC by wangguan1995

### PR types

New features
### PR changes

- [.gitignore]: add files of checkpoints and post-process, which will be ignored.
- [examples/cylinder/3d_unsteady_discrete/*]: delete previous example files.
- [config.yaml]: add configuration files for managing hyper-parameters.
- [vtk_generator.py]: generate *.vtu files. It can attach results on a mesh either.
- [load_baseline_data.py]: a prototype file reader using 'meshio'.
- [*_constraint.py]: instead of sampling points in geometry, they take points data directly
- [data/__init__.py]: increase the number of workers to '1' for reducing 'dataloader' cost
- [dataset/__init__.py  array_dataset.py mse.py]: add minibatch_Dataloader for const loss weights
- [solver.py]: split data before prediction for saving GPU cache

### Describe

Refactor the 3d cylinder experiment with new API, optimized the efficiency of file inputs, enlarged the time steps to 99th(2 vortex shedding period)， and developed a quantitative method of diagnosing the result.

2023-04-09 08:55 UTC, HydrogenSulfate requested changes

2023-04-09 08:55 UTC, HydrogenSulfate commented on examples/cylinder/3d_unsteady_discrete/cylinder3d_unsteady.py
> +        weight_value=eq_wgt,
TODO: `weight_dict` 功能从 `Constraint` 迁移到 `Loss` 模块的 `reduction`参数后面，并改名为 `weight_expr`

2023-04-09 08:55 UTC, HydrogenSulfate commented on examples/cylinder/3d_unsteady_discrete/cylinder3d_unsteady.py
> +            "init_w": init_w,
这里的 `data_file` 直接构造为 `{"t": init_t, "x": init_x, "y": init_y, "z": init_z}`即可，不需要再使用 `alias_dict` 做重复转换

2023-04-09 08:55 UTC, HydrogenSulfate commented on examples/cylinder/3d_unsteady_discrete/cylinder3d_unsteady.py
> +    inlet_constraint = new_psci.constraint.SupervisedConstraint(
`inlet_constraint` -> `bc_inlet`

2023-04-09 08:55 UTC, HydrogenSulfate commented on examples/cylinder/3d_unsteady_discrete/cylinder3d_unsteady.py
> +        },
同上

2023-04-09 08:55 UTC, HydrogenSulfate commented on examples/cylinder/3d_unsteady_discrete/cylinder3d_unsteady.py
> +        name="INLET",
`nam = "BC_inlet"`

2023-04-09 08:55 UTC, HydrogenSulfate commented on examples/cylinder/3d_unsteady_discrete/cylinder3d_unsteady.py
> +    cylinder_constraint = new_psci.constraint.SupervisedConstraint(
改名，同上

2023-04-09 08:55 UTC, HydrogenSulfate commented on examples/cylinder/3d_unsteady_discrete/cylinder3d_unsteady.py
> +        },
同上修改

2023-04-09 08:55 UTC, HydrogenSulfate commented on examples/cylinder/3d_unsteady_discrete/cylinder3d_unsteady.py
> +        name="CYLINDER",
同上修改

2023-04-09 08:55 UTC, HydrogenSulfate commented on examples/cylinder/3d_unsteady_discrete/cylinder3d_unsteady.py
> +        },
同上修改

2023-04-09 08:55 UTC, HydrogenSulfate commented on examples/cylinder/3d_unsteady_discrete/cylinder3d_unsteady.py
> +        },
同上修改

2023-04-09 08:55 UTC, HydrogenSulfate commented on examples/cylinder/3d_unsteady_discrete/cylinder3d_unsteady.py
> +        },
同上修改

2023-04-09 08:55 UTC, HydrogenSulfate commented on examples/cylinder/3d_unsteady_discrete/cylinder3d_unsteady.py
> +        },
同上修改

2023-04-09 08:55 UTC, HydrogenSulfate commented on examples/cylinder/3d_unsteady_discrete/cylinder3d_unsteady.py
> +        },
同上修改

2023-04-09 08:55 UTC, HydrogenSulfate commented on examples/cylinder/3d_unsteady_discrete/cylinder3d_unsteady.py
> +        },
同上修改

2023-04-09 08:55 UTC, HydrogenSulfate commented on examples/cylinder/3d_unsteady_discrete/cylinder3d_unsteady.py
> +        },
同上修改

2023-04-09 08:55 UTC, HydrogenSulfate commented on examples/cylinder/3d_unsteady_discrete/cylinder3d_unsteady.py
> +    constraint_dict[sup_constraint.name] = sup_constraint
参考 https://github.com/PaddlePaddle/PaddleScience/blob/develop/examples/ldc/ldc2d_unsteady_Re10.py#LL118C5-L126C6

2023-04-09 08:55 UTC, HydrogenSulfate commented on examples/cylinder/3d_unsteady_discrete/cylinder3d_unsteady.py
> +        learning_rate=learning_rate,
`learning_rate=具体数值`

2023-04-09 08:55 UTC, HydrogenSulfate commented on examples/cylinder/3d_unsteady_discrete/cylinder3d_unsteady.py
> +                "sampler": None,
`"sampler": None,` 删除

2023-04-09 08:55 UTC, HydrogenSulfate commented on examples/cylinder/3d_unsteady_discrete/cylinder3d_unsteady.py
> +    output_dir = "./outputs_0404/"
`output_dir` 的设置放到demo代码开头，参考
https://github.com/PaddlePaddle/PaddleScience/blob/develop/examples/ldc/ldc2d_unsteady_Re10.py#LL22C5-L23C41

2023-04-09 08:55 UTC, HydrogenSulfate commented on examples/cylinder/3d_unsteady_discrete/cylinder3d_unsteady.py
> +    train_solver.train()
Solver相关代码参考
https://github.com/PaddlePaddle/PaddleScience/pull/241/files#diff-373072c8dd6e6f9fdbbc0cdc242b763748afc45c60aa57ab0f3a80f93e9644c6R191-R228

2023-04-09 08:55 UTC, HydrogenSulfate commented on examples/cylinder/3d_unsteady_discrete/vtk_generator.py
整合至 `Visulizer` 模块中

2023-04-09 08:55 UTC, HydrogenSulfate commented on paddlescience/neo_geometry/mesh.py
不要对 `Mesh` 类的已有代码进行改动

2023-04-09 08:55 UTC, HydrogenSulfate commented on ppsci/constraint/interior_constraint.py
不要对 `InteriorConstraint` 已有代码进行改动

2023-04-09 08:55 UTC, HydrogenSulfate commented on ppsci/constraint/supervised_constraint.py
> +        elif type(data_file) is dict:
使用 `isinstance`

2023-04-09 08:55 UTC, HydrogenSulfate commented on ppsci/constraint/supervised_constraint.py
> +                    label[key] = np.full_like(next(iter(input.values())), float(value))
显式指定类型 `np.full_like(..., ..., "float32")`

2023-04-09 08:55 UTC, HydrogenSulfate commented on ppsci/constraint/supervised_constraint.py
> +
weight功能迁移至Loss模块，待移除

2023-04-09 08:55 UTC, HydrogenSulfate commented on ppsci/constraint/supervised_constraint.py
> +        weight_value=1.0,
`SupervisedInitialConstraint` 应该是可以被 `SupervisedConstraint` 等价替换的

2023-04-09 08:55 UTC, HydrogenSulfate commented on ppsci/data/__init__.py
该文件不要改动

2023-04-09 08:55 UTC, HydrogenSulfate commented on ppsci/data/dataset/array_dataset.py
> +class MiniBatchDataset(io.Dataset):
这个类跟 `NamedArrayDataset` 有什么区别吗，尽量用 `NamedArrayDataset` 代替

2023-04-09 08:55 UTC, HydrogenSulfate commented on ppsci/equation/__init__.py
> +from ppsci.utils import misc  # isort: skip
1. 这里为什么要加上   # isort: skip 呢
2. 删除多余换行

2023-04-09 08:55 UTC, HydrogenSulfate commented on ppsci/loss/mse.py
TODO：Loss模块添加 `weight_expr` 功能

2023-04-09 08:55 UTC, HydrogenSulfate commented on ppsci/solver/solver.py
> +            cur_metric = float("inf")
重复语句，删除

2023-04-09 08:55 UTC, HydrogenSulfate commented on ppsci/solver/solver.py
>          return pred_dict
TOOD：重构predict，支持batch size预测

2023-04-09 08:55 UTC, HydrogenSulfate commented on ppsci/solver/train.py
删除多余换行

2023-04-09 08:55 UTC, HydrogenSulfate commented on ppsci/validate/data_validator.py
> +        data_dict = data
参数直接命名为 `data_dict` 即可

2023-04-10 02:53 UTC, wangguan1995 commented on examples/cylinder/3d_unsteady_discrete/load_baseline_data.py
> +def load_vtk(
![image](https://user-images.githubusercontent.com/39621324/230816024-712c2df3-32a5-42ae-983e-9d677870ce14.png)

2023-04-17 08:04 UTC, wangguan1995 commented on examples/cylinder/3d_unsteady_discrete/cylinder3d_unsteady.py
> +        learning_rate=learning_rate,
> `learning_rate=具体数值`

为方便调试，放置于line73

2023-04-17 08:06 UTC, wangguan1995 commented on ppsci/data/dataset/array_dataset.py
> +class MiniBatchDataset(io.Dataset):
> 这个类跟 `NamedArrayDataset` 有什么区别吗，尽量用 `NamedArrayDataset` 代替

没有weight

2023-04-21 09:07 UTC, HydrogenSulfate requested changes

2023-04-21 09:07 UTC, HydrogenSulfate commented on ppsci/geometry/pointcloud.py
> +        data_key,
把原有参数`xxx_path` 改为 `xxx`，然后点云上除坐标外的数据叫做 `attributes`

2023-04-21 09:07 UTC, HydrogenSulfate commented on ppsci/geometry/pointcloud.py
> +
重写父类 `uniform_points`

2023-04-21 09:07 UTC, HydrogenSulfate commented on ppsci/solver/solver.py
> -
不要改动原有代码的换行

2023-04-21 09:07 UTC, HydrogenSulfate commented on ppsci/solver/train.py
> +
TODO：collate_fn代替这段代码

2023-04-21 09:07 UTC, HydrogenSulfate commented on ppsci/solver/train.py
> +
不要改动原有换行

2023-04-21 09:07 UTC, HydrogenSulfate commented on ppsci/utils/reader.py
> -
不要改动原有换行

2023-04-21 09:07 UTC, HydrogenSulfate commented on ppsci/utils/reader.py
> +    return input_dict, label_dict
hardcode

2023-04-21 09:07 UTC, HydrogenSulfate commented on ppsci/validate/data_validator.py
功能可以由 https://paddlescience-docs.readthedocs.io/zh/latest/zh/api/validate/#ppsci.validate.SupervisedValidator 代替

2023-04-24 07:13 UTC, HydrogenSulfate requested changes

2023-04-24 07:13 UTC, HydrogenSulfate commented on ppsci/loss/mse.py
> +    def __init__(self, reduction: str = "mean", weight_expr: Union[float, Dict] = -1):
1. `weight_expr` 改为 `weight`
2. 参数类型改为 `Dict[str, float]`

2023-04-24 07:13 UTC, HydrogenSulfate commented on ppsci/loss/mse.py
> +        else:
删除其他分支代码，只留下`self.weight = weight`

2023-04-24 07:13 UTC, HydrogenSulfate commented on ppsci/loss/mse.py
> +
``` py
if isinstance(self.weight, float):
    loss *= self.weight
elif isinstance(self.weight, dict) and key in self.weight:
    loss *= self.weight[key]
```

2023-04-24 07:13 UTC, HydrogenSulfate commented on ppsci/solver/solver.py
> +import numpy as np
删除多余import

2023-04-24 07:13 UTC, HydrogenSulfate commented on ppsci/solver/solver.py
> +            self.visu_func = ppsci.solver.visu.visualize_func_3D
`visualize_func_3D` 合并到 `visualize_func`

2023-04-24 07:13 UTC, HydrogenSulfate commented on ppsci/solver/train.py
> +            )
不要改动这里的代码

2023-04-24 07:13 UTC, HydrogenSulfate commented on ppsci/utils/reader.py
> +
删除多余空行

2023-04-24 07:13 UTC, HydrogenSulfate commented on ppsci/utils/reader.py
> +    """
完善docstring

2023-04-24 07:13 UTC, HydrogenSulfate commented on ppsci/visualize/vtu.py
> +    print(f"vtk_raw file saved at [{filename}]")
使用logger不要用print

2023-04-24 07:13 UTC, HydrogenSulfate commented on ppsci/visualize/vtu.py
> +        os.makedirs(path)
`os.makedirs(..., exist_ok=True)`

2023-05-05 12:23 UTC, HydrogenSulfate requested changes

2023-05-05 12:23 UTC, HydrogenSulfate commented on examples/cylinder/3d_unsteady_discrete/cylinder3d_unsteady.py
> +            [np.full((data_len_for_onestep, 1), int(t)) for t in time_tmp], axis=0
改成 `np.full((data_len_for_onestep, 1), t, "float32")`，去掉末尾的 `.astype("float32")`

2023-05-05 12:23 UTC, HydrogenSulfate commented on ppsci/solver/solver.py
> +            self.visualize(epoch_id)
去掉这行

2023-05-05 12:23 UTC, HydrogenSulfate commented on ppsci/data/dataset/vtu_dataset.py
> +        transforms: vision.Compose = None,
typehint 参考其他Class修改下

2023-05-06 03:33 UTC, HydrogenSulfate requested changes

2023-05-06 03:33 UTC, HydrogenSulfate commented on ppsci/data/dataset/vtu_dataset.py
> +        labels : Temporary interface for [load_vtk_withtime_file]
`labels : Temporary interface for [load_vtk_withtime_file]` 这句话是什么意思

2023-05-06 03:33 UTC, HydrogenSulfate commented on ppsci/data/dataset/vtu_dataset.py
> +        time_index (List): Time index list in increasing order
所有英文句子末尾加上句号.

2023-05-06 03:33 UTC, HydrogenSulfate commented on ppsci/data/dataset/vtu_dataset.py
> +                        next(iter(_input.values())), float(value), "float32"
float(value)->value

2023-05-06 03:33 UTC, HydrogenSulfate commented on ppsci/data/process/transform/preprocess.py
> +                data_dict[key] *= self.scale[key]
给`class Translate`的方法也加上这个if判断

2023-05-06 03:33 UTC, HydrogenSulfate commented on ppsci/geometry/pointcloud.py
> +        alias_dict (Tuple[str]): Alias name for coord key, such as {"X:0": "x", "X:1": "y"}.
改成如下代码
``` py
interior (Union[str, Dict[str, np.ndarray]]): Filepath or dict data, which store interior points of a point cloud.
attributes(Dict): Dict stores informations except coordinates
coord_keys (Tuple[str, ...]): Tuple of coordinate keys, such as ("x", "y").
boundary (Union[str, Dict[str, np.ndarray]]): Filepath or dict data, which store boundary points of a point cloud.
boundary_normal (Union[str, Dict[str, np.ndarray]]): Filepath or dict data, which store boundary normal points of a point cloud.
alias_dict (Tuple[str]): Alias name for coord key, such as {"X:0": "x", "X:1": "y"}.
```

2023-05-06 03:33 UTC, HydrogenSulfate commented on ppsci/utils/reader.py
> +    label_keys: List = [],
类型改为Tuple[str, ...]，并且不要设置默认值

2023-05-06 03:33 UTC, HydrogenSulfate commented on ppsci/utils/reader.py
> +                input_dict[key].append(np.full((n, 1), float(index * time_step)))
np.full((n, 1), index * time_step, "float32")

2023-05-06 03:33 UTC, HydrogenSulfate commented on ppsci/utils/reader.py
> +                i = i + 1
i += 1

2023-05-06 03:33 UTC, HydrogenSulfate commented on ppsci/utils/reader.py
> +        if input_keys is not None:
删除`if input_keys is not None:`

2023-05-06 03:33 UTC, HydrogenSulfate commented on ppsci/utils/reader.py
> +        if label_keys is not None:
删除`if label_keys is not None:`

2023-05-06 03:33 UTC, HydrogenSulfate commented on ppsci/utils/reader.py
> +            input_dict[key] = np.concatenate(input_dict[key], axis=0).astype("float32")
删除axis=0和.astype("float32")

2023-05-06 03:33 UTC, HydrogenSulfate commented on ppsci/utils/reader.py
> +            label_dict[key] = np.concatenate(label_dict[key], axis=0).astype("float32")
删除axis=0和.astype("float32")

2023-05-06 03:33 UTC, HydrogenSulfate commented on ppsci/visualize/visualizer.py
> +        data_len_for_onestep: int = None,
1. batch_size移动到上面，和其他类保持一致
2. 用Optional包装默认值为None的typehint 
3. 可视化器只负责可视化，指标计算代码和相关参数移动到Validate里面

2023-05-06 03:33 UTC, HydrogenSulfate commented on ppsci/visualize/visualizer.py
> +            label (Dict): reference baseline result
Dict[str, paddle.Tensor]

2023-05-06 03:33 UTC, HydrogenSulfate commented on ppsci/visualize/vtu.py
> +def save_vtu(filename, label, coordinates):
1. `save_vtu` -> `save_vtu_to_mesh`
2. 参数改为 `filename, data_dict, coord_keys, value_keys`

2023-05-08 08:45 UTC, HydrogenSulfate commented on ppsci/data/dataset/vtu_dataset.py
> +        label_keys (Optional[Tuple[str, ...]]): List of label keys.
List of -> Tuple of

2023-05-08 08:49 UTC, HydrogenSulfate commented on ppsci/utils/reader.py
> +    label_keys: Optional[Tuple[str, ...]] = (),
label_keys不要设置默认值

2023-05-08 08:52 UTC, HydrogenSulfate commented on ppsci/visualize/visualizer.py
> +        data_len_for_onestep (Optional[int]): Data length for one time step.
这个是不是和num_timestamps 重复了

2023-05-09 10:40 UTC, HydrogenSulfate requested changes

2023-05-09 10:40 UTC, HydrogenSulfate commented on ppsci/data/dataset/vtu_dataset.py
> +        label_keys (Optional[Tuple[str, ...]]): Tuple of label keys.
末尾加上Defaults to None.

2023-05-09 10:40 UTC, HydrogenSulfate commented on ppsci/geometry/pointcloud.py
> +        alias_dict (Tuple[str]): Alias name for coord key, such as {"X:0": "x", "X:1": "y"}.
alias_dict类型是Optional[Dict[str, str]]

2023-05-09 10:40 UTC, HydrogenSulfate commented on ppsci/geometry/pointcloud.py
> +        alias_dict: Tuple[str] = None,
alias_dict类型是Optional[Dict[str, str]]

2023-05-16 02:34 UTC, HydrogenSulfate requested changes

2023-05-16 02:34 UTC, HydrogenSulfate commented on ppsci/data/dataset/vtu_dataset.py
> +        transforms: vision.Compose = None,
transforms参数默认是None，外面包上 Optional

2023-05-16 02:34 UTC, HydrogenSulfate commented on ppsci/visualize/visualizer.py
> +        coord_keys = list(filter(lambda x: x != "t", self.input_dict))
能用列表解析就不要用filter函数

``` py
coord_keys = [x for x in self.input_dict if x != "t"]
```

2023-05-16 06:58 UTC, HydrogenSulfate approved these changes
LGTM

2023-05-16 06:59 UTC, merged