add Transformer-Physx doc
PaddlePaddle/PaddleScience pull request #251
Opened 2023-04-13 09:27 UTC by zhiminzhang0830

### PR types

Others
### PR changes

Docs
### Describe

添加Transformer-Physx算法案例文档

主要修改点：
1. 增加Lorenz的案例文档；
2. 添加了Transformer-Physx相关的API文档；

其他：
1. 修复了因路径修改Cylinder 2d案例文档路径索引问题；
2. 修复了ppsci/arch/__init__.py中的license首行问题；

TODO:
1. 添加Cylinder案例文档
2. 添加Rossler案例文档

2023-04-16 07:09 UTC, HydrogenSulfate requested changes

2023-04-16 07:09 UTC, HydrogenSulfate commented on ppsci/visualize/__init__.py
> +from ppsci.visualize.plot import save_plot_from_3d_dict  # isort:skip
这里有必要加上 `# isort:skip` 吗

2023-04-18 07:31 UTC, zhiminzhang0830 commented on docs/zh/examples/lorenz.md
done

2023-04-18 09:47 UTC, HydrogenSulfate requested changes

2023-04-18 09:47 UTC, HydrogenSulfate commented on docs/zh/examples/lorenz.md
> +$$
三条方程应该是同时成立的，建议放在同一个math block下，并且用左花括号括起来

2023-04-18 09:47 UTC, HydrogenSulfate commented on docs/zh/examples/lorenz.md
> +如下图所示，该方法主要包含两个网络模型：Embedding 模型和 Transformer 模型。其中，Embedding 模型的 Encoder 模块负责将物理状态变量进行编码映射为编码向量，Decoder 模块则负责将编码向量映射为物理状态变量；Transformer 模型作用于编码空间，其输入是 Embedding 模型 Encoder 模块的输出，利用当前时刻的编码向量预测下一时刻的编码
1. “由预测的编码向量可以通过 Embedding 模型的 Decoder 模块得到对应的物理状态变量”，改为“预测得到的编码向量可以被 Embedding 模型的 Decoder 模块解码，得到对应的物理状态变量”
2. “详细细节” 去掉“详细”

2023-04-18 09:47 UTC, HydrogenSulfate commented on docs/zh/examples/lorenz.md
> +数据集采用了 [Transformer-Physx](https://github.com/zabaras/transformer-physx) 中提供的数据。该数据集中的数据使用龙格－库塔（Runge-Kutta）传统数值求解法求得，每个时间步大小为0.01，初始位置随机从以下的范围中选取：
1. “该数据集中的数据使用龙格－库塔（Runge-Kutta）传统数值求解法求得”改为“该数据集使用龙格－库塔（Runge-Kutta）传统数值求解方法得到“
2. “初始位置随机从以下的范围中选取”改为“初始位置从以下范围中随机选取”

2023-04-18 09:47 UTC, HydrogenSulfate commented on docs/zh/examples/lorenz.md
> +首先将代码中定义的各个参数变量展示如下，每个参数的具体含义会在下面使用到时进行解释。
“首先将代码中定义的各个参数变量展示如下”改为“首先展示代码中定义的各个参数变量”

2023-04-18 09:47 UTC, HydrogenSulfate commented on docs/zh/examples/lorenz.md
> +`SupervisedConstraint` 的第一个参数是训练数据集的文件路径，此处填入变量 `train_file_path`；
这里是否重复使用了数据集文件路径这一参数，应该只需要给Dataset即可

2023-04-18 09:47 UTC, HydrogenSulfate commented on docs/zh/examples/lorenz.md
> +第五个参数是数据的加载方式，这里使用上文中定义的 `train_dataloader`；
全文中的配置字典 `xxx_dataloader` 改为 `xxx_dataloader_cfg`

2023-04-18 09:47 UTC, HydrogenSulfate commented on docs/zh/examples/cylinder2d_unsteady_transformer_physx.md
> +类 `PhysformerGPT2` 除了需要填入 `input_keys` `output_keys` 外，还需要设置 Transformer 模型的层数 `num_layers`、上下文的大小 `num_ctx`、输入的 Embedding 向量的长度 `embed_size`、多头注意力机制的参数 `num_heads`，在这里填入的数值为6、16、128、4。
除了需要填入 `input_keys` `output_keys`，中间加一个顿号、

2023-04-18 09:47 UTC, HydrogenSulfate commented on docs/zh/examples/cylinder2d_unsteady_transformer_physx.md
> +可以看到，程序首先载入了训练好的 Embedding 模型，然后在 `OutputTransform` 的 `__call__` 函数内实现了编码向量到物理状态空间的变换。
`OutputTransform` 是否可以用一个函数代替呢

2023-04-18 10:14 UTC, zhiminzhang0830 commented on docs/zh/examples/cylinder2d_unsteady_transformer_physx.md
> +可以看到，程序首先载入了训练好的 Embedding 模型，然后在 `OutputTransform` 的 `__call__` 函数内实现了编码向量到物理状态空间的变换。
类`OutputTransform`在初始化时需要传入额外的参数 `model`,这样`__call__` 直接调用即可，不再需要调用时传入 `model`，感觉使用类的方式更合适一些？

2023-04-18 10:20 UTC, zhiminzhang0830 commented on docs/zh/examples/lorenz.md
> +`SupervisedConstraint` 的第一个参数是训练数据集的文件路径，此处填入变量 `train_file_path`；
目前在`SupervisedConstraint`内需要这个参数判断数据集文件后缀，用于程序走不同的`if`分支

2023-04-18 10:38 UTC, HydrogenSulfate commented on docs/zh/examples/lorenz.md
> +`SupervisedConstraint` 的第一个参数是训练数据集的文件路径，此处填入变量 `train_file_path`；
TODO：后续参照ViV修改一下代码

2023-04-18 11:26 UTC, HydrogenSulfate approved these changes

2023-04-18 11:27 UTC, HydrogenSulfate approved these changes
LGTM

2023-04-18 11:27 UTC, merged