add Euler Beam
PaddlePaddle/PaddleScience pull request #267
Opened 2023-04-23 09:21 UTC by zhiminzhang0830

### PR types

New features
### PR changes

APIs
### Describe

增加Euler Beam案例

2023-04-23 11:08 UTC, HydrogenSulfate requested changes

2023-04-23 11:08 UTC, HydrogenSulfate commented on ppsci/equation/pde/euler_beam.py
> +        self.add_equation("euler_beam", eulerbeam_compute_func)
方程名改为 `Biharmonic`，增加 `dim`、`q`、`D`参数，表示空间维度、载荷、刚度，这样适用1、2、3维的情况。三维公式如下

$$
(\dfrac{\partial^2 }{\partial x} + \dfrac{\partial^2 }{\partial y}+\dfrac{\partial^2 }{\partial z})(\dfrac{\partial^2 }{\partial x} + \dfrac{\partial^2 }{\partial y}+\dfrac{\partial^2 }{\partial z})(u)=\dfrac{q}{D}
$$

2023-04-26 03:20 UTC, zhiminzhang0830 commented on examples/euler_beam/euler_beam.py
> +    paddle.fluid.core.set_prim_eager_enabled(True)
done

2023-04-26 03:20 UTC, zhiminzhang0830 commented on examples/euler_beam/euler_beam.py
> +    optimizer = ppsci.optimizer.Adam(learning_rate=0.001)([model])
done

2023-04-26 03:21 UTC, zhiminzhang0830 commented on examples/euler_beam/euler_beam.py
> +        pretrained_model_path=f"./{output_dir}/checkpoints/best_model",
dne

2023-04-26 03:21 UTC, zhiminzhang0830 commented on ppsci/equation/pde/euler_beam.py
> +        self.add_equation("euler_beam", eulerbeam_compute_func)
已修改

2023-04-26 16:42 UTC, HydrogenSulfate requested changes

2023-04-26 16:42 UTC, HydrogenSulfate commented on examples/euler_beam/euler_beam.py
> +from regex import D
删除无用 import

2023-04-26 16:42 UTC, HydrogenSulfate commented on examples/euler_beam/euler_beam.py
> +
76行的空行删除

2023-04-26 16:42 UTC, HydrogenSulfate commented on examples/euler_beam/euler_beam.py
> +        return -(x**4) / 24 + x**3 / 6 - x**2 / 4
该函数移动至set validator下方

2023-04-26 16:42 UTC, HydrogenSulfate commented on ppsci/equation/pde/biharmonic.py
> +                    biharmonic += hessian(u__, out[key])
``` py
invars = ("x", "y", "z")[:self.dim]
for invar_i in invars:
    for invar_j in invars:
        biharmonic += hessian(hessian(u, invar_i), invar_j)
```

2023-04-27 02:17 UTC, zhiminzhang0830 commented on examples/euler_beam/euler_beam.py
> +
done

2023-04-27 02:18 UTC, zhiminzhang0830 commented on examples/euler_beam/euler_beam.py
> +        return -(x**4) / 24 + x**3 / 6 - x**2 / 4
done

2023-04-27 02:18 UTC, zhiminzhang0830 commented on ppsci/equation/pde/biharmonic.py
> +                    biharmonic += hessian(u__, out[key])
eone

2023-04-27 02:55 UTC, HydrogenSulfate approved these changes

2023-04-27 03:30 UTC, merged