update laplace2d example
PaddlePaddle/PaddleScience pull request #272
Opened 2023-04-24 15:27 UTC by zhiminzhang0830

### PR types

Bug fixes 
### PR changes

APIs
### Describe

根据新版的solver，更新laplace2d案例代码

2023-04-25 11:42 UTC, HydrogenSulfate requested changes

2023-04-25 11:42 UTC, HydrogenSulfate commented on examples/laplace/laplace2d_v2.py
> +    vis_points = geom["rect"].sample_interior(total_size, evenly=True)
可视化的时候可以把边界也加上，这样一共 $10201=101^2=9801+400$ 个点，参考https://paddlescience-docs.readthedocs.io/zh/latest/zh/examples/ldc2d_steady/#38

2023-04-25 11:43 UTC, HydrogenSulfate commented
TODO: 添加Laplace2D的文档

2023-04-26 02:00 UTC, zhiminzhang0830 commented on examples/laplace/laplace2d_v2.py
> +    vis_points = geom["rect"].sample_interior(total_size, evenly=True)
sample_interior 函数在 evenly=True 时，采样的点已经包含边界点，已将采样点修改为 10201 个点。

2023-04-26 02:01 UTC, zhiminzhang0830 commented
> TODO: 添加Laplace2D的文档

done

2023-04-26 02:22 UTC, HydrogenSulfate requested changes

2023-04-26 02:22 UTC, HydrogenSulfate commented on examples/laplace/laplace2d_v2.py
> -        geom=geom,
这里的geom应该不用删掉吧

2023-04-26 03:02 UTC, zhiminzhang0830 commented on examples/laplace/laplace2d_v2.py
> -        geom=geom,
done

2023-04-26 05:25 UTC, HydrogenSulfate approved these changes

2023-04-26 05:25 UTC, merged