add trunc_normal_ initializer
PaddlePaddle/PaddleScience pull request #278
Opened 2023-04-28 08:58 UTC by zhiminzhang0830

### PR types

New features
### PR changes

APIs
### Describe

增加初始化函数trunc_normal_

2023-04-29 14:16 UTC, HydrogenSulfate requested changes

2023-04-29 14:16 UTC, HydrogenSulfate commented on ppsci/utils/initializer.py
> +        warnings.warn(
用 `logger` 代替 `warnings`

2023-05-01 08:57 UTC, zhiminzhang0830 commented on ppsci/utils/initializer.py
> +        warnings.warn(
done

2023-05-01 09:59 UTC, HydrogenSulfate commented on ppsci/utils/initializer.py
> +            stacklevel=2,
`stacklevel=2` 参数是必要的吗，感觉可以去掉

2023-05-01 10:07 UTC, zhiminzhang0830 commented on ppsci/utils/initializer.py
> +            stacklevel=2,
done

2023-05-01 10:24 UTC, HydrogenSulfate approved these changes

2023-05-01 12:53 UTC, merged