Tipc fix 0525
PaddlePaddle/PaddleScience pull request #344
Opened 2023-05-25 08:05 UTC by wangguan1995

### PR types

Bug fixes
### PR changes

Others
### Describe

fix bugs caused by examples and paddle update
Now following examples work well in python3.10:
- cylinder2d_unsteady_Re100
- train_eular_beam

2023-05-25 08:37 UTC, HydrogenSulfate requested changes

2023-05-25 08:37 UTC, HydrogenSulfate commented on test_tipc/benchmark_train.sh
> +cd ${PDSC_DIR}${workdir}
`${PDSC_DIR}${workdir}` -> `${PDSC_DIR}/${workdir}`

2023-05-25 08:37 UTC, HydrogenSulfate commented on test_tipc/configs/train_2d_unsteady_continuous/train_2d_unsteady_continuous.txt
> +workdir:/examples/cylinder/2d_unsteady
`workdir:examples/cylinder/2d_unsteady`

2023-05-25 08:37 UTC, HydrogenSulfate commented on test_tipc/configs/train_eular_beam/train_eular_beam.txt
> +workdir:/examples/euler_beam
`workdir:examples/euler_beam`

2023-05-25 08:39 UTC, HydrogenSulfate requested changes

2023-05-25 08:39 UTC, HydrogenSulfate commented on test_tipc/benchmark_train.sh
> +echo -e "\n* [workdir] is now set : \n" ${PDSC_DIR}${workdir} "\n"
` ${PDSC_DIR}/${workdir}`

2023-05-25 08:39 UTC, HydrogenSulfate commented on test_tipc/prepare.sh
> +    cd ${PDSC_DIR}${workdir}
改为 `cd ${PDSC_DIR}/${workdir}`，并且 cd 应该放在 if 外面。无论有没有数据集存在，都需要进入案例文件夹才能运行案例文件

2023-05-26 04:49 UTC, wangguan1995 commented on test_tipc/prepare.sh
> +    cd ${PDSC_DIR}${workdir}
案例运行在另一个shell cd

2023-05-26 04:49 UTC, wangguan1995 commented on test_tipc/prepare.sh
> +    cd ${PDSC_DIR}${workdir}
> 改为 `cd ${PDSC_DIR}/${workdir}`，并且 cd 应该放在 if 外面。无论有没有数据集存在，都需要进入案例文件夹才能运行案例文件

案例运行在另一个shell cd

2023-05-26 06:07 UTC, HydrogenSulfate approved these changes
LGTM

2023-05-26 06:07 UTC, merged