add docker
PaddlePaddle/PaddleScience pull request #396
Opened 2023-06-19 07:12 UTC by sanbuphy

### PR types

Others

### PR changes

Others

### Describe

  https://github.com/PaddlePaddle/PaddleScience/issues/379

2023-06-29 08:06 UTC, sanbuphy commented
> 你好，build之后尝试训练，但遇到了下面截图里的问题，找不到GPU ![image](https://user-images.githubusercontent.com/23737287/249710224-0898cd33-006a-4a1c-a840-c4269769cd25.png)
> 
> ![image](https://user-images.githubusercontent.com/23737287/249709952-88a43ba9-904b-4433-ba92-cfbd9fad9ac1.png)

启动docker的时候带上了 --gpus all了嘛

2023-06-29 08:38 UTC, HydrogenSulfate commented
> > 你好，build之后尝试训练，但遇到了下面截图里的问题，找不到GPU ![image](https://user-images.githubusercontent.com/23737287/249710224-0898cd33-006a-4a1c-a840-c4269769cd25.png)
> > ![image](https://user-images.githubusercontent.com/23737287/249709952-88a43ba9-904b-4433-ba92-cfbd9fad9ac1.png)
> 
> 启动docker的时候带上了 --gpus all了嘛

我的docker版本比较老，不支持 --gpus all 参数，但是我用的是 nvidia-docker run，理论上后者应该也能获取到GPU吧，但是就是检测不到

2023-06-29 08:47 UTC, sanbuphy commented
> > > 你好，build之后尝试训练，但遇到了下面截图里的问题，找不到GPU ![image](https://user-images.githubusercontent.com/23737287/249710224-0898cd33-006a-4a1c-a840-c4269769cd25.png)
> > > ![image](https://user-images.githubusercontent.com/23737287/249709952-88a43ba9-904b-4433-ba92-cfbd9fad9ac1.png)
> > 
> > 
> > 启动docker的时候带上了 --gpus all了嘛
> 
> 我的docker版本比较老，不支持 --gpus all 参数，所以我用的是 nvidia-docker run，理论上后者应该也能获取到GPU吧，但是就是检测不到

进去后nvidia-smi是正常的吗，如果是正常的很可能是paddle的安装问题，run check也不行吗

2023-06-29 09:46 UTC, HydrogenSulfate commented
> > > > 你好，build之后尝试训练，但遇到了下面截图里的问题，找不到GPU ![image](https://user-images.githubusercontent.com/23737287/249710224-0898cd33-006a-4a1c-a840-c4269769cd25.png)
> > > > ![image](https://user-images.githubusercontent.com/23737287/249709952-88a43ba9-904b-4433-ba92-cfbd9fad9ac1.png)
> > > 
> > > 
> > > 启动docker的时候带上了 --gpus all了嘛
> > 
> > 
> > 我的docker版本比较老，不支持 --gpus all 参数，所以我用的是 nvidia-docker run，理论上后者应该也能获取到GPU吧，但是就是检测不到
> 
> 进去后nvidia-smi是正常的吗，如果是正常的很可能是paddle的安装问题，run check也不行吗

用不了nvidia-smi

2023-06-30 07:18 UTC, HydrogenSulfate requested changes

2023-06-30 07:18 UTC, HydrogenSulfate commented on docker/Dockerfile
> +    rm -rf /var/lib/apt/lists/*
能不用&&和反斜杠，改成多行 RUN吗？

2023-06-30 07:18 UTC, HydrogenSulfate commented on docker/Dockerfile
> +#install PaddleScience and pymesh
#后加空格

2023-06-30 07:18 UTC, HydrogenSulfate commented on docker/Dockerfile
> +    rm -rf /src
文件结尾换行

2023-06-30 07:18 UTC, HydrogenSulfate commented on docker/README.md
docker 使用方法写到 docs/zh/install_setup.md 中

2023-06-30 07:18 UTC, HydrogenSulfate commented on docker/run.sh
> +docker run --gpus all -it -v ./:/work paddlescience
1. 可以不用 && 和 \ 压行'
2. 文件末尾换行

2023-07-01 06:58 UTC, closed without merging