add Polygon sdf
PaddlePaddle/PaddleScience pull request #406
Opened 2023-06-24 16:47 UTC by mrcangye

### PR types

New features
### PR changes

APIs
### Describe

#376
测试代码
```python
import ppsci
from ppsci.utils import logger
from ppsci import visualize

logger.init_logger()

geo = ppsci.geometry.Polygon(((0, 0), (1, 0), (2, 1), (2, 2), (0, 2)))
points_dict = geo.sample_interior(n=100000) # 可视化100000个点
visualize.vtu.save_vtu_from_dict("./visualize_sdf.vtu", points_dict, geo.dim_keys, ("sdf", ))
```

2023-06-25 10:04 UTC, HydrogenSulfate commented
看了下范围，感觉不太对？
左边是用Poly生成的边长为 $\sqrt 2$ 的矩形的sdf
右边是用Rectangle生成的同边长的矩形的sdf，可以看到Rectangle的结果是对的，Poly的结果范围并不正确
![image](https://github.com/PaddlePaddle/PaddleScience/assets/23737287/f6780096-8533-4a19-b303-5f26af4c1727)

2023-06-26 01:57 UTC, mrcangye commented
> 看了下范围，感觉不太对？ 左边是用Poly生成的边长为 2 的矩形的sdf 右边是用Rectangle生成的同边长的矩形的sdf，可以看到Rectangle的结果是对的，Poly的结果范围并不正确 ![image](https://github.com/PaddlePaddle/PaddleScience/assets/23737287/f6780096-8533-4a19-b303-5f26af4c1727)

我修改了下代码，得出的结果如下：
![Screenshot - 2023-06-26 09 55 58](https://github.com/PaddlePaddle/PaddleScience/assets/20467386/cc03b8c9-d589-4c5b-a690-2aa625966399)
使用的测试代码如下：
```python
import ppsci
from ppsci.utils import logger
from ppsci import visualize

logger.init_logger()

geo = ppsci.geometry.Polygon(((0, 1), (1, 0), (0, -1), (-1, 0)))
points_dict = geo.sample_interior(n=500000) # 可视化500000个点
visualize.vtu.save_vtu_from_dict("./visualize_sdf.vtu", points_dict, geo.dim_keys, ("sdf", ))
```
这样的范围是正确的嘛

2023-06-26 02:25 UTC, HydrogenSulfate requested changes

2023-06-26 02:25 UTC, HydrogenSulfate commented on ppsci/geometry/geometry_2d.py
> +        return sdf_value
`return -sdf_value`，内部点的sdf是负数

2023-06-26 02:26 UTC, HydrogenSulfate commented
> > 看了下范围，感觉不太对？ 左边是用Poly生成的边长为 2 的矩形的sdf 右边是用Rectangle生成的同边长的矩形的sdf，可以看到Rectangle的结果是对的，Poly的结果范围并不正确 ![image](https://user-images.githubusercontent.com/23737287/248546570-f6780096-8533-4a19-b303-5f26af4c1727.png)
> 
> 我修改了下代码，得出的结果如下： ![Screenshot - 2023-06-26 09 55 58](https://user-images.githubusercontent.com/20467386/248618726-cc03b8c9-d589-4c5b-a690-2aa625966399.png) 使用的测试代码如下：
> 
> ```python
> import ppsci
> from ppsci.utils import logger
> from ppsci import visualize
> 
> logger.init_logger()
> 
> geo = ppsci.geometry.Polygon(((0, 1), (1, 0), (0, -1), (-1, 0)))
> points_dict = geo.sample_interior(n=500000) # 可视化500000个点
> visualize.vtu.save_vtu_from_dict("./visualize_sdf.vtu", points_dict, geo.dim_keys, ("sdf", ))
> ```
> 
> 这样的范围是正确的嘛

用五角星看了下结果基本是对了，但返回值还需要加一个负号
![image](https://github.com/PaddlePaddle/PaddleScience/assets/23737287/f1fdfd15-ea0a-4d73-ba01-cb36087973c8)

2023-06-26 06:58 UTC, HydrogenSulfate requested changes

2023-06-26 06:58 UTC, HydrogenSulfate commented on ppsci/geometry/geometry_2d.py
> +        sdf_value = np.random.random((points.shape[0], 1))
用 empty 代替 random，`x = np.empty((points.shape[0], 1), dtype=paddle.get_default_dtype())`

2023-06-26 06:58 UTC, HydrogenSulfate commented on ppsci/geometry/geometry_2d.py
> +                )
尽量避免单字符的变量命名，e、w、b、d、c 都修改一下

2023-06-26 06:58 UTC, mrcangye commented on ppsci/geometry/geometry_2d.py
> +                )
收到，这就改

2023-06-26 08:14 UTC, HydrogenSulfate requested changes

2023-06-26 08:14 UTC, HydrogenSulfate commented on ppsci/geometry/geometry_2d.py
> +                        Vector_ij[0] * Vector_in[1] > Vector_ij[1] * Vector_in[0],
变量名开头不要大写，改为小写

2023-06-26 10:52 UTC, HydrogenSulfate commented
code-style-check CI 挂了，commit之前请先安装pre-commit
``` sh
pip install pre-commit
pre-commit install
```

2023-06-26 16:56 UTC, mrcangye commented
> code-style-check CI 挂了，commit之前请先安装pre-commit
> 
> ```shell
> pip install pre-commit
> pre-commit install
> ```

已经修改，谢谢你！

2023-06-27 02:20 UTC, HydrogenSulfate approved these changes
LGTM

2023-06-27 02:21 UTC, merged