add PaddleScience docker
PaddlePaddle/PaddleScience pull request #411
Opened 2023-07-01 07:07 UTC by sanbuphy

### PR types

Others

### PR changes

Others

### Describe

https://github.com/PaddlePaddle/PaddleScience/issues/377

2023-07-03 02:49 UTC, HydrogenSulfate requested changes

2023-07-03 02:49 UTC, HydrogenSulfate commented on docker/Dockerfile
稍微修改了一下，加了点 apt 源和换了个 python 的下载地址，防止下载速度过慢或者网络无响应
``` sh
FROM nvcr.io/nvidia/cuda:11.6.2-cudnn8-runtime-ubuntu20.04

RUN echo "deb http://mirrors.aliyun.com/ubuntu/ bionic main restricted universe multiverse" >> /etc/apt/sources.list
RUN echo "deb-src http://mirrors.aliyun.com/ubuntu/ bionic main restricted universe multiverse" >> /etc/apt/sources.list
RUN echo "deb http://mirrors.aliyun.com/ubuntu/ bionic-security main restricted universe multiverse" >> /etc/apt/sources.list
RUN echo "deb-src http://mirrors.aliyun.com/ubuntu/ bionic-security main restricted universe multiverse" >> /etc/apt/sources.list
RUN echo "deb http://mirrors.aliyun.com/ubuntu/ bionic-updates main restricted universe multiverse" >> /etc/apt/sources.list
RUN echo "deb-src http://mirrors.aliyun.com/ubuntu/ bionic-updates main restricted universe multiverse" >> /etc/apt/sources.list
RUN echo "deb http://mirrors.aliyun.com/ubuntu/ bionic-proposed main restricted universe multiverse" >> /etc/apt/sources.list
RUN echo "deb-src http://mirrors.aliyun.com/ubuntu/ bionic-proposed main restricted universe multiverse" >> /etc/apt/sources.list
RUN echo "deb http://mirrors.aliyun.com/ubuntu/ bionic-backports main restricted universe multiverse" >> /etc/apt/sources.list
RUN echo "deb-src http://mirrors.aliyun.com/ubuntu/ bionic-backports main restricted universe multiverse" >> /etc/apt/sources.list
RUN echo "deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial main restricted universe multiverse" >> /etc/apt/sources.list
RUN echo "deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-security main restricted universe multiverse" >> /etc/apt/sources.list
RUN echo "deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-updates main restricted universe multiverse" >> /etc/apt/sources.list
RUN echo "deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-backports main restricted universe multiverse" >> /etc/apt/sources.list

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    g++ gcc cmake wget xz-utils git make zlib1g-dev openssl libssl-dev libffi-dev libeigen3-dev sqlite3 libsqlite3-dev libx11-dev libgl1-mesa-dev bzip2 libbz2-dev liblzma-dev \
    # pymesh dependency
    libeigen3-dev libgmp-dev libgmpxx4ldbl libmpfr-dev libboost-dev libboost-thread-dev libtbb-dev && \
    apt-get clean autoclean && \
    rm -rf /var/lib/apt/lists/*

RUN wget https://mirrors.huaweicloud.com/python/3.7.11/Python-3.7.11.tgz && \
    tar -xf Python-3.7.11.tgz && \
    cd Python-3.7.11 && \
    ./configure --with-ssl && \
    make -j -notest && \
    make install && \
    cd .. && rm -rf Python-3.7.11 && rm Python-3.7.11.tgz && \
    ln -s /usr/local/bin/python3.7 /usr/local/bin/python

RUN python3 -m pip install --upgrade pip -i https://pypi.douban.com/simple/ && pip install pysdf open3d db-sqlite3 -i https://pypi.douban.com/simple/

# install PaddleScience and pymesh
COPY ./PaddleScience /src/PaddleScience
COPY ./pymesh.tar.xz /src/pymesh.tar.xz

RUN cd /src && \
    ls /src && \
    tar -xvf pymesh.tar.xz && \
    cd pymesh && \
    python3 setup.py install

RUN cd /src && \
    python3 -m ensurepip --upgrade && \
    pip3 config set global.index-url https://pypi.doubanio.com/simple/ && \
    # ensure paddle install normally
    ln -s /usr/lib/x86_64-linux-gnu/libcudnn.so.8 /usr/local/cuda/lib64/libcudnn.so && \
    ln -s /usr/local/cuda/lib64/libcublas.so.11 /usr/local/cuda/lib64/libcublas.so && \
    echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64/' >> ~/.bashrc && \
    echo 'export PATH=$PATH:/usr/lib/x86_64-linux-gnu/' >> /etc/profile && \
    /bin/bash -c "source ~/.bashrc" && \
    /bin/bash -c "source /etc/profile" && \
    python3 -m pip install paddlepaddle-gpu==0.0.0.post116 -f https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html && \
    cd PaddleScience && pip3 install -r requirements.txt && pip install -e . && \
    rm -rf /src
```

2023-07-03 02:49 UTC, HydrogenSulfate commented on docker/run.sh
去掉这个文件里的冗余末尾空格，

2023-07-03 02:49 UTC, HydrogenSulfate commented on docs/zh/install_setup.md
放在 `1.1 python 环境安装[可选]` 前面，作为 1.1

2023-07-03 02:49 UTC, HydrogenSulfate commented
commit 之前请安装 pre-commit 
``` sh
pip install pre-commit
pre-commit install
```

2023-07-03 03:26 UTC, HydrogenSulfate requested changes

2023-07-03 03:26 UTC, HydrogenSulfate commented on docker/Dockerfile
> +ENV PATH="$PATH:/usr/lib/x86_64-linux-gnu/""
1. 末尾多了一个"
2. 文件末尾加上换行

2023-07-03 03:26 UTC, HydrogenSulfate commented on docs/zh/install_setup.md
> +为了更方便使用 PaddleScience,这里推荐你可以通过 docker 直接获取对应环境，按照下列流程可以快速启动：
描述改为：如果你对 docker 有一定了解，则可以通过我们提供的 docker 文件直接构建出能运行 PaddleScience 的环境。按照下列步骤构建 docker 并自动进入该环境，以运行 PaddleScience。

2023-07-03 03:26 UTC, HydrogenSulfate commented on docs/zh/install_setup.md
> +1. 下载 pymesh 预编译文件放到 PaddleScience/docker 目录下：docker/pymesh.tar.xz
修改为：下载 pymesh 预编译文件 pymesh.tar.xz 放到 PaddleScience/docker 目录下：docker/pymesh.tar.xz

2023-07-03 03:26 UTC, HydrogenSulfate commented on docs/zh/install_setup.md
描述和 run.sh 中去掉克隆和安装 PaddleScience 的步骤，docker 安装只安装必要环境，PaddleScience 安装在下面的章节

2023-07-03 05:52 UTC, sanbuphy commented on docs/zh/install_setup.md
done

2023-07-03 06:33 UTC, HydrogenSulfate requested changes

2023-07-03 06:33 UTC, HydrogenSulfate commented on docker/run.sh
> +docker run --gpus all -it -v $pwd/:/work paddlescience
$PWD，PWD大写，不能小写把？

2023-07-03 06:33 UTC, HydrogenSulfate commented on docs/zh/install_setup.md
> +    cd /work/PaddleScience && pip install -e .
你这个章节里，删除有关下载/安装 PaddleScience 的描述，安装 PaddleScience 在后续章节才出现

2023-07-03 06:51 UTC, sanbuphy commented on docs/zh/install_setup.md
> +    cd /work/PaddleScience && pip install -e .
done

2023-07-04 11:48 UTC, HydrogenSulfate requested changes

2023-07-04 12:28 UTC, sanbuphy commented on docker/run.sh
> +docker run --gpus all -it -v $PWD/:/work paddlescience
这个需要每个都这样吗，只有老版本的才要把

2023-07-05 05:36 UTC, HydrogenSulfate commented on docker/run.sh
> +docker run --gpus all -it -v $PWD/:/work paddlescience
> 这个需要每个都这样吗，只有老版本的才要把

如果改成 nvidia-docker 的方式，能兼容新版，那就得用 nvidia-docker

2023-07-05 05:38 UTC, sanbuphy commented on docker/run.sh
> +docker run --gpus all -it -v $PWD/:/work paddlescience
> > 这个需要每个都这样吗，只有老版本的才要把
> 
> 如果改成 nvidia-docker 的方式，能兼容新版，那就得用 nvidia-docker

新版本的直接docker 启动就好，没有nvidia--docker把，我觉的比较好的是在文档中显式说明

2023-07-05 06:13 UTC, HydrogenSulfate commented on docker/run.sh
> +docker run --gpus all -it -v $PWD/:/work paddlescience
> > > 这个需要每个都这样吗，只有老版本的才要把
> > 
> > 
> > 如果改成 nvidia-docker 的方式，能兼容新版，那就得用 nvidia-docker
> 
> 新版本的直接docker 启动就好，没有nvidia--docker把，我觉的比较好的是在文档中显式说明

如果 nvidia-docker 不兼容新版docker，而docker --all gpus 不兼容老的docker，那能不能在 run.sh 中判断一下 docker --version 的版本，根据其版本，用if分支分分别执行不同的docker命令

2023-07-05 06:34 UTC, sanbuphy commented on docker/run.sh
> +docker run --gpus all -it -v $PWD/:/work paddlescience
这个可以尝试，本质只要判断有没有安装nvidia-docker和docker就可以了

2023-07-05 07:04 UTC, HydrogenSulfate commented on docker/run.sh
> +docker run --gpus all -it -v $PWD/:/work paddlescience
> 这个可以尝试，本质只要判断有没有安装nvidia-docker和docker就可以了

这个能麻烦在PR里加一下这个功能吗，然后再加一下下方红框的参数，防止 apt 安装因为网络问题失败
![01C63413E70C4EB0C1C8F453D2D5F257](https://github.com/PaddlePaddle/PaddleScience/assets/23737287/41021181-ac6e-4dc7-82a8-4215edc1a14f)

2023-07-05 08:38 UTC, sanbuphy commented on docker/run.sh
> +docker run --gpus all -it -v $PWD/:/work paddlescience
好的

2023-07-06 08:46 UTC, sanbuphy commented on docker/run.sh
> +docker run --gpus all -it -v $PWD/:/work paddlescience
已经修改完毕

2023-07-06 09:34 UTC, HydrogenSulfate approved these changes
LGTM

2023-07-06 09:35 UTC, merged