addleScience 的 equation 模块添加单元测试 test_navier_stokes
PaddlePaddle/PaddleScience pull request #414
Opened 2023-07-02 10:04 UTC by mrcangye

### PR types

New features
### PR changes

 APIs
### Describe

#378

2023-07-02 10:04 UTC, mrcangye commented
还在修改中.....

2023-07-05 05:41 UTC, HydrogenSulfate requested changes

2023-07-05 05:41 UTC, HydrogenSulfate commented on test/equation/test_navier_stokes.py
> +    p = paddle.randn([batch_size, 1])
1. u、v、w、p是模型输出，不是输入数据
    ``` py
    x,y==>u,v,p
    x,y,z==>u,v,w,p
    ```

2. 数据t是可选的，如果有t的话，concat也是(t,x,y)，而不是(x,y,t)

2023-07-07 10:06 UTC, luotao1 commented
顺便解决下 CodeStyle 流水线的问题

2023-07-08 08:29 UTC, mrcangye commented on test/equation/test_navier_stokes.py
> +    p = paddle.randn([batch_size, 1])
ok,今晚我整一版出来，然后艾特老哥

2023-07-08 08:30 UTC, mrcangye commented
> 顺便解决下 CodeStyle 流水线的问题

好嘞

2023-07-08 08:38 UTC, HydrogenSulfate requested changes

2023-07-08 08:38 UTC, HydrogenSulfate commented on test/equation/test_navier_stokes.py
> +    return momentum_z
1. 函数末尾的 `_expected_result` 去掉
2. `if time is True` -> `if time`

2023-07-08 08:38 UTC, HydrogenSulfate commented on test/equation/test_navier_stokes.py
> +    )
化简代码
``` py
x = ...
y = ...
inputs = (x, y)
if dim == 3:
    z = ...
    inputs = inputs + (z, )
if time:
    t = ...
    inputs = (t, ) + inputs

input_data = paddle.concat(inputs, axis=1)

model = nn.Sequential(
    nn.Linear(input_data.shape[1], 1),
    nn.Tanh(),
)
```

2023-07-08 08:38 UTC, HydrogenSulfate commented on test/equation/test_navier_stokes.py
> +    assert paddle.allclose(expected_result, test_result)
写的完全不对

2023-07-08 14:37 UTC, HydrogenSulfate requested changes

2023-07-08 14:37 UTC, HydrogenSulfate commented on test/equation/test_navier_stokes.py
> +    )
inputs_dims 是 `int` 类型，但在 116 行却用了 `len(inputs_dims)`

2023-07-08 14:37 UTC, HydrogenSulfate commented on test/equation/test_navier_stokes.py
> +        "t": t,
这里应该也是会报错的，t 在 time=False的时候并没有定义

2023-07-08 14:37 UTC, HydrogenSulfate commented on test/equation/test_navier_stokes.py
> +        )
添加单个元素用.append

2023-07-08 14:37 UTC, HydrogenSulfate commented on test/equation/test_navier_stokes.py
> +        )
直接赋值即可，不需要update一个字典实例

2023-07-08 14:37 UTC, HydrogenSulfate commented on test/equation/test_navier_stokes.py
建议修改正确之后，运行一下 `pytest --cov ./ppsci/equation/ test/equation/test_navier_stokes.py` 能得到预期结果再 commit

2023-07-08 14:54 UTC, mrcangye commented on test/equation/test_navier_stokes.py
好的，我切换一下本地环境试试，二次框架的好像安不上pytest的cov插件

2023-07-08 16:36 UTC, mrcangye commented on test/equation/test_navier_stokes.py
@HydrogenSulfate 小哥醒了回我就行。现在测试用例通过了，但是覆盖率是0%，我有点不大理解，这种情况大概要怎么处理呢？

2023-07-09 05:49 UTC, HydrogenSulfate requested changes

2023-07-09 05:49 UTC, HydrogenSulfate commented on test/equation/test_navier_stokes.py
> +        t = None
if not time

2023-07-09 05:50 UTC, HydrogenSulfate commented on test/equation/test_navier_stokes.py
> @HydrogenSulfate 小哥醒了回我就行。现在测试用例通过了，但是覆盖率是0%，我有点不大理解，这种情况大概要怎么处理呢？ ![Screenshot - 2023-07-09 00 33 55](https://user-images.githubusercontent.com/20467386/252020746-1e69e1e7-122f-412d-b903-6ff8e8c65f1d.png) 以及这个： ![网页捕获_9-7-2023_03659_](https://user-images.githubusercontent.com/20467386/252020792-3f391fbd-0a91-4ee7-963c-0d66d9dd5fb7.jpeg)

可能是环境问题吧，我这里显示覆盖率100%

2023-07-09 05:51 UTC, mrcangye commented on test/equation/test_navier_stokes.py
泪目~！！！

2023-07-10 03:16 UTC, HydrogenSulfate approved these changes
LGTM

2023-07-10 03:16 UTC, merged

2023-07-10 03:20 UTC, mrcangye commented
谢谢小哥的耐心教导！！！比心~

2023-07-10 03:20 UTC, mrcangye commented
> LGTM

谢谢小哥的耐心教导！！！比心~