为equatiohn/pde/linear_elasticity.py添加单元测试
PaddlePaddle/PaddleScience pull request #416
Opened 2023-07-02 17:20 UTC by ruoyunbai

### PR types

Others
### PR changes

Others
### Describe

为equatiohn/pde/linear_elasticity.py添加单元测试

2023-07-03 06:51 UTC, HydrogenSulfate commented
![image](https://github.com/PaddlePaddle/PaddleScience/assets/23737287/9fdb74e6-0e1a-4d0d-a82e-b00f4d69912c)
这个单测的认领人好像不是你这个账号

2023-07-03 13:22 UTC, HydrogenSulfate requested changes

2023-07-03 13:22 UTC, HydrogenSulfate commented on test/equation/test_linear_elasticity.py
> +    return jacobian(jacobian(y, x), x)
jacobian 和 hessian 的函数移动到所有函数的上方

2023-07-03 13:22 UTC, HydrogenSulfate commented on test/equation/test_linear_elasticity.py
> +        )
用 paddle.split 而不是手动切片得到各个分量的结果

2023-07-03 13:22 UTC, HydrogenSulfate commented on test/equation/test_linear_elasticity.py
> +# test_linear_elasticity_navier_y(1e4, 0.3, None, None, 1, 2, True)
删除注释

2023-07-03 13:22 UTC, HydrogenSulfate commented on test/equation/test_linear_elasticity.py
> +    ],
目前这个类还未添加对 `E` 和 `nu` 的处理逻辑，应该为 `E` 和 `nu` 设置为None，而 `lambda_` 和 `mu` 设置为实数值

2023-07-04 05:53 UTC, HydrogenSulfate commented
> > ![image](https://user-images.githubusercontent.com/23737287/250479219-9fdb74e6-0e1a-4d0d-a82e-b00f4d69912c.png) 这个单测的认领人好像不是你这个账号
> 
> 老师让我看看这个，我没认领/(ㄒoㄒ)/~~

那没事儿，可以按照review改一下，到时候合你的PR

2023-07-05 04:02 UTC, HydrogenSulfate requested changes

2023-07-06 02:22 UTC, HydrogenSulfate requested changes

2023-07-06 02:22 UTC, HydrogenSulfate commented on test/equation/test_linear_elasticity.py
> +    )
虽然E和nu暂时只会是None，但这里的E和nu应该用传进来的参数填写吧

2023-07-06 02:22 UTC, HydrogenSulfate commented on test/equation/test_linear_elasticity.py
> +    ]
这里为什么要给 test_output_names 赋值两次呢

2023-07-06 02:22 UTC, HydrogenSulfate commented on test/equation/test_linear_elasticity.py
> +        test_output[name] = linear_elasticity.equations[name](data_dict)
跟277~279重复了，应该先按照dim，处理好test_output_names，然后再`test_output[name] = linear_elasticity.equations[name](data_dict)`就行了

2023-07-07 06:15 UTC, HydrogenSulfate requested changes
再改一处就OK了

2023-07-07 06:15 UTC, HydrogenSulfate commented on test/equation/test_linear_elasticity.py
> +        input_data = paddle.concat([input_data, t], axis=1)
PaddleScience里，时间数据t如果有的话，会排在通道维度的最前面，`input_data = paddle.concat([t, input_data], axis=1)`

2023-07-07 07:38 UTC, HydrogenSulfate requested changes

2023-07-07 07:38 UTC, HydrogenSulfate commented on test/equation/test_linear_elasticity.py
> +        input_data = paddle.concat([input_data, t], axis=1)
> okok

感觉你应该理解错了，我的意思是 时间t和其他通道的数据堆叠在一起时，应该排在第一个通道上……
也就是第 177行代码应该改成 `input_data = paddle.concat([t, input_data], axis=1)`

2023-07-10 03:16 UTC, HydrogenSulfate approved these changes
LGTM

2023-07-10 03:16 UTC, merged

2023-07-10 03:51 UTC, luotao1 commented
hi, @ruoyunbai 
- 非常感谢你对飞桨框架的贡献，我们正在运营一个PFCC组织，会通过定期分享技术知识与发布开发者主导任务的形式持续为飞桨框架做贡献，详情可见 https://github.com/luotao1 主页说明。
- 如果你对PFCC有兴趣，请发送邮件至 [ext_paddle_oss@baidu.com](mailto:ext_paddle_oss@baidu.com)，我们会邀请你加入~