Deep Spatio-Temporal 论文源码转换
PaddlePaddle/PaddleScience pull request #502
Opened 2023-08-23 12:22 UTC by co63oc

### PR types

Others
### PR changes

Others
### Describe

https://github.com/PaddlePaddle/Paddle/issues/55663#paddlepaddle14
![图片](https://github.com/PaddlePaddle/PaddleScience/assets/4617245/5a243be6-40c4-446c-bf0b-ff9ed7eb2aa3)

2023-08-24 03:43 UTC, luotao1 commented
@njjtan @172w 两位选手请注意下，赛题14的论文二已经提交PR了

2023-08-24 06:16 UTC, HydrogenSulfate requested changes
PR描述里提供的图片看起来好像没有训练完？麻烦提供一下复现的精度和原论文的精度指标

2023-08-24 08:16 UTC, co63oc commented on jointContribution/Deep-Spatio-Temporal/README.md
> +修改 torch 库为 paddle
1

2023-08-24 08:16 UTC, co63oc commented on jointContribution/Deep-Spatio-Temporal/README.md
> +------------------------------
1

2023-08-24 08:16 UTC, co63oc commented on jointContribution/Deep-Spatio-Temporal/README.md
1

2023-08-24 08:16 UTC, co63oc commented on jointContribution/Deep-Spatio-Temporal/getNRELdata.py
> +#!/usr/bin/env python
1

2023-08-24 08:16 UTC, co63oc commented on jointContribution/Deep-Spatio-Temporal/src/datamgr.py
> +#!/usr/bin/env python
1

2023-08-24 08:16 UTC, co63oc commented on jointContribution/Deep-Spatio-Temporal/src/datamgr.py
> +
1

2023-08-24 08:16 UTC, co63oc commented on jointContribution/Deep-Spatio-Temporal/src/datamgr.py
> +from paddle.io import Dataset
1

2023-08-24 08:16 UTC, co63oc commented on jointContribution/Deep-Spatio-Temporal/src/datamgr.py
> +
1

2023-08-24 08:16 UTC, co63oc commented on jointContribution/Deep-Spatio-Temporal/src/datamgr.py
> +from sklearn.neighbors import NearestNeighbors
1

2023-08-24 08:17 UTC, co63oc commented on jointContribution/Deep-Spatio-Temporal/src/datamgr.py
> +        self.ids = paddle.to_tensor(paddle.arange(200), dtype=paddle.float32).reshape(
1

2023-08-24 08:17 UTC, co63oc commented on jointContribution/Deep-Spatio-Temporal/src/datamgr.py
> +            self.neighbors = paddle.to_tensor(paddle.arange(200)).reshape((200, 1))
1

2023-08-24 08:17 UTC, co63oc commented on jointContribution/Deep-Spatio-Temporal/src/datamgr.py
> +        #         self._reformat_1d_to_2d()
1

2023-08-24 08:18 UTC, co63oc commented on jointContribution/Deep-Spatio-Temporal/src/datamgr.py
> +
1

2023-08-24 08:18 UTC, co63oc commented on jointContribution/Deep-Spatio-Temporal/src/datamgr.py
> +        # y = y[:, [0, self.K, self.K + 1, self.K + 2]]
1

2023-08-24 08:46 UTC, co63oc commented
> PR描述里提供的图片看起来好像没有训练完？麻烦提供一下复现的精度和原论文的精度指标

已增加 Test Loss

2023-08-24 09:55 UTC, co63oc commented
> > > PR描述里提供的图片看起来好像没有训练完？麻烦提供一下复现的精度和原论文的精度指标
> > 
> > 
> > 已增加 Test Loss
> 
> 这个好像不是完整训练完的loss？模型复现需要提供完整训练后的指标

图片已更新为训练完成图片
![图片](https://github.com/PaddlePaddle/PaddleScience/assets/4617245/7b8cf76a-2f94-469e-9329-f3b37ef3795d)

2023-08-24 10:50 UTC, HydrogenSulfate requested changes

2023-08-24 10:50 UTC, HydrogenSulfate commented on jointContribution/Deep-Spatio-Temporal/src/model.py
> +        """
docstring不正确，修改一下，风格与ppsci内代码保持一致

2023-08-24 10:50 UTC, HydrogenSulfate commented on jointContribution/Deep-Spatio-Temporal/src/model.py
> +        """
同上

2023-08-24 10:50 UTC, HydrogenSulfate commented on jointContribution/Deep-Spatio-Temporal/src/model.py
> +            assert (output == hidden).all()
这里的assert是否有必要？一般很少对densetensor进行逐元素检查，否则会占用一定的计算时间吧？

2023-08-24 10:50 UTC, HydrogenSulfate commented on jointContribution/Deep-Spatio-Temporal/src/utils.py
> +    )
使用`paddle.ParamAttr`即可

2023-08-24 10:50 UTC, HydrogenSulfate commented on jointContribution/Deep-Spatio-Temporal/train.py
> +    print("Running with following command line arguments: {}".format(args))
改为f-string

2023-08-24 10:50 UTC, HydrogenSulfate commented on jointContribution/Deep-Spatio-Temporal/train.py
> +        data_mgr = datamgr.DataMgr(file_path="./data/" + args.name + ".csv", K=K)
路径拼接使用os.path.join

2023-08-24 10:50 UTC, HydrogenSulfate commented on jointContribution/Deep-Spatio-Temporal/src/trainer.py
> +                )
路径拼接用os.path.join

2023-08-24 10:50 UTC, HydrogenSulfate commented on jointContribution/Deep-Spatio-Temporal/src/trainer.py
> +                self.model.state_dict(), "outputs/" + self.SAVE_FILE + ".pdparams"
路径拼接用os.path.join

2023-08-24 10:50 UTC, HydrogenSulfate commented on jointContribution/Deep-Spatio-Temporal/train.py
> +    outdf.to_csv("outputs/" + SAVE_FILE + "_metrics.csv")
路径拼接用os.path.join

2023-08-24 10:51 UTC, HydrogenSulfate commented
> > > > PR描述里提供的图片看起来好像没有训练完？麻烦提供一下复现的精度和原论文的精度指标
> > > 
> > > 
> > > 已增加 Test Loss
> > 
> > 
> > 这个好像不是完整训练完的loss？模型复现需要提供完整训练后的指标
> 
> 图片已更新为训练完成图片 ![图片](https://user-images.githubusercontent.com/4617245/262936182-7b8cf76a-2f94-469e-9329-f3b37ef3795d.png)

哦哦好吧，看起来是这个案例收敛速度太快，总的300轮在10轮就提前结束了

2023-08-24 11:23 UTC, co63oc commented on jointContribution/Deep-Spatio-Temporal/src/model.py
> +        """
已修改增加Args

2023-08-24 11:23 UTC, co63oc commented on jointContribution/Deep-Spatio-Temporal/src/model.py
> +        """
1

2023-08-24 11:24 UTC, co63oc commented on jointContribution/Deep-Spatio-Temporal/src/trainer.py
> +                self.model.state_dict(), "outputs/" + self.SAVE_FILE + ".pdparams"
1

2023-08-24 11:25 UTC, co63oc commented on jointContribution/Deep-Spatio-Temporal/src/model.py
> +            assert (output == hidden).all()
已有数据占用时间不大，如果数据有错误，assert可以验证

2023-08-24 11:25 UTC, co63oc commented on jointContribution/Deep-Spatio-Temporal/src/utils.py
> +    )
1

2023-08-24 11:25 UTC, co63oc commented on jointContribution/Deep-Spatio-Temporal/train.py
> +    print("Running with following command line arguments: {}".format(args))
1

2023-08-24 11:25 UTC, co63oc commented on jointContribution/Deep-Spatio-Temporal/train.py
> +        data_mgr = datamgr.DataMgr(file_path="./data/" + args.name + ".csv", K=K)
1

2023-08-24 11:25 UTC, co63oc commented on jointContribution/Deep-Spatio-Temporal/src/trainer.py
> +                )
1

2023-08-24 11:25 UTC, co63oc commented on jointContribution/Deep-Spatio-Temporal/train.py
> +    outdf.to_csv("outputs/" + SAVE_FILE + "_metrics.csv")
1

2023-08-24 11:27 UTC, co63oc commented
> 哦哦好吧，看起来是这个案例收敛速度太快，总的300轮在10轮就提前结束了

轮次是Epoch，count 这是计算best_loss如果连续10轮小于val_loss，就结束计算

2023-08-24 12:36 UTC, HydrogenSulfate requested changes
返回值类型稍微修改下，其他应该没啥问题了

2023-08-24 12:36 UTC, HydrogenSulfate commented on jointContribution/Deep-Spatio-Temporal/src/model.py
> +            Tensor: The hidden variable returned by the decoder.
返回值用`Tuple[Tensor, Tensor]`类型

2023-08-24 22:08 UTC, co63oc commented on jointContribution/Deep-Spatio-Temporal/src/model.py
> +            Tensor: The hidden variable returned by the decoder.
1

2023-08-26 05:59 UTC, HydrogenSulfate approved these changes
LGTM

2023-08-26 05:59 UTC, merged