PaddleScience 论文复现 Deep learning based denoising process
PaddlePaddle/PaddleScience pull request #511
Opened 2023-08-30 00:31 UTC by co63oc

### PR types

Others
### PR changes

Others
### Describe

https://github.com/PaddlePaddle/Paddle/issues/55663#paddlepaddle14
题目：Deep learning based denoising process

Test Loss 信息
| Test Loss | torch | paddle |
| - | - | - |
| | 0.0003 | 0.0003 |

2023-09-01 06:00 UTC, HydrogenSulfate requested changes

2023-09-01 06:00 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/main.py
> +    )
1. 打印的内容从缩写改为nlayer, nkernel, nchannel, ndownsample, lossnum

2023-09-01 06:00 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/config.yaml
> +Randomintensity: True
yaml文件布尔值开头不用大写

2023-09-01 06:00 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/config.yaml
> +learning_rate: 1e-5
1. yaml感知科学计数法需要小数点，改成1.0e5，

2023-09-01 06:00 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/config.yaml
> +pod_data_name: "poddata.mat"
yaml字符串可以不用双引号

2023-09-01 06:00 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/main.py
> +    config = util.load_config(CONFIG_PATH, "config.yaml")
这里加载yaml的代码感觉有一些冗余，传一个参数即可

2023-09-01 06:00 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/main.py
> +        learning_rate=float(config["learning_rate"]),
小数点加上后这里就不需要转成float这个操作了

2023-09-01 06:00 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/main.py
> +    if config["Scheduler"] == 1:
直接`if config["Scheduler"]` 即可

2023-09-01 06:00 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/main.py
> +    FPATH = util.setup_log_directory(config)
FPATH ==> output_dir

2023-09-01 06:00 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/models/basicblock.py
> +"""
注释信息放文件最上方

2023-09-01 06:00 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/models/basicblock.py
> +import paddle.nn as nn
==> from paddle import nn

2023-09-01 06:00 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/models/basicblock.py
> +def sequential(*args):
==> `to_sequential`

2023-09-01 06:00 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/models/basicblock.py
> +    """
用vscode的docstring生成器写正确的注释

2023-09-01 06:00 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/utils/cosine_annealing_with_warmup.py
文件名改成 `lr_scheduler.py`

2023-09-01 06:00 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/main.py
> +from utils.cosine_annealing_with_warmup import CosineAnnealingWarmUpRestarts
==》 
``` py
from utils import lr_scheduler
lr_scheduler.CosineAnnealingWarmUpRestarts(...)
```

2023-09-01 06:00 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/main.py
> +    epoch, loss_, evalloss_, Timecal = (
1. TimeCal这个变量看起来后续没有被调用过，看起来是个训练计时的东西，如果没用的话可以删掉，如果有用的话加上对应调用的代码

2023-09-01 06:00 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/models/network_model_batch.py
> +from utils.pixelshuffle1d import PixelUnshuffle1D
不要从模块中直接导入某个类或者变量使用，而应该导入对应模块，然后通过`.`访问

2023-09-01 06:00 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/models/network_model_batch.py
> +        """
1. 英文句子开头大写，末尾加上句号`.`
2. Returns 字段去掉
3. doctsring 移动至Networkn下方，不需要放在__init__里

2023-09-01 06:00 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/models/network_model_batch.py
> +        ), "Examples of activation function: R, L, BR, BL, IR, IL"
对于入参的检查用if xxx: raise XXXError，assert是对于内部开发者生成的变量进行检查的，不是一个用于检查入参的手段。尽量不要滥用assert代替raise xxxError

2023-09-01 06:00 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/models/network_model_batch.py
> +import models.basicblock as B
不要as B，程序编写尽量不要使用单个字符，可以as Block或者直接用basicblock即可

2023-09-01 06:00 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/utils/Mydataset.py
> +        )
1. paddle 的 Dataset.__getitem__是不需要手动转tensor的，转tensor会在组batch`collate_fn`内部自动进行，所以删掉to_tensor的操作
2. astype操作应该在__init__就转换完毕

2023-09-01 06:00 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/main.py
> +        )
这里的写法不对，学习率初始化不依赖于optimizer，所以`CosineAnnealingWarmUpRestarts`需要进行改写，然后这里同步改动

2023-09-01 06:00 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/utils/cosine_annealing_with_warmup.py
> +        self.optimizer.set_lr(self.get_lr()[0])
1. optimizer会自动读取lr的学习率作为当前学习率，为什么需要手动给optimizer设置学习率呢
2. 这里建议改成正常的Lrscheduler的写法，去掉对optimizer的依赖，并且改完之后跟原来的学习率保持一致（这可以通过在训练过程中调用`optimizer.get_lr()`确认）

2023-09-01 06:00 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/utils/pixelshuffle1d.py
> +
\+ from paddle import nn

2023-09-01 06:00 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/utils/pixelshuffle1d.py
> +class PixelShuffle1D(paddle.nn.Layer):
paddle.nn.Layer ==> nn.Layer

2023-09-01 06:00 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/utils/pixelshuffle1d.py
> +class PixelUnshuffle1D(paddle.nn.Layer):
同上

2023-09-01 06:00 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/utils/util.py
> +from .Mydataset import MapDataset
同模块导入写法问题，修改一下

2023-09-01 06:00 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/utils/util.py
> +    return config
参数改为一个`config_path`即可

2023-09-01 06:00 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/utils/util.py
> +def get_dataset(DATA_PATH, datafile_name, podfile_name):
参数用小写`DATA_PATH`

2023-09-01 06:00 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/utils/util.py
> +
删除空行

2023-09-01 06:00 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/utils/util.py
> +        batch_size=8,
这里改为4或者2吧，8太大了

2023-09-01 06:00 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/utils/util.py
> +        num_workers=5,
改为4

2023-09-01 06:00 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/utils/util.py
> +        if config["Scheduler"] == 1:
=> `if config["Scheduler"]:`

2023-09-01 06:00 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/utils/util.py
> +            "Timecal": Timecal,
确认一下`Timecal`是否是有用的

2023-09-01 06:00 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/utils/util.py
> +        # plt.xlabel('wavelength (nm)')
无用注释可以删掉

2023-09-01 06:00 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/utils/util.py
> +        plt.plot(wv, model(testshow.unsqueeze(1))[i].squeeze().numpy())
每次模型推理输入数据看起来是一样的，可以先把`model(testshow.unsqueeze(1))`存到for循环的外面，然后再在for循环里面访问结果的不同位置

2023-09-01 06:00 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/utils/util.py
> +                model(testshow.unsqueeze(1))[i].squeeze().numpy()
同上

2023-09-01 08:35 UTC, co63oc commented on jointContribution/DU_CNN/.gitignore
> +utils/__pycache__/
1

2023-09-01 08:35 UTC, co63oc commented on jointContribution/DU_CNN/CHANGE.md
1

2023-09-01 08:35 UTC, co63oc commented on jointContribution/DU_CNN/README.md
1

2023-09-01 08:35 UTC, co63oc commented on jointContribution/DU_CNN/config.yaml
> +Randomintensity: True
1

2023-09-01 08:35 UTC, co63oc commented on jointContribution/DU_CNN/config.yaml
> +learning_rate: 1e-5
1

2023-09-01 08:35 UTC, co63oc commented on jointContribution/DU_CNN/config.yaml
> +pod_data_name: "poddata.mat"
1

2023-09-01 08:35 UTC, co63oc commented on jointContribution/DU_CNN/main.py
> +from utils.cosine_annealing_with_warmup import CosineAnnealingWarmUpRestarts
1

2023-09-01 08:35 UTC, co63oc commented on jointContribution/DU_CNN/main.py
> +    config = util.load_config(CONFIG_PATH, "config.yaml")
1

2023-09-01 08:35 UTC, co63oc commented on jointContribution/DU_CNN/main.py
> +    )
1

2023-09-01 08:35 UTC, co63oc commented on jointContribution/DU_CNN/main.py
> +    FPATH = util.setup_log_directory(config)
1

2023-09-01 08:35 UTC, co63oc commented on jointContribution/DU_CNN/main.py
> +        learning_rate=float(config["learning_rate"]),
1

2023-09-01 08:35 UTC, co63oc commented on jointContribution/DU_CNN/main.py
> +    if config["Scheduler"] == 1:
1

2023-09-01 08:35 UTC, co63oc commented on jointContribution/DU_CNN/main.py
> +        )
但是如果不设置optimizer的学习率，Loss会偏大
optimizer.set_lr(scheduler.get_lr()[0])

原Loss是0.0003
![图片](https://github.com/PaddlePaddle/PaddleScience/assets/4617245/da649f77-4b93-44e4-864c-1915854084b9)

2023-09-01 08:35 UTC, co63oc commented on jointContribution/DU_CNN/main.py
> +    epoch, loss_, evalloss_, Timecal = (
已删除

2023-09-01 08:35 UTC, co63oc commented on jointContribution/DU_CNN/models/basicblock.py
> +import paddle.nn as nn
1

2023-09-01 08:35 UTC, co63oc commented on jointContribution/DU_CNN/models/basicblock.py
> +"""
1

2023-09-01 08:35 UTC, co63oc commented on jointContribution/DU_CNN/models/basicblock.py
> +def sequential(*args):
1

2023-09-01 08:35 UTC, co63oc commented on jointContribution/DU_CNN/models/basicblock.py
> +    """
1

2023-09-01 08:35 UTC, co63oc commented on jointContribution/DU_CNN/models/network_model_batch.py
> +import models.basicblock as B
1

2023-09-01 08:35 UTC, co63oc commented on jointContribution/DU_CNN/models/network_model_batch.py
> +from utils.pixelshuffle1d import PixelUnshuffle1D
1

2023-09-01 08:35 UTC, co63oc commented on jointContribution/DU_CNN/models/network_model_batch.py
> +        """
1

2023-09-01 08:35 UTC, co63oc commented on jointContribution/DU_CNN/models/network_model_batch.py
> +        ), "Examples of activation function: R, L, BR, BL, IR, IL"
1

2023-09-01 08:35 UTC, co63oc commented on jointContribution/DU_CNN/utils/Mydataset.py
> +        )
1

2023-09-01 08:35 UTC, co63oc commented on jointContribution/DU_CNN/utils/cosine_annealing_with_warmup.py
1

2023-09-01 08:35 UTC, co63oc commented on jointContribution/DU_CNN/utils/cosine_annealing_with_warmup.py
> +        self.optimizer.set_lr(self.get_lr()[0])
如果不设置optimizer的学习率，Loss会偏大
optimizer.set_lr(scheduler.get_lr()[0])

原Loss是0.0003
![图片](https://github.com/PaddlePaddle/PaddleScience/assets/4617245/d9ee6090-d220-4ba0-a300-1840dd644669)

2023-09-01 08:35 UTC, co63oc commented on jointContribution/DU_CNN/utils/pixelshuffle1d.py
> +
1

2023-09-01 08:35 UTC, co63oc commented on jointContribution/DU_CNN/utils/pixelshuffle1d.py
> +class PixelShuffle1D(paddle.nn.Layer):
1

2023-09-01 08:35 UTC, co63oc commented on jointContribution/DU_CNN/utils/pixelshuffle1d.py
> +class PixelUnshuffle1D(paddle.nn.Layer):
1

2023-09-01 08:35 UTC, co63oc commented on jointContribution/DU_CNN/utils/util.py
> +from .Mydataset import MapDataset
1

2023-09-01 08:35 UTC, co63oc commented on jointContribution/DU_CNN/utils/util.py
> +    return config
1

2023-09-01 08:35 UTC, co63oc commented on jointContribution/DU_CNN/utils/util.py
> +def get_dataset(DATA_PATH, datafile_name, podfile_name):
1

2023-09-01 08:35 UTC, co63oc commented on jointContribution/DU_CNN/utils/util.py
> +
1

2023-09-01 08:35 UTC, co63oc commented on jointContribution/DU_CNN/utils/util.py
> +        num_workers=5,
1

2023-09-01 08:35 UTC, co63oc commented on jointContribution/DU_CNN/utils/util.py
> +        batch_size=8,
1

2023-09-01 08:35 UTC, co63oc commented on jointContribution/DU_CNN/utils/util.py
> +        if config["Scheduler"] == 1:
1

2023-09-01 08:35 UTC, co63oc commented on jointContribution/DU_CNN/utils/util.py
> +            "Timecal": Timecal,
已删除

2023-09-01 08:35 UTC, co63oc commented on jointContribution/DU_CNN/utils/util.py
> +        # plt.xlabel('wavelength (nm)')
1

2023-09-01 08:35 UTC, co63oc commented on jointContribution/DU_CNN/utils/util.py
> +        plt.plot(wv, model(testshow.unsqueeze(1))[i].squeeze().numpy())
1

2023-09-01 08:35 UTC, co63oc commented on jointContribution/DU_CNN/utils/util.py
> +                model(testshow.unsqueeze(1))[i].squeeze().numpy()
1

2023-09-01 12:07 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/main.py
> +        )
> 但是如果不设置optimizer的学习率，Loss会偏大 optimizer.set_lr(scheduler.get_lr()[0])
> 
> 原Loss是0.0003 ![图片](https://user-images.githubusercontent.com/4617245/264967685-da649f77-4b93-44e4-864c-1915854084b9.png)

这块可以把改之前、改之后、pytorch三者的学习率在所有step上打印出来进行对比，在optimizer.step()的前一行打印学习率，这样是最准的，代码如下：

``` py
# pytorch
print(optimizer.param_groups[0]["lr"])

# paddle
optimizer.get_lr()

optimizer.step()
```

我估计是某些改动会导致step跟pytorch错位了1步

2023-09-01 12:09 UTC, HydrogenSulfate requested changes

2023-09-01 12:09 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/utils/lr_scheduler.py
> +        self.last_epoch = math.floor(epoch)
这是什么操作，epoch是int类型为什么需要floor。。。

2023-09-01 22:24 UTC, co63oc commented on jointContribution/DU_CNN/utils/lr_scheduler.py
> +        self.last_epoch = math.floor(epoch)
计算过程中可能为小数，floor是向下取整

2023-09-01 22:27 UTC, co63oc commented on jointContribution/DU_CNN/main.py
> +        )
不是错位，原有代码有设置lr 
https://github.com/ytg7146/DU_CNN/blob/b1024dfb9d61decad1e58e643cc9418715ff47f1/utils/cosine_annealing_with_warmup.py#L56 
![图片](https://github.com/PaddlePaddle/PaddleScience/assets/4617245/5052a062-26ad-46c2-ae9c-4f8b5f2e3987)

2023-09-02 06:01 UTC, HydrogenSulfate requested changes

2023-09-02 06:01 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/utils/lr_scheduler.py
> +        self.last_epoch = math.floor(epoch)
> 计算过程中可能为小数，floor是向下取整

你代码里的step调用没有传入epoch参数，所以执行58行，这里epoch只会被修改为self.last_epoch+1，感觉没有遇到epoch为小数的情况啊

2023-09-02 08:06 UTC, co63oc commented on jointContribution/DU_CNN/utils/lr_scheduler.py
> +        self.last_epoch = math.floor(epoch)
![图片](https://github.com/PaddlePaddle/PaddleScience/assets/4617245/f8678b7c-b172-4a8e-bf3c-9904155c9bda)

paddle中有参数指定last_epoch ，这里step的epoch参数是指定上一轮epoch测试，
step 传入 epoch参数可能为小数，和T_mult计算

2023-09-02 08:49 UTC, HydrogenSulfate requested changes

2023-09-02 08:49 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/models/network_model_batch.py
> +        act_mode (string): Batch norm + activation function; 'BR' means BN+ReLU.
1. string ==> str
2. 带默认参数的docstring结尾加上 `Defaults to 默认参数.`

2023-09-02 08:49 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/.gitignore
> +data/rawdataM.mat
结尾添加空行

2023-09-02 08:49 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/models/basicblock.py
> +            L.append(nn.ReLU())
两行可以合并： `if t in ("R", "r"):`

2023-09-02 08:49 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/models/basicblock.py
> +            L.append(nn.LeakyReLU(negative_slope=negative_slope))
同上，可以合并

2023-09-02 08:49 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/models/basicblock.py
> +    """
句子结尾加上英文句号

2023-09-02 08:49 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/utils/lr_scheduler.py
> +from paddle.optimizer.lr import LRScheduler
==> `from paddle.optimizer import lr`

2023-09-02 08:49 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/utils/mydataset.py
> +from paddle.io import Dataset
==> `from paddle import io`

2023-09-02 08:49 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/utils/util.py
> +from paddle.io import DataLoader
==> `from paddle import io`

2023-09-02 08:49 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/utils/util.py
> +    return output_dir
==>
``` py
output_dir = f"./{nlayer}layers_{nkernel}kernel_{nchannel}channel_down{ndownsample}_loss{lossnum}"
output_logs_dir = os.path.join(output_dir, "logs")
os.makedirs(output_logs_dir, exist_ok=True)
return output_dir
```

2023-09-02 08:49 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/utils/util.py
> +def load_network(PATH, model, optimizer):
形参用小写

2023-09-02 08:49 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/utils/util.py
> +                ).astype(paddle.get_default_dtype())
==> `paddle.get_default_dtype()`作为to_tensor的dtype参数传入

2023-09-02 08:49 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/utils/util.py
> +            optimizer.set_lr(scheduler.get_lr()[0])
`optimizer.set_lr(scheduler.get_lr()[0])` 这行代码是必要的吗，没有应该也没事儿？
optimizer.set_lr常见于用于不使用lr_scheduler，手动计算学习率的情况；在使用scheduler的情况下，不会再手动调用optimizer.set_lr

2023-09-02 08:49 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/utils/util.py
> +            (label).subtract(randint * poddata["snapshot_mean"]), poddata["V"]
label两侧多余括号可以去掉

2023-09-02 08:49 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/utils/util.py
> +            (output.squeeze()).subtract(randint * poddata["snapshot_mean"]),
output.squeeze()两侧多余括号可以去掉

2023-09-02 08:49 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/utils/util.py
> +            (output.squeeze()).subtract(randint * poddata["snapshot_mean"]),
同上

2023-09-02 08:49 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/utils/util.py
> +            (label).subtract(randint * poddata["snapshot_mean"]), poddata["V"]
同上

2023-09-02 08:49 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/utils/util.py
> +        loss = criterion(normouputpca, normlabelpca)
同上

2023-09-02 08:49 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/utils/util.py
> +    )
同样的问题

2023-09-02 08:49 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/utils/util.py
> +    testshow_predict = model(testshow.unsqueeze(1))
感觉这里可以直接转成.numpy，下方用到testshow_predict的位置全部都是要转成numpy的

2023-09-02 08:49 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/utils/util.py
> +        plt.plot(wv, testshow_predict[i].squeeze().numpy())
上面转成numpy，这可以不用转

2023-09-02 08:49 UTC, HydrogenSulfate commented on jointContribution/DU_CNN/utils/util.py
> +            (testshow_predict[i].squeeze().numpy() - testshow_label[i].numpy())
上面转成numpy，这可以不用转

2023-09-02 09:52 UTC, co63oc commented on jointContribution/DU_CNN/utils/util.py
> +            optimizer.set_lr(scheduler.get_lr()[0])
这行需要设置，测试scheduler get_lr的学习率没有自动设置

2023-09-02 09:52 UTC, co63oc commented on jointContribution/DU_CNN/models/network_model_batch.py
> +        act_mode (string): Batch norm + activation function; 'BR' means BN+ReLU.
1

2023-09-02 09:52 UTC, co63oc commented on jointContribution/DU_CNN/.gitignore
> +data/rawdataM.mat
1

2023-09-02 09:52 UTC, co63oc commented on jointContribution/DU_CNN/models/basicblock.py
> +            L.append(nn.ReLU())
1

2023-09-02 09:52 UTC, co63oc commented on jointContribution/DU_CNN/models/basicblock.py
> +            L.append(nn.LeakyReLU(negative_slope=negative_slope))
1

2023-09-02 09:52 UTC, co63oc commented on jointContribution/DU_CNN/models/basicblock.py
> +    """
1

2023-09-02 09:52 UTC, co63oc commented on jointContribution/DU_CNN/utils/lr_scheduler.py
> +from paddle.optimizer.lr import LRScheduler
1

2023-09-02 09:52 UTC, co63oc commented on jointContribution/DU_CNN/utils/mydataset.py
> +from paddle.io import Dataset
1

2023-09-02 09:52 UTC, co63oc commented on jointContribution/DU_CNN/utils/util.py
> +from paddle.io import DataLoader
1

2023-09-02 09:52 UTC, co63oc commented on jointContribution/DU_CNN/utils/util.py
> +    return output_dir
1

2023-09-02 09:53 UTC, co63oc commented on jointContribution/DU_CNN/utils/util.py
> +def load_network(PATH, model, optimizer):
1

2023-09-02 09:53 UTC, co63oc commented on jointContribution/DU_CNN/utils/util.py
> +                ).astype(paddle.get_default_dtype())
1

2023-09-02 09:53 UTC, co63oc commented on jointContribution/DU_CNN/utils/util.py
> +            (label).subtract(randint * poddata["snapshot_mean"]), poddata["V"]
1

2023-09-02 09:53 UTC, co63oc commented on jointContribution/DU_CNN/utils/util.py
> +            (output.squeeze()).subtract(randint * poddata["snapshot_mean"]),
1

2023-09-02 09:53 UTC, co63oc commented on jointContribution/DU_CNN/utils/util.py
> +            (output.squeeze()).subtract(randint * poddata["snapshot_mean"]),
1

2023-09-02 09:53 UTC, co63oc commented on jointContribution/DU_CNN/utils/util.py
> +            (label).subtract(randint * poddata["snapshot_mean"]), poddata["V"]
1

2023-09-02 09:53 UTC, co63oc commented on jointContribution/DU_CNN/utils/util.py
> +        loss = criterion(normouputpca, normlabelpca)
1

2023-09-02 09:53 UTC, co63oc commented on jointContribution/DU_CNN/utils/util.py
> +    )
1

2023-09-02 09:53 UTC, co63oc commented on jointContribution/DU_CNN/utils/util.py
> +    testshow_predict = model(testshow.unsqueeze(1))
1

2023-09-02 09:53 UTC, co63oc commented on jointContribution/DU_CNN/utils/util.py
> +        plt.plot(wv, testshow_predict[i].squeeze().numpy())
1

2023-09-02 09:54 UTC, co63oc commented on jointContribution/DU_CNN/utils/util.py
> +            (testshow_predict[i].squeeze().numpy() - testshow_label[i].numpy())
1

2023-09-05 07:24 UTC, HydrogenSulfate requested changes

2023-09-05 13:05 UTC, co63oc commented
已修改更新last_lr，取消optimizer.set_lr

2023-09-05 13:29 UTC, HydrogenSulfate approved these changes
LGTM

2023-09-06 01:58 UTC, HydrogenSulfate commented
> 已修改更新last_lr，取消optimizer.set_lr

看起来CI卡住了，可以提交一个空的commit刷新一下，`git commit --allow-empty -m "refresh CI"`

2023-09-06 03:37 UTC, merged