Surrogate add doc
PaddlePaddle/PaddleScience pull request #513
Opened 2023-08-30 07:57 UTC by wangguan1995

### PR types

Add doc
### PR changes

Docs
### Describe

Add docs for Aneurysm2D and Pipe flow

2023-08-30 10:51 UTC, HydrogenSulfate requested changes
全文检查一下标题序号、数学符号、代码块的正确性

2023-08-30 10:51 UTC, HydrogenSulfate commented on docs/zh/examples/labelfree_DNN_surrogate.md
> +```
代码行数不对

2023-08-30 10:51 UTC, HydrogenSulfate commented on docs/zh/examples/labelfree_DNN_surrogate.md
> +#### 2.2.4 约束构建
标题序号不正确

2023-08-30 10:51 UTC, HydrogenSulfate commented on docs/zh/examples/labelfree_DNN_surrogate.md
> +    本案例只作为demo展示，尚未进行充分调优，下方部分展示结果可能与 论文复现结果 存在一定差别。
这个删掉

2023-08-30 10:54 UTC, HydrogenSulfate requested changes

2023-08-30 10:54 UTC, HydrogenSulfate commented on docs/images/labelfree_DNN_surrogate/encoded_bc_eq.png
文件删除

2023-08-30 10:54 UTC, HydrogenSulfate commented on docs/images/labelfree_DNN_surrogate/encoded_bc_pipe.png
文件删除

2023-08-30 10:54 UTC, HydrogenSulfate commented on mkdocs.yml
> +          - labelfree_DNN_surrogate: zh/examples/labelfree_DNN_surrogate.md
改成 Labelfree_DNN_surrogate

2023-08-30 10:54 UTC, HydrogenSulfate commented on docs/zh/examples/labelfree_DNN_surrogate.md
末尾加上参考文献章节，参考hPINNs案例

2023-09-01 11:56 UTC, HydrogenSulfate requested changes

2023-09-01 11:56 UTC, HydrogenSulfate commented on docs/zh/examples/labelfree_DNN_surrogate.md
> +    第三个参数是约束方程作用的计算域，此处填入在 [2.3.2 计算域构建](#232) 章节实例化好的 `interior_geom` 即可；
1. 计算域构建代码没放里面
2. 章节号不对

2023-09-01 11:56 UTC, HydrogenSulfate commented on docs/zh/examples/labelfree_DNN_surrogate.md
> +</figure>
对图里的内容稍加说明

2023-09-01 11:56 UTC, HydrogenSulfate commented on docs/zh/examples/labelfree_DNN_surrogate.md
> +    /workspace/wangguan/PaddleScience_Surrogate/examples/aneurysm/aneurysm_flow.py:204:204
所有 ../../images/labelfree_DNN_surrogate/ 替换成 https://paddle-org.bj.bcebos.com/paddlescience/docs/labelfree_DNN_surrogate/

2023-09-01 11:58 UTC, HydrogenSulfate requested changes

2023-09-01 11:58 UTC, HydrogenSulfate commented on docs/zh/examples/labelfree_DNN_surrogate.md
> +``` py linenums="168"
行号不对

2023-09-04 03:05 UTC, HydrogenSulfate requested changes

2023-09-04 03:05 UTC, HydrogenSulfate commented on docs/zh/examples/labelfree_DNN_surrogate.md
> +## 1. 问题简介
==》 背景简介

2023-09-04 03:05 UTC, HydrogenSulfate commented on docs/zh/examples/labelfree_DNN_surrogate.md
> +  ![pipe](../../images/labelfree_DNN_surrogate/aneurysm_result_3.png)
图片路径的前缀改为 `https://paddle-org.bj.bcebos.com/paddlescience/docs/labelfree_DNN_surrogate/`

2023-09-05 01:50 UTC, HydrogenSulfate requested changes

2023-09-05 01:50 UTC, HydrogenSulfate commented on docs/zh/examples/labelfree_DNN_surrogate.md
> +
删除

2023-09-05 01:51 UTC, HydrogenSulfate requested changes

2023-09-05 01:51 UTC, HydrogenSulfate commented on docs/zh/examples/labelfree_DNN_surrogate.md
> +### 3.3 完整代码
3后面加上.

2023-09-05 01:51 UTC, HydrogenSulfate commented on docs/zh/examples/labelfree_DNN_surrogate.md
> +### 3.4. 结果展示
4后面删除.

2023-09-06 05:35 UTC, HydrogenSulfate requested changes

2023-09-06 05:35 UTC, HydrogenSulfate commented on docs/zh/examples/labelfree_DNN_surrogate.md
> +    第三个参数是约束方程作用的计算域，此处填入在 [3.2.3 计算域构建](#332) 章节实例化好的 `interior_geom` 即可；
`#332==>#323`

2023-09-06 06:06 UTC, HydrogenSulfate approved these changes
LGTM

2023-09-06 06:23 UTC, merged

2023-09-06 07:19 UTC, wangguan1995 commented
撒花