【快乐开源】添加 HamiltonianMonteCarlo API
PaddlePaddle/PaddleScience pull request #523
Opened 2023-09-03 14:41 UTC by yangguohao

### PR types
New features

### PR changes
APIs

### Describe
Add HamiltonianMonteCarlo API
相关 Issues :https://github.com/PaddlePaddle/PaddleScience/issues/450

2023-09-04 02:13 UTC, HydrogenSulfate requested changes

2023-09-04 02:13 UTC, HydrogenSulfate commented on ppsci/probability/hmc.py
> +import paddle
文件开头加上和其他文件一样的license

2023-09-04 02:13 UTC, HydrogenSulfate commented on ppsci/probability/hmc.py
> +    def __init__(self, tensor):
加上type hint

2023-09-04 02:13 UTC, HydrogenSulfate commented on ppsci/probability/hmc.py
> +class HamiltonianMonteCarlo:
docstring补上description

2023-09-04 02:13 UTC, HydrogenSulfate commented on ppsci/probability/hmc.py
> +import paddle
加上一行 `from paddle import distribution`

2023-09-04 02:13 UTC, HydrogenSulfate commented on ppsci/probability/hmc.py
> +        distribution (paddle.distribution.Distribution): The Distribution that need to be sampled.
==> `distribution.Distribution`

2023-09-04 02:13 UTC, HydrogenSulfate commented on ppsci/probability/hmc.py
> +        trial = HMC.run_chain(1000, paddle.to_tensor(0.))
Examples 代码前面加上`>>> `

2023-09-04 02:13 UTC, HydrogenSulfate commented on ppsci/probability/hmc.py
> +        )
minimum的两个实参类型应该都是tensor，这段代码是可以运行的吗？

``` log
ValueError: (InvalidArgument) minimum(): argument 'x' (position 0) must be Tensor, but got int (at ../paddle/fluid/pybind/eager_utils.cc:1005)
```

2023-09-04 08:18 UTC, yangguohao commented on ppsci/probability/hmc.py
> +import paddle
已修改

2023-09-04 08:18 UTC, yangguohao commented on ppsci/probability/hmc.py
> +    def __init__(self, tensor):
已修改

2023-09-04 08:18 UTC, yangguohao commented on ppsci/probability/hmc.py
> +class HamiltonianMonteCarlo:
已修改

2023-09-04 08:18 UTC, yangguohao commented on ppsci/probability/hmc.py
> +import paddle
这里加上后 pre-commit 会提示没有使用到，无法通过因此没有添加

2023-09-04 08:19 UTC, yangguohao commented on ppsci/probability/hmc.py
> +        distribution (paddle.distribution.Distribution): The Distribution that need to be sampled.
同上，仍然保持为 paddle.distribution.Distribution

2023-09-04 08:19 UTC, yangguohao commented on ppsci/probability/hmc.py
> +        trial = HMC.run_chain(1000, paddle.to_tensor(0.))
已修改

2023-09-04 08:19 UTC, yangguohao commented on ppsci/probability/hmc.py
> +        )
已修改

2023-09-05 03:29 UTC, yangguohao commented
@HydrogenSulfate 您好，已经修改了，麻烦再 review 下

2023-09-05 08:22 UTC, yangguohao commented
好的 稍后我补充一下

2023-09-06 08:44 UTC, yangguohao commented
添加了一个单测，pyro 的 model 我没太明白是如何实现的，找了一个比较简单的验证采样方法的准确性。

2023-09-06 08:50 UTC, HydrogenSulfate requested changes

2023-09-06 08:50 UTC, HydrogenSulfate commented on test/probability/test_hmc.py
> +def test_normal(true_mean, true_std):
改成 `test_HamiltonianMonteCarlo` 吧

2023-09-06 12:21 UTC, yangguohao commented on test/probability/test_hmc.py
> +def test_normal(true_mean, true_std):
已修改

2023-09-07 07:17 UTC, HydrogenSulfate commented
还需要在 `docs/zh/api` 添加一个 `probability.md` 文件夹，然后内容参考 `docs/zh/api/equation.md`，这样文档里能看到 `probability` 这个模块和下面的API

2023-09-07 12:02 UTC, yangguohao commented on test/probability/test_hmc.py
已修改

2023-09-07 12:02 UTC, yangguohao commented on ppsci/probability/hmc.py
已添加

2023-09-07 12:02 UTC, yangguohao commented on ppsci/probability/hmc.py
已添加

2023-09-07 12:03 UTC, yangguohao commented
> 还需要在 `docs/zh/api` 添加一个 `probability.md` 文件夹，然后内容参考 `docs/zh/api/equation.md`，这样文档里能看到 `probability` 这个模块和下面的API

等这个 PR 合入后我开始补充

2023-09-07 14:52 UTC, HydrogenSulfate approved these changes
LGTM; TODO: update API document

2023-09-07 14:52 UTC, merged