【快乐开源】迁移 DeepCFD 案例至 PaddleScience
PaddlePaddle/PaddleScience pull request #529
Opened 2023-09-06 14:17 UTC by MayYouBeProsperous

### PR types

Others
### PR changes

Others
### Describe

- https://github.com/PaddlePaddle/PaddleScience/issues/439
参考
-

2023-09-08 02:41 UTC, HydrogenSulfate requested changes

2023-09-11 11:29 UTC, HydrogenSulfate requested changes

2023-09-11 11:29 UTC, HydrogenSulfate commented on ppsci/arch/unetex.py
> +                # 反池化操作，为上采样
==> #  upsample operations

2023-09-12 03:26 UTC, HydrogenSulfate commented
@MayYouBeProsperous review好了，有时间可以修改一下代码

2023-09-12 04:06 UTC, MayYouBeProsperous commented on examples/deepcdf/deepcdf.py
> +def split_tensors(*tensors, ratio):
Done.

2023-09-12 04:06 UTC, MayYouBeProsperous commented on examples/deepcdf/deepcdf.py
> +    assert len(tensors) > 0
Done.

2023-09-12 04:06 UTC, MayYouBeProsperous commented on examples/deepcdf/deepcdf.py
> +        assert len(tensor) == count
Done.

2023-09-12 04:06 UTC, MayYouBeProsperous commented on examples/deepcdf/deepcdf.py
> +    def loss_expr(output_dict, *args):
Done.

2023-09-12 04:06 UTC, MayYouBeProsperous commented on examples/deepcdf/deepcdf.py
> +        output = output_dict["output"]
Done.

2023-09-12 04:06 UTC, MayYouBeProsperous commented on examples/deepcdf/deepcdf.py
> +            )
Done.

2023-09-12 04:06 UTC, MayYouBeProsperous commented on examples/deepcdf/deepcdf.py
> +        ).abs()
Done.

2023-09-12 04:06 UTC, MayYouBeProsperous commented on examples/deepcdf/deepcdf.py
> +        epochs=EPOCHS,
Done.

2023-09-12 04:06 UTC, MayYouBeProsperous commented on examples/deepcdf/deepcdf.py
> +    output_dict = solver.predict({"input": test_x})
Done.

2023-09-12 04:06 UTC, MayYouBeProsperous commented on examples/deepcdf/deepcdf.py
> +        f"Total MSE is {Total_MSE.detach().numpy()[0]}, Ux MSE is {Ux_MSE.detach().numpy()[0]}, Uy MSE is {Uy_MSE.detach().numpy()[0]}, p MSE is {p_MSE.detach().numpy()[0]}"
Done.

2023-09-12 04:06 UTC, MayYouBeProsperous commented on ppsci/arch/__init__.py
> +from ppsci.arch.unetex import UNetEx
Done.

2023-09-12 04:06 UTC, MayYouBeProsperous commented on ppsci/arch/unetex.py
> +from paddle.nn.utils import weight_norm
Done.

2023-09-12 04:06 UTC, MayYouBeProsperous commented on ppsci/arch/unetex.py
> +    bn=True,
Done.

2023-09-12 04:06 UTC, MayYouBeProsperous commented on ppsci/arch/unetex.py
> +    assert kernel_size % 2 == 1
Done.

2023-09-12 04:06 UTC, MayYouBeProsperous commented on ppsci/arch/unetex.py
> +    bn=True,
Done.

2023-09-12 04:06 UTC, MayYouBeProsperous commented on ppsci/arch/unetex.py
> +        )
Done.

2023-09-12 04:06 UTC, MayYouBeProsperous commented on ppsci/arch/unetex.py
> +    bn=True,
Done.

2023-09-12 04:06 UTC, MayYouBeProsperous commented on ppsci/arch/unetex.py
> +    in_channels, filters, kernel_size, wn=True, bn=True, activation=nn.ReLU, layers=2
Done.

2023-09-12 04:06 UTC, MayYouBeProsperous commented on ppsci/arch/unetex.py
> +        encoder = encoder + [encoder_layer]
Done.

2023-09-12 04:06 UTC, MayYouBeProsperous commented on ppsci/arch/unetex.py
> +    out_channels, filters, kernel_size, wn=True, bn=True, activation=nn.ReLU, layers=2
Done.

2023-09-12 04:06 UTC, MayYouBeProsperous commented on ppsci/arch/unetex.py
> +        output_key (str): Name of function data for output).
Done.

2023-09-12 04:06 UTC, MayYouBeProsperous commented on ppsci/arch/unetex.py
> +        out_channels (int): The output tensor channels.
Done.

2023-09-12 04:06 UTC, MayYouBeProsperous commented on ppsci/arch/unetex.py
> +        layers (int): Number of Decoders. Defaults to 3.
Done.

2023-09-12 04:06 UTC, MayYouBeProsperous commented on ppsci/arch/unetex.py
> +        >>> model = ppsci.arch.ppsci.arch.UNetEx("input", "output", 3, 3, [8, 16, 32, 32], 5, Flase, False), wind_model)
Done.

2023-09-12 04:06 UTC, MayYouBeProsperous commented on ppsci/arch/unetex.py
> +        activation: Optional[paddle.nn.Layer] = nn.ReLU,
Done.

2023-09-12 04:06 UTC, MayYouBeProsperous commented on ppsci/arch/unetex.py
> +        final_activation: Optional[paddle.nn.Layer] = None,
Done.

2023-09-12 04:06 UTC, MayYouBeProsperous commented on ppsci/arch/unetex.py
> +        assert len(filters) > 0
Done.

2023-09-12 04:06 UTC, MayYouBeProsperous commented on ppsci/arch/unetex.py
> +            )
Done.

2023-09-12 04:06 UTC, MayYouBeProsperous commented on ppsci/arch/unetex.py
> +    def decode(self, _x, _tensors, _indices, _sizes):
Done.

2023-09-12 04:06 UTC, MayYouBeProsperous commented on ppsci/arch/unetex.py
> +import paddle.nn as nn
Done.

2023-09-12 04:50 UTC, MayYouBeProsperous commented
> @MayYouBeProsperous review好了，有时间可以修改一下代码

辛苦了，已修改代码

2023-09-12 06:11 UTC, HydrogenSulfate requested changes
LGTM

另外案例文档撰写的时候，数据集下载地址可以填写如下：
- https://paddle-org.bj.bcebos.com/paddlescience/datasets/DeepCFD/dataX.pkl
- https://paddle-org.bj.bcebos.com/paddlescience/datasets/DeepCFD/dataY.pkl

2023-09-12 06:11 UTC, HydrogenSulfate commented on examples/deepcdf/deepcdf.py
> +                "name": "DistributedBatchSampler",
这里应该只需要用 `BatchSampler` 就行了，多卡的情况下会在 `build_dataloader` 中自动替换成 `DistributedBatchSampler`

2023-09-12 06:45 UTC, MayYouBeProsperous commented on examples/deepcdf/deepcdf.py
> +                "name": "DistributedBatchSampler",
Done.

2023-09-12 06:45 UTC, MayYouBeProsperous commented on examples/deepcdf/deepcdf.py
> +      ratio (float): split ratio. For example, tensor list A is split to A1 and A2. len(A1) / len(A) = ratio.
Done.

2023-09-13 08:03 UTC, HydrogenSulfate commented
整个项目的命名是不是错了，应该是CFD而不是CDF，可以改一下

2023-09-15 03:36 UTC, luotao1 commented
> To do: 编写案例文档

记得补充下案例文档哈

2023-09-23 09:37 UTC, HydrogenSulfate requested changes
辛苦大佬写的文档，主要有一些代码上的小问题和文档整体代码块错位，修改后应该可以合了

2023-09-23 09:37 UTC, HydrogenSulfate commented on docs/zh/examples/deepcfd.md
> +数据集官网为：https://zenodo.org/record/3666056/files/DeepCFD.zip?download=1
官网==》原始下载地址

2023-09-23 09:37 UTC, HydrogenSulfate commented on docs/zh/examples/deepcfd.md
> +```
代码块位置不对，
![image](https://github.com/PaddlePaddle/PaddleScience/assets/23737287/f0ee06f1-474f-4583-8a1f-aed17eec8569)

2023-09-23 09:37 UTC, HydrogenSulfate commented on docs/zh/examples/deepcfd.md
> +第三个参数是约束条件的名字，方便后续对其索引。此次命名为 sup_constraint。
sup_constraint ==> `"sup_constraint"`

2023-09-23 09:37 UTC, HydrogenSulfate commented on examples/deepcfd/deepcfd.py
> +        # visualizer=visualizer,
这行注释可以删掉

2023-09-23 09:37 UTC, HydrogenSulfate commented on examples/deepcfd/deepcfd.py
> +                np.transpose(y, (0, 2, 3, 1)).reshape((981 * 172 * 79, 3)) ** 2, axis=0
981、172、79应该属于magic number，可以用全大写变量表示一下

2023-09-23 09:37 UTC, HydrogenSulfate commented on examples/deepcfd/deepcfd.py
> +    DATASET_PATH = "./datasets/deepCDF/"
1. DATASET_PATH移动到205行下面
2. 文档的“数据集介绍”章节添加一下数据集下载命令，参考如下
![image](https://github.com/PaddlePaddle/PaddleScience/assets/23737287/37edbd28-ef04-4bbd-9546-97aeb4ab249d)
3. `./datasets/deepCDF/` 改为 `./datasets` 即可，因为这已经是在`deepcfd`案例文件夹下了

2023-09-23 09:37 UTC, HydrogenSulfate commented on examples/deepcfd/deepcfd.py
> +      ratio (float): Split ratio. For example, tensor list A is split to A1 and A2. len(A1) / len(A) = ratio.
docstring加上返回值
``` py
...

Returns:
    Tuple[List[np.array], List[np.array]]: Splited tensors.
```

2023-09-23 09:37 UTC, HydrogenSulfate commented on examples/deepcfd/deepcfd.py
> +        raise ValueError("Tensors shouldn't be empty.")
38后面空行

2023-09-23 09:37 UTC, HydrogenSulfate commented on examples/deepcfd/deepcfd.py
> +    if len(tensors) == 1:
47前面空行

2023-09-23 09:37 UTC, HydrogenSulfate commented on examples/deepcfd/deepcfd.py
> +def predict_and_save_plot(
同样，docstring加上返回值

2023-09-23 09:37 UTC, HydrogenSulfate commented on examples/deepcfd/deepcfd.py
> +    test_x, test_y = test_dataset[:]
这里是否需要[:]浅复制操作？后续应该不涉及对输入数据的修改吧

2023-09-23 09:37 UTC, HydrogenSulfate commented on examples/deepcfd/deepcfd.py
> +    PLOT_DIR = os.path.join(OUTPUT_DIR, "visu")
visu ==> visual

2023-09-23 09:37 UTC, HydrogenSulfate commented on ppsci/arch/unetex.py
> +        filters (Tuple[int, ...]): Number of filters. Defaults to [16, 32, 64].
1. 默认值非None的参数，docstring中类型后面加上`, optional`，比如： `Tuple[int, ...], optional`
2. 默认值为None的参数，docstring中类型用`Optional[...]`，比如 `Optional[Type[nn.Layer]]`
3. docstring中出现了`paddle.nn.Layer`，这应该是没更新导致的，可以基于autodocstring重新生成最新的docstring进行修改
4. 默认值最好不要使用可变类型如list、dict，可以使用None然后在代码里面对入参判None，赋予默认值；或者使用小括号 `(...)`

2023-09-23 09:42 UTC, HydrogenSulfate requested changes

2023-09-23 09:42 UTC, HydrogenSulfate commented on docs/zh/examples/deepcfd.md
> +```
完整代码可以不加 `:1:304`，直接使用整个文件即可

2023-09-24 02:42 UTC, MayYouBeProsperous reviewed
好的 已按照要求修改了

2023-09-24 02:42 UTC, MayYouBeProsperous commented on docs/zh/examples/deepcfd.md
> +```
Done.

2023-09-24 02:42 UTC, MayYouBeProsperous commented on docs/zh/examples/deepcfd.md
> +数据集官网为：https://zenodo.org/record/3666056/files/DeepCFD.zip?download=1
Done.

2023-09-24 02:42 UTC, MayYouBeProsperous commented on docs/zh/examples/deepcfd.md
> +```
Done.

2023-09-24 02:42 UTC, MayYouBeProsperous commented on docs/zh/examples/deepcfd.md
> +第三个参数是约束条件的名字，方便后续对其索引。此次命名为 sup_constraint。
Done.

2023-09-24 02:42 UTC, MayYouBeProsperous commented on examples/deepcfd/deepcfd.py
> +      ratio (float): Split ratio. For example, tensor list A is split to A1 and A2. len(A1) / len(A) = ratio.
Done.

2023-09-24 02:42 UTC, MayYouBeProsperous commented on examples/deepcfd/deepcfd.py
> +    if len(tensors) == 1:
Done.

2023-09-24 02:42 UTC, MayYouBeProsperous commented on examples/deepcfd/deepcfd.py
> +def predict_and_save_plot(
这个函数没有返回值

2023-09-24 02:42 UTC, MayYouBeProsperous commented on examples/deepcfd/deepcfd.py
> +    DATASET_PATH = "./datasets/deepCDF/"
Done.

2023-09-24 02:42 UTC, MayYouBeProsperous commented on examples/deepcfd/deepcfd.py
> +    test_x, test_y = test_dataset[:]
好的

2023-09-24 02:42 UTC, MayYouBeProsperous commented on examples/deepcfd/deepcfd.py
> +                np.transpose(y, (0, 2, 3, 1)).reshape((981 * 172 * 79, 3)) ** 2, axis=0
Done.

2023-09-24 02:42 UTC, MayYouBeProsperous commented on examples/deepcfd/deepcfd.py
> +        # visualizer=visualizer,
Done.

2023-09-24 02:42 UTC, MayYouBeProsperous commented on examples/deepcfd/deepcfd.py
> +    PLOT_DIR = os.path.join(OUTPUT_DIR, "visu")
Done.

2023-09-24 02:42 UTC, MayYouBeProsperous commented on ppsci/arch/unetex.py
> +        filters (Tuple[int, ...]): Number of filters. Defaults to [16, 32, 64].
好的感谢

2023-09-24 02:42 UTC, MayYouBeProsperous commented on examples/deepcfd/deepcfd.py
> +        raise ValueError("Tensors shouldn't be empty.")
Done.

2023-09-24 08:12 UTC, HydrogenSulfate requested changes

2023-09-24 08:12 UTC, HydrogenSulfate commented on docs/zh/examples/deepcfd.md
> +其中 $\bf{u}$ 是速度差（具有 x 和 y 两个维度），$\rho$ 是密度， $p$ 是压强场，$\bf{f}$ 是体积力（例如重力）。
速度差 ==> 速度场？

2023-09-24 08:12 UTC, HydrogenSulfate commented on docs/zh/examples/deepcfd.md
> +  <figcaption>OpenFOAM 计算结果与 DeepCFD 预测结果对比</figcaption>
1. ==> `OpenFOAM 计算结果与 DeepCFD 预测结果对比，从左到右分别为：水平速度分量（Ux），垂直速度分量（Uy）以及流体压强（p）`

2023-09-24 08:12 UTC, HydrogenSulfate commented on docs/zh/examples/deepcfd.md
> +
图片下面加一句简单结论：可以看到DeepCFD方法与OpenFOAM的结果基本一致

2023-09-24 08:58 UTC, MayYouBeProsperous commented on docs/zh/examples/deepcfd.md
> +
Done.

2023-09-24 08:58 UTC, MayYouBeProsperous commented on docs/zh/examples/deepcfd.md
> +  <figcaption>OpenFOAM 计算结果与 DeepCFD 预测结果对比</figcaption>
Done.

2023-09-24 08:58 UTC, MayYouBeProsperous commented on docs/zh/examples/deepcfd.md
> +其中 $\bf{u}$ 是速度差（具有 x 和 y 两个维度），$\rho$ 是密度， $p$ 是压强场，$\bf{f}$ 是体积力（例如重力）。
Done.

2023-09-24 10:08 UTC, HydrogenSulfate approved these changes
LGTM

2023-09-24 15:13 UTC, merged