PaddleScience 论文复现 Extended Physics-Informed Neural Networks (XPINNs)
PaddlePaddle/PaddleScience pull request #535
Opened 2023-09-09 05:14 UTC by co63oc

### PR types

Others
### PR changes

Others
### Describe

https://github.com/PaddlePaddle/Paddle/issues/55663#paddlepaddle14

赛题十四：PaddleScience 领域经典论文复现
论文一
题目：Extended Physics-Informed Neural Networks (XPINNs)

网络结构已转换一致，但是精度差别较大，代码没有找到问题，不确定是否paddle其他配置问题
Test Loss 信息
| Test Loss | torch | paddle |
| - | - | - |
| | 1.794519e-02 | 8.653355e-01 |

torch运行
![图片](https://github.com/PaddlePaddle/PaddleScience/assets/4617245/34f41d69-80df-42af-aa90-a7025c795863)
Loss
![图片](https://github.com/PaddlePaddle/PaddleScience/assets/4617245/144ee2c8-4fb9-41a0-861a-27e3675a8a0c)

paddle运行
![图片](https://github.com/PaddlePaddle/PaddleScience/assets/4617245/751aae44-5686-4a4d-bdda-da96701da893)
Loss
![图片](https://github.com/PaddlePaddle/PaddleScience/assets/4617245/23a38a31-bbef-41f8-8ef5-1a2f3eaad87c)

2023-09-09 12:58 UTC, HydrogenSulfate requested changes

2023-09-09 12:58 UTC, HydrogenSulfate commented on jointContribution/XPINNs/XPINN_2D_PoissonsEqn.py
> +            loss.clear_grad()
看到精度没对齐，应该是这行的问题？`Tensor.clear_grad` 只能清空 `Tensor` 自己的梯度，梯度更新完应该调用`self.optimizer.clear_grad()`

2023-09-09 13:30 UTC, co63oc commented on jointContribution/XPINNs/XPINN_2D_PoissonsEqn.py
> +            loss.clear_grad()
修改为 self.optimizer.clear_grad() 可以对齐精度

2023-09-11 02:44 UTC, HydrogenSulfate commented on jointContribution/XPINNs/XPINN_2D_PoissonsEqn.py
> +    Max_iter = 701
源代码好像是501，这里为改成701的原因是什么呢

2023-09-11 05:08 UTC, co63oc commented on jointContribution/XPINNs/XPINN_2D_PoissonsEqn.py
> +    Max_iter = 701
是用来对齐精度，迭代501次Loss较大

2023-09-11 06:19 UTC, HydrogenSulfate commented on jointContribution/XPINNs/XPINN_2D_PoissonsEqn.py
> +    Max_iter = 701
> 是用来对齐精度，迭代501次Loss较大

一般论文复现默认使用相同的训练策略，如果转换成paddle后，需要增大epoch来对齐精度，可能是某些地方仍然没有对齐，比如参数初始化之类的细节

2023-09-11 07:29 UTC, co63oc commented on jointContribution/XPINNs/XPINN_2D_PoissonsEqn.py
> +    Max_iter = 701
修改tensorflow 版本1.13.2-gpu，paddle 精度可以对齐

2023-09-11 08:04 UTC, co63oc commented on jointContribution/XPINNs/XPINN_2D_PoissonsEqn.py
> +    Max_iter = 701
> > 修改tensorflow 版本1.13.2-gpu，paddle 精度可以对齐，PR描述已更新
> 
> OK，我运行下试试看

不是tensorflow 版本问题，是代码有改动，我再看下

2023-09-11 08:11 UTC, co63oc commented on jointContribution/XPINNs/XPINN_2D_PoissonsEqn.py
> +    Max_iter = 701
![图片](https://github.com/PaddlePaddle/PaddleScience/assets/4617245/98b6548d-7fba-4adb-a5b1-be91f635e32d)
![图片](https://github.com/PaddlePaddle/PaddleScience/assets/4617245/57dbaff4-cf4f-4747-a229-3468560908db)

使用 paddle.nn.initializer.TruncatedNormal 提示不支持 float64，是支持float32

2023-09-11 09:34 UTC, co63oc commented on jointContribution/XPINNs/XPINN_2D_PoissonsEqn.py
> +    Max_iter = 701
参数有W, b, a，b和a是固定初始值, W使用 XavierNormal和使用 TruncatedNormal  float32精度不对齐

2023-09-11 09:45 UTC, HydrogenSulfate commented on jointContribution/XPINNs/XPINN_2D_PoissonsEqn.py
> +    Max_iter = 701
> 参数有W, b, a，b和a是固定初始值, W使用 XavierNormal和使用 TruncatedNormal float32精度不对齐

PaddleScience里有这个API，看下能不能等价复现一下，https://github.com/PaddlePaddle/PaddleScience/blob/develop/ppsci/utils/initializer.py#L151

2023-09-11 09:49 UTC, co63oc commented on jointContribution/XPINNs/XPINN_2D_PoissonsEqn.py
> +    Max_iter = 701
![图片](https://github.com/PaddlePaddle/PaddleScience/assets/4617245/113f2dbd-76ca-4cec-a0cc-035cd09462b4)
同样错误不支持float64

2023-09-11 09:53 UTC, HydrogenSulfate commented on jointContribution/XPINNs/XPINN_2D_PoissonsEqn.py
> +    Max_iter = 701
> ![图片](https://user-images.githubusercontent.com/4617245/266979994-113f2dbd-76ca-4cec-a0cc-035cd09462b4.png) 同样错误不支持float64

看了一下，是这部分代码有点问题，可以再to_tensor末尾加上, _tensor.dtype

``` py
_tensor = paddle.multiply(_tensor, paddle.to_tensor(std * math.sqrt(2.0), _tensor.dtype))
_tensor = paddle.add(_tensor, paddle.to_tensor(mean, _tensor.dtype))
```

2023-09-11 10:02 UTC, co63oc commented on jointContribution/XPINNs/XPINN_2D_PoissonsEqn.py
> +    Max_iter = 701
![图片](https://github.com/PaddlePaddle/PaddleScience/assets/4617245/3933dfc8-fac7-4939-8432-637e3d768396)
结果为0

2023-09-11 10:20 UTC, co63oc commented on jointContribution/XPINNs/XPINN_2D_PoissonsEqn.py
> +    Max_iter = 701
```
    def xavier_init(self, size):
        in_dim = size[0]
        out_dim = size[1]        
        import ppsci
        param = paddle.empty(size, "float64")
        param = ppsci.utils.initializer.trunc_normal_(param, 0.0, 1.0)
        return paddle.nn.initializer.Assign(param)
```

paddle.nn.initializer.Assign 不支持float64
![图片](https://github.com/PaddlePaddle/PaddleScience/assets/4617245/c8ac51bc-6573-4b42-926b-7cdb06ee71ee)

2023-09-11 11:23 UTC, HydrogenSulfate commented on jointContribution/XPINNs/XPINN_2D_PoissonsEqn.py
> +    Max_iter = 701
> 

暂时用lambda代替下看看
``` py
import numpy as np

x_np = np.zeros([2, 2], "float64")

w = paddle.create_parameter(
    x_np.shape,
    dtype="float64",
    default_initializer=lambda p_ten, _: p_ten.set_value(x_np)
)

print(w)

"""
Tensor(shape=[2, 2], dtype=float64, place=Place(gpu:0), stop_gradient=False,
       [[0., 0.],
        [0., 0.]])
"""
```

2023-09-11 11:37 UTC, co63oc commented on jointContribution/XPINNs/XPINN_2D_PoissonsEqn.py
> +    Max_iter = 701
修改后精度为 4.684577e-02, tensorflow精度是 1.794519e-02
```
    def w_init(self, size):
        in_dim = size[0]
        out_dim = size[1]        
        xavier_stddev = np.sqrt(2/(in_dim + out_dim))
        param = paddle.empty(size, "float64")
        param = ppsci.utils.initializer.trunc_normal_(param, 0.0, xavier_stddev)
        return lambda p_ten, _: p_ten.set_value(param)
```

![图片](https://github.com/PaddlePaddle/PaddleScience/assets/4617245/34e5492d-cad9-435d-945b-04b10c5c30af)

2023-09-11 11:41 UTC, HydrogenSulfate commented on jointContribution/XPINNs/XPINN_2D_PoissonsEqn.py
> +    Max_iter = 701
> 修改后精度为 4.684577e-02, tensorflow精度是 1.794519e-02
> 
> ```
>     def w_init(self, size):
>         in_dim = size[0]
>         out_dim = size[1]        
>         xavier_stddev = np.sqrt(2/(in_dim + out_dim))
>         param = paddle.empty(size, "float64")
>         param = ppsci.utils.initializer.trunc_normal_(param, 0.0, xavier_stddev)
>         return lambda p_ten, _: p_ten.set_value(param)
> ```
> 
> ![图片](https://user-images.githubusercontent.com/4617245/267006248-34e5492d-cad9-435d-945b-04b10c5c30af.png)

分布相同的情况下，两个框架生成的随机数也是存在不同的，这个diff大概率是合理的，我这边明天换个随机种子再跑下paddle看看

2023-09-12 11:25 UTC, HydrogenSulfate requested changes

2023-09-12 11:25 UTC, HydrogenSulfate commented on jointContribution/XPINNs/README.md
> +安装latex软件包，python依赖
详细说明下latex软件包怎么安装的，我这边pip 安装latex仍然会报错

2023-09-12 12:40 UTC, co63oc commented on jointContribution/XPINNs/README.md
> +安装latex软件包，python依赖
下面有代码
![图片](https://github.com/PaddlePaddle/PaddleScience/assets/4617245/d1c1b6fa-0a6d-4139-a2e3-839e913d89c2)

2023-09-12 12:40 UTC, co63oc commented on jointContribution/XPINNs/XPINN_2D_PoissonsEqn.py
> +        return lambda p_ten, _: p_ten.set_value(param)
1

2023-09-12 12:41 UTC, co63oc commented on jointContribution/XPINNs/XPINN_2D_PoissonsEqn.py
> +        return weights, biases, A
修改为 amplitudes

2023-09-12 12:41 UTC, co63oc commented on jointContribution/XPINNs/.gitignore
1

2023-09-13 07:29 UTC, HydrogenSulfate approved these changes
LGTM

2023-09-13 07:29 UTC, merged