赛题十五：PIRBN 子目录 1D_nonlinear_spring
PaddlePaddle/PaddleScience pull request #536
Opened 2023-09-12 09:13 UTC by co63oc

### PR types

Others 
### PR changes

Others 
### Describe

https://github.com/PaddlePaddle/Paddle/issues/55663

赛题十五：PaddleScience 领域前沿论文复现
实现 子目录 1D_nonlinear_spring

测试精度L1
| - | Tensorflow | Paddle |
| - | - | - |
| L1 | 3.83261e-05 | 7.71585e-05 |

Tensorflow 运行
![图片](https://github.com/PaddlePaddle/PaddleScience/assets/4617245/63dbd446-3065-4782-92a0-ff0137cc030b)

Paddle运行
![图片](https://github.com/PaddlePaddle/PaddleScience/assets/4617245/6bf62664-ab97-4420-95ff-39fadea3a528)

2023-09-13 04:49 UTC, wangguan1995 requested changes
NTK plot needs to be implemented.

2023-09-13 04:49 UTC, wangguan1995 commented on jointContribution/PIRBN/1D_nonlinear_spring/rbn_net.py
> +    def forward(self, inputs):  # Defines the computation from inputs to outputs
此处应该是用了类似论文Page13的激活函数
尝试单独抽象出激活函数 def activate（）

2023-09-13 04:49 UTC, wangguan1995 commented on jointContribution/PIRBN/requirements.txt
> +numpy
这个requirements在PaddleScience主目录下已经有了
如果有新的库需要添加，请加到主目录下的requirement.txt

2023-09-13 23:26 UTC, co63oc commented on jointContribution/PIRBN/1D_nonlinear_spring/OPT.py
> +class Adam:
已修改Adam

2023-09-13 23:33 UTC, co63oc commented on jointContribution/PIRBN/1D_nonlinear_spring/Cal_jac.py
> +def cal_adapt(pirbn, x):
修改为 pirbn.cal_ntk ，变量为  Kg
已增加引用公式页
可视化为 analytical_solution.output_fig subplot(2, 3, 4)

使用原tensorflow代码https://github.com/JinshuaiBai/PIRBN/tree/main/1D_sine_function，显示图和论文图Fig.1不同，设置参数mu=4, b=10.0
```
### Define mu
mu = 4

### Define the number of sample points
ns = 51

### Define the sample points' interval
dx = 1./(ns-1)

### Initialise sample points' coordinates
xy = np.zeros((ns, 1)).astype(np.float32)
for i in range(0, ns):
    xy[i, 0] = i * dx
xy_b = np.array([[0.], [1.]])

x = [xy, xy_b]
y = [-4*mu**2*np.pi**2*np.sin(2*mu*np.pi*xy)]

### Set up raidal basis network
n_in = 1
n_out = 1
n_neu = 61
b=10.
c = [-0.1, 1.1]
```
![图片](https://github.com/PaddlePaddle/PaddleScience/assets/4617245/f920ef58-8283-4db9-985a-39ec3a9d6dac)
原论文图
![图片](https://github.com/PaddlePaddle/PaddleScience/assets/4617245/f1358037-2ba9-47f5-a4bb-981a89b62c3a)

2023-09-13 23:34 UTC, co63oc commented on jointContribution/PIRBN/1D_nonlinear_spring/Main.py
> +plt.plot(xy, xy * np.sin(xy))
1

2023-09-13 23:34 UTC, co63oc commented on jointContribution/PIRBN/1D_nonlinear_spring/Main.py
> +plt.savefig(os.path.join(target_dir, "1D_nonlinear_spring.png"))
analytical_solution 子图 plt.subplot(2, 3, 2) 计算absolute error

2023-09-13 23:34 UTC, co63oc commented on jointContribution/PIRBN/1D_nonlinear_spring/OPT.py
> +class Adam:
1

2023-09-13 23:41 UTC, co63oc commented on jointContribution/PIRBN/1D_nonlinear_spring/rbn_net.py
> +    def forward(self, inputs):  # Defines the computation from inputs to outputs
设置激活函数 RBF_layer1.rbf_activate

2023-09-13 23:41 UTC, co63oc commented on jointContribution/PIRBN/requirements.txt
> +numpy
1

2023-09-19 00:36 UTC, co63oc commented on jointContribution/PIRBN/README.md
> +      **PDE**: $\frac{\partial^2 }{\partial x^2}u(x)-4\mu^2\pi^2 sin(2\mu\pi(x))=0, x\in[0,1]$
Fig1, Fig2, Fig3 使用tanh和论文不一致

Fig6改变激活函数和论文一致
Fig1 
![图片](https://github.com/PaddlePaddle/PaddleScience/assets/4617245/9f15b2e0-e888-4075-b556-f732d7f2176d)
Fig2
![图片](https://github.com/PaddlePaddle/PaddleScience/assets/4617245/581ff322-82aa-4a53-a058-b16a650998aa)
Fig3
![图片](https://github.com/PaddlePaddle/PaddleScience/assets/4617245/1025df39-e9d9-4ead-bf55-9215615c26a2)
Fig6
![图片](https://github.com/PaddlePaddle/PaddleScience/assets/4617245/88465466-38ea-4ffd-8db2-730ab985fa67)

公式和源码是一致 
![图片](https://github.com/PaddlePaddle/PaddleScience/assets/4617245/1f7ce35c-0aaa-4c93-9065-5a195008ebc5)

2023-09-19 00:36 UTC, co63oc commented on jointContribution/PIRBN/pirbn.py
> +class Dif(paddle.nn.Layer):
1

2023-09-19 00:37 UTC, co63oc commented on jointContribution/PIRBN/pirbn.py
> +        # Formula (4), Page5, \gamma variable
https://arxiv.org/ftp/arxiv/papers/2304/2304.06234.pdf
![图片](https://github.com/PaddlePaddle/PaddleScience/assets/4617245/571dcf59-78ab-48f1-9982-19b2bd968ca9)

2023-09-19 00:39 UTC, co63oc commented on jointContribution/PIRBN/pirbn.py
> +                # Fig.1, Page8, Kg variable
https://arxiv.org/ftp/arxiv/papers/2304/2304.06234.pdf

![图片](https://github.com/PaddlePaddle/PaddleScience/assets/4617245/a4c8a0dc-2a5b-43ad-8682-118b1f043be1)

2023-09-19 00:39 UTC, co63oc commented on jointContribution/PIRBN/train.py
> +        return loss, [self.his_l1, self.his_l2]
1

2023-09-19 00:39 UTC, co63oc commented on jointContribution/PIRBN/pirbn.py
> +        gamma_g = 0.0
1

2023-09-19 00:39 UTC, co63oc commented on jointContribution/PIRBN/pirbn.py
> +        gamma_b = 0.0
1

2023-09-19 00:40 UTC, co63oc commented on jointContribution/PIRBN/train.py
> +        self.his_l2 = []
1

2023-09-19 00:40 UTC, co63oc commented on jointContribution/PIRBN/train.py
> +        loss, l1, l2 = self.Loss(self.x_train, self.y_train, self.a_g, self.a_b)
1

2023-09-19 00:41 UTC, co63oc commented on jointContribution/PIRBN/rbn_net.py
> +        return self.rbf_activate(x_new)
https://arxiv.org/ftp/arxiv/papers/2304/2304.06234.pdf
是在Page10
![图片](https://github.com/PaddlePaddle/PaddleScience/assets/4617245/da8bc9bf-7516-48a2-b57a-a62f96e9f3c1)

2023-09-19 01:12 UTC, co63oc commented on jointContribution/PIRBN/README.md
> +      **PDE**: $\frac{\partial^2 }{\partial x^2}u(x)-4\mu^2\pi^2 sin(2\mu\pi(x))=0, x\in[0,1]$
不同激活函数设置
```
    def gaussian_function(self, temp_x):
        x0 = (
            paddle.reshape(
                paddle.arange(self.n_neu, dtype=paddle.get_default_dtype()),
                (1, self.n_neu),
            )
            * (self.c[1] - self.c[0])
            / (self.n_neu - 1)
            + self.c[0]
        )
        x_new = temp_x - x0
        s = self.b * self.b
        return paddle.exp(-(x_new * x_new) * s)

    def tanh_function(self, temp_x):
        return paddle.tanh(temp_x)
```

2023-09-19 11:19 UTC, wangguan1995 requested changes
need debug for fig 1

2023-09-19 11:19 UTC, wangguan1995 commented on jointContribution/PIRBN/train.py
> +# Used to calculate the second-order derivatives
删掉

2023-09-20 03:19 UTC, co63oc commented on jointContribution/PIRBN/train.py
> +# Used to calculate the second-order derivatives
已增加 PINN 目录运行PINN.py, Kg结果图
![图片](https://github.com/PaddlePaddle/PaddleScience/assets/4617245/d3a4c25b-241d-4aa5-af53-b500913bb68d)

Page页码已修改

注释已删除 
![图片](https://github.com/PaddlePaddle/PaddleScience/assets/4617245/da6662c9-d69b-48c2-8d2d-fa3472acb805)

2023-10-16 11:17 UTC, wangguan1995 reviewed
need to fix

2023-10-16 11:17 UTC, wangguan1995 commented on jointContribution/PIRBN/rbn_net.py
> +            # self.add_parameter(f"W_{l}", W)
删除

2023-10-16 11:17 UTC, wangguan1995 commented on docs/zh/examples/pirbn.md
> +PIRBN 案例针对 epoch=20001 和 learning\_rate=1e-3 的参数配置进行了实验，结果返回Loss为 0.13567。
图片发给我，几个图分别解释下，按照论文的图片题注进行翻译

2023-10-16 11:17 UTC, wangguan1995 commented on jointContribution/PIRBN/main.py
> +# # # Fig.2
uncomment

2023-10-16 11:17 UTC, wangguan1995 commented on docs/zh/examples/pirbn.md
> +## 1. 背景简介
<img width="684" alt="image" src="https://github.com/PaddlePaddle/PaddleScience/assets/39621324/41b9c88d-4ce3-4bca-834e-16a7e9da851f">
加点图片

2023-10-16 11:17 UTC, wangguan1995 commented on docs/zh/examples/pirbn.md
> +## 1. 背景简介
顺便说明一下
<img width="855" alt="image" src="https://github.com/PaddlePaddle/PaddleScience/assets/39621324/5ae7e7b9-5d9d-4a3e-b3de-b6467c76b27a">
不同阶数的高斯激活函数

2023-10-16 11:17 UTC, wangguan1995 commented on jointContribution/PIRBN/main.py
> +    # x_bc = np.ones((50, 1))
删除无用行

2023-10-16 11:17 UTC, wangguan1995 commented on jointContribution/PIRBN/main.py
> +    # print(y[:10])
删除调试行

2023-10-16 11:17 UTC, wangguan1995 commented on jointContribution/PIRBN/main.py
> +    # paddle.summary(rbn, input=paddle.to_tensor(x_eq))
删除调试行

2023-10-16 11:17 UTC, wangguan1995 commented on jointContribution/PIRBN/rbn_net.py
> +            # w = paddle.load("./PINN/w.tensor")
删除调试行

2023-10-16 11:54 UTC, co63oc commented on jointContribution/PIRBN/rbn_net.py
> +            # self.add_parameter(f"W_{l}", W)
1

2023-10-16 11:54 UTC, co63oc commented on jointContribution/PIRBN/main.py
> +# # # Fig.2
1

2023-10-16 11:54 UTC, co63oc commented on jointContribution/PIRBN/main.py
> +    # x_bc = np.ones((50, 1))
1

2023-10-16 11:54 UTC, co63oc commented on jointContribution/PIRBN/main.py
> +    # print(y[:10])
1

2023-10-16 11:54 UTC, co63oc commented on jointContribution/PIRBN/main.py
> +    # paddle.summary(rbn, input=paddle.to_tensor(x_eq))
1

2023-10-16 11:54 UTC, co63oc commented on jointContribution/PIRBN/rbn_net.py
> +            # w = paddle.load("./PINN/w.tensor")
1

2023-10-17 08:33 UTC, wangguan1995 reviewed
need fix

2023-10-17 08:33 UTC, wangguan1995 commented on docs/zh/examples/pirbn.md
> +jointContribution/PIRBN/main.py:47:47
![image](https://github.com/PaddlePaddle/PaddleScience/assets/39621324/3fd9c1ae-9368-4c3c-b409-297e443534a5)
行数不对

2023-10-17 08:51 UTC, co63oc commented on docs/zh/examples/pirbn.md
> +jointContribution/PIRBN/main.py:47:47
已修改

2023-10-17 10:40 UTC, wangguan1995 approved these changes
Pass

2023-10-17 11:07 UTC, HydrogenSulfate requested changes

2023-10-17 11:07 UTC, HydrogenSulfate commented on jointContribution/PIRBN/rbn_net.py
> +        b (List[float32]|float32): Initial value for hyperparameter b.
1. Union[List[float], float]
2. List[float]
3. 加上 `activation_function` 的说明

2023-10-17 11:07 UTC, HydrogenSulfate commented on jointContribution/PIRBN/rbn_net.py
> +            # b.shape == [1]
删除该行

2023-10-17 11:07 UTC, HydrogenSulfate commented on jointContribution/PIRBN/rbn_net.py
> +                shape=[1, 1],
shape=b[1].shape

2023-10-17 11:07 UTC, HydrogenSulfate commented on jointContribution/PIRBN/rbn_net.py
> +
删除空行

2023-10-17 11:07 UTC, HydrogenSulfate commented on jointContribution/PIRBN/rbn_net.py
> +    def ini_ab(self):
ini_ab是什么含义呢，建议改成具体英文名字，ini->init

2023-10-17 11:07 UTC, HydrogenSulfate commented on jointContribution/PIRBN/train.py
> +        # self.x_train = [self.X_r, self.X_u]
如果这里的代码没有用到的话，可以删除

2023-10-17 11:07 UTC, HydrogenSulfate commented on jointContribution/PIRBN/README.md
添加训练命令

2023-10-17 12:14 UTC, co63oc commented on jointContribution/PIRBN/jacobian_test.py
1

2023-10-17 12:14 UTC, co63oc commented on jointContribution/PIRBN/rbn_net.py
> +        b (List[float32]|float32): Initial value for hyperparameter b.
1

2023-10-17 12:14 UTC, co63oc commented on jointContribution/PIRBN/rbn_net.py
> +            # b.shape == [1]
1

2023-10-17 12:14 UTC, co63oc commented on jointContribution/PIRBN/rbn_net.py
> +                shape=[1, 1],
1

2023-10-17 12:15 UTC, co63oc commented on jointContribution/PIRBN/rbn_net.py
> +
1

2023-10-17 12:15 UTC, co63oc commented on jointContribution/PIRBN/rbn_net.py
> +    def ini_ab(self):
1

2023-10-17 12:15 UTC, co63oc commented on jointContribution/PIRBN/train.py
> +        # self.x_train = [self.X_r, self.X_u]
1

2023-10-17 12:15 UTC, co63oc commented on jointContribution/PIRBN/README.md
1

2023-10-20 05:15 UTC, HydrogenSulfate approved these changes
LGTM

2023-10-20 05:16 UTC, merged