【Hackathon 5th No.56】A Physics-Informed Neural Network to solve 2D steady-state heat equation
PaddlePaddle/PaddleScience pull request #560
Opened 2023-10-06 12:48 UTC by Gxinhu

### PR types
ohters

others
### PR changes

others
### Describe

https://github.com/PaddlePaddle/Paddle/issues/57262

### Result
#### 原始
- MSE loss 0.019
- PINN结果与FDM结果 MSE loss 0.0015

#### 复现
- MSE loss 0.011
- PINN结果与FDM结果 MSE loss 0.0013

```
...
[2023/10/06 12:43:12] ppsci INFO: [Train][Epoch 986/1000][Avg] loss: 0.01095, EQ: 0.00166, BC_top: 0.00329, BC_bottom: 0.00133, BC_left: 0.00253, BC_right: 0.00214
[2023/10/06 12:43:12] ppsci MESSAGE: Finish saving checkpoint to ./output_heat2d/checkpoints/latest
[2023/10/06 12:43:12] ppsci INFO: [Train][Epoch 987/1000][Iter: 1/1] lr: 0.00050, loss: 0.01095, EQ: 0.00166, BC_top: 0.00329, BC_bottom: 0.00132, BC_left: 0.00254, BC_right: 0.00214, batch_cost: 0.00822s, reader_cost: 0.00001s, ips: 1204959.66319 samples/s, eta: 0:00:00
[2023/10/06 12:43:12] ppsci INFO: [Train][Epoch 987/1000][Avg] loss: 0.01095, EQ: 0.00166, BC_top: 0.00329, BC_bottom: 0.00132, BC_left: 0.00254, BC_right: 0.00214
[2023/10/06 12:43:12] ppsci MESSAGE: Finish saving checkpoint to ./output_heat2d/checkpoints/latest
[2023/10/06 12:43:12] ppsci INFO: [Train][Epoch 988/1000][Iter: 1/1] lr: 0.00050, loss: 0.01095, EQ: 0.00166, BC_top: 0.00329, BC_bottom: 0.00132, BC_left: 0.00253, BC_right: 0.00214, batch_cost: 0.00822s, reader_cost: 0.00001s, ips: 1205027.41716 samples/s, eta: 0:00:00
[2023/10/06 12:43:12] ppsci INFO: [Train][Epoch 988/1000][Avg] loss: 0.01095, EQ: 0.00166, BC_top: 0.00329, BC_bottom: 0.00132, BC_left: 0.00253, BC_right: 0.00214
[2023/10/06 12:43:12] ppsci MESSAGE: Finish saving checkpoint to ./output_heat2d/checkpoints/latest
[2023/10/06 12:43:12] ppsci INFO: [Train][Epoch 989/1000][Iter: 1/1] lr: 0.00050, loss: 0.01094, EQ: 0.00166, BC_top: 0.00329, BC_bottom: 0.00132, BC_left: 0.00254, BC_right: 0.00214, batch_cost: 0.00822s, reader_cost: 0.00001s, ips: 1205147.48129 samples/s, eta: 0:00:00
[2023/10/06 12:43:12] ppsci INFO: [Train][Epoch 989/1000][Avg] loss: 0.01094, EQ: 0.00166, BC_top: 0.00329, BC_bottom: 0.00132, BC_left: 0.00254, BC_right: 0.00214
[2023/10/06 12:43:12] ppsci MESSAGE: Finish saving checkpoint to ./output_heat2d/checkpoints/latest
[2023/10/06 12:43:12] ppsci INFO: [Train][Epoch 990/1000][Iter: 1/1] lr: 0.00050, loss: 0.01094, EQ: 0.00165, BC_top: 0.00328, BC_bottom: 0.00132, BC_left: 0.00254, BC_right: 0.00214, batch_cost: 0.00822s, reader_cost: 0.00001s, ips: 1205186.26048 samples/s, eta: 0:00:00
[2023/10/06 12:43:12] ppsci INFO: [Train][Epoch 990/1000][Avg] loss: 0.01094, EQ: 0.00165, BC_top: 0.00328, BC_bottom: 0.00132, BC_left: 0.00254, BC_right: 0.00214
[2023/10/06 12:43:12] ppsci MESSAGE: Finish saving checkpoint to ./output_heat2d/checkpoints/latest
[2023/10/06 12:43:12] ppsci INFO: [Train][Epoch 991/1000][Iter: 1/1] lr: 0.00050, loss: 0.01093, EQ: 0.00165, BC_top: 0.00329, BC_bottom: 0.00132, BC_left: 0.00254, BC_right: 0.00214, batch_cost: 0.00822s, reader_cost: 0.00001s, ips: 1205214.21870 samples/s, eta: 0:00:00
[2023/10/06 12:43:12] ppsci INFO: [Train][Epoch 991/1000][Avg] loss: 0.01093, EQ: 0.00165, BC_top: 0.00329, BC_bottom: 0.00132, BC_left: 0.00254, BC_right: 0.00214
[2023/10/06 12:43:12] ppsci MESSAGE: Finish saving checkpoint to ./output_heat2d/checkpoints/latest
[2023/10/06 12:43:12] ppsci INFO: [Train][Epoch 992/1000][Iter: 1/1] lr: 0.00050, loss: 0.01093, EQ: 0.00165, BC_top: 0.00328, BC_bottom: 0.00132, BC_left: 0.00254, BC_right: 0.00214, batch_cost: 0.00822s, reader_cost: 0.00001s, ips: 1205184.68439 samples/s, eta: 0:00:00
[2023/10/06 12:43:12] ppsci INFO: [Train][Epoch 992/1000][Avg] loss: 0.01093, EQ: 0.00165, BC_top: 0.00328, BC_bottom: 0.00132, BC_left: 0.00254, BC_right: 0.00214
[2023/10/06 12:43:12] ppsci MESSAGE: Finish saving checkpoint to ./output_heat2d/checkpoints/latest
[2023/10/06 12:43:12] ppsci INFO: [Train][Epoch 993/1000][Iter: 1/1] lr: 0.00050, loss: 0.01093, EQ: 0.00165, BC_top: 0.00329, BC_bottom: 0.00132, BC_left: 0.00253, BC_right: 0.00214, batch_cost: 0.00822s, reader_cost: 0.00001s, ips: 1205198.02212 samples/s, eta: 0:00:00
[2023/10/06 12:43:12] ppsci INFO: [Train][Epoch 993/1000][Avg] loss: 0.01093, EQ: 0.00165, BC_top: 0.00329, BC_bottom: 0.00132, BC_left: 0.00253, BC_right: 0.00214
[2023/10/06 12:43:12] ppsci MESSAGE: Finish saving checkpoint to ./output_heat2d/checkpoints/latest
[2023/10/06 12:43:12] ppsci INFO: [Train][Epoch 994/1000][Iter: 1/1] lr: 0.00050, loss: 0.01092, EQ: 0.00164, BC_top: 0.00328, BC_bottom: 0.00132, BC_left: 0.00254, BC_right: 0.00214, batch_cost: 0.00822s, reader_cost: 0.00001s, ips: 1205170.49793 samples/s, eta: 0:00:00
[2023/10/06 12:43:12] ppsci INFO: [Train][Epoch 994/1000][Avg] loss: 0.01092, EQ: 0.00164, BC_top: 0.00328, BC_bottom: 0.00132, BC_left: 0.00254, BC_right: 0.00214
[2023/10/06 12:43:12] ppsci MESSAGE: Finish saving checkpoint to ./output_heat2d/checkpoints/latest
[2023/10/06 12:43:12] ppsci INFO: [Train][Epoch 995/1000][Iter: 1/1] lr: 0.00050, loss: 0.01092, EQ: 0.00164, BC_top: 0.00329, BC_bottom: 0.00131, BC_left: 0.00254, BC_right: 0.00213, batch_cost: 0.00822s, reader_cost: 0.00001s, ips: 1205182.53995 samples/s, eta: 0:00:00
[2023/10/06 12:43:12] ppsci INFO: [Train][Epoch 995/1000][Avg] loss: 0.01092, EQ: 0.00164, BC_top: 0.00329, BC_bottom: 0.00131, BC_left: 0.00254, BC_right: 0.00213
[2023/10/06 12:43:12] ppsci MESSAGE: Finish saving checkpoint to ./output_heat2d/checkpoints/latest
[2023/10/06 12:43:12] ppsci INFO: [Train][Epoch 996/1000][Iter: 1/1] lr: 0.00050, loss: 0.01091, EQ: 0.00164, BC_top: 0.00327, BC_bottom: 0.00132, BC_left: 0.00254, BC_right: 0.00214, batch_cost: 0.00821s, reader_cost: 0.00001s, ips: 1205277.54479 samples/s, eta: 0:00:00
[2023/10/06 12:43:12] ppsci INFO: [Train][Epoch 996/1000][Avg] loss: 0.01091, EQ: 0.00164, BC_top: 0.00327, BC_bottom: 0.00132, BC_left: 0.00254, BC_right: 0.00214
[2023/10/06 12:43:12] ppsci MESSAGE: Finish saving checkpoint to ./output_heat2d/checkpoints/latest
[2023/10/06 12:43:12] ppsci INFO: [Train][Epoch 997/1000][Iter: 1/1] lr: 0.00050, loss: 0.01091, EQ: 0.00164, BC_top: 0.00329, BC_bottom: 0.00131, BC_left: 0.00254, BC_right: 0.00213, batch_cost: 0.00821s, reader_cost: 0.00001s, ips: 1205395.96890 samples/s, eta: 0:00:00
[2023/10/06 12:43:12] ppsci INFO: [Train][Epoch 997/1000][Avg] loss: 0.01091, EQ: 0.00164, BC_top: 0.00329, BC_bottom: 0.00131, BC_left: 0.00254, BC_right: 0.00213
[2023/10/06 12:43:12] ppsci MESSAGE: Finish saving checkpoint to ./output_heat2d/checkpoints/latest
[2023/10/06 12:43:12] ppsci INFO: [Train][Epoch 998/1000][Iter: 1/1] lr: 0.00050, loss: 0.01091, EQ: 0.00163, BC_top: 0.00327, BC_bottom: 0.00132, BC_left: 0.00253, BC_right: 0.00215, batch_cost: 0.00821s, reader_cost: 0.00001s, ips: 1205466.82007 samples/s, eta: 0:00:00
[2023/10/06 12:43:12] ppsci INFO: [Train][Epoch 998/1000][Avg] loss: 0.01091, EQ: 0.00163, BC_top: 0.00327, BC_bottom: 0.00132, BC_left: 0.00253, BC_right: 0.00215
[2023/10/06 12:43:12] ppsci MESSAGE: Finish saving checkpoint to ./output_heat2d/checkpoints/latest
[2023/10/06 12:43:12] ppsci INFO: [Train][Epoch 999/1000][Iter: 1/1] lr: 0.00050, loss: 0.01091, EQ: 0.00163, BC_top: 0.00330, BC_bottom: 0.00130, BC_left: 0.00254, BC_right: 0.00213, batch_cost: 0.00821s, reader_cost: 0.00001s, ips: 1205457.18673 samples/s, eta: 0:00:00
[2023/10/06 12:43:12] ppsci INFO: [Train][Epoch 999/1000][Avg] loss: 0.01091, EQ: 0.00163, BC_top: 0.00330, BC_bottom: 0.00130, BC_left: 0.00254, BC_right: 0.00213
[2023/10/06 12:43:12] ppsci MESSAGE: Finish saving checkpoint to ./output_heat2d/checkpoints/latest
[2023/10/06 12:43:12] ppsci INFO: [Train][Epoch 1000/1000][Iter: 1/1] lr: 0.00050, loss: 0.01091, EQ: 0.00163, BC_top: 0.00326, BC_bottom: 0.00133, BC_left: 0.00253, BC_right: 0.00215, batch_cost: 0.00821s, reader_cost: 0.00001s, ips: 1205472.65255 samples/s, eta: 0:00:00
[2023/10/06 12:43:12] ppsci INFO: [Train][Epoch 1000/1000][Avg] loss: 0.01091, EQ: 0.00163, BC_top: 0.00326, BC_bottom: 0.00133, BC_left: 0.00253, BC_right: 0.00215
[2023/10/06 12:43:12] ppsci MESSAGE: Finish saving checkpoint to ./output_heat2 [...]

2023-10-09 09:45 UTC, luotao1 commented
开发之前请撰写 RFC 文档：[PaddleSciece RFC 文档](https://github.com/PaddlePaddle/community/blob/master/rfcs/Science/template.md)

2023-10-09 12:12 UTC, Gxinhu commented
> 开发之前请撰写 RFC 文档：[PaddleSciece RFC 文档](https://github.com/PaddlePaddle/community/blob/master/rfcs/Science/template.md)

已补交RFC

2023-10-19 07:21 UTC, liaoxin2 requested changes

2023-10-19 07:21 UTC, liaoxin2 commented on jointContribution/Heat_PINN/main.py
> +    plt.savefig(os.path.join(OUTPUT_DIR, "fdm.png"))
此处保存的图片应该是两个图片，包含pinn方法的图片，仅用fdm.png命名有点不太好

2023-10-19 08:01 UTC, Gxinhu commented on jointContribution/Heat_PINN/main.py
> +    NPOINT_RIGHT = 25
![image](https://github.com/PaddlePaddle/PaddleScience/assets/12217422/2db6ece6-3bba-41c1-8db9-466a1a556738)
原复现仓库使用的就是每一条边25个点

2023-10-19 11:05 UTC, liaoxin2 commented on jointContribution/Heat_PINN/main.py
> +    NPOINT_RIGHT = 25
好的，那就按照原代码每一条边25个点

2023-10-23 03:05 UTC, liaoxin2 requested changes

2023-10-23 03:06 UTC, HydrogenSulfate requested changes

2023-10-23 03:06 UTC, HydrogenSulfate commented on docs/images/tmp/pinn_fdm_comparison.png
图片我给上传好了，麻烦把文档里的文件路径改成url路径：

https://paddle-org.bj.bcebos.com/paddlescience/docs/Heat_PINN/pinn_fdm_comparison.png.PNG

https://paddle-org.bj.bcebos.com/paddlescience/docs/Heat_PINN/profiles.PNG

2023-10-24 08:12 UTC, liaoxin2 requested changes

2023-10-24 08:12 UTC, liaoxin2 commented on docs/zh/examples/heat_pinn.md
> +```py linenums="131"
```suggestion
```py linenums="130"
```

2023-10-24 08:12 UTC, liaoxin2 commented on docs/zh/examples/heat_pinn.md
> +上图分别为温度 $T$ 的横截线图（ $y=\\{-0.75,-0.50,-0.25,0.00,0.25,0.50,0.75\\}$ ）和纵截线图（ $x=\\{-0.75,-0.50,-0.25,0.00,0.25,0.50,0.75\\}$ ），可以看到 PINN 与 FDM 方法的计算结果基本一致。
大括号无法显示，将\去掉一个

2023-10-24 08:15 UTC, liaoxin2 commented on docs/zh/examples/heat_pinn.md
> +u = f(x, y)
```suggestion
u = f(x, y),
```
添加一个逗号

2023-10-24 09:11 UTC, liaoxin2 requested changes

2023-10-24 09:11 UTC, liaoxin2 commented on docs/zh/examples/heat_pinn.md
> +```
请再重新检查一下所有代码块是否是对应的，你在代码前面添加了一些说明，都要重新修改了

2023-10-24 09:11 UTC, liaoxin2 commented on docs/zh/examples/heat_pinn.md
> +```
![image](https://github.com/PaddlePaddle/PaddleScience/assets/136409501/71a0d284-84b9-4391-b843-6091c18140b9)
这里将train_dataloader_cfg也放进去

2023-10-24 11:49 UTC, HydrogenSulfate requested changes
output_heat2d下的权重已经上传好了，所以output_heat2d文件夹可以删掉了。辛苦删除一下。其他的没什么大问题

2023-10-24 13:15 UTC, merged

2023-11-02 06:50 UTC, luotao1 commented
hi, @Gxinhu 
- 非常感谢你对飞桨框架的贡献，我们正在运营一个PFCC组织，会通过定期分享技术知识与发布开发者主导任务的形式持续为飞桨框架做贡献，详情可见 https://github.com/luotao1 主页说明。
- 如果你对PFCC有兴趣，请发送邮件至 [ext_paddle_oss@baidu.com](mailto:ext_paddle_oss@baidu.com)，我们会邀请你加入~

2023-12-26 02:45 UTC, luotao1 commented
hi, @Gxinhu 
- 为后续证书+奖金发放，请发送邮件至 [ext_paddle_oss@baidu.com](mailto:ext_paddle_oss@baidu.com)，我们会邀请你加入本期冠军群~