【Hackathon 5th No.56】2D steady-state heat equation, paddle and paddlescience implementations.
PaddlePaddle/PaddleScience pull request #562
Opened 2023-10-09 03:46 UTC by moosewoler

### PR types

Others

### PR changes

Others

### Describe

2维稳态热传导方程，paddle API实现与paddlescience API实现。

2023-10-20 13:48 UTC, HydrogenSulfate requested changes

2023-10-20 13:48 UTC, HydrogenSulfate commented on jointContribution/2DHeat-PINN/2dheat-pinn-paddlescience/2dheat-pinn-paddlescience.ipynb
1. PaddleScience 案例文件格式为 .py 文件，文档使用 .md 格式，不使用代码+文档混合的 ipynb格式文件，请将代码分离到 `heat_pinn_2d.py` 文件，文档分离到 `heat_pinn_2d.md` 文件。
2. .py代码文件撰写请参考以下范例代码进行编写：https://github.com/PaddlePaddle/PaddleScience/blob/develop/examples/bracket/bracket.py
3. .md文档文件请参考以下范例文档进行撰写（文档开头的“模型评估命令”可以不用写）
https://github.com/PaddlePaddle/PaddleScience/blob/develop/docs/zh/examples/bracket.md ；文档撰写完毕之后根据 https://paddlescience-docs.readthedocs.io/zh/latest/zh/development/#3 教程自行本地预览，校对文档内容、格式直至无误
4. 运行文件请移动到 `PaddleScience/examples/heat_pinn/` 目录下
本PR中部分图片超链接已经帮你上传，可以在文档中使用：
https://paddle-org.bj.bcebos.com/paddlescience/docs/Heat_PINN/heat_pinn1.PNG
https://paddle-org.bj.bcebos.com/paddlescience/docs/Heat_PINN/heat_pinn2.PNG
https://paddle-org.bj.bcebos.com/paddlescience/docs/Heat_PINN/heat_pinn3.PNG
https://paddle-org.bj.bcebos.com/paddlescience/docs/Heat_PINN/heat_pinn4.PNG

2023-10-20 13:48 UTC, HydrogenSulfate commented on jointContribution/2DHeat-PINN/2dheat-pinn-paddle/2dheat-pinn-paddle.ipynb
基于paddle API的开发代码属于中间结果，可以删除，只保留基于PaddleScience的实现

2023-11-02 06:47 UTC, luotao1 commented
已经有 PR 合入了，如果需要更新和完善，可以在原来的 PR 上进行修改，感谢！
- https://github.com/PaddlePaddle/PaddleScience/pull/560

2023-11-02 06:47 UTC, closed without merging