add vae
PaddlePaddle/PaddleScience pull request #573
Opened 2023-10-18 07:10 UTC by DrRyanHuang

### PR types

### PR changes

### Describe

2023-10-19 03:29 UTC, HydrogenSulfate commented
感谢大佬提PR，可以合并一下最新develop分支的代码，然后案例可以用hydra改造一下，参考这个案例：https://github.com/PaddlePaddle/PaddleScience/tree/develop/examples/bracket

2023-10-24 16:41 UTC, DrRyanHuang commented
@HydrogenSulfate 不好意思，打扰了，AISTUDIO原文用到了 `Julia` 环境，我这边写test的时候也配置配置一个 `Julia` 环境，还是怎么操作一下嘞? 😆

原文地址 ：https://aistudio.baidu.com/projectdetail/5541961

```python
# julia 依赖
os.environ['JULIA_DEPOT_PATH'] = '/home/aistudio/opt/julia_package'
# pip 依赖
sys.path.append('/home/aistudio/opt/external-libraries')

# julieries
from julia.api import Julia
jl = Julia(compiled_modules=False,runtime="/home/aistudio/opt/julia-1.8.5/bin/julia")
# import julia
from julia import Main
```

2023-10-25 05:38 UTC, HydrogenSulfate commented
> @HydrogenSulfate 不好意思，打扰了，AISTUDIO原文用到了 `Julia` 环境，我这边写test的时候也配置配置一个 `Julia` 环境，还是怎么操作一下嘞? 😆
> 
> 原文地址 ：https://aistudio.baidu.com/projectdetail/5541961
> 
> ```python
> # julia 依赖
> os.environ['JULIA_DEPOT_PATH'] = '/home/aistudio/opt/julia_package'
> # pip 依赖
> sys.path.append('/home/aistudio/opt/external-libraries')
> 
> # julieries
> from julia.api import Julia
> jl = Julia(compiled_modules=False,runtime="/home/aistudio/opt/julia-1.8.5/bin/julia")
> # import julia
> from julia import Main
> ```



> @HydrogenSulfate 不好意思，打扰了，AISTUDIO原文用到了 `Julia` 环境，我这边写test的时候也配置配置一个 `Julia` 环境，还是怎么操作一下嘞? 😆
> 
> 原文地址 ：https://aistudio.baidu.com/projectdetail/5541961
> 
> ```python
> # julia 依赖
> os.environ['JULIA_DEPOT_PATH'] = '/home/aistudio/opt/julia_package'
> # pip 依赖
> sys.path.append('/home/aistudio/opt/external-libraries')
> 
> # julieries
> from julia.api import Julia
> jl = Julia(compiled_modules=False,runtime="/home/aistudio/opt/julia-1.8.5/bin/julia")
> # import julia
> from julia import Main
> ```

测试文件test.ipynb只是一个测试功能是否正常的文件，本地测试使用，可以不用提交到PR里。

2023-10-25 05:40 UTC, HydrogenSulfate commented
> @HydrogenSulfate 不好意思，打扰了，AISTUDIO原文用到了 `Julia` 环境，我这边写test的时候也配置配置一个 `Julia` 环境，还是怎么操作一下嘞? 😆
> 
> 原文地址 ：https://aistudio.baidu.com/projectdetail/5541961
> 
> ```python
> # julia 依赖
> os.environ['JULIA_DEPOT_PATH'] = '/home/aistudio/opt/julia_package'
> # pip 依赖
> sys.path.append('/home/aistudio/opt/external-libraries')
> 
> # julieries
> from julia.api import Julia
> jl = Julia(compiled_modules=False,runtime="/home/aistudio/opt/julia-1.8.5/bin/julia")
> # import julia
> from julia import Main
> ```

可以将上述路径配置写到hydra yaml文件里，然后通过cfg.JULIA.xxx访问即可。

2023-10-25 05:51 UTC, HydrogenSulfate requested changes

2023-10-25 05:51 UTC, HydrogenSulfate commented on examples/RegAE/train_new.py
> +import sys; sys.path.append(r"C:\Users\zihao\Desktop\lbwnb\PaddleScience")
这行可以删除，因为通过 `pip install -e .` 或 `export PYTHONPATH=\`pwd\`` 的方式安装，应该都不需要这行路径设置代码。

2023-10-25 05:51 UTC, HydrogenSulfate commented on examples/RegAE/train_new.py
> +#     return F.mse_loss(output_dict["pred"], label_dict["label"].y)
一些无用的注释可以删除

2023-10-25 05:51 UTC, HydrogenSulfate commented on examples/RegAE/train_new.py
> +    )
AutoEncoder的初始化超参数移动至RegAE.yaml配置文件里

2023-10-25 05:51 UTC, HydrogenSulfate commented on examples/RegAE/train_new.py
> +    solver.train()
文件末尾换行

2023-10-25 05:51 UTC, HydrogenSulfate commented on ppsci/arch/vae.py
> +        )
base.Arch的子类需要做成符号化的形式，即需要具有 input_keys、output_keys两个属性

2023-10-25 05:51 UTC, HydrogenSulfate commented on ppsci/arch/vae.py
> +    def forward(self, x, noise):
forward中的张量计算放到forward_tensor中，然后forward内主要负责从输入的字典中找到并组装出真正的输入张量

2023-10-25 05:51 UTC, HydrogenSulfate commented on ppsci/data/dataset/npz_dataset.py
> +    def fit(self, data):
内部使用的函数前面加一个下划线：`_fit`

2023-10-25 05:51 UTC, HydrogenSulfate commented on ppsci/data/dataset/npz_dataset.py
> +    def inverse_transform(self, data):
同上

2023-10-25 05:51 UTC, HydrogenSulfate commented on ppsci/data/dataset/npz_dataset.py
> +class ScalerStd(object):
删除(object)，python3已经不需要从object继承

2023-10-25 05:51 UTC, HydrogenSulfate commented on ppsci/data/dataset/npz_dataset.py
> +            return self.test_data[idx]
dataset需要返回input、label、weight三个数据字典

2023-10-25 05:51 UTC, HydrogenSulfate commented on ppsci/loss/kl.py
> +        return loss
文件末尾换行

2023-10-25 05:51 UTC, HydrogenSulfate commented on ppsci/loss/kl.py
> +    def forward(self, mu, log_sigma):
所有loss子类的forward写法统一，接受output_dict, label_dict, weight_dict三个变量，然后计算loss并以一个标量Tensor的形式返回。可以将N(0,1)的数据作为标签数据，从label_dict传入

2024-01-24 03:36 UTC, HydrogenSulfate commented
closed for #660

2024-01-24 03:36 UTC, closed without merging