modify laplace2d to hydra style
PaddlePaddle/PaddleScience pull request #575
Opened 2023-10-18 08:02 UTC by xusuyong

### PR types

### PR changes

### Describe

2023-10-18 08:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleScience?pullRequest=575) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleScience?pullRequest=575) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleScience?pullRequest=575) it.</sub>

2023-10-18 08:30 UTC, HydrogenSulfate requested changes

2023-10-18 08:30 UTC, HydrogenSulfate commented on docs/zh/examples/laplace2d.md
> +    tar -xvf laplace2d_dataset.tar
这个模型没有来自文件的数据集，可以删除除最后一行外的代码

2023-10-18 08:30 UTC, HydrogenSulfate commented on examples/laplace/laplace2d.py
> +    NPOINT_BC = cfg.NPOINT_BC
这里两行可以删除，

2023-10-18 08:30 UTC, HydrogenSulfate commented on examples/laplace/laplace2d.py
>      NPOINT_TOTAL = NPOINT_INTERIOR + NPOINT_BC
`NPOINT_TOTAL = cfg.NPOINT_INTERIOR + cfg.NPOINT_BC`

2023-10-18 08:30 UTC, HydrogenSulfate commented on examples/laplace/laplace2d.py
1. 构造的几何的对角线坐标可以放YAML里：cfg.DIAGONAL_COORD
2. 优化器使用的学习率也放到YAML：cfg.TRAIN.learning_rate

2023-10-18 08:30 UTC, HydrogenSulfate commented on examples/laplace/laplace2d.py
> +
删除137行

2023-10-18 08:30 UTC, HydrogenSulfate commented on examples/laplace/laplace2d.py
> +    # # set output directory
删除多余井号#

2023-10-18 08:30 UTC, HydrogenSulfate commented on examples/laplace/laplace2d.py
> +    logger.init_logger("ppsci", osp.join(cfg.output_dir, "train.log"), "info")
`eval.log`

2023-10-18 08:30 UTC, HydrogenSulfate commented on examples/laplace/laplace2d.py
> +    NPOINT_TOTAL = NPOINT_INTERIOR + NPOINT_BC
修改同上

2023-10-18 08:30 UTC, HydrogenSulfate commented on examples/laplace/laplace2d.py
> +    main()
文件末尾换行

2023-10-19 04:00 UTC, HydrogenSulfate requested changes

2023-10-19 04:00 UTC, HydrogenSulfate commented on docs/zh/examples/laplace2d.md
> +    tar -xvf laplace2d_dataset.tar
删除`tar -xvf laplace2d_dataset.tar`

2023-10-19 04:01 UTC, HydrogenSulfate requested changes

2023-10-19 04:01 UTC, HydrogenSulfate commented on examples/laplace/laplace2d.py
> +
函数和函数之间空两行

2023-10-19 04:01 UTC, HydrogenSulfate commented on examples/laplace/laplace2d.py
tar -xvf laplace2d_dataset.tar

2023-10-19 09:42 UTC, HydrogenSulfate approved these changes
LGTM

2023-10-19 12:10 UTC, merged

2023-11-02 08:11 UTC, luotao1 commented
hi, @xusuyong 
- 非常感谢你对飞桨框架的贡献，我们正在运营一个PFCC组织，会通过定期分享技术知识与发布开发者主导任务的形式持续为飞桨框架做贡献，详情可见 https://github.com/luotao1 主页说明。
- 如果你对PFCC有兴趣，请发送邮件至 [ext_paddle_oss@baidu.com](mailto:ext_paddle_oss@baidu.com)，我们会邀请你加入~