hydra 改造 phylstm
PaddlePaddle/PaddleScience pull request #579
Opened 2023-10-19 07:07 UTC by co63oc

### PR types

Others
### PR changes

Others
### Describe

https://github.com/PaddlePaddle/PaddleScience/issues/571

19 phylstm的转换

2023-10-19 09:21 UTC, HydrogenSulfate requested changes

2023-10-19 09:21 UTC, HydrogenSulfate commented on docs/zh/examples/phylstm.md
1. 参考bracket，在开头加上训练命令
    ![image](https://github.com/PaddlePaddle/PaddleScience/assets/23737287/30df85e3-886c-498c-ade1-4d04f817178f)
2. 这两个案例运行前需要下载数据集，所以训练命令里也加一下数据集下载的命令

2023-10-19 09:21 UTC, HydrogenSulfate commented on examples/phylstm/conf/phylstm2.yaml
> +  eval_with_no_grad: true
文件末尾空行

2023-10-19 09:21 UTC, HydrogenSulfate commented on examples/phylstm/conf/phylstm2.yaml
> +data_file: data_boucwen.mat
``` yaml
log_freq: 20

# set data file path
DATA_FILE_PATH: data_boucwen.mat

...
```

2023-10-19 09:21 UTC, HydrogenSulfate commented on examples/phylstm/conf/phylstm2.yaml
> +  checkpoint_path: null
移动至learning_rate下方

2023-10-19 09:21 UTC, HydrogenSulfate commented on examples/phylstm/conf/phylstm3.yaml
问题同phylstm2.ytaml

2023-10-19 09:21 UTC, HydrogenSulfate commented on docs/zh/examples/phylstm.md
>  ```
这里引用YAML文件的epochs字段

2023-10-19 10:38 UTC, co63oc commented on docs/zh/examples/phylstm.md
1

2023-10-19 10:45 UTC, co63oc commented on examples/phylstm/conf/phylstm2.yaml
> +  eval_with_no_grad: true
如果只增加换行提交时会去掉，现在是增加空格，这样提交后有空行

2023-10-19 11:11 UTC, HydrogenSulfate commented on examples/phylstm/conf/phylstm2.yaml
> +  eval_with_no_grad: true
不会吧，我本地没出现过这个问题啊，yaml文件末尾空一行就行了，是被pre-commit去掉了吗？
![image](https://github.com/PaddlePaddle/PaddleScience/assets/23737287/02032f05-f928-4f9f-8d17-7a8abf36c38f)

2023-10-19 11:25 UTC, co63oc commented on examples/phylstm/conf/phylstm2.yaml
> +  eval_with_no_grad: true
现在提交可以了

2023-10-19 11:36 UTC, co63oc commented
8239de2 修改是去掉多的一个换行

2023-10-19 12:21 UTC, HydrogenSulfate commented on examples/phylstm/conf/phylstm3.yaml
> +    input_size: 1
> `phylstm3_net:` 这个中间字段应该是多余的可以删掉，因为两个模型并不共用同一个yaml文件；然后代码文件里也对应删除一下

phylstm2_net也同理

2023-10-19 12:58 UTC, co63oc commented on examples/phylstm/conf/phylstm3.yaml
> +    input_size: 1
1

2023-10-20 02:27 UTC, HydrogenSulfate approved these changes
LGTM

2023-10-20 03:33 UTC, merged