【hydra No.20】改造 bubble
PaddlePaddle/PaddleScience pull request #581
Opened 2023-10-19 14:16 UTC by co63oc

### PR types

Others 
### PR changes

Others 
### Describe

https://github.com/PaddlePaddle/PaddleScience/issues/571

19 bubble的转换

2023-10-20 02:49 UTC, HydrogenSulfate requested changes

2023-10-20 02:49 UTC, HydrogenSulfate commented on examples/bubble/bubble.py
之前想过合并的问题，但是觉得训练、评估代码会通过判断条件混在一起，阅读性比较差，还是分开来比较好，代码长一点没关系。

2023-10-20 02:49 UTC, HydrogenSulfate commented on examples/bubble/bubble.py
> +            constraint,
eval 不需要传入 `constraint` 参数

2023-10-20 03:26 UTC, co63oc commented on examples/bubble/bubble.py
已修改拆分

2023-10-20 03:27 UTC, co63oc commented on examples/bubble/bubble.py
> +            constraint,
已去掉constraint

2023-10-20 14:14 UTC, HydrogenSulfate requested changes
辛苦再修改下，没其他问题了应该

2023-10-20 14:14 UTC, HydrogenSulfate commented on examples/bubble/bubble.py
> +        "f{cfg.output_dir}/visual/result.vtu",
==>`osp.join()`

2023-10-20 14:14 UTC, HydrogenSulfate commented on examples/bubble/bubble.py
> +        "f{cfg.output_dir}/visual/result.vtu",
==>`osp.join()`

2023-10-24 02:29 UTC, HydrogenSulfate approved these changes
LGTM

2023-10-24 02:29 UTC, merged