Add hydra for hpinns model
PaddlePaddle/PaddleScience pull request #582
Opened 2023-10-20 00:46 UTC by co63oc

### PR types

Others 
### PR changes

Others 
### Describe

https://github.com/PaddlePaddle/PaddleScience/issues/571

11 hpinns的转换
因train, eval有较多初始化代码相同，合并为一个调用train_or_evaluate

2023-10-20 02:51 UTC, HydrogenSulfate requested changes

2023-10-20 02:51 UTC, HydrogenSulfate commented on examples/hpinns/holography.py
同 bubble，train和eval代码分开来写，否则两者混在一起阅读性会比较差

2023-10-20 02:51 UTC, HydrogenSulfate commented on examples/hpinns/holography.py
> +        solver.eval()
eval模式下不应该再调.train()函数了吧？

2023-10-20 08:22 UTC, co63oc commented on examples/hpinns/holography.py
> +        solver.eval()
已取消solver.train()

2023-10-24 08:51 UTC, lijialin03 commented on examples/hpinns/holography.py
> +    model_re = ppsci.arch.MLP(in_keys, **cfg.MODEL.re_net)
in_keys挪到yaml文件里吧

2023-10-24 08:51 UTC, lijialin03 commented on examples/hpinns/holography.py
> +    func_module.train_mode = cfg.TRAIN_MODE
同tempoGAN案例的pr中所说，这类只是赋值了一下的参数，直接在调用的时候改成调用cfg.xxx，不需要进行这步额外的赋值了

2023-10-24 08:51 UTC, lijialin03 commented on examples/hpinns/holography.py
> +    model_eps = ppsci.arch.MLP(in_keys, **cfg.MODEL.eps_net)
input_key加到yaml中只有，这边也需要同步修改

2023-10-24 23:57 UTC, co63oc commented on examples/hpinns/holography.py
> +    model_eps = ppsci.arch.MLP(in_keys, **cfg.MODEL.eps_net)
已修改

2023-10-25 06:53 UTC, lijialin03 commented on docs/zh/examples/hpinns.md
> +examples/hpinns/conf/hpinns.yaml:53:57
还有这两行
max_iter: 15000
epochs_lbfgs: 1

2023-10-25 07:03 UTC, co63oc commented on docs/zh/examples/hpinns.md
> +examples/hpinns/conf/hpinns.yaml:53:57
已增加

2023-10-25 07:55 UTC, HydrogenSulfate approved these changes
LGTM

2023-10-25 07:55 UTC, merged