Adapt DeepCFD to hydra
PaddlePaddle/PaddleScience pull request #583
Opened 2023-10-20 03:18 UTC by MayYouBeProsperous

### PR types

Others
### PR changes

Others
### Describe

DeepCFD 案例代码重构，添加评估函数 evaluate，及其训练命令。

2023-10-26 11:15 UTC, HydrogenSulfate requested changes
辛苦大佬再修改一下

2023-10-26 11:15 UTC, HydrogenSulfate commented on docs/zh/examples/deepcfd.md
> +    ```
``` suggestion
    ``` sh
    # linux
    wget -P ./datasets/ https://paddle-org.bj.bcebos.com/paddlescience/datasets/DeepCFD/dataX.pkl
    wget -P ./datasets/ https://paddle-org.bj.bcebos.com/paddlescience/datasets/DeepCFD/dataY.pkl
    # windows
    # curl -o ./datasets/dataX.pkl https://paddle-org.bj.bcebos.com/paddlescience/datasets/DeepCFD/dataX.pkl
    # curl -o ./datasets/dataX.pkl https://paddle-org.bj.bcebos.com/paddlescience/datasets/DeepCFD/dataY.pkl
    python deepcfd.py
    ```
```

2023-10-26 11:15 UTC, HydrogenSulfate commented on docs/zh/examples/deepcfd.md
>  ```
==> ``` yaml

2023-10-26 11:15 UTC, HydrogenSulfate commented on docs/zh/examples/deepcfd.md
> +训练过程会调用优化器来更新模型参数，此处选择较为常用的 `Adam` 优化器，学习率设置为 0.001，权值衰减设置为 0.005。
==> 权重衰减

2023-10-26 11:15 UTC, HydrogenSulfate commented on examples/deepcfd/conf/deepcfd.yaml
> +  unetex:
unetex这个字段可以删除，单模型的情况下，参数直接放到MODEL:字段下即可

2023-10-26 11:15 UTC, HydrogenSulfate commented on examples/deepcfd/deepcfd.py
> +    logger.init_logger("ppsci", os.path.join(cfg.output_dir, "train.log"), "info")
==> eval.log

2023-10-26 11:15 UTC, HydrogenSulfate commented on examples/deepcfd/deepcfd.py
> +    model = ppsci.arch.UNetEx("input", "output", **cfg.MODEL.unetex)
input和output也可以放到配置文件里

2023-10-26 11:15 UTC, HydrogenSulfate commented on examples/deepcfd/deepcfd.py
> +    model = ppsci.arch.UNetEx("input", "output", **cfg.MODEL.unetex)
同上

2023-10-26 11:15 UTC, HydrogenSulfate commented on examples/deepcfd/deepcfd.py
>      VISU_INDEX = 0
VISU_INDEX这个变量可以删掉，因为没有第二个使用它的地方

2023-10-27 02:30 UTC, MayYouBeProsperous commented on docs/zh/examples/deepcfd.md
> +    ```
Done.

2023-10-27 02:30 UTC, MayYouBeProsperous commented on docs/zh/examples/deepcfd.md
>  ```
Done.

2023-10-27 02:30 UTC, MayYouBeProsperous commented on docs/zh/examples/deepcfd.md
> +训练过程会调用优化器来更新模型参数，此处选择较为常用的 `Adam` 优化器，学习率设置为 0.001，权值衰减设置为 0.005。
Done.

2023-10-27 02:30 UTC, MayYouBeProsperous commented on examples/deepcfd/conf/deepcfd.yaml
> +  unetex:
好的

2023-10-27 02:30 UTC, MayYouBeProsperous commented on examples/deepcfd/deepcfd.py
> +    model = ppsci.arch.UNetEx("input", "output", **cfg.MODEL.unetex)
Done.

2023-10-27 02:30 UTC, MayYouBeProsperous commented on examples/deepcfd/deepcfd.py
> +    logger.init_logger("ppsci", os.path.join(cfg.output_dir, "train.log"), "info")
Done.

2023-10-27 02:30 UTC, MayYouBeProsperous commented on examples/deepcfd/deepcfd.py
> +    model = ppsci.arch.UNetEx("input", "output", **cfg.MODEL.unetex)
Done.

2023-10-27 02:30 UTC, MayYouBeProsperous commented on examples/deepcfd/deepcfd.py
>      VISU_INDEX = 0
好的已修改

2023-10-27 02:54 UTC, HydrogenSulfate requested changes
其他没什么问题了，辛苦大佬修改

2023-10-27 02:54 UTC, HydrogenSulfate commented on examples/deepcfd/deepcfd.py
>      eval_dataloader_cfg = {
train函数里的eval_dataloader_cfg的batchsize改成cfg里的参数

2023-10-27 03:41 UTC, MayYouBeProsperous commented on examples/deepcfd/deepcfd.py
>      eval_dataloader_cfg = {
好的，辛苦大佬 review

2023-10-27 04:41 UTC, HydrogenSulfate approved these changes
LGTM

2023-10-27 04:41 UTC, merged