【hydra No.9】darcy2d
PaddlePaddle/PaddleScience pull request #590
Opened 2023-10-22 02:50 UTC by co63oc

### PR types

Others 
### PR changes

Others 
### Describe

https://github.com/PaddlePaddle/PaddleScience/issues/571

9 darcy2d

2023-10-22 03:17 UTC, co63oc commented
CI中按原参数测试会有错误
![image](https://github.com/PaddlePaddle/PaddleScience/assets/4617245/6c8b6d05-7de7-49ed-8883-4041e7abadcb)

2023-10-26 09:55 UTC, HydrogenSulfate requested changes

2023-10-26 09:55 UTC, HydrogenSulfate commented on examples/darcy/conf/darcy2d.yaml
> +    residual_validator: 8192
residual_validator移动到EVAL.batch_size

2023-10-26 09:55 UTC, HydrogenSulfate commented on examples/darcy/conf/darcy2d.yaml
> +  pretrained_model_path: null
``` suggestion
eval_with_no_grad: false
```

2023-10-26 09:55 UTC, HydrogenSulfate commented on examples/darcy/conf/darcy2d.yaml
> +  checkpoint_path: null
移动至本级字段的最下方

2023-10-26 09:55 UTC, HydrogenSulfate commented on examples/darcy/darcy2d.py
> +    NPOINT_EVAL = cfg.NPOINT_PDE
这行可以删除

2023-10-26 09:55 UTC, HydrogenSulfate commented on docs/zh/examples/darcy2d.md
> +``` py linenums="41"
``` suggestion
``` yaml linenums="41"
```

2023-10-26 09:57 UTC, HydrogenSulfate requested changes

2023-10-26 09:57 UTC, HydrogenSulfate commented on examples/darcy/darcy2d.py
> +    # set visualizer(optional)
``` suggestion
    # set visualizer
```

2023-10-26 09:57 UTC, HydrogenSulfate commented on examples/darcy/darcy2d.py
>      # visualize prediction for pretrained model(optional)
``` suggestion
    # visualize prediction
```

2023-10-27 03:04 UTC, HydrogenSulfate requested changes
辛苦修改之后顺便合入一下最新分支，里面解决了CI挂掉的问题

2023-10-27 03:04 UTC, HydrogenSulfate commented on docs/zh/examples/darcy2d.md
> +examples/darcy/darcy2d.py:172:192
172:198

2023-10-27 03:04 UTC, HydrogenSulfate commented on docs/zh/examples/darcy2d.md
>  ```
39:47

2023-10-27 03:15 UTC, co63oc commented
已合并develop分支

2023-10-27 04:00 UTC, co63oc commented
![image](https://github.com/PaddlePaddle/PaddleScience/assets/4617245/27dacd37-5e57-4db4-a881-d13227582a7e)
CI错误提示是tools目录
代码没有tools目录
![image](https://github.com/PaddlePaddle/PaddleScience/assets/4617245/9c23e80c-5b8d-4c9d-9b64-4f48fadb93bb)

2023-10-27 05:18 UTC, HydrogenSulfate approved these changes
LGTM

2023-10-27 05:18 UTC, merged

2025-02-14 07:56 UTC, pecanjk commented
L-BFGS进行finetune时，loss nan，测过多次

![图片](https://github.com/user-attachments/assets/782782e6-c0ca-4b1a-ad8d-409d0a284aba)

2025-02-14 08:27 UTC, HydrogenSulfate commented
> L-BFGS进行finetune时，loss nan，测过多次
> 
> ![图片](https://private-user-images.githubusercontent.com/33588322/413210172-782782e6-c0ca-4b1a-ad8d-409d0a284aba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzk1MjA3NjQsIm5iZiI6MTczOTUyMDQ2NCwicGF0aCI6Ii8zMzU4ODMyMi80MTMyMTAxNzItNzgyNzgyZTYtYzBjYS00YjFhLWFkOGQtNDA5ZDBhMjg0YWJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjE0VDA4MDc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlZmJiNmQzZTRkN2ZkMWJmMmI5NzgyZjg1MzRlNmE3ODBmYTU0ZWNjYTg4Nzg4MDk0MzA3Yjc5N2VmYWFjNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-vUbrw1FYewwWFA0GLcMM3aadmaX0Nda5S_YAsDOrzQ)

我这里运行没出现问题，paddlepaddle-develop + PaddleScience develop
![image](https://github.com/user-attachments/assets/742d4efa-9686-43e0-96a2-d1bb29a46ec2)
![image](https://github.com/user-attachments/assets/42340533-a375-43bd-96b1-ed9184656576)

2025-02-14 08:34 UTC, pecanjk commented
我的是ubuntu 22.04 
NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2
paddlepaddle-gpu是cuda11.8版的

paddlepaddle-gpu         3.0.0.dev20250205
paddlesci                1.0.0.post607+g22231b5 /home/xxx/PaddleScience

我这Adam这一步最后的loss比你的高不少
![图片](https://github.com/user-attachments/assets/7402c519-46de-4e16-8538-3ddd2f546c2d)

2025-02-14 08:47 UTC, HydrogenSulfate commented
> 我的是ubuntu 22.04 NVIDIA-SMI 535.183.01 Driver Version: 535.183.01 CUDA Version: 12.2 paddlepaddle-gpu是cuda11.8版的
> 
> paddlepaddle-gpu 3.0.0.dev20250205 paddlesci 1.0.0.post607+g22231b5 /home/xxx/PaddleScience
> 
> 我这Adam这一步最后的loss比你的高不少 ![图片](https://private-user-images.githubusercontent.com/33588322/413224203-7402c519-46de-4e16-8538-3ddd2f546c2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzk1MjMwNTEsIm5iZiI6MTczOTUyMjc1MSwicGF0aCI6Ii8zMzU4ODMyMi80MTMyMjQyMDMtNzQwMmM1MTktNDZkZS00ZTE2LTg1MzgtM2RkZDJmNTQ2YzJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjE0VDA4NDU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjZjQ4OWYzNTI0MWZkM2FjMjY2NmU4Njc3YTRmY2EzZjFlZmFmMGE2OWYwZWE3ODQ3NTE5ZDZjYjVmNDVjZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8QWyQ1oi8Dmb4o40nhgEiT0WsTqJS_FPcmdU5MLrFOk)

可以尝试在AIStudio上新建一个项目运行试试看，可能是硬件问题？