[WIP]【快乐开源】迁移 CFDGCN 案例至 PaddleScience
PaddlePaddle/PaddleScience pull request #609
Opened 2023-10-30 02:48 UTC by MayYouBeProsperous

### PR types

### PR changes

### Describe

- https://github.com/PaddlePaddle/PaddleScience/issues/441

2023-11-29 07:53 UTC, MayYouBeProsperous commented on ppsci/data/dataset/airfoil_dataset.py
> +        if edges_tran:
amgnet和本模型数据集相同，但图格式不太一样吗

2023-11-29 13:09 UTC, HydrogenSulfate requested changes

2023-11-29 13:09 UTC, HydrogenSulfate commented on ppsci/data/dataset/airfoil_dataset.py
> +        if edges_tran:
看了下AMGNet的代码，这里的转置主要是为了后续在获取sender、receiver以及模型里涉及edge_index的切片更方便。这里可以加这么一个参数，但是名字改一下吧，叫`transpose_edges`，然后Docstring：`Whether transpose the edges array from (2, num_edges) to (num_edges, 2) for convenient of slicing.`

2023-12-01 11:23 UTC, MayYouBeProsperous commented on ppsci/arch/cfdgcn.py
> +UnionTensor = Union[paddle.Tensor, np.ndarray]
Done.

2023-12-01 11:23 UTC, MayYouBeProsperous commented on ppsci/arch/cfdgcn.py
> +def quad2tri(elems: np.array) -> Tuple[List[int], List[int]]:
已修改

2023-12-01 11:23 UTC, MayYouBeProsperous commented on ppsci/arch/cfdgcn.py
> +            new_edges.append(paddle.to_tensor(([[e[0]], [e[2]]]), dtype=paddle.int64))
Done.

2023-12-01 11:23 UTC, MayYouBeProsperous commented on ppsci/arch/cfdgcn.py
> +    output_filename: Union[str, PathLike],
好的已修改

2023-12-01 11:23 UTC, MayYouBeProsperous commented on ppsci/arch/cfdgcn.py
> +        self.mesh_file = meshes_temp_dir + "/" + str(os.getpid()) + "_mesh.su2"
Done.

2023-12-01 11:23 UTC, MayYouBeProsperous commented on ppsci/arch/cfdgcn.py
> +            )
确实不用，移到了 init 中

2023-12-01 11:23 UTC, MayYouBeProsperous commented on ppsci/data/dataset/airfoil_dataset.py
> +        if edges_tran:
Done.

2023-12-01 11:23 UTC, MayYouBeProsperous commented on ppsci/data/process/batch_transform/__init__.py
> +        batch = np.array([g.tensor() for g in batch])
np.array 中的元素是graph对象，本来想返回 list，但下面代码会报错。
https://github.com/PaddlePaddle/PaddleScience/blob/5442d9a2d7f4cfad849dd606216a4a8c4ef0b3a9/ppsci/solver/train.py#L74

2023-12-08 10:53 UTC, MayYouBeProsperous commented on ppsci/arch/cfdgcn.py
Done.

2023-12-08 11:03 UTC, MayYouBeProsperous commented
`CFDGCN` 的 forward 中也会合并图，所以还是将 collate_fn 保持原样，转而调整 `CFDGCN` 。

2023-12-10 07:24 UTC, HydrogenSulfate approved these changes
LGTM

2023-12-10 07:24 UTC, HydrogenSulfate commented
> `CFDGCN` 的 forward 中也会合并图，所以还是将 collate_fn 保持原样，转而修改 `CFDGCN` ，这样代码更整洁。

辛苦大佬

2023-12-10 07:49 UTC, MayYouBeProsperous commented
文档还在编写中

2023-12-11 02:37 UTC, merged