【hydra No.9】cylinder2d_unsteady
PaddlePaddle/PaddleScience pull request #624
Opened 2023-11-03 08:33 UTC by zbt78

PR types
Others

PR changes
Others

Describe
https://github.com/PaddlePaddle/PaddleScience/issues/571
No.9 cylinder2d_unsteady
1、使用第三方库 [hydra](https://hydra.cc/docs/0.11/intro/)适配 cylinder2d_unsteady案例
2、cylinder2d_unsteady案例代码重构，添加评估函数 evaluate，及其训练/评估命令和预训练模型、指标

2023-11-03 14:17 UTC, HydrogenSulfate requested changes

2023-11-03 14:17 UTC, HydrogenSulfate commented on docs/zh/examples/cylinder2d_unsteady.md
> +    ```
评估命令可以先删除

2023-11-03 14:17 UTC, HydrogenSulfate commented on docs/zh/examples/cylinder2d_unsteady.md
> +    ``` sh
``` sh
# linux
wget https://paddle-org.bj.bcebos.com/paddlescience/datasets/cylinder2d_unsteady_Re100/cylinder2d_unsteady_Re100_dataset.tar
# windows
# curl https://paddle-org.bj.bcebos.com/paddlescience/datasets/cylinder2d_unsteady_Re100/cylinder2d_unsteady_Re100_dataset.tar --output cylinder2d_unsteady_Re100_dataset.tar
# unzip it
tar -xvf bracket_dataset.tar
python cylinder2d_unsteady_Re100.py
```

2023-11-03 14:17 UTC, HydrogenSulfate commented on examples/cylinder/2d_unsteady/cylinder2d_unsteady_Re100.py
> +        "NavierStokes": ppsci.equation.NavierStokes(cfg.viscosity, cfg.density, 2, True)
==> cfg.VISCOSITY, cfg.DENSITY

2023-11-03 14:17 UTC, HydrogenSulfate commented on examples/cylinder/2d_unsteady/cylinder2d_unsteady_Re100.py
> +    NPOINT_PDE = cfg.NPOINT_PDE
直接使用cfg.NPOINT_PDE代替NPOINT_PDE

2023-11-03 14:17 UTC, HydrogenSulfate commented on examples/cylinder/2d_unsteady/cylinder2d_unsteady_Re100.py
> +    NPOINT_OUTLET = cfg.NPOINT_OUTLET
同上

2023-11-03 14:17 UTC, HydrogenSulfate commented on examples/cylinder/2d_unsteady/cylinder2d_unsteady_Re100.py
> +        eval_freq=cfg.TRAIN.EVAL_FREQ,
EVAL_FREQ==>eval_freq

2023-11-03 14:17 UTC, HydrogenSulfate commented on examples/cylinder/2d_unsteady/conf/cylinder2d_unsteady.yaml
> +  pretrained_model_path: null
TRAIN.pretrained_model_path可以删除

2023-11-03 14:17 UTC, HydrogenSulfate commented on examples/cylinder/2d_unsteady/cylinder2d_unsteady_Re100.py
> +    equation = {"NavierStokes": ppsci.equation.NavierStokes(0.02, 1.0, 2, True)}
这里的方程仍然可以使用cfg的参数

2023-11-03 14:17 UTC, HydrogenSulfate commented on examples/cylinder/2d_unsteady/cylinder2d_unsteady_Re100.py
> +        ),
`time_rect`这个几何在评估函数中没有使用，可以删除

2023-11-03 14:17 UTC, HydrogenSulfate commented on examples/cylinder/2d_unsteady/cylinder2d_unsteady_Re100.py
> +                "./datasets/domain_eval.csv",
该路径使用cfg.DOMAIN_EVAL_PATH控制

2023-11-03 14:17 UTC, HydrogenSulfate commented on examples/cylinder/2d_unsteady/conf/cylinder2d_unsteady.yaml
> +
新增 `# set validator data path`，存放DOMAIN_EVAL_PATH

2023-11-03 16:53 UTC, zbt78 commented on examples/cylinder/2d_unsteady/cylinder2d_unsteady_Re100.py
> +    # visualize prediction after finished training
All Done.

2023-11-06 08:39 UTC, HydrogenSulfate approved these changes
LGTM

2023-11-06 08:39 UTC, merged