【hydra No.5】shock_wave
PaddlePaddle/PaddleScience pull request #627
Opened 2023-11-06 15:28 UTC by DrRyanHuang

### PR types

Others

### PR changes

Others

### Describe

5. examples/shock_wave.md
- https://github.com/PaddlePaddle/PaddleScience/issues/571

2023-11-07 02:51 UTC, HydrogenSulfate requested changes

2023-11-07 02:51 UTC, HydrogenSulfate commented on examples/shock_wave/conf/shock_wave.yaml
两个配置文件：`shock_wave_Ma2.0.yaml`和`shock_wave_Ma0.728.yaml`

2023-11-07 02:51 UTC, HydrogenSulfate commented on examples/shock_wave/conf/shock_wave.yaml
> +
只保留一个空行

2023-11-07 02:51 UTC, HydrogenSulfate commented on examples/shock_wave/conf/shock_wave.yaml
> +  model:
`model`这一级可以删除，配置直接放`MODEL`下面

2023-11-07 02:51 UTC, HydrogenSulfate commented on examples/shock_wave/conf/shock_wave.yaml
> +
单个空行

2023-11-07 02:51 UTC, HydrogenSulfate commented on examples/shock_wave/conf/shock_wave.yaml
> +  eval_during_train: true
`eval_during_train: false`

2023-11-07 02:51 UTC, HydrogenSulfate commented on examples/shock_wave/conf/shock_wave.yaml
> +    max_iter: 100
删除lr_scheduler、epochs、iters_per_epoch字段，只保留learning_rate和max_iter

2023-11-07 02:51 UTC, HydrogenSulfate commented on examples/shock_wave/shock_wave.py
> +        f"./output_shock_wave_{cfg.MA:.3f}" if not cfg.output_dir else cfg.output_dir
OUTPUT_DIR这个字段可以删除了，直接使用cfg.output_dir

2023-11-07 02:51 UTC, HydrogenSulfate commented on examples/shock_wave/shock_wave.py
> +    model = ppsci.arch.MLP(**cfg.MODEL.model)
全局替换：`cfg.MODEL.model`-->`cfg.MODEL`

2023-11-07 02:51 UTC, HydrogenSulfate commented on examples/shock_wave/shock_wave.py
> +    optimizer = ppsci.optimizer.LBFGS(cfg.TRAIN.lr_scheduler.learning_rate,
``` py
optimizer = ppsci.optimizer.LBFGS(cfg.TRAIN.learning_rate, max_iter=cfg.TRAIN.max_iter)(model)
```

2023-11-07 02:51 UTC, HydrogenSulfate commented on examples/shock_wave/shock_wave.py
> +    EPOCHS = 100 if not cfg.TRAIN.epochs else cfg.TRAIN.epochs
删除EPOCHS字段，由cfg.TRAIN.epochs控制

2023-11-07 02:51 UTC, HydrogenSulfate commented on examples/shock_wave/shock_wave.py
> +        raise ValueError(f"cfg.mode should in ['train'], but got '{cfg.mode}'")
补充evaluate函数

2023-11-07 02:51 UTC, HydrogenSulfate commented on examples/shock_wave/shock_wave.py
> +    main()
文件末尾换行

2023-11-07 02:52 UTC, HydrogenSulfate commented
提交代码之前请安装pre-commit，否则code style CI无法通过
``` sh
pip install pre-commit
pre-commit install
```

2023-11-08 05:43 UTC, HydrogenSulfate commented
修改之前可以先把develop分支合并一下，解决冲突

2023-11-12 10:55 UTC, DrRyanHuang commented
`yaml` 和 `py` 文件修改无误之后，我再更新 `shock_wave.md` 😄😄

2023-11-13 04:04 UTC, HydrogenSulfate requested changes

2023-11-13 04:04 UTC, HydrogenSulfate commented on examples/shock_wave/shock_wave.py
> +
删除多余空行

2023-11-13 04:04 UTC, HydrogenSulfate commented on examples/shock_wave/shock_wave.py
> +    equation = {"Euler2D": Euler2D(), "BC_EQ": BC_EQ()}
此处删除equation变量，评估过程不需要equation参与

2023-11-13 04:04 UTC, HydrogenSulfate commented on examples/shock_wave/shock_wave.py
> +        equation=equation,
删除equation参数

2023-11-13 04:04 UTC, HydrogenSulfate commented on examples/shock_wave/shock_wave.py
> +    equation["BC_EQ"].solver = solver
删除

2023-11-13 04:04 UTC, HydrogenSulfate commented on examples/shock_wave/shock_wave.py
> +    name_value = cfg.MODEL.input_keys
所有name_value用cfg.MODEL.input_keys替换，不再使用这个中间变量

2023-11-14 12:26 UTC, HydrogenSulfate requested changes

2023-11-14 12:26 UTC, HydrogenSulfate commented on examples/shock_wave/conf/shock_wave_Ma0.728.yaml
> +seed: 2023
seed改为42，跟原来保持一致

2023-11-14 12:26 UTC, HydrogenSulfate commented on examples/shock_wave/shock_wave.py
> +        cfg.MODEL.input_keys + ("sin", "cos"),
==> `["sin", "cos"]`，否则list和tuple相加会报错

2023-11-14 12:26 UTC, HydrogenSulfate commented on examples/shock_wave/shock_wave.py
>          eval_with_no_grad=True,
Solver初始化的末尾参数麻烦修改成以下代码，这样配置文件能控制的字段更完整
``` py
pretrained_model_path=cfg.TRAIN.pretrained_model_path,
checkpoint_path=cfg.TRAIN.checkpoint_path,
eval_with_no_grad=cfg.EVAL.eval_with_no_grad,
```

2023-11-14 12:26 UTC, HydrogenSulfate commented on examples/shock_wave/shock_wave.py
> +        eval_with_no_grad=True,
这里改成`eval_with_no_grad=cfg.EVAL.eval_with_no_grad,`

2023-11-14 13:13 UTC, HydrogenSulfate requested changes
这个改完可以开始改文档了，预训练模型地址如下：
``` sh
https://paddle-org.bj.bcebos.com/paddlescience/models/shockwave/shock_wave_Ma2_pretrained.pdparams
https://paddle-org.bj.bcebos.com/paddlescience/models/shockwave/shock_wave_Ma0728_pretrained.pdparams
```

2023-11-14 13:13 UTC, HydrogenSulfate commented on examples/shock_wave/shock_wave.py
> +    solver.eval()
删除solver.eval()，这个模型只有训练和预测，没有评估

2023-11-15 02:21 UTC, HydrogenSulfate requested changes

2023-11-15 02:21 UTC, HydrogenSulfate commented on examples/shock_wave/shock_wave.py
> +@hydra.main(version_base=None, config_path="./conf", config_name="shock_wave.yaml")
==> `config_name="shock_wave_Ma2.0.yaml"`

2023-11-15 02:26 UTC, HydrogenSulfate commented
另一个实验的训练、预测命令可以通过`python shock_wave.py -cn=shock_wave_Ma0.728`里的-cn参数重新指定读取的配置文件

2023-11-15 02:44 UTC, HydrogenSulfate requested changes

2023-11-15 02:44 UTC, HydrogenSulfate commented on docs/zh/examples/shock_wave.md
> +    ```
嵌套卡片的形式，不是写在一个codeblock里，https://github.com/PaddlePaddle/PaddleScience/edit/develop/docs/zh/examples/amgnet.md

2023-11-15 02:44 UTC, HydrogenSulfate commented on docs/zh/examples/shock_wave.md
> +
删除多余空行

2023-11-15 02:44 UTC, HydrogenSulfate commented on docs/zh/examples/shock_wave.md
> +    # another configuration file
改为嵌套卡片形式，删除another configuration file注释

2023-11-15 03:39 UTC, HydrogenSulfate requested changes

2023-11-15 03:39 UTC, HydrogenSulfate commented on docs/zh/examples/shock_wave.md
> +        # curl https://paddle-org.bj.bcebos.com/paddlescience/models/shockwave/shock_wave_Ma2_pretrained.pdparams --output shock_wave_Ma2_pretrained.pdparams
训练不需要下载预训练模型，删除该命令

2023-11-15 03:39 UTC, HydrogenSulfate commented on docs/zh/examples/shock_wave.md
> +        # curl https://paddle-org.bj.bcebos.com/paddlescience/models/shockwave/shock_wave_Ma0728_pretrained.pdparams --output shock_wave_Ma0728_pretrained.pdparams
同上，删除下载命令

2023-11-15 03:39 UTC, HydrogenSulfate commented on docs/zh/examples/shock_wave.md
> +    === "Ma=2"
卡片名称改为`Ma=2.0`跟文档末尾的卡片名保持一致

2023-11-15 03:39 UTC, HydrogenSulfate commented on docs/zh/examples/shock_wave.md
> +=== "模型评估命令"
==> 模型预测命令

2023-11-15 03:39 UTC, HydrogenSulfate commented on docs/zh/examples/shock_wave.md
> +    === "Ma=2"
==> Ma=2.0

2023-11-15 07:14 UTC, HydrogenSulfate approved these changes
LGTM

2023-11-15 07:14 UTC, merged