modify fourcast to hydra style
PaddlePaddle/PaddleScience pull request #633
Opened 2023-11-10 09:51 UTC by zhiminzhang0830

### PR types

Function optimization

### PR changes

Others

### Describe

将FourCastNet案例中的代码修改为使用hydra进行配置

TODO：
更新案例文档

2023-11-13 05:31 UTC, HydrogenSulfate requested changes

2023-11-13 05:31 UTC, HydrogenSulfate commented on examples/fourcastnet/train_pretrain.py
> +    dist.init_parallel_env()
感觉这两行代码可以删掉，分布式的初始化已经在Solver的fleet.init里完成了

2023-11-13 05:31 UTC, HydrogenSulfate commented on examples/fourcastnet/train_pretrain.py
> +            "num_workers": cfg.TRAIN.num_workers,
同上，num_workers感觉可以删掉

2023-11-15 12:51 UTC, zhiminzhang0830 commented on examples/fourcastnet/conf/fourcastnet_finetune.yaml
> +    dir: outputs_fourcastnet_finetune
此模型会在训练precip时作为预训练模型加载进来，带时间的话将不能自动加载

2023-11-15 12:53 UTC, zhiminzhang0830 commented
@HydrogenSulfate done

2023-11-15 12:56 UTC, HydrogenSulfate reviewed
再改一下文档应该就可以了

2023-11-16 08:39 UTC, HydrogenSulfate approved these changes
LGTM

2023-11-16 08:39 UTC, merged