[Add&Modify]Add biharmonic2d example and some other modifies
PaddlePaddle/PaddleScience pull request #651
Opened 2023-11-21 08:07 UTC by lijialin03

### PR types

Others
### PR changes

Others
### Describe

1. add biharmonic2d example
2. add biharmonic2d doc
3. modify biharmonic equation api
4. modify deephpms doc
5. delate some docstring of ppsci.utils.misc.py

2023-11-21 09:29 UTC, HydrogenSulfate requested changes

2023-11-21 09:29 UTC, HydrogenSulfate commented on examples/biharmonic2d/biharmonic2d.py
> +    optimizer_lbfgs = ppsci.optimizer.LBFGS(**cfg.TRAIN.opt.lbfgs)((disp_net,))
单模型可以不用tuple包裹

2023-11-21 09:29 UTC, HydrogenSulfate commented on examples/biharmonic2d/biharmonic2d.py
> +        "num_workers": 0,
是否能设置为1或者更大的值？可以参考batch_cost和reader_cost调调

2023-11-21 09:29 UTC, HydrogenSulfate commented on examples/biharmonic2d/biharmonic2d.py
> +            "y": lambda d: d["y"],
这里的x和y两项是必要的吗？看起来只需要M_y?

2023-11-21 09:29 UTC, HydrogenSulfate commented on examples/biharmonic2d/biharmonic2d.py
> +            "y": lambda d: d["y"],
同上

2023-11-21 09:29 UTC, HydrogenSulfate commented on examples/biharmonic2d/biharmonic2d.py
> +            "y": lambda d: d["y"],
同上

2023-11-21 09:29 UTC, HydrogenSulfate commented on examples/biharmonic2d/biharmonic2d.py
> +            "y": lambda d: d["y"],
同上

2023-11-21 09:29 UTC, HydrogenSulfate commented on examples/biharmonic2d/biharmonic2d.py
> +    save_load.load_pretrain(disp_net, cfg.EVAL.pretrained_model_path)
这个可以用Solver(pretrained_model_path=...)替换

2023-11-21 09:29 UTC, HydrogenSulfate commented on examples/biharmonic2d/biharmonic2d.py
> +    outs_pred = disp_net({"x": x_faltten, "y": y_faltten})
是否可以使用solver.predict接口进行预测？

2023-11-21 09:29 UTC, HydrogenSulfate commented on examples/biharmonic2d/conf/biharmonic2d.yaml
> +  disp_net:
单模型可以删除disp_net这个字段

2023-11-21 09:29 UTC, HydrogenSulfate commented on examples/biharmonic2d/conf/biharmonic2d.yaml
> +  opt:
opt-->optimizer

2023-11-21 09:29 UTC, HydrogenSulfate commented on ppsci/equation/pde/biharmonic.py
> +            q = q(invars)
这个删除吧，当前对Callable的支持限制在某一个完整的Equation上，某个参数为Callable的应该还不是这么写

2023-11-21 09:30 UTC, HydrogenSulfate reviewed
index和README里更新一下这个案例的链接

2023-11-21 09:38 UTC, lijialin03 commented on examples/biharmonic2d/biharmonic2d.py
> +            "y": lambda d: d["y"],
![image](https://github.com/PaddlePaddle/PaddleScience/assets/124568209/019d9def-02fa-484c-8993-60b6efa58539)
这么写是为了让output_dict里包含key='x'，'y'

2023-11-22 05:12 UTC, HydrogenSulfate approved these changes
LGTM

2023-11-22 05:20 UTC, merged