【Hackathon 5th No.54】NSFnets (Navier-Stokes Flow nets): Physics-informed neural networks for the incompressible Navier-Stokes equations
PaddlePaddle/PaddleScience pull request #670
Opened 2023-11-24 13:53 UTC by DUCH714

### PR types
Others 

### PR changes
Others

### Describe
Implementing NSFnet4 by PaddleScience

2023-12-21 10:08 UTC, wangguan1995 commented
LGTM + 需要完善文档，需要按照代码规范修改，需要进一步提高精度，最终修改合入docs/index.md，README.md

2024-01-22 09:55 UTC, HydrogenSulfate requested changes

2024-01-22 09:55 UTC, HydrogenSulfate commented on docs/zh/examples/nsfnet4.md
整个文件使用markdownlint格式化：<https://paddlescience-docs.readthedocs.io/zh/latest/zh/development/#33-markdownlint>

2024-01-22 09:55 UTC, HydrogenSulfate commented on docs/zh/examples/nsfnet4.md
> +    python VP_NSFNet4.py    mode=eval  data_dir=./data/  EVAL.pretrained_model_path=https://paddle-org.bj.bcebos.com/paddlescience/models/nsfnet/nsfnet4.pdparams
删除多余空格

2024-01-22 09:55 UTC, HydrogenSulfate commented on examples/nsfnet/VP_NSFNet4.py
> +    train_vb1 = np.load(data_path + "train_vb2.npy")
`import os.path as osp`，路径拼接一律使用 `osp.join`代替`+`号

2024-01-22 09:55 UTC, HydrogenSulfate commented on examples/nsfnet/VP_NSFNet4.py
> +    wb_train = train_vb1[:, 2:3].astype("float32")
1. 这里的大片astype可以移动到上面各个完整数据numpy.load完毕后的转换，而不是在这里写大片的astype
2. astype的参数建议改为`paddle.get_default_dtype()`，而不是固定的float32

2024-01-22 09:55 UTC, HydrogenSulfate commented on examples/nsfnet/VP_NSFNet4.py
> +    test_v = np.load(data_path + "test43_vp.npy")
同理，osp.join

2024-01-22 09:55 UTC, HydrogenSulfate commented on examples/nsfnet/VP_NSFNet4.py
> +    p_star = test_v[:, 3:4].astype("float32")
同理，类型转换逻辑应该尽量往前移动，而不是在后期进行多次转换

2024-01-22 09:55 UTC, HydrogenSulfate commented on examples/nsfnet/VP_NSFNet4.py
> +        raise ValueError(f"cfg.mode should in ['train', 'eval'], but got '{cfg.mode}'")
main函数移动至最下方

2024-01-22 09:55 UTC, HydrogenSulfate commented on examples/nsfnet/VP_NSFNet4.py
> +    OUTPUT_DIR = cfg.output_dir
将`XXX = cfg.xxx`这类多余的语句删除，直接访问`cfg.xxx`里的数据即可

2024-01-22 09:55 UTC, HydrogenSulfate commented on examples/nsfnet/VP_NSFNet4.py
> +    logger.init_logger("ppsci", f"{OUTPUT_DIR}/train.log", "info")
同上，路径拼接使用osp.join

2024-01-22 09:55 UTC, HydrogenSulfate commented on examples/nsfnet/VP_NSFNet4.py
> +    BETA = cfg.beta
同上

2024-01-22 09:55 UTC, HydrogenSulfate commented on examples/nsfnet/VP_NSFNet4.py
> +def generate_data(data_path):
参数名根据实际语义，建议从`data_path`改为`data_dir`

2024-01-22 09:55 UTC, HydrogenSulfate commented on examples/nsfnet/VP_NSFNet4.py
> +    train_dataloader_cfg_0 = {
这个0表示初值条件吗？可以使用`_ic`，`_0`不太容易让人明白这是什么意思

2024-01-22 09:55 UTC, HydrogenSulfate commented on examples/nsfnet/VP_NSFNet4.py
> +    )
`_0`改为`_ic`

2024-01-22 09:55 UTC, HydrogenSulfate commented on examples/nsfnet/VP_NSFNet4.py
> +    optimizer = ppsci.optimizer.Adam(lr_scheduler)(model)
这里可以自行计算完毕后填写在yaml中，然后`lr_scheduler = ppsci.optimizer.lr_scheduler.Piecewise(
        **cfg.TRAIN.lr_scheduler
    )()`即可，参考<https://github.com/PaddlePaddle/PaddleScience/blob/develop/examples/bracket/conf/bracket.yaml#L81-L87>

2024-01-22 09:55 UTC, HydrogenSulfate commented on examples/nsfnet/VP_NSFNet4.py
> +    logger.init_logger("ppsci", f"{OUTPUT_DIR}/eval.log", "info")
train函数负责训练，这里不需要创建`eval.log`

2024-01-22 09:55 UTC, HydrogenSulfate commented on examples/nsfnet/VP_NSFNet4.py
> +    )
参数顺序尽量和Solver的参数顺序保持一致，如`output_dir`不应该最下方

2024-01-22 09:55 UTC, HydrogenSulfate commented on examples/nsfnet/VP_NSFNet4.py
> +    print("L2 error picture is saved at ")
使用logger.info或logger.message代替print

2024-01-22 09:55 UTC, HydrogenSulfate commented on examples/nsfnet/conf/VP_NSFNet4.yaml
> +
配置文件参考bracket.yaml<https://github.com/PaddlePaddle/PaddleScience/blob/develop/examples/bracket/conf/bracket.yaml>修改规范

2024-01-22 10:08 UTC, DUCH714 commented on docs/zh/examples/nsfnet4.md
不是使用vscode编译，无法安装markdownlint拓展

2024-01-22 10:17 UTC, DUCH714 commented on examples/nsfnet/VP_NSFNet4.py
> +    OUTPUT_DIR = cfg.output_dir
像OUTPUT_DIR这种后面还会反复用，不算多余语句

2024-01-22 10:29 UTC, DUCH714 commented on examples/nsfnet/VP_NSFNet4.py
> +    optimizer = ppsci.optimizer.Adam(lr_scheduler)(model)
并不是指数衰减或等距衰减，无法自行计算

2024-01-22 10:42 UTC, HydrogenSulfate commented on docs/zh/examples/nsfnet4.md
> 不是使用vscode编译，无法安装markdownlint拓展

@wangguan1995 帮忙格式化一下

2024-01-22 10:43 UTC, HydrogenSulfate commented on examples/nsfnet/VP_NSFNet4.py
> +    OUTPUT_DIR = cfg.output_dir
> 像OUTPUT_DIR这种后面还会反复用，不算多余语句

反复使用也可以通过`cfg.xxx`，OUTPUT_DIR属于是不必要的中间变量

2024-01-22 10:43 UTC, HydrogenSulfate commented
> 0和IC那个，在偏微分方程中，_0是指u_0即u|t=0的意思，一般不写作ic，源码当中也是用0来表示的。
> 
> 而且写作ic，严谨来说也应该把_b写作bc。
> 
> 另外ic歧义较多，如 initial condition, integral condition, 以及 interior condition。
> 
> 虽然已改，但不建议写作ic。

好的

2024-01-22 10:46 UTC, DUCH714 commented on examples/nsfnet/VP_NSFNet4.py
> +    optimizer = ppsci.optimizer.Adam(lr_scheduler)(model)
epoch_list和lr_list之前我和 @wangguan1995 尝试过，如果填入yaml会导致CI过不了（我一开始就是把epoch_list和lr_list写入了yaml里面），具体报错原因可以看我之前的版本。因此现在在NSFNet1 2 3 4中都是写在代码里面

2024-01-22 10:51 UTC, DUCH714 commented on examples/nsfnet/VP_NSFNet4.py
> +    optimizer = ppsci.optimizer.Adam(lr_scheduler)(model)
可能写的格式不对？我们之前的写法如这个文件：https://github.com/DUCH714/hackthon5th53/blob/44ee77bcb5f425f6150815ce5423dbc1f7c0e160/examples/nsfnet/conf/VP_NSFNet1.yaml

2024-01-22 11:11 UTC, DUCH714 commented on examples/nsfnet/VP_NSFNet4.py
> +    OUTPUT_DIR = cfg.output_dir
已改，并将eval中的data_path=cfg.data_dir一并修改

2024-01-22 11:13 UTC, DUCH714 commented on examples/nsfnet/VP_NSFNet4.py
> +    optimizer = ppsci.optimizer.Adam(lr_scheduler)(model)
已删除EPOCHS、ITERS_PER_EPOCH

2024-01-22 11:14 UTC, HydrogenSulfate commented on examples/nsfnet/VP_NSFNet4.py
> +    optimizer = ppsci.optimizer.Adam(lr_scheduler)(model)
> 可能写的格式不对？我们之前的写法如这个文件：https://github.com/DUCH714/hackthon5th53/blob/44ee77bcb5f425f6150815ce5423dbc1f7c0e160/examples/nsfnet/conf/VP_NSFNet1.yaml

需要看一下具体的CI报错：是PaddleScience的测试还是codestype测试？然后具体的问题是什么，能给一个错误的截图吗？
![Uploading image.png…]()

2024-01-22 11:14 UTC, DUCH714 commented
已将SEED改为cfg.seed

2024-01-22 11:24 UTC, DUCH714 commented on examples/nsfnet/VP_NSFNet4.py
> +    optimizer = ppsci.optimizer.Adam(lr_scheduler)(model)
比较难找，已设置为该格式重新上传，看看能不能过吧

2024-01-22 11:46 UTC, DUCH714 commented on examples/nsfnet/VP_NSFNet4.py
> +    optimizer = ppsci.optimizer.Adam(lr_scheduler)(model)
没报错了，已修改。

2024-01-22 12:21 UTC, HydrogenSulfate requested changes

2024-01-22 12:21 UTC, HydrogenSulfate commented on docs/zh/examples/nsfnet4.md
> +与论文中描述相同, 我们使用分段学习率构造Adam优化器, 其中可以通过调节_epoch_list_来调节训练轮数。
删除_epoch_list_两侧下划线

2024-01-22 12:21 UTC, HydrogenSulfate commented on docs/zh/examples/nsfnet4.md
> +[Github NSFnets](https://github.com/Alexzihaohu/NSFnets/tree/master)
使用无序列表形式,前面加上短划线：`- xxx`

2024-01-22 12:21 UTC, HydrogenSulfate commented on examples/nsfnet/VP_NSFNet4.py
> +    t0_train = np.zeros(train_ini1[:, 0:1].shape, np.float32)
改为`np.zeros_like(train_ini1[:, 0:1])`

2024-01-22 12:21 UTC, HydrogenSulfate commented on examples/nsfnet/VP_NSFNet4.py
> +    ppsci.utils.misc.set_random_seed(cfg.seed)
136-138行代码可以删除，创建logger和固定种子在配置文件中的callback会在程序运行前自动执行

2024-01-22 12:21 UTC, HydrogenSulfate commented on examples/nsfnet/VP_NSFNet4.py
> +    valida_dataloader_cfg = {
valida-->valid

2024-01-22 12:21 UTC, HydrogenSulfate commented on examples/nsfnet/VP_NSFNet4.py
> +        new_epoch_list.append(sum(cfg.epoch_list[: i + 1]))
new_epoch_list这个变量没使用到？

2024-01-22 12:21 UTC, HydrogenSulfate commented on examples/nsfnet/VP_NSFNet4.py
> +        visualizer=None,
visualizer=None可以删除

2024-01-22 12:21 UTC, HydrogenSulfate commented on examples/nsfnet/VP_NSFNet4.py
> +        eval_with_no_grad=False,
eval_with_no_grad应该是True吧，因为看测试数据集需要计算的是u, v, w, p,这几个是模型输出，不涉及微分计算

2024-01-22 12:21 UTC, HydrogenSulfate commented on examples/nsfnet/VP_NSFNet4.py
> +
同上，删除320-322行

2024-01-22 12:21 UTC, HydrogenSulfate commented on examples/nsfnet/VP_NSFNet4.py
> +    plt.savefig(cfg.output_dir + "/error.jpg")
1. 路径使用osp.join 连接
2. /error.jpg去掉前面的斜杠

2024-01-22 12:21 UTC, HydrogenSulfate commented on examples/nsfnet/VP_NSFNet4.py
> +    plt.savefig(cfg.output_dir + "/z=0 plane")
路径问题同上

2024-01-22 12:21 UTC, HydrogenSulfate commented on examples/nsfnet/VP_NSFNet4.py
> +    plt.savefig(cfg.output_dir + "/x=0 plane")
路径问题同上

2024-01-22 12:21 UTC, HydrogenSulfate commented on examples/nsfnet/conf/VP_NSFNet4.yaml
> +iters_per_epoch: 150
这个字段可以删除了吧，在TRAIN下面已经有了

2024-01-22 12:21 UTC, HydrogenSulfate commented on examples/nsfnet/conf/VP_NSFNet4.yaml
> +
多余的空行可以删一下，如25、27行

2024-01-22 12:21 UTC, HydrogenSulfate commented on examples/nsfnet/conf/VP_NSFNet4.yaml
> +train:
train->TRAIN

2024-01-22 12:21 UTC, HydrogenSulfate commented on examples/nsfnet/conf/VP_NSFNet4.yaml
> +    lr_list: [1e-3, 1e-4, 1e-5, 1e-6, 1e-7]
多余空行可以删一下

2024-01-23 02:59 UTC, HydrogenSulfate submitted a review, later dismissed
LGTM

@wangguan1995 帮忙检查下文档并格式化

2024-01-25 12:00 UTC, HydrogenSulfate approved these changes
LGTM

2024-01-25 12:00 UTC, merged