Hackathon 5th No.63 PhyCRNet: Physics-informed Convolutional-Recurrent Network for Solving Spatiotemporal PDEs
PaddlePaddle/PaddleScience pull request #674
Opened 2023-11-30 17:30 UTC by DUCH714

### PR types
Others 

### PR changes
Others

### Describe
Continue the work [#557](https://github.com/PaddlePaddle/PaddleScience/pull/557)

2024-01-18 03:47 UTC, HydrogenSulfate requested changes

2024-01-18 03:47 UTC, HydrogenSulfate commented on examples/phycrnet/conf/fitzhugh_nagumo_RD_equation.yaml
> +    dir: outputs_phycrnet/${now:%Y-%m-%d}/${now:%H-%M-%S}/${hydra.job.override_dirname}
这里的名字和另一个案例建议区分一下

2024-01-18 03:47 UTC, HydrogenSulfate commented on examples/phycrnet/conf/lambda_omega_RD_equation.yaml
> +    dir: outputs_phycrnet/${now:%Y-%m-%d}/${now:%H-%M-%S}/${hydra.job.override_dirname}
同上

2024-01-18 03:47 UTC, HydrogenSulfate commented on examples/phycrnet/main.py
> +    num_convlstm = 1
常量使用大写

2024-01-18 03:47 UTC, HydrogenSulfate commented on examples/phycrnet/main.py
> +    optimizer = ppsci.optimizer.Adam(cfg.TRAIN.lr_scheduler.learning_rate)(model)
为什么上面实例化了学习率调节器，却给opt设定了恒定学习率呢？

2024-01-18 03:47 UTC, HydrogenSulfate commented on examples/phycrnet/main.py
> +    checkpoint_path = os.path.join(cfg.output_dir, "phycrnet.pdparams")
os.path==> osp，其他地方都检查一下

2024-01-18 03:47 UTC, HydrogenSulfate commented on examples/phycrnet/main.py
> +    paddle.save(layer_state_dict, checkpoint_path)
训练过程会自动保存最新的模型参数到latest.pdparams，不需要在这里手动保存

2024-01-18 03:47 UTC, HydrogenSulfate commented on examples/phycrnet/main.py
> +    num_convlstm = 1
大写

2024-01-18 03:47 UTC, HydrogenSulfate commented on mkdocs.yml
> +          - PhyCRNet: zh/examples/phycrnet.md
文档位置按字典序排序

2024-01-18 03:47 UTC, HydrogenSulfate commented on ppsci/arch/__init__.py
> +
按字典序排序，并且不要有多余空行

2024-01-18 03:47 UTC, HydrogenSulfate commented on ppsci/arch/phycrnet.py
> +lapl_op = [
常量大写

2024-01-18 03:47 UTC, HydrogenSulfate commented on ppsci/arch/phycrnet.py
> +partial_y = [
常量大写

2024-01-18 03:47 UTC, HydrogenSulfate commented on ppsci/arch/phycrnet.py
> +partial_x = [
常量大写

2024-01-18 03:47 UTC, HydrogenSulfate commented on ppsci/arch/phycrnet.py
> +def initialize_weights(module):
内部使用的函数建议以单划线`_`开头

2024-01-18 03:47 UTC, HydrogenSulfate commented on ppsci/arch/phycrnet.py
> +            )
doctest格式不正确，78~86行需要以 `...` 开头

2024-01-18 03:47 UTC, HydrogenSulfate commented on ppsci/arch/phycrnet.py
> +            setattr(self, name, cell)
不建议通过这种setattr的方式设置网络层，这是一种不推荐而且不符合正常使用习惯的做法。正确的做法应该是使用`nn.LayerList`去封装多层平行的网络结构，然后通过下标访问。<https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/LayerList_cn.html#layerlist>

2024-01-18 03:47 UTC, HydrogenSulfate commented on ppsci/arch/phycrnet.py
> +            self._all_layers.append(cell)
同理

2024-01-18 03:47 UTC, HydrogenSulfate commented on ppsci/arch/phycrnet.py
> +                name = "convlstm{}".format(i)
同理

2024-01-18 03:47 UTC, HydrogenSulfate commented on ppsci/arch/phycrnet.py
> +        R = 200.0
这里的R是一个magicnumber，能否说明一下具体意义呢？

2024-01-18 07:13 UTC, DUCH714 commented on examples/phycrnet/main.py
> +    optimizer = ppsci.optimizer.Adam(cfg.TRAIN.lr_scheduler.learning_rate)(model)
源码使用了调节器，但是在实际调试中发现恒定学习率效果更优

2024-01-18 07:14 UTC, DUCH714 commented on examples/phycrnet/main.py
> +    optimizer = ppsci.optimizer.Adam(cfg.TRAIN.lr_scheduler.learning_rate)(model)
已改为匹配源码

2024-01-19 05:09 UTC, HydrogenSulfate approved these changes
LGTM

2024-01-19 05:32 UTC, merged