heat exchanger
PaddlePaddle/PaddleScience pull request #693
Opened 2023-12-11 03:18 UTC by liaoxin2

### PR types
One of New example

### PR changes
heat exchanger APIs

### Describe
heat exchanger code

2023-12-14 08:02 UTC, HydrogenSulfate requested changes

2023-12-14 08:02 UTC, HydrogenSulfate commented on ppsci/equation/pde/heat_exchanger.py
> +    Subscripts \(\mathrm{h}\), \(\mathrm{c}\), and \(\mathrm{w}\) denote the hot fluid side, cold fluid side, and heat transfer wall, respectively.
公式在文档中无法渲染，参考<https://katex.org/docs/supported.html#style-color-size-and-font>文档重新写一下公式，然后mkdocs serve确认下能正确渲染

2023-12-14 08:02 UTC, HydrogenSulfate commented on ppsci/equation/pde/heat_exchanger.py
> +        w_c: (eta_o*alpha*A)_c/(M*c_pw)
1. 参数前加上英文描述
2. 句子结尾加上英文逗号`.`

2023-12-14 08:02 UTC, HydrogenSulfate commented on ppsci/equation/__init__.py
> +from ppsci.equation.pde import HeatExchanger
把HeatExchanger加到equation.md中

2023-12-16 06:11 UTC, HydrogenSulfate requested changes

2023-12-16 06:11 UTC, HydrogenSulfate commented on examples/heat_exchanger/heat_exchanger.py
> +            "T_h": lambda out: out["T_h"] - T_hin,
删除末尾逗号，变成一行

2023-12-16 06:11 UTC, HydrogenSulfate commented on examples/heat_exchanger/heat_exchanger.py
> +            "T_h": lambda out: out["T_c"] - T_cin,
同上，整合成一行

2023-12-16 06:11 UTC, HydrogenSulfate commented on examples/heat_exchanger/heat_exchanger.py
> +            "T_h": lambda out: out["T_h"] - T_hin,
同上，整合成一行

2023-12-16 06:11 UTC, HydrogenSulfate commented on examples/heat_exchanger/heat_exchanger.py
> +            "T_h": lambda out: out["T_c"] - T_cin,
同上，整合成一行

2023-12-16 06:11 UTC, HydrogenSulfate commented on examples/heat_exchanger/heat_exchanger.py
> +    )
pretrained_model_path: null， checkpoint_path: null、eval_with_no_grad: true这两个配置文件中的参数并没有填写在这里

2023-12-16 06:11 UTC, HydrogenSulfate commented on examples/heat_exchanger/heat_exchanger.py
> +    )
eval_with_no_grad: true这两个配置文件中的参数并没有填写在这里

2023-12-16 06:11 UTC, HydrogenSulfate commented on ppsci/arch/PI_deeponets_HE.py
> +class PI_DeepONets(base.Arch):
根据这个模型的代码，感觉是比较定制化的热交换DeepONet，可以叫HEDeepONet

2023-12-16 06:11 UTC, HydrogenSulfate commented on ppsci/arch/PI_deeponets_HE.py
> +# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
文件名一律小写，改为 `he_deeponet.py`

2023-12-18 09:04 UTC, liaoxin2 commented on ppsci/equation/pde/heat_exchanger.py
> +        >>> pde = ppsci.equation.HeatExchanger(1.0,1.0,1.0,1.0,1.0,1.0)
参数之间是用逗号隔开的，1.0是一个参数

2023-12-20 04:12 UTC, HydrogenSulfate requested changes

2023-12-20 04:12 UTC, HydrogenSulfate commented on examples/heat_exchanger/heat_exchanger.py
所有文件里的`PI_DeepONets`改为`HEDeepONets`

2023-12-20 04:12 UTC, HydrogenSulfate commented on ppsci/arch/PI_deeponets_HE.py
这个文件是不是多余的，可以删除掉

2023-12-20 08:21 UTC, HydrogenSulfate approved these changes
LGTM

2023-12-21 08:04 UTC, merged