【PPSCI Doc No.75, 77-85】
PaddlePaddle/PaddleScience pull request #703
Opened 2023-12-16 07:54 UTC by NKNaN

### PR types
Others

### PR changes
Docs

### Describe
No.75, 77-85

2023-12-20 04:07 UTC, HydrogenSulfate requested changes
感谢大佬提交PR

2023-12-20 04:07 UTC, HydrogenSulfate commented on ppsci/loss/func.py
> +
这里可以删掉，因为 FunctionalLoss 不需要 reduction这个参数

2023-12-20 04:07 UTC, HydrogenSulfate commented on ppsci/loss/func.py
>      def __init__(
可以把下方的reduction这个参数删除

2023-12-20 04:07 UTC, HydrogenSulfate commented on ppsci/loss/func.py
>          reduction (Literal["mean", "sum"], optional): Reduction method. Defaults to "mean".
可以删除reduction参数

2023-12-20 05:33 UTC, NKNaN commented on ppsci/loss/func.py
> +
已删除

2023-12-20 05:33 UTC, NKNaN commented on ppsci/loss/func.py
>          reduction (Literal["mean", "sum"], optional): Reduction method. Defaults to "mean".
已删除

2023-12-20 05:33 UTC, NKNaN commented on ppsci/loss/func.py
>      def __init__(
已删除

2023-12-21 07:48 UTC, HydrogenSulfate requested changes
函数f处的参数加粗一下就行了，辛苦

2023-12-21 07:48 UTC, HydrogenSulfate commented on ppsci/loss/func.py
> +    L = f(x, y)
``` suggestion
    L = f(\mathbf{x}, \mathbf{y})
```

2023-12-21 11:12 UTC, HydrogenSulfate approved these changes
LGTM

2023-12-21 11:12 UTC, merged