add doc for CFDGCN example
PaddlePaddle/PaddleScience pull request #720
Opened 2023-12-25 05:37 UTC by MayYouBeProsperous

### PR types

Others 

### PR changes

Docs 

### Describe

CDFGCN 案例文档

2023-12-25 06:56 UTC, HydrogenSulfate commented on docs/zh/examples/cfdgcn.md
保留一个空行

2023-12-25 07:10 UTC, HydrogenSulfate requested changes
辛苦大佬撰写文档！文档质量很高 :+1:

2023-12-25 07:10 UTC, HydrogenSulfate commented on docs/zh/examples/cfdgcn.md
> +wget -nc -P ./datasets/ https://bj.bcebos.com/v1/ai-studio-online/ba71af9a00fb4aa5ac0d34cca67d9c39332ca4ebb0b2462cb3a8503de2dfc367?responseContentDisposition=attachment%3B%20filename%3Ddata.zip
这个我重新传一下吧，不然下载过来的名字不太对的

2023-12-25 07:10 UTC, HydrogenSulfate commented on docs/zh/examples/cfdgcn.md
> +export SU2_HOME=<your path of su2 directory>
这里可以写的更清晰一点，假设 su2 的文件夹叫`SU2`，那么可以写成：`/absolute_path/to/SU2/`

2023-12-25 07:10 UTC, HydrogenSulfate commented on docs/zh/examples/cfdgcn.md
> +下方展示了模型对计算域中每个点的压力$p(x,y)$、x(水平)方向流速$u(x,y)$、y(垂直)方向流速$v(x,y)$的预测结果与参考结果。
"x(水平)方向流速"两侧加上美元符号$

2023-12-25 07:10 UTC, HydrogenSulfate commented on docs/zh/examples/cfdgcn.md
> +    wget -nc -P ./datasets/ https://bj.bcebos.com/v1/ai-studio-online/ba71af9a00fb4aa5ac0d34cca67d9c39332ca4ebb0b2462cb3a8503de2dfc367?responseContentDisposition=attachment%3B%20filename%3Ddata.zip
根据下面的 unzip data.zip 这里是否不需要 `-P ./datasets` ?

2023-12-25 07:10 UTC, HydrogenSulfate commented on docs/zh/examples/cfdgcn.md
> +    wget -nc -P ./datasets/ https://bj.bcebos.com/v1/ai-studio-online/netdisk/fdec42eb993c4c9cb5fa21c641a9e5e88f9bb7b1c5e54154afd50d6198552752?responseContentDisposition=attachment%3B%20filename%3DSU
同上，是否可以删除`-P ./datasets/`

2023-12-25 07:13 UTC, HydrogenSulfate commented on docs/zh/examples/cfdgcn.md
> +wget -nc -P ./datasets/ https://bj.bcebos.com/v1/ai-studio-online/ba71af9a00fb4aa5ac0d34cca67d9c39332ca4ebb0b2462cb3a8503de2dfc367?responseContentDisposition=attachment%3B%20filename%3Ddata.zip
data.zip: <https://paddle-org.bj.bcebos.com/paddlescience/datasets/CFDGCN/data.zip>

2023-12-25 07:16 UTC, HydrogenSulfate commented on docs/zh/examples/cfdgcn.md
> +wget -nc -P ./datasets/ https://bj.bcebos.com/v1/ai-studio-online/ba71af9a00fb4aa5ac0d34cca67d9c39332ca4ebb0b2462cb3a8503de2dfc367?responseContentDisposition=attachment%3B%20filename%3Ddata.zip
SU2Bin.tgz: <https://paddle-org.bj.bcebos.com/paddlescience/datasets/CFDGCN/SU2Bin.tgz>

2023-12-25 12:58 UTC, HydrogenSulfate requested changes
文本应该没啥问题了，麻烦大佬再用vscode右键格式化一下，有很多地方会被修改
![image](https://github.com/PaddlePaddle/PaddleScience/assets/23737287/75639f32-d75d-491b-9f05-168f792c2826)

2023-12-25 13:02 UTC, HydrogenSulfate requested changes

2023-12-25 13:02 UTC, HydrogenSulfate commented on docs/zh/examples/cfdgcn.md
>  ```
==> ``` 后面加上 `shell`

2023-12-25 14:21 UTC, MayYouBeProsperous commented
> 文本应该没啥问题了，麻烦大佬再用vscode右键格式化一下，有很多地方会被修改 ![image](https://private-user-

这个需要什么插件吗，我这里格式化没有变化。

2023-12-26 02:25 UTC, HydrogenSulfate commented
> > 文本应该没啥问题了，麻烦大佬再用vscode右键格式化一下，有很多地方会被修改 ![image](https://private-user-
> 
> 这个需要什么插件吗，我这里格式化没有变化。

Markdownlint应该是

2023-12-26 04:51 UTC, HydrogenSulfate approved these changes
LGTM 👍

2023-12-26 06:09 UTC, merged