【PPSCI Doc No.93-96, 98-102】
PaddlePaddle/PaddleScience pull request #730
Opened 2023-12-31 07:55 UTC by NKNaN

### PR types
Others

### PR changes
Docs

### Describe
PPSCI Doc No.93-96, 98-102

2024-01-01 13:47 UTC, HydrogenSulfate requested changes
辛苦大佬

2024-01-01 13:47 UTC, HydrogenSulfate commented on ppsci/utils/misc.py
> +               [6.]])}
这里可以打印一下arr.shape，然后用for循环打印一下result里的k, v.shape，这样子能更直观

2024-01-01 13:47 UTC, HydrogenSulfate commented on ppsci/utils/misc.py
> +        <BLANKLINE>
这里的两处<BLANKLINE>感觉不是很有必要，删掉也行？

2024-01-03 03:44 UTC, NKNaN commented on ppsci/utils/misc.py
> +               [6.]])}
已修改

2024-01-03 03:44 UTC, NKNaN commented on ppsci/utils/misc.py
> +        <BLANKLINE>
已删除

2024-01-03 05:05 UTC, HydrogenSulfate commented on ppsci/utils/misc.py
> +
这里需要空行的原因是什么呢，可以删除吗

2024-01-03 05:16 UTC, NKNaN commented on ppsci/utils/misc.py
> +
已删除

2024-01-03 05:31 UTC, HydrogenSulfate approved these changes
LGTM

2024-01-03 05:31 UTC, merged