update PhyGeoNet
PaddlePaddle/PaddleScience pull request #731
Opened 2024-01-01 05:52 UTC by zhiminzhang0830

### PR types

Others
### PR changes

Others
### Describe

更新PhyGeoNet案例代码
TODO：更新案例文档

2024-01-01 14:14 UTC, HydrogenSulfate requested changes

2024-01-01 14:14 UTC, HydrogenSulfate commented on examples/phygeonet/heat_equation.py
> +    def _transform_out(_input, _output, pad_singleside=pad_singleside):
加一下type-hint以及docstring

2024-01-01 14:14 UTC, HydrogenSulfate commented on examples/phygeonet/heat_equation.py
> +from utils import visualize
改为`import util`+`utils.xxx`的调用方式

2024-01-01 14:14 UTC, HydrogenSulfate commented on examples/phygeonet/heat_equation.py
> +        Jinv = _input["jinvs"]
Jinv变量改为小写

2024-01-01 14:14 UTC, HydrogenSulfate commented on examples/phygeonet/heat_equation.py
> +    OFV_sb = paddle.to_tensor(data["OFV_sb"])
同，改为小写

2024-01-01 14:14 UTC, HydrogenSulfate commented on examples/phygeonet/heat_equation.py
> +    OFV_sb = OFV_sb.numpy()
改为小写

2024-01-01 14:14 UTC, HydrogenSulfate commented on examples/phygeonet/heat_equation_with_bc.py
> +    for j in range(batchSize):
改为batch_size

2024-01-01 14:14 UTC, HydrogenSulfate commented on examples/phygeonet/heat_equation_with_bc.py
> +    logger.info(eV / len_data)
打印时说明一下该内容的含义，比如 `f"xxxx: {eV / len_data}"`

2024-01-01 14:14 UTC, HydrogenSulfate commented on examples/phygeonet/heat_equation_with_bc.py
> +    ParaList = [1, 2, 3, 4, 5, 6, 7]
全大写

2024-01-01 14:14 UTC, HydrogenSulfate commented on examples/phygeonet/heat_equation_with_bc.py
> +        fig1.savefig(f"{cfg.output_dir}/Para{i}T.png", bbox_inches="tight")
路径拼接一律使用`osp.join`

2024-01-01 14:14 UTC, HydrogenSulfate commented on examples/phygeonet/utils.py
> +def dfdx(f, dydeta, dydxi, Jinv, h=0.01):
1. 加上typehint和docstring，并说明这是离散差分的形式来近似计算微分
2. 变量统一按照其语义进行大小写

2024-01-01 14:14 UTC, HydrogenSulfate commented on examples/phygeonet/utils.py
> +def dfdy(f, dxdxi, dxdeta, Jinv, h=0.01):
同上

2024-01-01 14:14 UTC, HydrogenSulfate commented on examples/phygeonet/utils.py
> +def setAxisLabel(ax, type):
函数名使用小写，并用单下划线分隔单词

2024-01-01 14:14 UTC, HydrogenSulfate commented on examples/phygeonet/utils.py
> +def gen_e2vcg(x):
e2vcg意义不明，在docstring中补上说明

2024-01-01 14:14 UTC, HydrogenSulfate commented on examples/phygeonet/utils.py
> +def tikzplotlib_fix_ncols(obj):
这个函数好像没用到，可以删除？

2024-01-01 14:14 UTC, HydrogenSulfate commented on examples/phygeonet/utils.py
> +    return e2vcg.astype("int")
改为"int64"

2024-01-02 11:43 UTC, zhiminzhang0830 commented
@HydrogenSulfate done

2024-01-03 02:41 UTC, HydrogenSulfate requested changes

2024-01-03 02:41 UTC, HydrogenSulfate commented on examples/phygeonet/heat_equation.py
> +    logger.init_logger("ppsci", osp.join(cfg.output_dir, "train.log"), "info")
seed和logger初始化参考这个PR，用callback代替：<https://github.com/PaddlePaddle/PaddleScience/pull/735/files#diff-3c52abd045ca9579a698e50fac809f4ef64a0ceb1b4051f97f60ede43acc7091R17-R19>

2024-01-03 02:41 UTC, HydrogenSulfate commented on examples/phygeonet/heat_equation.py
> +
同上

2024-01-03 02:41 UTC, HydrogenSulfate commented on examples/phygeonet/heat_equation_with_bc.py
2个py文件修改一下

2024-01-03 11:19 UTC, zhiminzhang0830 commented
@HydrogenSulfate done

2024-01-03 11:22 UTC, HydrogenSulfate approved these changes
LGTM

2024-01-03 12:19 UTC, HydrogenSulfate approved these changes
LGTM

2024-01-03 12:19 UTC, merged