Surrogate fix
PaddlePaddle/PaddleScience pull request #740
Opened 2024-01-05 11:51 UTC by wangguan1995

### PR types

Bug fixes
### PR changes

Docs APIs
### Describe

refactor docs ,refactor into configuration style

2024-01-05 13:04 UTC, HydrogenSulfate requested changes

2024-01-05 13:04 UTC, HydrogenSulfate commented on examples/aneurysm/aneurysm_flow.py
>      logger.init_logger("ppsci", f"{OUTPUT_DIR}/train.log", "info")
seed和_init_logger删除，现在会在callback中完成，不需要手动调用

2024-01-05 13:04 UTC, HydrogenSulfate commented on examples/aneurysm/aneurysm_flow.py
> +    OUTPUT_DIR = cfg.output_dir
删除该无用变量

2024-01-05 13:04 UTC, HydrogenSulfate commented on examples/aneurysm/aneurysm_flow.py
>      X_OUT = X_IN + L
这类超参数定义放到配置文件里，参考 aneurysm.yaml，全部通过cfg.xxx访问

2024-01-05 13:04 UTC, HydrogenSulfate commented on examples/aneurysm/aneurysm_flow.py
> +    BATCH_SIZE = cfg.TRAIN.batch_size
删除无用变量

2024-01-05 13:04 UTC, HydrogenSulfate commented on examples/aneurysm/aneurysm_flow.py
删除空行

2024-01-05 13:04 UTC, HydrogenSulfate commented on examples/aneurysm/aneurysm_flow.py
> +def evaluate(cfg: DictConfig):
evaluate函数也进行同样的改动，删除无用中间变量&多余空行

2024-01-05 13:04 UTC, HydrogenSulfate commented on examples/aneurysm/conf/aneurysm_flow.yaml
连续的空行保留一个

2024-01-05 13:05 UTC, HydrogenSulfate requested changes

2024-01-05 13:05 UTC, HydrogenSulfate commented on docs/zh/examples/labelfree_DNN_surrogate.md
放上预训练模型和对应精度信息，如下所示
![image](https://github.com/PaddlePaddle/PaddleScience/assets/23737287/c20aaad8-b2c0-42ea-8195-787fbe053c95)

2024-01-08 05:10 UTC, wangguan1995 reviewed
fix

2024-01-08 05:10 UTC, wangguan1995 commented on examples/aneurysm/aneurysm_flow.py
>      X_OUT = X_IN + L
X_OUT为非网络训练参数

2024-01-08 05:27 UTC, HydrogenSulfate requested changes

2024-01-08 05:27 UTC, HydrogenSulfate commented on examples/aneurysm/conf/aneurysm_flow.yaml
参照bracket.yaml修改，问题如：output_dir是一级字段不需要放在EVAL下面、dir后面仍然错误使用的是outputs_VIV

2024-01-08 11:45 UTC, HydrogenSulfate approved these changes
LGTM

2024-01-08 11:45 UTC, merged