update phygeonet doc
PaddlePaddle/PaddleScience pull request #747
Opened 2024-01-10 12:38 UTC by zhiminzhang0830

### PR types

Others
### PR changes

Docs
### Describe

更新PhyGeoNet案例文档

2024-01-11 11:54 UTC, HydrogenSulfate requested changes

2024-01-11 11:54 UTC, HydrogenSulfate commented on docs/zh/examples/phygeonet.md
下方预训练模型名字末尾加上 `.pdparams`

2024-01-12 02:05 UTC, zhiminzhang0830 commented on docs/zh/examples/phygeonet.md
done

2024-01-12 02:06 UTC, HydrogenSulfate approved these changes
LGTM

2024-01-12 03:40 UTC, merged