【PPSCI Doc No.20】ppsci.arch.DeepPhyLSTM
PaddlePaddle/PaddleScience pull request #756
Opened 2024-01-17 10:35 UTC by megemini

### PR types

Others

### PR changes

Docs

### Describe

完善 ppsci.arch.DeepPhyLSTM 的示例 ～

由于对此模型的具体应用还不熟悉，请帮忙看看这样修改是否合适 ～

关联 PR https://github.com/PaddlePaddle/PaddleScience/issues/686

@HydrogenSulfate 请评审 ～

2024-01-17 10:54 UTC, HydrogenSulfate requested changes
感谢大佬提交PR，另外想问一个问题，xdoctest相比pydoctest有什么不可代替的优势吗，我粗略看了一下xdoctest的文档，感觉没有发现很强的优势呢

2024-01-17 10:54 UTC, HydrogenSulfate commented on ppsci/arch/phylstm.py
> +
这个末尾空行感觉可以删掉吧

2024-01-17 11:14 UTC, megemini commented
> 感谢大佬提交PR，另外想问一个问题，xdoctest相比pydoctest有什么不可代替的优势吗，我粗略看了一下xdoctest的文档，感觉没有发现很强的优势呢

pydoctest 没深入用过，大体翻了一下它的代码，相比 doctest 和 xdoctest ，好像缺少 directive 的支持，一些配置也没有，比如忽略空格/空行，使用 `...` 等 ～

之前 paddle 引入 xdcotest 的时候做了一些扩展，比如支持数值类型的比对，支持 cpu/gpu 之类针对 paddle 的 tensor 的模糊比对之类的 ～

pydoctest 相比 xdoctest 多了支持 vscode 的支持 ～

各取所需吧 ～ ：）

2024-01-17 11:15 UTC, megemini commented on ppsci/arch/phylstm.py
> +
已删除 ～

2024-01-17 11:44 UTC, HydrogenSulfate approved these changes
LGTM。

然后关于xdoctest，我觉得我可能举个具体的例子比较好。
PaddleScience目前用的pydoctest其实有很多的执行代码被我加了SKIP，因为这些代码里面的打印函数调用的是logger而不是print（为了整个套件统一，否则非常混乱），所以打印信息的前面会有当前的时间，这就导致pydoctest这种需要把预期信息写在docstring里的不太能很好地工作，所以我想这块xdoctest能否解决呢，比如我打印的信息如下

``` log
[2023.11.11] ppsci INFO: [1,2,3,4]
```

实际上我只想对`ppsci INFO:` 后面真正的输出进行比价偶

2024-01-17 11:45 UTC, merged

2024-01-18 04:27 UTC, megemini commented
> 实际上我只想对ppsci INFO: 后面真正的输出进行比较，xdoctest可以解决这种情况吗，如果可以的话我觉得换xdoctest还是很有必要的

不能 ～ doctest 之类的工具目前都是比对字符串 ～ 所以会产生各类问题，比如你这里只需要一部分输出，而 paddle 那边需要 float 类型的比对 ～～～

目前 doctest 的工具支持的还都不是很好，paddle 那边的做法是 patch，也就是主动介入输出的比对，或者说，可以在字符串比对前先自己做一些处理 ～ 比如，你这里可以做个 patch，自己先把需要比对的字符串 `[2023.11.11] ppsci INFO: [1,2,3,4]` 截取出 `[1,2,3,4]` ，然后再送入 xdoctest ～

不过，你这里用的是 logger 的输出，我没试过这个要怎么捕获 ～～～

不知道我对你那边的应用场景，理解的对不对？