【PPSCI Doc No.107】update doc for `ppsci.visualize.save_vtu_to_mesh`
PaddlePaddle/PaddleScience pull request #763
Opened 2024-01-19 12:21 UTC by ooooo-create

### PR types

Others
### PR changes

Docs
### Describe

No.107
link #686

2024-01-22 10:01 UTC, HydrogenSulfate requested changes
辛苦修改一下

2024-01-22 10:01 UTC, HydrogenSulfate commented on ppsci/visualize/vtu.py
> +        >>> ppsci.visualize.save_vtu_to_mesh(filename, data_dict, coord_keys, value_keys) # doctest: +SKIP
第163行改为:`tuple(data_dict[key] for key in coord_keys)`，否则会有警告`sys:1: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.`

2024-01-23 09:55 UTC, ooooo-create commented on ppsci/visualize/vtu.py
> +        >>> ppsci.visualize.save_vtu_to_mesh(filename, data_dict, coord_keys, value_keys) # doctest: +SKIP
好的～，已添加

2024-01-23 10:58 UTC, HydrogenSulfate approved these changes
LGTM

2024-01-23 10:58 UTC, merged