【PPSCI Doc No.21、22】ppsci.arch.LorenzEmbedding、ppsci.arch.LRosslerEmbedding
PaddlePaddle/PaddleScience pull request #780
Opened 2024-02-07 14:07 UTC by Turingg

**PR types**
Others

**PR changes**
Docs

**Describe**
完善 ppsci.arch.LorenzEmbedding 、ppsci.arch.LRosslerEmbedding的示例 ～
任务链接：https://github.com/PaddlePaddle/PaddleScience/issues/686
对此模型的具体应用还不熟悉QVQ，阔以看看能这样写嘛

@HydrogenSulfate

2024-02-07 15:42 UTC, HydrogenSulfate requested changes
感谢大佬年前还提交PR，辛苦修改一下

2024-02-07 15:42 UTC, HydrogenSulfate commented on ppsci/arch/embedding_koopman.py
> +
一般class的`__init__`方法可以不用写Return字段

2024-02-07 15:42 UTC, HydrogenSulfate commented on ppsci/arch/embedding_koopman.py
> +
此处不需要添加空行

2024-02-07 15:42 UTC, HydrogenSulfate commented on ppsci/arch/embedding_koopman.py
> +        ...     std = None,
等号用于指定参数时两侧不用加空格

2024-02-07 15:42 UTC, HydrogenSulfate commented on ppsci/arch/embedding_koopman.py
> +        >>> from ppsci.arch.embedding_koopman import LorenzEmbedding
`>>> from ppsci.arch.embedding_koopman import LorenzEmbedding`可以删除吧

2024-02-07 15:42 UTC, HydrogenSulfate commented on ppsci/arch/embedding_koopman.py
> +        [8, 3, 3]
问题同上

2024-02-07 15:42 UTC, HydrogenSulfate commented on ppsci/arch/embedding_koopman.py
> +
此处空行删除

2024-02-07 16:25 UTC, Turingg commented on ppsci/arch/embedding_koopman.py
> +
改完噜QVQ

2024-02-20 03:34 UTC, HydrogenSulfate approved these changes
LGTM

2024-02-20 07:36 UTC, merged