【PPSCI Export&Infer No. 29】 add export and inference
PaddlePaddle/PaddleScience pull request #793
Opened 2024-03-02 13:46 UTC by NKNaN

### PR types
Others

### PR changes
Others

### Describe
https://github.com/PaddlePaddle/PaddleScience/issues/788

2024-03-03 14:44 UTC, HydrogenSulfate requested changes
感谢大佬提交代码。@lijialin03 周一辛苦看一下几个模型的推理结果是否符合预期

2024-03-03 14:44 UTC, HydrogenSulfate commented on docs/zh/examples/topopt.md
> +    python topopt.py mode=export INFER.pretrained_model_name=Uniform
是否可以以注释的形式补充另外几个Poisson系列的模型呢？

2024-03-03 14:44 UTC, HydrogenSulfate commented on examples/topopt/conf/topopt.yaml
> +          - EXPORT.pretrained_model_name
EXPORT->INFER

2024-03-03 14:44 UTC, HydrogenSulfate commented on examples/topopt/conf/topopt.yaml
> +  export_path: ./inference/topopt
如果在pretrained_model_path_dict里的模型是互相独立的，可以把export_path改为`./inference/topopt_${INFER.pretrained_model_name}`

2024-03-03 14:44 UTC, HydrogenSulfate commented on examples/topopt/conf/topopt.yaml
> +  save_res_path: ./inference/predicted
此处的save_res_path也可以改为`./inference/predicted_${INFER.pretrained_model_name}`

2024-03-03 14:44 UTC, HydrogenSulfate commented on examples/topopt/topopt.py
> +            cfg.EXPORT.pretrained_model_name
EXPORT->INFER

2024-03-03 14:44 UTC, HydrogenSulfate commented on examples/topopt/topopt.py
> +# model inference
这行注释可以删除

2024-03-03 14:44 UTC, HydrogenSulfate commented on examples/topopt/topopt.py
> +):
1. save_topopt_img函数可以加一下typehint
2. 为了更容易理解和更符合语义，建议这两个参数名改一下：`npy`->`save_npy`，`res_path`->`save_dir`

2024-03-03 14:44 UTC, HydrogenSulfate commented on examples/topopt/topopt.py
> +        print(ground_truth[i])
两处print可以删除，否则会打印大量矩阵元素，如果是为了友好提示可以在for循环的最后一行使用logger.message信息打印保存成功的提示

2024-03-03 14:44 UTC, HydrogenSulfate commented on examples/topopt/topopt.py
> +            with open(osp(res_path, "Prediction_" + str(i) + ".npy"), "wb") as f:
两处字符串拼接改为f-string：`"Prediction_" + str(i) + ".png"`改为`f"Prediction_{i}.png"`

2024-03-03 14:44 UTC, HydrogenSulfate commented on examples/topopt/topopt.py
> +    output = output_dict["output"]
``` suggestion
    output = output_dict["output"]
    import os
    os.makedirs(res_path, exist_ok=True)
```

2024-03-03 14:48 UTC, HydrogenSulfate requested changes

2024-03-03 14:48 UTC, HydrogenSulfate commented on examples/topopt/topopt.py
> +from deploy.python_infer import pinn_predictor
这几行import建议放在对应函数内部，否则会影响整体topopt的代码块行数定位

2024-03-04 02:18 UTC, NKNaN commented on docs/zh/examples/topopt.md
> +    python topopt.py mode=export INFER.pretrained_model_name=Uniform
已修改

2024-03-04 02:18 UTC, NKNaN commented on examples/topopt/conf/topopt.yaml
> +          - EXPORT.pretrained_model_name
已修改

2024-03-04 02:18 UTC, NKNaN commented on examples/topopt/conf/topopt.yaml
> +  export_path: ./inference/topopt
已修改

2024-03-04 02:18 UTC, NKNaN commented on examples/topopt/conf/topopt.yaml
> +  save_res_path: ./inference/predicted
已修改

2024-03-04 02:18 UTC, NKNaN commented on examples/topopt/topopt.py
> +from deploy.python_infer import pinn_predictor
已修改

2024-03-04 02:18 UTC, NKNaN commented on examples/topopt/topopt.py
> +            cfg.EXPORT.pretrained_model_name
已修改

2024-03-04 02:18 UTC, NKNaN commented on examples/topopt/topopt.py
> +# model inference
已删除

2024-03-04 02:18 UTC, NKNaN commented on examples/topopt/topopt.py
> +):
已修改

2024-03-04 02:18 UTC, NKNaN commented on examples/topopt/topopt.py
> +    output = output_dict["output"]
已修改

2024-03-04 02:18 UTC, NKNaN commented on examples/topopt/topopt.py
> +        print(ground_truth[i])
忘记删掉了(✿◡‿◡)，已修改

2024-03-04 02:18 UTC, NKNaN commented on examples/topopt/topopt.py
> +            with open(osp(res_path, "Prediction_" + str(i) + ".npy"), "wb") as f:
已修改

2024-03-04 06:24 UTC, lijialin03 commented
> 感谢大佬提交代码。@lijialin03 周一辛苦看一下几个模型的推理结果是否符合预期

已验证推理结果符合预期

2024-03-04 06:25 UTC, HydrogenSulfate approved these changes
LGTM

2024-03-04 06:25 UTC, merged