[Hackathon 6th Code Camp No.15] support earthformer
PaddlePaddle/PaddleScience pull request #816
Opened 2024-03-21 11:50 UTC by Yang-Changhui

### PR types

### PR changes

### Describe

2024-03-21 11:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleScience?pullRequest=816) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleScience?pullRequest=816) before we can accept your contribution.<br/><hr/>**Yang-Changhui** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleScience?pullRequest=816) it.</sub>

2024-03-21 14:19 UTC, Yang-Changhui commented
这边显示已经同意啦
![image](https://github.com/PaddlePaddle/PaddleScience/assets/71805205/8a967e74-ce12-417b-9761-72db882788f3)

2024-03-25 03:46 UTC, HydrogenSulfate requested changes

2024-03-25 03:47 UTC, HydrogenSulfate commented
代码commit前请安装pre-commit

2024-03-25 11:19 UTC, Yang-Changhui commented on examples/earthformer/enso/train.py
> +        {key: InputSpec([1, 12, 24, 48, 1], "float32", name=key) for key in model.input_keys},
![image](https://github.com/PaddlePaddle/PaddleScience/assets/71805205/ca2ad860-d655-4857-a9a7-58e3db7b26ae)
由于代码中有这个reshape操作，设为None会导致冲突

2024-03-26 13:29 UTC, HydrogenSulfate requested changes

2024-03-26 13:29 UTC, HydrogenSulfate commented on examples/earthformer/sevir/helps.py
> +    return result
这个函数是否跟另一个文件中的一样，如果一样建议只保留一个？

2024-03-26 13:29 UTC, HydrogenSulfate commented on examples/earthformer/sevir/train.py
> +from helps import train_mse_func
同上，建议通过模块调用

2024-03-26 13:29 UTC, HydrogenSulfate commented on ppsci/data/dataset/sevir_dataset.py
> +from paddle.nn.functional import avg_pool2d
同上，建议使用F.avg_pool2d

2024-03-26 13:29 UTC, HydrogenSulfate commented on ppsci/data/dataset/sevir_dataset.py
> +        raise NotImplementedError
建议改为`NotImplementedError(f"{in_layout} is invalid.")`

2024-03-26 13:29 UTC, HydrogenSulfate commented on ppsci/data/dataset/sevir_dataset.py
> +        raise NotImplementedError
同上

2024-03-26 13:29 UTC, HydrogenSulfate commented on ppsci/data/dataset/sevir_dataset.py
> +        raise NotImplementedError
同上

2024-03-26 13:29 UTC, HydrogenSulfate commented on ppsci/data/dataset/sevir_dataset.py
> +        raise NotImplementedError
同上

2024-03-26 13:29 UTC, HydrogenSulfate commented on ppsci/data/dataset/sevir_dataset.py
> +        }
paddle的dataset不需要在getitem里手动转tensor，返回numpy即可

2024-03-26 13:29 UTC, HydrogenSulfate commented on ppsci/utils/registry.py
不建议引入registry机制，会增加代码阅读难度和调试难度，尤其是可能会影响python报错栈的准确性和简洁性

2024-03-26 13:29 UTC, HydrogenSulfate commented on ppsci/utils/__init__.py
不建议引入registry机制，会增加代码阅读难度和调试难度，尤其是可能会影响python报错栈

2024-03-26 13:29 UTC, HydrogenSulfate commented on ppsci/arch/cuboid_transformer.py
> +        return act
建议完善下ppsci/arch/activation.py，尽量复用已有代码

2024-03-26 13:29 UTC, HydrogenSulfate commented on ppsci/arch/cuboid_transformer.py
> +        super(RMSNorm, self).__init__()
改为super().__init__()

2024-03-26 13:29 UTC, HydrogenSulfate commented on ppsci/arch/cuboid_transformer.py
> +            default_initializer=nn.initializer.Assign(init_data),
可以直接使用nn.initializer.Constant(1.0)

2024-03-26 13:29 UTC, HydrogenSulfate commented on ppsci/arch/cuboid_transformer.py
> +            self.add_parameter(name="offset", parameter=self.offset)
可以直接使用nn.initializer.Constant(value)代替Assign初始化，减少代码量

2024-03-27 02:19 UTC, Yang-Changhui commented on examples/earthformer/enso/train.py
> +            key: InputSpec([1, 12, 24, 48, 1], "float32", name=key)
> 第一个维度是否可以改为None？

https://github.com/PaddlePaddle/PaddleScience/pull/816#discussion_r1539151724
因为reshape操作，设置为None会导致维度冲突

2024-03-27 09:14 UTC, Yang-Changhui commented on ppsci/arch/cuboid_transformer.py
> +            self.add_parameter(name="offset", parameter=self.offset)
这个好像不能用nn.initializer.Constant，因为init_data是一个矩阵，不是一个数

2024-03-27 09:55 UTC, Yang-Changhui commented on examples/earthformer/enso/train.py
> +        },
请问，weight_decay这个参数的初始化中是0.01，cfg.TRAIN.wd为1e-5，Optimizer的实例化是按照那个初始化呢

2024-03-27 12:56 UTC, HydrogenSulfate commented on examples/earthformer/enso/train.py
> +        },
> 请问，weight_decay这个参数的初始化中是0.01，cfg.TRAIN.wd为1e-5，Optimizer的实例化是按照那个初始化呢

看了下官网的，可以先这么写吧，问题不大。

2024-03-27 12:56 UTC, HydrogenSulfate commented on examples/earthformer/enso/train.py
> +            key: InputSpec([1, 12, 24, 48, 1], "float32", name=key)
> > 第一个维度是否可以改为None？
> 
> [#816 (comment)](https://github.com/PaddlePaddle/PaddleScience/pull/816#discussion_r1539151724) 因为reshape操作，设置为None会导致维度冲突

哦哦好的，那先写成1好了

2024-03-28 01:54 UTC, Yang-Changhui commented on examples/earthformer/enso/train.py
> +        },
我尝试把这个去掉，重新训练了以下，对结果没什么影响，感觉可以去掉

2024-03-28 02:53 UTC, HydrogenSulfate commented on examples/earthformer/enso/train.py
> +        },
> 我尝试把这个参数去掉，重新训练了一下，对结果没什么影响，感觉可以去掉

确认了下外部的wd是全局指定，并且可以被params参数内指定的wd覆盖，
![image](https://github.com/PaddlePaddle/PaddleScience/assets/23737287/cb774736-ec4b-4dad-8e14-59da7080ac90)

![image](https://github.com/PaddlePaddle/PaddleScience/assets/23737287/24930eb2-bd1c-418e-8491-078556fba640)

而learning_rate是缩放倍率的关系，即最终的lr是全局lr乘以params字典内指定的lr

上述行为跟torch应该是一致的。

2024-03-28 03:08 UTC, HydrogenSulfate requested changes

2024-03-28 03:08 UTC, HydrogenSulfate commented on ppsci/data/dataset/enso_dataset.py
> +    def GetDataShape(self):
类方法使用小写

2024-03-28 03:08 UTC, HydrogenSulfate commented on ppsci/data/dataset/enso_dataset.py
对于入参的合法性检查，建议使用if+raise XXXError判断，assert断言用于内部产生的变量判断是否符合预期，两种方法使用场景是不同的

2024-03-28 03:08 UTC, HydrogenSulfate commented on ppsci/utils/__init__.py
get_parameter_names是一个高度定制化并不是很通用的函数，不建议加到utils里去

2024-03-28 03:08 UTC, HydrogenSulfate commented on ppsci/utils/get_param.py
该函数可以与调用该函数的代码放在一起，但不建议单独建一个文件，不太有必要。

2024-03-28 03:18 UTC, HydrogenSulfate requested changes

2024-03-28 03:18 UTC, HydrogenSulfate commented on examples/earthformer/enso/train.py
> +import enso_metric
本地python模块的import顺序应该是在最下方跟ppsci一起才对，为什么会跑到上面呢？

2024-03-28 03:18 UTC, HydrogenSulfate commented on examples/earthformer/enso/train.py
> +import xarray as xr
对于这类不通用只为某几个案例使用的模块导入行为，可以分两种情况考虑
1. 不会被ppsci模块导入，如train.py，可以使用以下语句代替，能提示用户如何安装该模块
``` py
try:
    import xxx
except ModuleNotFoundError:
    raise ModuleNotFoundError(
        "Please install xxx with `pip install xxx`."
    )
```
2. 对于会被ppsci模块导入的子模块，如enso_dataset.py，作如下修改：

``` py
impot 
try:
    import xxx
except ModuleNotFoundError:
    pass # 这样不影响正常用户使用

Class XXXDataset:
    def __init__(....):
        super().__init__()
        if importlib.util.find_spec("xxx") is None:
            raise ModuleNotFoundError(
                "To use RadarDataset, please install 'xxx' via: `pip install "
                "xxx` first."
            ) # 在实例化该Dataset的时候检查并提示安装命令
```

否则随着代码变多，项目的不必要依赖会越来越多，这显然是不合理的

2024-03-28 03:56 UTC, Yang-Changhui commented
> 建议重新进行一次完整的pre-commit，code-style-check流水线挂了

code-style-check流水线挂了是因为，已有的jointContribution有很多不符合代码规范的，而且好像不能自动修复，得手动改，这部分也需要我改吗

2024-03-28 06:28 UTC, HydrogenSulfate commented
> > 建议重新进行一次完整的pre-commit，code-style-check流水线挂了
> 
> code-style-check流水线挂了是因为，已有的jointContribution有很多不符合代码规范的，而且好像不能自动修复，得手动改，这部分也需要我改吗

这应该是因为你的PR改动了jointContribution文件夹下的代码，原因可能是手动调用了pre-commit把整个PaddleScience都格式化了一遍。如果太麻烦的话可以把jointContribution整个文件夹切回未改动的状态：`git checkout ./jointContribution develop`

2024-03-28 06:28 UTC, HydrogenSulfate commented
> > > 建议重新进行一次完整的pre-commit，code-style-check流水线挂了
> > 
> > 
> > code-style-check流水线挂了是因为，已有的jointContribution有很多不符合代码规范的，而且好像不能自动修复，得手动改，这部分也需要我改吗
> 
> 这应该是因为你的PR改动了jointContribution文件夹下的代码，所以被pre-commit当做修改文件捕获，可能是手动调用了pre-commit把整个PaddleScience都格式化了一遍。如果太麻烦的话可以把jointContribution整个文件夹切回未改动的状态：`git checkout ./jointContribution develop`

2024-03-29 07:20 UTC, zhiminzhang0830 commented on ppsci/data/dataset/sevir_dataset.py
> +    def _old_save_downsampled_dataset(self, save_dir, downsample_dict, verbose=True):
没有使用到的函数可以删除

2024-03-29 07:20 UTC, zhiminzhang0830 commented on ppsci/data/dataset/sevir_dataset.py
> +    def save_downsampled_dataset(self, save_dir, downsample_dict, verbose=True):
确认是否有使用，没有使用可以删除此函数

2024-03-30 07:52 UTC, Yang-Changhui commented on jointContribution/XPINNs/XPINN_2D_PoissonsEqn.py
这个文件我没有修改啊。不知道为什么会被检测出来

2024-04-01 03:47 UTC, zhiminzhang0830 commented on ppsci/arch/cuboid_transformer.py
> +        target_shape : Shape of the input tensor. It will be (T_out, H, W, C_out)
Shape of the target tensor

2024-04-01 03:47 UTC, zhiminzhang0830 commented on ppsci/arch/cuboid_transformer_decoder.py
> +        maxW
完善数据类型和变量含义

2024-04-01 03:47 UTC, zhiminzhang0830 commented on ppsci/arch/cuboid_transformer_decoder.py
> +    """
完善docstring，按照ppsci的风格进行args部分的注释 ”变量名称(类型): 变量含义、默认值的描述“，例如：
```
    Args:
        input_keys (Tuple[str, ...]): Name of input keys, such as ("input",).
        output_keys (Tuple[str, ...]): Name of output keys, such as ("output",).
        img_size (Tuple[int, ...], optional): Image size. Defaults to (720, 1440).
        patch_size (Tuple[int, ...], optional): Path. Defaults to (8, 8).
        in_channels (int, optional): The input tensor channels. Defaults to 20.
        out_channels (int, optional): The output tensor channels. Defaults to 20.
        embed_dim (int, optional): The embedding dimension for PatchEmbed. Defaults to 768.
        depth (int, optional): Number of transformer depth. Defaults to 12.
        mlp_ratio (float, optional): Number of ratio used in MLP. Defaults to 4.0.
        drop_rate (float, optional): The drop ratio used in MLP. Defaults to 0.0.
        drop_path_rate (float, optional): The drop ratio used in DropPath. Defaults to 0.0.
        num_blocks (int, optional): Number of blocks. Defaults to 8.
        sparsity_threshold (float, optional): The value of threshold for softshrink. Defaults to 0.01.
        hard_thresholding_fraction (float, optional): The value of threshold for keep mode. Defaults to 1.0.
        num_timestamps (int, optional): Number of timestamp. Defaults to 1.

    """
```

2024-04-01 03:47 UTC, zhiminzhang0830 commented on ppsci/data/dataset/enso_dataset.py
> +    """_summary_
更新summary

2024-04-02 12:49 UTC, zhiminzhang0830 commented on ppsci/arch/cuboid_transformer_decoder.py
> +        attn_drop (float, optional): The attention dropout.. Defaults to 0.0.
删除dropout后多余的标点符号

2024-04-02 12:49 UTC, zhiminzhang0830 commented on ppsci/arch/cuboid_transformer_decoder.py
> +        proj_drop (float, optional): The projrction dropout.. Defaults to 0.0.
删除dropout后多余的标点符号

2024-04-02 12:49 UTC, zhiminzhang0830 commented on ppsci/arch/cuboid_transformer_decoder.py
> +        separate_global_qkv (bool, optional): Whether to use different network to calc q_global, k_global, v_global. . Defaults to False.
删除v_global后多余的标点符号

2024-04-06 10:13 UTC, zhiminzhang0830 commented on ppsci/arch/cuboid_transformer_decoder.py
> +        """
删除此部分

2024-04-06 10:13 UTC, zhiminzhang0830 commented on ppsci/arch/cuboid_transformer_utils.py
> +        self.scale.stop_gradient = not True
not True 改为 False，其他类似代码也替换下

2024-04-06 10:13 UTC, zhiminzhang0830 commented on ppsci/data/dataset/__init__.py
> -from ppsci.data.dataset.dgmr_dataset import DGMRDataset
不要删除此行代码

2024-04-24 06:40 UTC, Yang-Changhui commented
@HydrogenSulfate 你好，我现在有一个简单的前向，initencoder，相同的网络，相同输入，相同权重，使用reprod_log检查，误差为0.00067，这是最小测试单元，
paddle_torch_forward_error：https://aistudio.baidu.com/projectdetail/7781433?sUid=650866&shared=1&ts=1713940796780 ，麻烦您帮忙检查一下，谢谢

2024-05-13 07:46 UTC, closed without merging