【PPSCI Doc No.66-74】
PaddlePaddle/PaddleScience pull request #829
Opened 2024-04-01 14:13 UTC by 1want2sleep

### PR types
Others

### PR changes
Docs

### Describe
补充了以下API的文档，包括功能介绍、输入参数描述、返回值描述、代码示例
ppsci.geometry.TimeDomain.on_initial
ppsci.geometry.TimeXGeometry.uniform_points
ppsci.geometry.TimeXGeometry.random_points
ppsci.geometry.TimeXGeometry.uniform_boundary_points
ppsci.geometry.TimeXGeometry.random_boundary_points
ppsci.geometry.TimeXGeometry.uniform_initial_points
ppsci.geometry.TimeXGeometry.random_initial_points
ppsci.geometry.TimeXGeometry.periodic_point
ppsci.geometry.TimeXGeometry.sample_initial_interior

2024-04-02 04:40 UTC, HydrogenSulfate requested changes
多处类似的问题可以一起修改

2024-04-02 04:40 UTC, HydrogenSulfate commented on ppsci/geometry/timedomain.py
> +        """Check if a specific time is on the initial time point
句子结尾加上英文句号"."

2024-04-02 04:40 UTC, HydrogenSulfate commented on ppsci/geometry/timedomain.py
> +            t (float): The time to be checked.
这里的t应该是一个np.ndarray

2024-04-02 04:40 UTC, HydrogenSulfate commented on ppsci/geometry/timedomain.py
> +            >>> paddle.set_default_dtype("float64")
paddle没必要设置dtype，因为几何模块用的是numpy后端

2024-04-02 04:40 UTC, HydrogenSulfate commented on ppsci/geometry/timedomain.py
> +            >>> print(check1, check2)
构造长度为5的np.ndarray，并且包含t0和非t0的元素用于检查，这样比测两次更简洁

2024-04-02 04:40 UTC, HydrogenSulfate commented on ppsci/geometry/timedomain.py
>      def on_initial(self, t):
加上type hint： `t: np.ndarray`

2024-04-02 04:40 UTC, HydrogenSulfate commented on ppsci/geometry/timedomain.py
> +            Ndarray: a set of spatial-temporal coordinate points 'tx' that represent sample points evenly distributed within the spatial-temporal domain.
使用`np.ndarray`代替`Ndarray`

2024-04-02 04:40 UTC, HydrogenSulfate commented on ppsci/geometry/timedomain.py
> +        Note: Before using this method, you need to specify time_step or timestamps.(See Examples)
可以在__init__内加上对time_step和timestamps的检查，然后这句话可以删除

2024-04-02 04:40 UTC, HydrogenSulfate commented on ppsci/geometry/timedomain.py
> +            >>> time_geom.timedomain.time_step = 0.001
time_step建议在TimeDomain构造时传入设置

2024-04-02 04:40 UTC, HydrogenSulfate commented on ppsci/geometry/timedomain.py
> +
打印一下ts的形状

2024-04-02 11:11 UTC, 1want2sleep commented
> 多处类似的问题可以一起修改

Done.

2024-04-02 11:11 UTC, 1want2sleep commented on ppsci/geometry/timedomain.py
> +        """Check if a specific time is on the initial time point
Done.

2024-04-03 14:21 UTC, HydrogenSulfate requested changes
感谢提交PR，有几处再略微修改一下即可

2024-04-03 14:21 UTC, HydrogenSulfate commented on ppsci/geometry/timedomain.py
> +            raise ValueError("Either time_step or timestamps must be provided.")
这里好像可以删除这个检查，因为两者可以都不设置，下方第三个分支就是处理这种情况的

2024-04-03 14:21 UTC, HydrogenSulfate commented on ppsci/geometry/timedomain.py
> +    def periodic_point(self, x: dict[str, np.ndarray], component: int):
dict类型的typehint统一使用 typing模块下的Dict

2024-04-03 14:21 UTC, HydrogenSulfate commented on ppsci/geometry/timedomain.py
> +            dict[str, np.ndarray] : contains the original timestamps and the coordinates of the spatial point after periodic processing.
同上，应该是大写的D

2024-04-03 14:21 UTC, HydrogenSulfate commented on ppsci/geometry/timedomain.py
> +
多余空行可以删除

2024-04-03 14:21 UTC, HydrogenSulfate commented on ppsci/geometry/timedomain.py
> +        criteria: callable = None,
callable同理使用typing下的`Callable`

2024-04-03 14:21 UTC, HydrogenSulfate commented on ppsci/geometry/timedomain.py
> +
同上，删除空行

2024-04-03 14:21 UTC, HydrogenSulfate commented on ppsci/geometry/timedomain.py
> +        self, n: int, random: str = "pseudo", criteria: callable = None
1. 使用typing下的`Callable`
2. 默认值为None的参数需要用`Optional`嵌套在原类型上：`Optional[Callble]`

2024-04-03 14:21 UTC, HydrogenSulfate commented on ppsci/geometry/timedomain.py
> +            criteria (method): Used to filter the generated boundary points, only points that meet certain conditions are retained. Default is None.
docstring内的类型也对应修改一下

2024-04-03 15:57 UTC, 1want2sleep commented on ppsci/geometry/timedomain.py
> +            raise ValueError("Either time_step or timestamps must be provided.")
All done.

2024-04-04 09:54 UTC, merged