【PPSCI Export&Infer No.23】viv
PaddlePaddle/PaddleScience pull request #832
Opened 2024-04-06 03:45 UTC by smallpoxscattered

### PR types

Others
### PR changes

Others
### Describe

- [【快乐开源】为 PaddleScience 案例添加 export 和 inference 功能](https://github.com/PaddlePaddle/PaddleScience/issues/788#top) #788 
  因为需要将equation导出  就在 ComposedNode 加入了paddle.nn.LayerList，不然导出找不到 callable_nodes

2024-04-06 09:16 UTC, HydrogenSulfate requested changes
感谢提交PR，辛苦修改一下

2024-04-06 09:16 UTC, HydrogenSulfate commented on examples/fsi/viv.py
> +    cfg.INFER.pdpiparams_path = cfg.INFER.pdpiparams_equ_path
equ->eqn

2024-04-06 09:16 UTC, HydrogenSulfate commented on ppsci/utils/symbolic.py
> +        self.callable_nodes = paddle.nn.LayerList(callable_nodes)
paddle.nn --> nn

2024-04-06 09:16 UTC, HydrogenSulfate commented on examples/fsi/viv.py
> +    jit.enable_to_static(False)
可以将func和model的计算写在一个函数中，函数接受输入t_f，输出f和eta，然后对这个函数进行动转静，这样只需要导出一份推理模型，inference也只需要用一个predictor

2024-04-06 12:19 UTC, smallpoxscattered commented on examples/fsi/viv.py
> +    jit.enable_to_static(False)
好的好的 改好了，但是写成一个函数好像有点难，我本来想用装饰器重写forward，但推理的时候报错有点多，我就写成一个类了，老师有什么建议吗

2024-04-06 12:51 UTC, HydrogenSulfate commented on examples/fsi/viv.py
> +    jit.enable_to_static(False)
> 好的好的 改好了，但是写成一个函数好像有点难，我本来想用装饰器重写forward，但推理的时候报错有点多，我就写成一个类了，老师有什么建议吗

类似于这种：
``` py
class A(nn.Layer):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        return nn.functional.relu(x)



class B(nn.Layer):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        return nn.functional.sigmoid(x)


ma = A()
mb = B()


def func(x):
    ya = ma(x["x"])
    yb = mb(x["x"])
    return {
        "ya": ya,
        "yb": yb,
    }
```

2024-04-06 12:57 UTC, smallpoxscattered commented on examples/fsi/viv.py
> +    jit.enable_to_static(False)
老师 他导出的时候会找不到参数  因为只是函数
    func(layer, path, input_spec, **configs)
  File "/usr/local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.9/site-packages/paddle/base/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/paddle/base/dygraph/base.py", line 66, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/paddle/jit/api.py", line 1106, in save
    state_var_dict[param_or_buffer.name]
UnboundLocalError: local variable 'state_var_dict' referenced before assignment

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

2024-04-07 01:35 UTC, smallpoxscattered commented on ppsci/utils/symbolic.py
> +        self.callable_nodes = paddle.nn.LayerList(callable_nodes)
老师  我已经都改好了   那个也改成函数形式了 您看看

2024-04-07 01:37 UTC, smallpoxscattered commented on examples/fsi/viv.py
> +    jit.enable_to_static(False)
老师 我已经都改好了 那个也改成函数形式了 您看看

2024-04-07 08:38 UTC, HydrogenSulfate requested changes

2024-04-07 08:38 UTC, HydrogenSulfate commented on examples/fsi/viv.py
> +    jit.enable_to_static(False)
我尝试优化了下你的代码，可以按照如下修改：

``` suggestion
def export(cfg: DictConfig):
    from paddle import nn
    from paddle.static import InputSpec

    # set model
    model = ppsci.arch.MLP(**cfg.MODEL)

    # initialize equation
    equation = {"VIV": ppsci.equation.Vibration(2, -4, 0)}

    # initialize solver
    solver = ppsci.solver.Solver(
        model,
        equation=equation,
        pretrained_model_path=cfg.INFER.pretrained_model_path,
    )

    # Convert equation to func
    f_func = ppsci.lambdify(
        solver.equation["VIV"].equations["f"],
        solver.model,
        list(solver.equation["VIV"].learnable_parameters),
    )

    class Wrapped_Model(nn.Layer):
        def __init__(self, model, func):
            super().__init__()
            self.model = model
            self.func = func

        def forward(self, x):
            model_out = self.model(x)
            func_out = self.func(x)
            return {**model_out, "f": func_out}

    solver.model = Wrapped_Model(model, f_func)

    # export models
    input_spec = [
        {key: InputSpec([None, 1], "float32", name=key) for key in model.input_keys},
    ]
    solver.export(input_spec, cfg.INFER.export_path, skip_prune_program=True)
```

2024-04-07 08:38 UTC, HydrogenSulfate commented on examples/fsi/conf/viv.yaml
> +  pretrained_model_path: "./viv_pretrained"
这里可以改为：`https://paddle-org.bj.bcebos.com/paddlescience/models/viv/viv_pretrained.pdparams`，我在 https://github.com/PaddlePaddle/PaddleScience/pull/834/files#diff-68effb6a6b046bfbf5b6cb8b843f284e8779eadfa5977b66870a783d6d61ebe7R105-R118 支持了自动下载方程参数文件的功能

2024-04-07 08:38 UTC, HydrogenSulfate commented on examples/fsi/conf/viv.yaml
> +  output_keys: ["eta", 'f']
"f"双引号

2024-04-07 08:38 UTC, HydrogenSulfate commented on docs/zh/examples/viv.md
> +    wget -nc https://paddle-org.bj.bcebos.com/paddlescience/models/viv/viv_pretrained.pdparams
这两行在pretrained_model_path改完之后就可以删除了

2024-04-07 10:45 UTC, smallpoxscattered commented on docs/zh/examples/viv.md
> +    wget -nc https://paddle-org.bj.bcebos.com/paddlescience/models/viv/viv_pretrained.pdparams
好的好的  改好了  辛苦老师了

2024-04-07 11:26 UTC, merged