PPSCI Doc No.41-57
PaddlePaddle/PaddleScience pull request #833
Opened 2024-04-06 10:42 UTC by wufei2

### PR types

Others
### PR changes

Others
### Describe

对以下文档进行了补全:
ppsci.geometry.Geometry.__and__
ppsci.geometry.Geometry.__or__
ppsci.geometry.Geometry.__sub__
ppsci.geometry.Geometry.__str__
ppsci.geometry.Geometry.difference
ppsci.geometry.Geometry.intersection
ppsci.geometry.Geometry.is_inside
ppsci.geometry.Geometry.on_boundary
ppsci.geometry.Geometry.periodic_point
ppsci.geometry.Geometry.random_boundary_points
ppsci.geometry.Geometry.random_points
ppsci.geometry.Geometry.sample_boundary
ppsci.geometry.Geometry.sample_interior
ppsci.geometry.Geometry.sdf_derivatives
ppsci.geometry.Geometry.uniform_boundary_points
ppsci.geometry.Geometry.uniform_points
ppsci.geometry.Geometry.union

2024-04-06 12:38 UTC, HydrogenSulfate requested changes
感谢提交PR，修改得很仔细👍。有几处小问题可以按照建议辛苦修改一下。

2024-04-06 12:38 UTC, HydrogenSulfate commented on ppsci/geometry/geometry.py
1. 函数的参数可以加上和typehint，与docstring保持一（当类型注解为类自身时，建议加上双引号，比如
`geom: "Geometry"`）
3. docstring的 Returns 类型外面好像不需要套上小括号？

2024-04-06 12:38 UTC, HydrogenSulfate commented on ppsci/geometry/geometry.py
> +            (np.ndarray): Boolean array where x is inside the geometry. The shape is [N, 1].
实测输出形状应该是`[N]`，下面类似的可以一起改一下

2024-04-06 12:38 UTC, HydrogenSulfate commented on ppsci/geometry/geometry.py
> +            >>> cuboid.sample_interior(2,"pseudo", None, True, True)
参数之间的逗号后面加上空格

2024-04-06 14:53 UTC, wufei2 commented on ppsci/geometry/geometry.py
> +            >>> cuboid.sample_interior(2,"pseudo", None, True, True)
All done

2024-04-07 03:16 UTC, HydrogenSulfate requested changes
有几处可能漏了的地方，还辛苦修改一下

2024-04-07 03:16 UTC, HydrogenSulfate commented on ppsci/geometry/geometry.py
>          criteria=None,
criteria的类型注解是`Optional[Callable]`

2024-04-07 03:16 UTC, HydrogenSulfate commented on ppsci/geometry/geometry.py
默认值为None的类型注解需要在原类型外面加上Optional，比如Optional[bool]

2024-04-07 03:16 UTC, HydrogenSulfate commented on ppsci/geometry/geometry.py
> +        self, n: int, random: str = "pseudo", criteria=None, evenly=False
比如，这里可以改为：`criteria: Optional[Callable]`和`evenly: bool = False`

2024-04-07 03:40 UTC, HydrogenSulfate requested changes

2024-04-07 03:40 UTC, HydrogenSulfate commented on ppsci/geometry/geometry.py
文件开头加一下：
from typing import Callable
from typing import Dict

2024-04-07 03:40 UTC, HydrogenSulfate commented on ppsci/geometry/geometry.py
> +                        their derivatives of SDF(optional). The shape is [N].
1. 返回值是Dict[str, np.ndarray]，而不是np.ndarray
1. their signed distance function. The shape is [N, 1].
2. their derivatives of SDF(optional). The shape is [N, D].

2024-04-07 03:40 UTC, HydrogenSulfate commented on ppsci/geometry/geometry.py
> +                        their area. The shape is [N].(only if the geometry is a mesh)
同上

2024-04-07 03:40 UTC, HydrogenSulfate commented on ppsci/geometry/geometry.py
> +    ) -> np.ndarray:
同上

2024-04-07 03:40 UTC, HydrogenSulfate commented on ppsci/geometry/geometry.py
> +    ) -> np.ndarray:
返回值类型改为Dict[str, np.ndarray]

2024-04-07 03:40 UTC, HydrogenSulfate commented on ppsci/geometry/geometry.py
> +        """
补充一下返回值类型

2024-04-07 08:05 UTC, HydrogenSulfate approved these changes
LGTM

2024-04-07 08:05 UTC, merged

2024-04-08 10:16 UTC, luotao1 commented
hi, @wufei2 
- 非常感谢你对飞桨的贡献，我们正在运营一个PFCC组织，会通过定期分享技术知识与发布开发者主导任务的形式持续为飞桨做贡献，详情可见 https://github.com/luotao1 主页说明。
- 如果你对PFCC有兴趣，请发送邮件至 [ext_paddle_oss@baidu.com](mailto:ext_paddle_oss@baidu.com)，我们会邀请你加入~