【PPSCI Doc No.23、25-29、31-34、97】
PaddlePaddle/PaddleScience pull request #840
Opened 2024-04-09 17:28 UTC by 1want2sleep

### PR types

Others

### PR changes

Docs

### Describe

补全 https://github.com/PaddlePaddle/PaddleScience/issues/686 中的23、25-29、31-34、97 api的文档
其中，第32 ppsci.autodiff.Jacobians.__call__ 没看出来有问题。
97 代码示例单独测试没问题 doctest有问题

2024-04-11 12:54 UTC, HydrogenSulfate requested changes
感谢提交PR，分布式的测试可以加上跳过代码

2024-04-11 12:54 UTC, HydrogenSulfate commented on ppsci/utils/misc.py
> +        >>> dist.init_parallel_env()
末尾加上：`  # doctest: +SKIP`

2024-04-11 12:54 UTC, HydrogenSulfate commented on ppsci/utils/misc.py
> +        >>> if dist.get_rank() == 0:
末尾加上`  # doctest: +SKIP`

2024-04-11 12:54 UTC, HydrogenSulfate commented on ppsci/utils/misc.py
> +        >>> result = ppsci.utils.misc.all_gather(data)
末尾加上`  # doctest: +SKIP`

2024-04-11 12:54 UTC, HydrogenSulfate commented on ppsci/utils/misc.py
> +        >>> print(result.numpy())
末尾加上`  # doctest: +SKIP`

2024-04-12 02:54 UTC, 1want2sleep commented on ppsci/arch/afno.py
> +        >>> model = ppsci.arch.AFNONet(("input", ), ("output", ), img_size=(180, 360))
Done.

2024-04-12 02:54 UTC, 1want2sleep commented on ppsci/utils/misc.py
> +        >>> dist.init_parallel_env()
All Done.

2024-04-12 04:28 UTC, HydrogenSulfate approved these changes
LGTM

2024-04-12 04:28 UTC, merged