【Hackathon 6th No.39】XPINN 迁移至 PaddleScience
PaddlePaddle/PaddleScience pull request #849
Opened 2024-04-15 08:44 UTC by MayYouBeProsperous

### PR types

Others
### PR changes

Others
### Describe

- RFC：https://github.com/PaddlePaddle/community/pull/835

原案例精度：0.04685
复现精度：0.04177
![image](https://github.com/PaddlePaddle/PaddleScience/assets/99723454/4be407cd-0bbe-49e8-a88d-0ca675c89183)

2024-04-15 11:40 UTC, HydrogenSulfate commented on examples/xpinn/xpinn.py
> +        paddle.squeeze(u_exact) - u_pred.flatten(), 2
squeeze改为flatten，两边语义一致

2024-04-15 11:40 UTC, HydrogenSulfate commented on examples/xpinn/xpinn.py
> +    ) / paddle.linalg.norm(paddle.squeeze(u_exact), 2)
squeeze改为flatten，两边语义一致

2024-04-15 11:41 UTC, HydrogenSulfate commented on examples/xpinn/xpinn.py
> +            in_[key] = paddle.cast(in_[key], paddle.float64)
数据从读入的时候就可以转换好

2024-04-15 11:42 UTC, HydrogenSulfate commented on examples/xpinn/xpinn.py
> +        return in_, _label, _weight
下划线在前面和后面的区别是？可以保持一致吗？

2024-04-15 11:42 UTC, HydrogenSulfate commented on examples/xpinn/xpinn.py
> +            ),
分解后的input_keys可以由基本的input_keys+XPINN生成，不建议使用hard code

2024-04-15 11:43 UTC, HydrogenSulfate commented on examples/xpinn/xpinn.py
> +            "label_keys": ("ub", "u_exact", "u_exact2", "u_exact3"),
u_exact==>u_exact1?

2024-04-15 11:44 UTC, HydrogenSulfate commented on examples/xpinn/xpinn.py
> +                yb=input_["yb"],
不建议使用x_f1、xb、yi1这类命名方式，看不太出来每个字段的含义

2024-04-15 11:44 UTC, HydrogenSulfate commented on examples/xpinn/xpinn.py
> +            ),
不建议使用x_f1、xb、yi1这类命名方式，看不太出来每个字段的含义

2024-04-15 11:45 UTC, HydrogenSulfate commented on examples/xpinn/xpinn.py
> +        return in_, _label, _weight
同上，下划线前后保持一致

2024-04-29 09:28 UTC, MayYouBeProsperous commented on examples/xpinn/xpinn.py
已上传

2024-04-29 09:28 UTC, MayYouBeProsperous commented on examples/xpinn/xpinn.py
> +# For the use of the second derivative: paddle.cos, paddle.exp
好的，已修改

2024-04-29 09:28 UTC, MayYouBeProsperous commented on examples/xpinn/xpinn.py
> +    return loss1, loss2, loss3
重新实现了XPINN的loss函数

2024-04-29 09:28 UTC, MayYouBeProsperous commented on examples/xpinn/xpinn.py
> +    return loss1 + loss2 + loss3
Done.

2024-04-29 09:28 UTC, MayYouBeProsperous commented on examples/xpinn/xpinn.py
> +        paddle.squeeze(u_exact) - u_pred.flatten(), 2
Done.

2024-04-29 09:28 UTC, MayYouBeProsperous commented on examples/xpinn/xpinn.py
> +    ) / paddle.linalg.norm(paddle.squeeze(u_exact), 2)
Done.

2024-04-29 09:28 UTC, MayYouBeProsperous commented on examples/xpinn/xpinn.py
> +
Done.

2024-04-29 09:28 UTC, MayYouBeProsperous commented on examples/xpinn/xpinn.py
> +            in_[key] = paddle.cast(in_[key], paddle.float64)
修改了 ppsci.utils.reader，这样可以吗

2024-04-29 09:28 UTC, MayYouBeProsperous commented on examples/xpinn/xpinn.py
> +        return in_, _label, _weight
疏忽了，已修改~

2024-04-29 09:28 UTC, MayYouBeProsperous commented on examples/xpinn/xpinn.py
> +            ),
input_keys 放在了配置文件中

2024-04-29 09:28 UTC, MayYouBeProsperous commented on examples/xpinn/xpinn.py
> +        return in_, _label, _weight
Done.

2024-04-29 09:28 UTC, MayYouBeProsperous commented on examples/xpinn/xpinn.py
> +            ),
好的，修改了命名

2024-04-29 09:28 UTC, MayYouBeProsperous commented on examples/xpinn/xpinn.py
> +                yb=input_["yb"],
好的，修改了命名

2024-04-29 09:28 UTC, MayYouBeProsperous commented on examples/xpinn/xpinn.py
> +            "label_keys": ("ub", "u_exact", "u_exact2", "u_exact3"),
数据集中的名字是 u_exact

2024-05-11 05:52 UTC, HydrogenSulfate requested changes

2024-05-11 05:52 UTC, HydrogenSulfate commented on ppsci/utils/reader.py
> +            and data_dict[key].dtype != np.float64
这里这么改会导致float64类型的数据不能被转换为float32，模型训练时数据与权重参数类型不匹配而报错。

2024-05-14 07:25 UTC, MayYouBeProsperous commented on ppsci/utils/reader.py
> +            and data_dict[key].dtype != np.float64
以前误以为有些算子只支持float64，已经修改。文档还在编写中。

2024-05-14 11:15 UTC, HydrogenSulfate requested changes

2024-05-14 11:15 UTC, HydrogenSulfate commented on examples/xpinn/xpinn.py
> +
这个函数看起来只被单独调用，建议放到get_second_derivatives上方，并且函数名前加上单个下划线

2024-05-14 11:15 UTC, HydrogenSulfate commented on examples/xpinn/xpinn.py
> +    def get_second_derivatives(
函数前面加上单下划线

2024-05-14 11:15 UTC, HydrogenSulfate commented on examples/xpinn/xpinn.py
> +def xpinn_loss(
函数前面加上单下划线

2024-05-14 11:15 UTC, HydrogenSulfate commented on examples/xpinn/xpinn.py
> +    # the shape of label_dict["residual_u_exact"] is [22387, 1], and be cut into [18211, 1] `_eval_by_dataset`(ppsci/solver/eval.py).
这个注释是什么意思呢？是输入的样本点数不等于输出的样本点数，导致在`_eval_by_dataset`被丢掉？

2024-05-14 11:15 UTC, HydrogenSulfate commented on examples/xpinn/xpinn.py
> +    return {"total": error_u_total}
total==>l2_error

2024-05-14 11:16 UTC, HydrogenSulfate commented on examples/xpinn/conf/xpinn.yaml
> +  eval_with_no_grad: false
```suggestion
hydra:
  run:
    # dynamic output directory according to running time and override name
    dir: outputs_xpinn/${now:%Y-%m-%d}/${now:%H-%M-%S}/${hydra.job.override_dirname}
  job:
    name: ${mode} # name of logfile
    chdir: false # keep current working direcotry unchaned
    config:
      override_dirname:
        exclude_keys:
          - TRAIN.checkpoint_path
          - TRAIN.pretrained_model_path
          - EVAL.pretrained_model_path
          - mode
          - output_dir
          - log_freq
  callbacks:
    init_callback:
      _target_: ppsci.utils.callbacks.InitCallback
  sweep:
    # output directory for multirun
    dir: ${hydra.run.dir}
    subdir: ./

# general settings
mode: train # running mode: train/eval
seed: 134
output_dir: ${hydra:run.dir}
log_freq: 20

# model settings
MODEL:
  num_boundary_points: 200 # Boundary points from subdomain 1
  num_residual1_points: 5000 # Residual points in three subdomain 1
  num_residual2_points: 1800 # Residual points in three subdomain 2
  num_residual3_points: 1200 # Residual points in three subdomain 3
  num_interface1: 100 # Interface points along the two interfaces
  num_interface2: 100
  layers1: [2, 30, 30, 1]
  layers2: [2, 20, 20, 20, 20, 1]
  layers3: [2, 25, 25, 25, 1]

# set training data file
TRAIN_DATA_FILE: "./data/XPINN_2D_PoissonEqn.mat"

# training settings
TRAIN:
  input_keys:
    [
      "residual1_x",
      "residual1_y",
      "residual2_x",
      "residual2_y",
      "residual3_x",
      "residual3_y",
      "interface1_x",
      "interface1_y",
      "interface2_x",
      "interface2_y",
      "boundary_x",
      "boundary_y",
    ]
  label_keys: ["boundary_u_exact"]
  alias_dict:
    {
      "residual1_x": "x_f1",
      "residual1_y": "y_f1",
      "residual2_x": "x_f2",
      "residual2_y": "y_f2",
      "residual3_x": "x_f3",
      "residual3_y": "y_f3",
      "interface1_x": "xi1",
      "interface1_y": "yi1",
      "interface2_x": "xi2",
      "interface2_y": "yi2",
      "boundary_x": "xb",
      "boundary_y": "yb",
      "boundary_u_exact": "ub",
      "residual_u_exact": "u_exact",
      "residual2_u_exact": "u_exact2",
      "residual3_u_exact": "u_exact3",
    }
  epochs: 501
  iters_per_epoch: 1
  save_freq: 50
  eval_during_train: true
  eval_freq: 50
  learning_rate: 0.0008
  batch_size: 4
  pretrained_model_path: null
  checkpoint_path: null

# evaluation settings
EVAL:
  label_keys:
    [
      "boundary_u_exact",
      "residual_u_exact",
      "residual2_u_exact",
      "residual3_u_exact",
    ]
  alias_dict:
    {
      "residual1_x": "x_f1",
      "residual1_y": "y_f1",
      "residual2_x": "x_f2",
      "residual2_y": "y_f2",
      "residual3_x": "x_f3",
      "residual3_y": "y_f3",
      "interface1_x": "xi1",
      "interface1_y": "yi1",
      "interface2_x": "xi2",
      "interface2_y": "yi2",
      "boundary_x": "xb",
      "boundary_y": "yb",
      "boundary_u_exact": "ub",
      "residual_u_exact": "u_exact",
      "residual2_u_exact": "u_exact2",
      "residual3_u_exact": "u_exact3",
    }
  batch_size: 1
  pretrained_model_path: null
  eval_with_no_grad: false

```

2024-05-14 11:17 UTC, HydrogenSulfate commented on examples/xpinn/plotting.py
> +            r"\usepackage[utf8x]{inputenc}",  # use utf8 fonts because your computer can handle it :)
```suggestion
            r"\usepackage[utf8x]{inputenc}",  # use utf8 fonts because your computer can handle it.
```

2024-05-27 14:46 UTC, MayYouBeProsperous commented on examples/xpinn/xpinn.py
> +def xpinn_loss(
Done.

2024-05-27 14:46 UTC, MayYouBeProsperous commented on examples/xpinn/xpinn.py
> +
Done.

2024-05-27 14:46 UTC, MayYouBeProsperous commented on examples/xpinn/xpinn.py
> +    def get_second_derivatives(
Done.

2024-05-27 14:46 UTC, MayYouBeProsperous commented on examples/xpinn/xpinn.py
> +    return {"total": error_u_total}
Done.

2024-05-27 14:46 UTC, MayYouBeProsperous commented on examples/xpinn/xpinn.py
> +    # the shape of label_dict["residual_u_exact"] is [22387, 1], and be cut into [18211, 1] `_eval_by_dataset`(ppsci/solver/eval.py).
是的，输入的样本点数小于标签点数，数据集提供的label_dict["residual_u_exact"] 本来包含了label_dict["residual2_u_exact"] 和 label_dict["residual3_u_exact"]。

2024-05-27 14:47 UTC, MayYouBeProsperous commented
麻烦制作一个数据集下载链接：https://github.com/PaddlePaddle/PaddleScience/blob/develop/jointContribution/XPINNs/data/XPINN_2D_PoissonEqn.mat

2024-05-28 02:44 UTC, HydrogenSulfate commented
> 麻烦制作一个数据集下载链接：https://github.com/PaddlePaddle/PaddleScience/blob/develop/jointContribution/XPINNs/data/XPINN_2D_PoissonEqn.mat

<https://paddle-org.bj.bcebos.com/paddlescience/datasets/XPINN/XPINN_2D_PoissonEqn.mat>

2024-05-29 11:26 UTC, HydrogenSulfate reviewed
训练后的精度好像跟原版的精度对不太上，可以检查一下可能哪个commit的改动导致的
![image](https://github.com/PaddlePaddle/PaddleScience/assets/23737287/65a15828-a9e4-4b92-8dce-7e159dd8078b)
![image](https://github.com/PaddlePaddle/PaddleScience/assets/23737287/2fd2a122-e7cf-4819-9854-c3538d009bc2)

2024-05-29 11:26 UTC, HydrogenSulfate commented on examples/xpinn/xpinn.py
> +            "file_path": cfg.TRAIN_DATA_FILE,
`cfg.TRAIN_DATA_FILE`好像没有出现在cfg里面，是不是跟`cfg.DATA_FILE`是一样的呢？

2024-05-29 11:31 UTC, HydrogenSulfate reviewed
cfg.TRAIN_DATA_FILE好像没有出现在cfg里面，应该是cfg.DATA_FILE？

2024-05-29 18:05 UTC, MayYouBeProsperous commented on examples/xpinn/xpinn.py
> +            "file_path": cfg.TRAIN_DATA_FILE,
是的，已修改

2024-05-30 02:27 UTC, HydrogenSulfate approved these changes
LGTM

2024-05-30 02:28 UTC, merged