【PPSCI Export&Infer No.25】bracket
PaddlePaddle/PaddleScience pull request #878
Opened 2024-05-06 08:04 UTC by 1want2sleep

### PR types
Others

### PR changes
Others
### Describe
https://github.com/PaddlePaddle/PaddleScience/issues/788

2024-05-06 08:58 UTC, HydrogenSulfate requested changes

2024-05-06 08:58 UTC, HydrogenSulfate commented on ppsci/autodiff/ad.py
>      """
这里的冲突处理一下

2024-05-07 12:35 UTC, 1want2sleep commented on ppsci/autodiff/ad.py
>      """
Done.

2024-05-07 13:18 UTC, HydrogenSulfate requested changes

2024-05-07 13:18 UTC, HydrogenSulfate commented on examples/bracket/bracket.py
> +
这两个函数辛苦移动到evaluate下方吧，按照一般流程的顺序排列

2024-05-07 14:55 UTC, 1want2sleep commented on examples/bracket/bracket.py
> +
Done.不辛苦(●ˇ∀ˇ●)

2024-05-08 05:24 UTC, HydrogenSulfate approved these changes
LGTM

2024-05-08 05:34 UTC, merged