【PPSCI Export&Infer No.35】nowcastnet
PaddlePaddle/PaddleScience pull request #895
Opened 2024-05-13 06:06 UTC by smallpoxscattered

### PR types

Others 
### PR changes

Others 
### Describe

导出有bug，还没修复

2024-05-14 03:44 UTC, HydrogenSulfate reviewed
提交代码前请按照说明安装pre-commit格式化代码，https://paddlescience-docs.readthedocs.io/zh/latest/zh/development/#4

2024-05-14 08:37 UTC, HydrogenSulfate commented on examples/nowcastnet/nowcastnet.py
> +        "data_type": np.float32(),
```suggestion
```

2024-05-14 08:37 UTC, HydrogenSulfate commented on examples/nowcastnet/nowcastnet.py
> +        shuffle=False,
```suggestion
```

2024-05-20 02:34 UTC, HydrogenSulfate requested changes
拉一下最新的develop分支跟这个PR的分支合并一下。

2024-05-20 04:39 UTC, smallpoxscattered commented
> 拉一下最新的develop分支跟这个PR的分支合并一下。

2024-05-20 04:40 UTC, smallpoxscattered commented
> 拉一下最新的develop分支跟这个PR的分支合并一下。

好的好的

2024-05-20 12:02 UTC, HydrogenSulfate requested changes

2024-05-20 12:02 UTC, HydrogenSulfate commented on docs/zh/cooperation.md
文件与本PR无关，不需要更改

2024-05-20 12:02 UTC, HydrogenSulfate commented on mkdocs.yml
文件与本PR无关，不需要更改

2024-05-20 12:02 UTC, HydrogenSulfate commented on ppsci/data/dataset/dgmr_dataset.py
文件与本PR无关，不需要更改

2024-05-20 12:02 UTC, HydrogenSulfate commented on ppsci/data/dataset/enso_dataset.py
文件与本PR无关，不需要更改

2024-05-20 12:03 UTC, smallpoxscattered commented on ppsci/data/dataset/enso_dataset.py
啊，这是我改的，我还以为是老师改的

2024-05-20 12:05 UTC, HydrogenSulfate commented on ppsci/data/dataset/enso_dataset.py
> 啊，这是我改的，我还以为是老师改的

这个PR我只帮忙改了dtype，其他文档没有改动

2024-05-20 12:08 UTC, smallpoxscattered commented on ppsci/data/dataset/enso_dataset.py
我也不知道咋回事，我再弄弄，抱歉了，老师

2024-05-20 12:37 UTC, zhiminzhang0830 commented on examples/nowcastnet/conf/nowcastnet.yaml
> +  pdpiparams_path: ${INFER.export_path}.pdiparams
字段名称麻烦修改下
```suggestion
  pdiparams_path: ${INFER.export_path}.pdiparams
```

2024-05-20 12:37 UTC, zhiminzhang0830 commented on examples/nowcastnet/conf/nowcastnet.yaml
添加 log_freq 字段，否则infer报错

2024-05-20 12:37 UTC, HydrogenSulfate approved these changes
LGTM

2024-05-20 12:42 UTC, smallpoxscattered commented on examples/nowcastnet/conf/nowcastnet.yaml
好的好的

2024-05-21 01:43 UTC, zhiminzhang0830 approved these changes
LGTM

2024-05-21 01:43 UTC, merged