[WIP]【Hackathon 6th No.37】GraphCastNet 代码迁移至 PaddleScience
PaddlePaddle/PaddleScience pull request #897
Opened 2024-05-14 09:13 UTC by MayYouBeProsperous

### PR types

Others

### PR changes

APIs, Docs

### Describe

尚未完成，请不用 review

2024-06-06 13:12 UTC, MayYouBeProsperous commented
麻烦制作数据集下载链接：https://aistudio.baidu.com/datasetdetail/252766

2024-06-07 04:29 UTC, lijialin03 commented
> 麻烦制作数据集下载链接：https://aistudio.baidu.com/datasetdetail/252766

数据集下载链接分别为：
[dataset.zip](https://paddle-org.bj.bcebos.com/paddlescience/datasets/graphcast/dataset.zip)
[dataset.zip](https://paddle-org.bj.bcebos.com/paddlescience/datasets/graphcast/dataset.zip)
[dataset.zip](https://paddle-org.bj.bcebos.com/paddlescience/datasets/graphcast/dataset.zip)
[dataset.zip](https://paddle-org.bj.bcebos.com/paddlescience/datasets/graphcast/dataset.zip)

2024-06-13 04:12 UTC, lijialin03 commented
我看标题中的WIP去掉了，代码现在是可以review的状态嘛

2024-06-13 08:56 UTC, MayYouBeProsperous commented
是的，可以 review 了。
CI 报错好像是注释的括号匹配问题，应该怎么解决呢
![image](https://github.com/PaddlePaddle/PaddleScience/assets/99723454/b65af636-ae35-4989-bdf2-b60a8e4a25e4)
![image](https://github.com/PaddlePaddle/PaddleScience/assets/99723454/fbb4a2bc-51a6-409f-9ce3-f5320e689de6)

2024-06-13 12:03 UTC, lijialin03 commented
> 是的，可以 review 了。 CI 报错好像是注释的括号匹配问题，应该怎么解决呢 ![image](https://private-user-images.githubusercontent.com/99723454/339292316-b65af636-ae35-4989-bdf2-b60a8e4a25e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNzE0MzQsIm5iZiI6MTcxODI3MTEzNCwicGF0aCI6Ii85OTcyMzQ1NC8zMzkyOTIzMTYtYjY1YWY2MzYtYWUzNS00OTg5LWJkZjItYjYwYThlNGEyNWU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDA5MzIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzMWFlYjcwMzI4MTlhNmI0YmI1YWYxN2RhZGQzZmYxNzRlNmEzMGVhYTYwMTcyZmVlZjI4Mjg5MTRhMzM0OWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WdHDrU1LzndzqDB4jKIXzvrBum4IP0p67ikLsQHKmIM) ![image](https://private-user-images.githubusercontent.com/99723454/339292421-fbb4a2bc-51a6-409f-9ce3-f5320e689de6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNzE0MzQsIm5iZiI6MTcxODI3MTEzNCwicGF0aCI6Ii85OTcyMzQ1NC8zMzkyOTI0MjEtZmJiNGEyYmMtNTFhNi00MDlmLTljZTMtZjUzMjBlNjg5ZGU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDA5MzIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1MGQzZjA0MmZiNTRmZDgxZjhhODFjYjM1NGFiODFhNDkyYjQ5NWMxYTU5Nzc2OGIzNjRlMDcyNDdkZjQyNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.82oAIh0wgF5UhodcNZM3jLEizvqm8idGon57XvGkqA4)

好嘞，这个先不管吧，等review完再说

2024-06-25 14:17 UTC, lijialin03 approved these changes
调用jointContribution/graphcast/run中的compare
输入运行结果后得到对齐结果为：
```
10m_u_component_of_wind diff is -2.356016193110792e-05
10m_v_component_of_wind diff is 7.523250922509292e-06
2m_temperature diff is 2.4777781459127155e-05
geopotential diff is -0.000539646573504715
mean_sea_level_pressure diff is -0.0005250472340893714
specific_humidity diff is 6.035347363899133e-10
temperature diff is 8.158555083697042e-07
total_precipitation_6hr diff is 1.8224237754237203e-09
u_component_of_wind diff is 1.7749217200032017e-06
v_component_of_wind diff is 7.323719328271271e-06
vertical_velocity diff is -2.375314757111974e-07
All diff is -8.92277301779838e-05
```
参考[https://github.com/PaddlePaddle/PaddleScience/pull/699](https://github.com/PaddlePaddle/PaddleScience/pull/699)，认为可以对齐

2024-06-26 03:34 UTC, HydrogenSulfate requested changes
辛苦提交PR，代码内容修改完毕之后，可以同步更新一下文档的代码块定位位置

2024-06-26 03:34 UTC, HydrogenSulfate commented on examples/graphcast/graphcast.py
> +        eval_with_no_grad=cfg.EVAL.eval_with_no_grad,
```suggestion
        model,
        validator=validator,
        cfg=cfg,
```

2024-06-26 03:34 UTC, HydrogenSulfate commented on ppsci/arch/graphcast.py
> +        """
class的docstring放到class名称下方，不放到__init__下面

2024-06-26 03:34 UTC, HydrogenSulfate commented on ppsci/data/dataset/atmospheric_dataset.py
> +        """
同上，移动到class名称的下方，不放在__init__里

2024-06-26 03:34 UTC, HydrogenSulfate commented on ppsci/data/dataset/atmospheric_dataset.py
> +    preserved_dims: typing.Tuple[str, ...] = ("batch", "lat", "lon"),
typing.XXX建议改为XXX

2024-06-26 03:34 UTC, HydrogenSulfate commented on ppsci/data/dataset/atmospheric_dataset.py
> +def merge_meshes(mesh_list: typing.Sequence[TriangularMesh]) -> TriangularMesh:
同上

2024-06-26 03:34 UTC, HydrogenSulfate commented on ppsci/data/dataset/atmospheric_dataset.py
> +) -> typing.List[TriangularMesh]:
同上

2024-06-26 03:34 UTC, HydrogenSulfate commented on ppsci/data/dataset/atmospheric_dataset.py
> +class _ChildVerticesBuilder(object):
python3不需要显式继承object
```suggestion
class _ChildVerticesBuilder:
```

2024-06-26 03:34 UTC, HydrogenSulfate commented on ppsci/data/dataset/spherical_swe_dataset.py
这类位置不需要加换行，其余文件同理，不需要添加换行

2024-06-26 06:30 UTC, MayYouBeProsperous commented on docs/zh/examples/graphcast.md
> +
Done.

2024-06-26 06:30 UTC, MayYouBeProsperous commented on docs/zh/examples/graphcast.md
> +    python graphcast.py
Done.

2024-06-26 06:30 UTC, MayYouBeProsperous commented on examples/graphcast/conf/graphcast_small.yaml
> +hydra:
Done.

2024-06-26 06:30 UTC, MayYouBeProsperous commented on examples/graphcast/conf/graphcast_small.yaml
> +          - log_freq
Done.

2024-06-26 06:30 UTC, MayYouBeProsperous commented on examples/graphcast/conf/graphcast_small.yaml
> +  pretrained_model_path: "data/params/GraphCast_small---ERA5-1979-2015---resolution-1.0---pressure-levels-13---mesh-2to5---precipitation-input-and-output.pdparams"
Done.

2024-06-26 06:30 UTC, MayYouBeProsperous commented on examples/graphcast/graphcast.py
> +        "num_workers": 1,
Done.

2024-06-26 06:30 UTC, MayYouBeProsperous commented on examples/graphcast/graphcast.py
> +        eval_with_no_grad=cfg.EVAL.eval_with_no_grad,
Done.

2024-06-26 06:30 UTC, MayYouBeProsperous commented on ppsci/data/__init__.py
> +        )
区别是要设置 collate_fn = batch_transform.default_collate_fn

2024-06-26 06:30 UTC, MayYouBeProsperous commented on ppsci/data/dataset/spherical_swe_dataset.py
这里是删除多余换行的

2024-06-26 06:30 UTC, MayYouBeProsperous commented on ppsci/arch/graphcast.py
> +        dst_type="mesh",
Done.

2024-06-26 06:30 UTC, MayYouBeProsperous commented on ppsci/arch/graphcast.py
> +class GraphCastGrid2Mesh(paddle.nn.Layer):
Done.

2024-06-26 06:30 UTC, MayYouBeProsperous commented on ppsci/arch/graphcast.py
> +class GraphCastMesh2Grid(paddle.nn.Layer):
Done.

2024-06-26 06:30 UTC, MayYouBeProsperous commented on ppsci/arch/graphcast.py
> +        """
Done.

2024-06-26 06:30 UTC, MayYouBeProsperous commented on ppsci/data/dataset/atmospheric_dataset.py
> +    preserved_dims: typing.Tuple[str, ...] = ("batch", "lat", "lon"),
好的，已修改

2024-06-26 06:30 UTC, MayYouBeProsperous commented on ppsci/data/dataset/atmospheric_dataset.py
> +        """
Done.

2024-06-26 06:30 UTC, MayYouBeProsperous commented on ppsci/data/dataset/atmospheric_dataset.py
> +def merge_meshes(mesh_list: typing.Sequence[TriangularMesh]) -> TriangularMesh:
Done.

2024-06-26 06:30 UTC, MayYouBeProsperous commented on ppsci/data/dataset/atmospheric_dataset.py
> +) -> typing.List[TriangularMesh]:
Done.

2024-06-26 06:30 UTC, MayYouBeProsperous commented on ppsci/data/dataset/atmospheric_dataset.py
> +class _ChildVerticesBuilder(object):
Done.

2024-06-26 08:44 UTC, HydrogenSulfate reviewed
LGTM

2024-06-26 11:28 UTC, HydrogenSulfate approved these changes
LGTM

2024-06-26 11:29 UTC, merged