add montecarlo integrate api
PaddlePaddle/PaddleScience pull request #932
Opened 2024-06-20 09:03 UTC by cxxly

### PR types

New fatures
### PR changes

APIs
### Describe

Add montecarlo integration.

2024-06-20 09:17 UTC, HydrogenSulfate requested changes

2024-06-20 09:17 UTC, HydrogenSulfate commented on ppsci/experimental/math_module.py
> +    fn: callable,
```suggestion
    fn: Callable,
```

2024-06-20 09:17 UTC, HydrogenSulfate commented on ppsci/experimental/math_module.py
> +        fn (func): The function to integrate over.
```suggestion
        fn (Callable): The function to integrate over.
```

2024-06-20 09:17 UTC, HydrogenSulfate commented on ppsci/experimental/math_module.py
> +        integration_domain (list or backend tensor, optional): Integration
```suggestion
        integration_domain (Optional[List[List[float]], paddle.Tensor]): Integration
```

2024-06-20 09:17 UTC, HydrogenSulfate commented on ppsci/experimental/math_module.py
> +        >>> paddle.seed(1024)
```suggestion
        >>> _ = paddle.seed(1024)
```

2024-06-20 09:17 UTC, HydrogenSulfate commented on ppsci/experimental/math_module.py
> +            integration_domain (backend tensor): Integration domain
函数注释里所有backend tensor改为paddle.Tensor

2024-06-20 09:17 UTC, HydrogenSulfate commented on ppsci/experimental/math_module.py
> +        N: int, integration_domain: paddle.Tensor, seed: int = None
```suggestion
        N: int, integration_domain: paddle.Tensor, seed: Optional[int] = None
```

2024-06-20 09:17 UTC, HydrogenSulfate commented on ppsci/experimental/math_module.py
> +        """Calculate random points for the integrand evaluation
句子结尾加上句号.

2024-06-20 09:17 UTC, HydrogenSulfate commented on ppsci/experimental/math_module.py
> +            integration_domain (backend tensor): Integration domain
句子结尾加上句号.

2024-06-20 09:17 UTC, HydrogenSulfate commented on ppsci/experimental/math_module.py
> +    Returns:
```suggestion

    Returns:
```

2024-06-20 09:17 UTC, HydrogenSulfate commented on ppsci/experimental/math_module.py
> +def evaluate_integrand(fn, points, weights=None, args=None):
该函数为非公开的辅助函数，前面加上单个下划线
```suggestion
def _evaluate_integrand(fn, points, weights=None, args=None):
```

2024-06-21 08:40 UTC, cxxly commented on ppsci/experimental/math_module.py
> +    fn: callable,
DONE

2024-06-21 08:40 UTC, cxxly commented on ppsci/experimental/math_module.py
> +        fn (func): The function to integrate over.
DONE

2024-06-21 08:41 UTC, cxxly commented on ppsci/experimental/math_module.py
> +        integration_domain (list or backend tensor, optional): Integration
DONE

2024-06-21 08:42 UTC, cxxly commented on ppsci/experimental/math_module.py
> +            integration_domain (backend tensor): Integration domain
DONE

2024-06-21 08:43 UTC, cxxly commented on ppsci/experimental/math_module.py
> +        N: int, integration_domain: paddle.Tensor, seed: int = None
DONE

2024-06-21 08:44 UTC, cxxly commented on ppsci/experimental/math_module.py
> +            integration_domain (backend tensor): Integration domain
DONE

2024-06-21 08:44 UTC, cxxly commented on ppsci/experimental/math_module.py
> +        """Calculate random points for the integrand evaluation
DONE

2024-06-21 08:45 UTC, cxxly commented on ppsci/experimental/math_module.py
> +def evaluate_integrand(fn, points, weights=None, args=None):
DONE

2024-06-24 06:17 UTC, HydrogenSulfate commented on ppsci/experimental/math_module.py
> +    integration_domain: Optional[List[List[float]], paddle.Tensor] = None,
```suggestion
    integration_domain: Union[List[List[float]], paddle.Tensor] = None,
```

2024-06-24 06:17 UTC, HydrogenSulfate commented on ppsci/experimental/math_module.py
> +        integration_domain (Optional[List[List[float]], paddle.Tensor]): Integration
```suggestion
        integration_domain (Union[List[List[float]], paddle.Tensor]): Integration
```

2024-06-24 06:17 UTC, HydrogenSulfate commented on ppsci/experimental/math_module.py
> +    dim: int, integration_domain: Optional[List[List[float]], paddle.Tensor]
```suggestion
    dim: int, integration_domain: Union[List[List[float]], paddle.Tensor]
```

2024-06-24 06:17 UTC, HydrogenSulfate commented on ppsci/experimental/math_module.py
> +        Tensor(shape=[], dtype=float32, place=Place(gpu:0), stop_gradient=True, 3.25152588)
```suggestion
        >>> import paddle
        >>> import ppsci

        >>> _ = paddle.seed(1024)
        >>> # The function we want to integrate, in this example
        >>> # f(x0,x1) = sin(x0) + e^x1 for x0=[0,1] and x1=[-1,1]
        >>> # Note that the function needs to support multiple evaluations at once (first
        >>> # dimension of x here)
        >>> # Expected result here is ~3.2698
        >>> def some_function(x):
        ...     return paddle.sin(x[:, 0]) + paddle.exp(x[:, 1])

        >>> # Compute the function integral by sampling 10000 points over domain
        >>> integral_value = ppsci.experimental.montecarlo_integrate(
        ...     some_function,
        ...     dim=2,
        ...     N=10000,
        ...     integration_domain=[[0, 1], [-1, 1]],
        ... )

        >>> print(integral_value)
        Tensor(shape=[], dtype=float32, place=Place(gpu:0), stop_gradient=True,
               3.25152588)
```

2024-06-25 02:29 UTC, HydrogenSulfate approved these changes
LGTM

2024-06-25 02:30 UTC, merged