DrugDiscovery
PaddlePaddle/PaddleScience pull request #960
Opened 2024-08-06 10:35 UTC by niushao12

### PR types

### PR changes

### Describe

2024-08-06 10:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleScience?pullRequest=960) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleScience?pullRequest=960) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleScience?pullRequest=960) it.</sub>

2024-08-06 10:54 UTC, HydrogenSulfate commented
@niushao12 好像跟最新的代码冲突了，可以跟最新的develop合并一下解决冲突
![image](https://github.com/user-attachments/assets/ef1a7d91-8328-4066-99b4-20fdba56b08b)

2024-08-06 11:51 UTC, HydrogenSulfate requested changes

2024-08-06 11:51 UTC, HydrogenSulfate commented on docs/zh/examples/moflow.md
案例文档可以加到mkdocs.yml里， 这样首页能展示出来https://github.com/PaddlePaddle/PaddleScience/blob/develop/mkdocs.yml#L40-L95

2024-08-06 11:51 UTC, HydrogenSulfate commented on docs/zh/examples/moflow.md
> +$$
双引号所表示的代码块请在其上方和下方各保留一个换行，否则其内的公式无法被识别渲染，其余几处公式块也请进行相同处理。
![image](https://github.com/user-attachments/assets/7b7f2157-1f1f-4b95-bb0f-731983c442df)

2024-08-06 11:51 UTC, HydrogenSulfate commented on docs/zh/examples/moflow.md
> +将$\Mu$分子图视为由原子作节点，键作边组成的无向图，其数学符号可记为$\mathcal{M} =  \mathcal{A} \times  \mathcal{B} \subset \mathbb{R}^{n \times k} \times \mathbb{R}^{c \times n \times n}$，其中，集合有$n$个原子，$k$种原子类型，$A(i,k)=1$代表节点$i$是$k
好像\Mu渲染不出来，可以先用\text{M}代替，看起来一样
```suggestion
将$\text{M}$分子图视为由原子作节点，键作边组成的无向图，其数学符号可记为$\mathcal{M} =  \mathcal{A} \times  \mathcal{B} \subset \mathbb{R}^{n \times k} \times \mathbb{R}^{c \times n \times n}$，其中，集合有$n$个原子，$k$种原子类型，$A(i,k)=1$代表节点$i$是$k$型原子，集合代表键（边）,键有$c$种类型，$B(c,i,j)=1$代表原子$i$和$j$之间以$c$类型的键连接,一个分子$\mathcal{M}$可以被看作是一个具有多类型节点和多类型边的无向图。主要的目标是学习一个分子生成模型$P_{\mathcal{M}}(M)$，即从$P_{\mathcal{M}}$中采样任意分子$\text{M}$的概率。为了捕捉分子图的组合原子和键结构，将$P_{\mathcal{M}}(M)$分解为两部分：
```

2024-08-06 11:51 UTC, HydrogenSulfate commented on examples/moflow/conf/moflow_optimize.yaml
> +          - log_freq
```suggestion
defaults:
  - ppsci_default
  - TRAIN: train_default
  - TRAIN/ema: ema_default
  - TRAIN/swa: swa_default
  - EVAL: eval_default
  - INFER: infer_default
  - hydra/job/config/override_dirname/exclude_keys: exclude_keys_default
  - _self_

hydra:
  run:
    # dynamic output directory according to running time and override name
    dir: outputs_moflow_optimize/${data_name}
  job:
    name: ${mode} # name of logfile
    chdir: false # keep current working directory unchanged
```

2024-08-06 11:51 UTC, HydrogenSulfate commented on examples/moflow/conf/moflow_optimize.yaml
> +  pretrained_model_path: outputs_moflow_train/${data_name}/checkpoints/latest
这个默认值建议设置为null，与其他案例保持一致，然后可以在文档开头的命令中再指定路径

2024-08-06 11:51 UTC, HydrogenSulfate commented on examples/moflow/conf/moflow_test.yaml
> +          - log_freq
```suggestion
defaults:
  - ppsci_default
  - TRAIN: train_default
  - TRAIN/ema: ema_default
  - TRAIN/swa: swa_default
  - EVAL: eval_default
  - INFER: infer_default
  - hydra/job/config/override_dirname/exclude_keys: exclude_keys_default
  - _self_

hydra:
  run:
    # dynamic output directory according to running time and override name
    dir: outputs_moflow_test/${data_name}
  job:
    name: ${mode} # name of logfile
    chdir: false # keep current working directory unchanged
```

2024-08-06 11:51 UTC, HydrogenSulfate commented on examples/moflow/conf/moflow_test.yaml
> +  pretrained_model_path: outputs_moflow_train/${data_name}/checkpoints/latest
同上，默认可以设置为null，然后在运行命令中指定

2024-08-06 11:51 UTC, HydrogenSulfate commented on examples/moflow/conf/moflow_train.yaml
> +          - log_freq
```suggestion
defaults:
  - ppsci_default
  - TRAIN: train_default
  - TRAIN/ema: ema_default
  - TRAIN/swa: swa_default
  - EVAL: eval_default
  - INFER: infer_default
  - hydra/job/config/override_dirname/exclude_keys: exclude_keys_default
  - _self_

hydra:
  run:
    # dynamic output directory according to running time and override name
    dir: outputs_moflow_train/${data_name}
  job:
    name: ${mode} # name of logfile
    chdir: false # keep current working directory unchanged
```

2024-08-06 11:51 UTC, HydrogenSulfate commented on docs/zh/examples/moflow.md
> +```
这个文档末尾是否可以加上参考文献这一章节，并加上测试结果的可视化效果图（如果有的话）

2024-08-06 11:51 UTC, HydrogenSulfate commented on examples/moflow/optimize_moflow.py
这个文件里面的代码麻烦加一些换行和注释

2024-08-06 11:51 UTC, HydrogenSulfate commented on examples/moflow/optimize_moflow.py
> +    out_1.stop_gradient = not True
not True --> False

2024-08-06 11:51 UTC, HydrogenSulfate commented on examples/moflow/optimize_moflow.py
> +
这个可以删除，在进入main函数时会自动由callback触发

2024-08-06 11:51 UTC, HydrogenSulfate commented on examples/moflow/conf/moflow_optimize.yaml
> +  mask_row_stride_list: 1,
yaml里面的列表可以写成[1, 2, 3, 4]，跟python类似，仅在末尾加上逗号是不正确的yaml语法

2024-08-06 11:51 UTC, HydrogenSulfate commented on examples/moflow/conf/moflow_optimize.yaml
> +  mask_row_stride_list: 1,
问题同上

2024-08-06 11:51 UTC, HydrogenSulfate commented on examples/moflow/conf/moflow_test.yaml
yaml文件里列表语法问题麻烦都修复一下

2024-08-06 11:51 UTC, HydrogenSulfate commented on examples/moflow/conf/moflow_test.yaml
> +  mask_row_stride_list: 1,
同样的问题

2024-08-06 11:51 UTC, HydrogenSulfate commented on examples/moflow/optimize_moflow.py
> +
yaml问题修复之后应该不需要这段字符串处理代码了

2024-08-06 11:51 UTC, HydrogenSulfate commented on examples/moflow/test_generate.py
> +    atomic_num_list = list(cfg.get(cfg.data_name).atomic_num_list)
yaml问题修复之后应该不需要这段字符串处理代码了

2024-08-06 11:51 UTC, HydrogenSulfate commented on examples/moflow/test_generate.py
> +    logger.init_logger("ppsci", osp.join(cfg.output_dir, f"{cfg.mode}.log"), "info")
同理，可删除

2024-08-06 11:51 UTC, HydrogenSulfate commented on examples/moflow/train_moflow.py
> +    """
按照规范的docstirng格式完善

2024-08-06 11:51 UTC, HydrogenSulfate commented on examples/moflow/train_moflow.py
> +
同理，可删除

2024-08-06 11:51 UTC, HydrogenSulfate commented on examples/moflow/train_moflow.py
> +
可在yaml问题修复后删除

2024-08-06 11:51 UTC, HydrogenSulfate commented on ppsci/arch/__init__.py
> +from ppsci.arch import moflow_transform  # isort:skip
这个可以删除，Arch只提供模型结构，moflow_transform.py可以移动到`examples/moflow/`下面

2024-08-06 11:51 UTC, HydrogenSulfate commented on ppsci/arch/__init__.py
> +    "moflow_transform",
同理，删除moflow_transform

2024-08-06 11:51 UTC, HydrogenSulfate commented on ppsci/arch/fpscores.pkl.gz
这个文件是什么作用呢？

2024-08-06 11:51 UTC, HydrogenSulfate commented on ppsci/arch/moflow_basic.py
变量命名与转换前的代码保持一致，out_4, out_5诸如此类不是一个有意义的名字

2024-08-06 11:51 UTC, HydrogenSulfate commented on ppsci/arch/moflow_basic.py
> +        """
按照其它已有代码的docstring规范补全，并移动到GraphConv下方

2024-08-06 11:51 UTC, HydrogenSulfate commented on ppsci/arch/moflow_basic.py
> +        """
按照其它已有代码的docstring规范补全

2024-08-06 11:51 UTC, HydrogenSulfate commented on ppsci/arch/moflow_net.py
> +    """
按照其它已有代码的docstring规范补全

2024-08-06 11:51 UTC, HydrogenSulfate commented on ppsci/arch/moflow_net.py
同理，变量命名请与转换签的保持一致

2024-08-06 11:51 UTC, HydrogenSulfate commented on ppsci/data/dataset/moflow_dataset.py
> +        """
1. Returns上方加一个换行
2. 补全docstring内容

2024-08-06 12:10 UTC, HydrogenSulfate commented on docs/zh/examples/moflow.md
> +| [qm9](https://pan.baidu.com/s/198rcBkFiTcwUqMBXZpRqhQ) <br> 提取码：lyp3|  loss(Residual): <br> 0.00300 |
已上传，麻烦修改成url<https://paddle-org.bj.bcebos.com/paddlescience/models/MoFlow/qm9/qed_pretrained.pdparams>

2024-08-06 12:10 UTC, HydrogenSulfate commented on docs/zh/examples/moflow.md
> +| [zinc250k](https://pan.baidu.com/s/1tjJX3CeWorlumSEkUDfRaw) <br>  提取码：36d4| loss(Residual): <br> 0.00500 |
`zinc250k/latest.pdparams`是什么模型，可以提供一个更合适的名字吗？

2024-08-07 01:34 UTC, niushao12 commented on docs/zh/examples/moflow.md
> +| [zinc250k](https://pan.baidu.com/s/1tjJX3CeWorlumSEkUDfRaw) <br>  提取码：36d4| loss(Residual): <br> 0.00500 |
zinc250k和qm9是不同的数据集训练的模型，可以叫zinc250k_pretrained

2024-08-07 01:52 UTC, niushao12 commented on docs/zh/examples/moflow.md
> +<a href="https://aistudio.baidu.com/aistudio/projectdetail/6184070?contributionType=1&sUid=438690&shared=1&ts=1684239806160" class="md-button md-button--primary" style>AI Studio快速体验</a>
好的

2024-08-07 03:15 UTC, HydrogenSulfate commented on docs/zh/examples/moflow.md
> +| [zinc250k](https://pan.baidu.com/s/1tjJX3CeWorlumSEkUDfRaw) <br>  提取码：36d4| loss(Residual): <br> 0.00500 |
已上传：<https://paddle-org.bj.bcebos.com/paddlescience/models/MoFlow/zinc250k/zinc250k_pretrained.pdparams>

然后还有一个问题，为什么zinc250k文件夹下除了latest.pdparams，还有一个qed模型文件？这个文件与qm9下面的qed模型文件是什么关系？参数是否完全一致？

2024-08-07 06:21 UTC, closed without merging