Update mkdocs.yml
PaddlePaddle/PaddleScience pull request #962
Opened 2024-08-07 07:00 UTC by niushao12

### PR types

### PR changes

### Describe

2024-08-07 07:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleScience?pullRequest=962) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleScience?pullRequest=962) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleScience?pullRequest=962) it.</sub>

2024-08-08 03:37 UTC, HydrogenSulfate requested changes
辛苦再修改一下

2024-08-08 03:37 UTC, HydrogenSulfate commented on docs/zh/examples/moflow.md
> +```
类似的代码块的定位全部都有问题，麻烦重新修改一下

2024-08-08 03:37 UTC, HydrogenSulfate commented on ppsci/arch/moflow_basic.py
> +        )
这类参数的创建方式建议改成：
```suggestion
        self.loc = self.create_parameter(
            [1, in_channel, 1, 1],
            default_initializer=nn.initializer.ConstantInitializer(value=0.0)
        )
```

2024-08-08 03:37 UTC, HydrogenSulfate commented on ppsci/arch/moflow_basic.py
> +        self.loc.stop_gradient = False
这个应该可以不用设置了，parameter的语义是可学习变量，因此其stop_gradient默认就是False

2024-08-08 03:37 UTC, HydrogenSulfate commented on ppsci/arch/moflow_basic.py
> +        self.scale.stop_gradient = False
同样的问题建议都修改一下，PaConvert对parameter转写不够简洁

2024-08-08 03:37 UTC, HydrogenSulfate commented on ppsci/arch/moflow_glow.py
> +        out_17.stop_gradient = not True
这类转写后自动编号而产生的变量名请改成和转写前的保持一致

2024-08-08 03:37 UTC, HydrogenSulfate commented on ppsci/arch/moflow_net.py
> +        hyper_params :More parameters derived from hyper_params for easy use
公开的接口docstring请和typehint保持一致，句子末尾加上句号.

2024-08-08 03:37 UTC, HydrogenSulfate commented on ppsci/arch/moflow_utils.py
> +}
字典的键的括号可以删掉吧？

2024-08-08 03:37 UTC, HydrogenSulfate commented on ppsci/arch/moflow_utils.py
> +        """
docstring的风格请和已有代码保持一致，可以使用vscode的autodocstring插件自动生成docstring

2024-08-08 03:37 UTC, HydrogenSulfate commented on ppsci/arch/moflow_utils.py
> +    """
同上

2024-08-08 03:37 UTC, HydrogenSulfate commented on ppsci/data/dataset/__init__.py
这个文件的修改为什么要把GridMeshAtmosphericDataset和ExtMoEENSODataset删掉？

2024-08-08 03:37 UTC, HydrogenSulfate commented on ppsci/data/dataset/__init__.py
> +        cfg (List[DictConfig]): dataset config list.
这里的修改有必要吗？

2024-08-08 03:38 UTC, HydrogenSulfate commented
另外本PR的标题麻烦修改成合适的内容，
![image](https://github.com/user-attachments/assets/9393f890-55bc-4afa-96d4-37372e13f43f)

2024-08-08 04:25 UTC, niushao12 commented on ppsci/data/dataset/__init__.py
这个应该不是我修改，我Sync fork最新的代码，更新之后修改的，您这边方便给我最新的文件么？

2024-08-08 04:25 UTC, niushao12 commented on ppsci/data/dataset/__init__.py
> +        cfg (List[DictConfig]): dataset config list.
这个文件除了增加我这边数据集类，其他没有动

2024-08-08 04:59 UTC, HydrogenSulfate commented on ppsci/data/dataset/__init__.py
> 这个应该不是我修改，我Sync fork最新的代码，更新之后修改的，您这边方便给我最新的文件么？

最新的文件是：<https://github.com/PaddlePaddle/PaddleScience/blob/develop/ppsci/data/dataset/__init__.py>

2024-08-08 04:59 UTC, HydrogenSulfate commented on ppsci/data/dataset/__init__.py
> +        cfg (List[DictConfig]): dataset config list.
> 这个文件除了增加我这边数据集类，其他没有动

红框里的是本PR的修改内容，可能是误操作引起的，可以还原回去

2024-08-08 08:27 UTC, HydrogenSulfate requested changes

2024-08-08 08:27 UTC, HydrogenSulfate commented on examples/moflow/conf/moflow_optimize.yaml
> +  hidden: '16' # Hidden dimension list for output regression
使用数字16即可

2024-08-08 08:27 UTC, HydrogenSulfate commented on examples/moflow/optimize_moflow.py
> +    logger.info("Hidden dim for output regression:{}".format(hidden))
hidden改为int后，此处代码对应修改

2024-08-08 08:50 UTC, lxw123123 commented
python -c "import ppsci; ppsci.utils.run_check()" 检查 会提示rdkit未安装 简易修改一下

2024-08-08 08:55 UTC, niushao12 commented
> python -c "import ppsci; ppsci.utils.run_check()" 检查 会提示rdkit未安装 简易修改一下

这个需要修改moflow_dataset的，得重新写一下这个文件了，里面有针对化学分子单独处理

2024-08-08 08:58 UTC, HydrogenSulfate commented
> > python -c "import ppsci; ppsci.utils.run_check()" 检查 会提示rdkit未安装 简易修改一下
> 
> 这个需要修改moflow_dataset的，得重新写一下这个文件了，里面有针对化学分子单独处理

涉及到特殊依赖包的内容，请将导入语句放到try里面(参考airfoil_dataset.py处理），这样不影响其他代码运行，也能在实际使用时报错，
![image](https://github.com/user-attachments/assets/3f82e355-b47f-4254-ad4d-4c2a80c675a2)

2024-08-08 09:03 UTC, HydrogenSulfate commented on ppsci/arch/fpscores.pkl.gz
这个文件是做什么用的呢？

2024-08-08 09:08 UTC, niushao12 commented on ppsci/arch/fpscores.pkl.gz
优化评估模型的时候用的

2024-08-08 09:10 UTC, niushao12 commented on ppsci/arch/fpscores.pkl.gz
![Uploading image.png…]()

2024-08-08 09:10 UTC, lxw123123 commented
我这里使用paddle2.6.1版本测试，这里有语法报错
 File "/workspaces/PaddleScience/ppsci/arch/moflow_basic.py", line 184, in __init__
    self.w_l = paddle.create_parameter(
TypeError: create_parameter() missing 1 required positional argument: 'dtype'

2024-08-08 09:12 UTC, niushao12 commented
> create_parameter



> 我这里使用paddle2.6.1版本测试，这里有语法报错 File "/workspaces/PaddleScience/ppsci/arch/moflow_basic.py", line 184, in **init** self.w_l = paddle.create_parameter( TypeError: create_parameter() missing 1 required positional argument: 'dtype'

这个错误我刚修复了，用新的修改的moflow_basic.py文件

2024-08-08 09:14 UTC, HydrogenSulfate commented on ppsci/arch/moflow_utils.py
这个文件是否应该移动到examples/moflow下面，因为这个属于案例的辅助函数，不应该放在arch/下面

2024-08-08 09:15 UTC, niushao12 commented on ppsci/arch/moflow_utils.py
好的，我移动修复一下

2024-08-08 09:18 UTC, HydrogenSulfate commented on ppsci/arch/fpscores.pkl.gz
这个文件比较大，可以在函数读取的时候判断一下examples/moflow/下是否有这个文件，没有的话自动下载一份保存下来，从保存的文件里再读取：<https://paddle-org.bj.bcebos.com/paddlescience/models/MoFlow/fpscores.pkl.gz>

`ppsci.utils.download._download('https://paddle-org.bj.bcebos.com/paddlescience/models/MoFlow/fpscores.pkl.gz', './')`

2024-08-08 09:23 UTC, lxw123123 commented
使用新的代码，train的时候有新的错误：
 File "/workspaces/PaddleScience/ppsci/loss/func.py", line 79, in forward
    assert isinstance(losses, dict), (
AssertionError: Loss computed by custom function should be type of 'dict', but got <class 'paddle.Tensor'>. Please check the return type of custom loss function.

2024-08-08 09:56 UTC, niushao12 commented
> 使用新的代码，train的时候有新的错误： File "/workspaces/PaddleScience/ppsci/loss/func.py", line 79, in forward assert isinstance(losses, dict), ( AssertionError: Loss computed by custom function should be type of 'dict', but got <class 'paddle.Tensor'>. Please check the return type of custom loss function.

我这边train的时候没有出现这种错误

2024-08-08 10:03 UTC, niushao12 commented
> 使用新的代码，train的时候有新的错误： File "/workspaces/PaddleScience/ppsci/loss/func.py", line 79, in forward assert isinstance(losses, dict), ( AssertionError: Loss computed by custom function should be type of 'dict', but got <class 'paddle.Tensor'>. Please check the return type of custom loss function.
loss 返回的是张量，这部分代码是PaddleScience中，之前我用字典返回total_loss时候报错，后来改成张量不报错了

2024-08-08 10:08 UTC, HydrogenSulfate commented on ppsci/arch/moflow_net.py
> +        return losses
这里改成字典的形式返回，给一个合适的键名字即可

2024-08-08 10:09 UTC, HydrogenSulfate commented on ppsci/arch/moflow_net.py
> +        return losses
> 这里改成字典的形式返回，给一个合适的键名字即可，ppsci目前要求所有的loss前向计算以字典的形式返回

2024-08-08 11:03 UTC, lxw123123 commented
![image](https://github.com/user-attachments/assets/55c414d4-9106-4e57-8334-3b2e75c05186)

2024-08-08 11:06 UTC, HydrogenSulfate commented
> ![image](https://private-user-images.githubusercontent.com/176906342/356193426-55c414d4-9106-4e57-8334-3b2e75c05186.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTUzNDIsIm5iZiI6MTcyMzExNTA0MiwicGF0aCI6Ii8xNzY5MDYzNDIvMzU2MTkzNDI2LTU1YzQxNGQ0LTkxMDYtNGU1Ny04MzM0LTNiMmU3NWMwNTE4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxMTA0MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YzViZGJhNTc0ZGQ3YzQ0ZjUwNDA5YzFiNzAzNjFlOTJkMjVhZjhhMzhkOWE4ZDQyN2JlZGRkYzllODk1MjIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.H7peFx4_T509BnYlL76xiH0r40_WECjeDs6Oy7pc-YU)

看起来是Orderedset软件包自己的问题：<https://github.com/simonpercivall/orderedset/issues/36>，可以按照issue里的建议，换成这个包：<https://github.com/rspeer/ordered-set>

2024-08-08 11:07 UTC, niushao12 commented
> ![image](https://private-user-images.githubusercontent.com/176906342/356193426-55c414d4-9106-4e57-8334-3b2e75c05186.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTU0MjIsIm5iZiI6MTcyMzExNTEyMiwicGF0aCI6Ii8xNzY5MDYzNDIvMzU2MTkzNDI2LTU1YzQxNGQ0LTkxMDYtNGU1Ny04MzM0LTNiMmU3NWMwNTE4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxMTA1MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOWFlNjllYzEzYzQ1ZTU3YWI2MzVjNjUxOGRiNWUzM2JhMmY2MTlmZjBjNTE5ZmYyMGMyOTM4YjQyMGYyYjdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F64Sgz8Ask681zd9X0QS2pd_OsIFwLD9nrUQSxK52oI)

python版本太高的缘故吧，您重新安装一下orderedset这个库，我的python版本是3.9.19

2024-08-08 11:09 UTC, HydrogenSulfate commented
> > ![image](https://private-user-images.githubusercontent.com/176906342/356193426-55c414d4-9106-4e57-8334-3b2e75c05186.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTU0MjIsIm5iZiI6MTcyMzExNTEyMiwicGF0aCI6Ii8xNzY5MDYzNDIvMzU2MTkzNDI2LTU1YzQxNGQ0LTkxMDYtNGU1Ny04MzM0LTNiMmU3NWMwNTE4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxMTA1MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOWFlNjllYzEzYzQ1ZTU3YWI2MzVjNjUxOGRiNWUzM2JhMmY2MTlmZjBjNTE5ZmYyMGMyOTM4YjQyMGYyYjdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F64Sgz8Ask681zd9X0QS2pd_OsIFwLD9nrUQSxK52oI)
> 
> python版本太高的缘故吧，您重新安装一下orderedset这个库，我的python版本是3.9.19

pythoncong 3.7开始，set和dict就已经是有序的了（键值对插入顺序），所以OrderedSet这个包或许没必要使用

2024-08-08 11:12 UTC, niushao12 commented
> > > ![image](https://private-user-images.githubusercontent.com/176906342/356193426-55c414d4-9106-4e57-8334-3b2e75c05186.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTU0MjIsIm5iZiI6MTcyMzExNTEyMiwicGF0aCI6Ii8xNzY5MDYzNDIvMzU2MTkzNDI2LTU1YzQxNGQ0LTkxMDYtNGU1Ny04MzM0LTNiMmU3NWMwNTE4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxMTA1MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOWFlNjllYzEzYzQ1ZTU3YWI2MzVjNjUxOGRiNWUzM2JhMmY2MTlmZjBjNTE5ZmYyMGMyOTM4YjQyMGYyYjdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F64Sgz8Ask681zd9X0QS2pd_OsIFwLD9nrUQSxK52oI)
> > 
> > 
> > python版本太高的缘故吧，您重新安装一下orderedset这个库，我的python版本是3.9.19
> 
> pythoncong 3.7开始，set和dict就已经是有序的了（键值对插入顺序），所以OrderedSet这个包或许没必要使用，直接使用`list(set(xxx))`就能去重

那我修改一下代码

2024-08-08 11:19 UTC, lxw123123 commented
![image](https://github.com/user-attachments/assets/f1473022-3861-411b-9257-21182727bb6a)
优化的时候显示json文件不存在，建议再检查一下所有的代码细节和所有的配置文件是否完整。是否还有细节错误。

2024-08-08 11:19 UTC, HydrogenSulfate commented
git commit前请安装pre-commit，否则code-style-check检查无法通过
![image](https://github.com/user-attachments/assets/13c03201-0fa0-48db-979a-ec43682f1acb)

2024-08-08 11:26 UTC, lxw123123 commented
![image](https://github.com/user-attachments/assets/81bbd281-4aae-4995-b549-e16903dcec55)
文档这里也有点问题，代码行空着的
![image](https://github.com/user-attachments/assets/a95a0987-5116-437a-9669-d5822f7b2f29)
海面温度模型 这里是不是打错字了

2024-08-08 11:28 UTC, niushao12 commented
> git commit前请安装pre-commit，否则code-style-check检查无法通过，`pre-commit run --files 你的文件夹路径` ![image](https://private-user-images.githubusercontent.com/23737287/356198622-13c03201-0fa0-48db-979a-ec43682f1acb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTY1ODksIm5iZiI6MTcyMzExNjI4OSwicGF0aCI6Ii8yMzczNzI4Ny8zNTYxOTg2MjItMTNjMDMyMDEtMGZhMC00OGRiLTk3OWEtZWM0MzY4MmYxYWNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDExMjQ0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5YWQ4NWYyZjY2YTRkNGVhMGM5ODhkOWE1NTM3NzM4ZmEzODUyODU1MmFlMmUzNTU5N2RmYWYyODU5ZGQwNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UrPFwUHHP3VUHGC9qH2HynytTtRt_jzujTtWOX6zaO8)

我安装了这个包了，git commit的时候没有报错，不知道为什么会报错，我们这边服务其上链接github失败，代码是用我这边电脑上传的。

2024-08-08 11:32 UTC, HydrogenSulfate commented
> > git commit前请安装pre-commit，否则code-style-check检查无法通过，`pre-commit run --files 你的文件夹路径` ![image](https://private-user-images.githubusercontent.com/23737287/356198622-13c03201-0fa0-48db-979a-ec43682f1acb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTY1ODksIm5iZiI6MTcyMzExNjI4OSwicGF0aCI6Ii8yMzczNzI4Ny8zNTYxOTg2MjItMTNjMDMyMDEtMGZhMC00OGRiLTk3OWEtZWM0MzY4MmYxYWNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDExMjQ0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5YWQ4NWYyZjY2YTRkNGVhMGM5ODhkOWE1NTM3NzM4ZmEzODUyODU1MmFlMmUzNTU5N2RmYWYyODU5ZGQwNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UrPFwUHHP3VUHGC9qH2HynytTtRt_jzujTtWOX6zaO8)
> 
> 我安装了这个包了，git commit的时候没有报错，不知道为什么会报错，我们这边服务其上链接github失败，代码是用我这边电脑上传的。

可以确认一下pre-commit是否在git commit命令执行之前安装的，另外如果安装成功，git commit时会自动启动多项钩子检查，如果都通过的话（绿色pass）才能真正被commit，否则会自动修改有问题的文件（个别情况可能需要手动修改），然后需要手动add一下被修改的文件再次commit，重复这个过程直到全部pass通过。如果在commit之后安装的，也可以手动执行`pre-commit run --files 你的文件夹路径`，手动运行钩子检查。

2024-08-08 11:32 UTC, lxw123123 commented
![image](https://github.com/user-attachments/assets/34447cb2-9f05-4bda-9f21-fc917490e0e6)
运行这个文件的时候optimize_moflow.py 报错这个

> > ![image](https://private-user-images.githubusercontent.com/176906342/356197760-f1473022-3861-411b-9257-21182727bb6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTY1ODksIm5iZiI6MTcyMzExNjI4OSwicGF0aCI6Ii8xNzY5MDYzNDIvMzU2MTk3NzYwLWYxNDczMDIyLTM4NjEtNDExYi05MjU3LTIxMTgyNzI3YmI2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxMTI0NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Nzk3YTk4Yjc5MWY1YjQzMDQ0OGNiYmVkZDNmYjhiNjhhZWVhOWNiMmQ5OThkMGM1M2U5Zjk0NzQ3N2I4ZjMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PiGjDX8JVVFPUCxc1bHB8I5mNKnqCKx7YvsifNvcuDI) 优化的时候显示json文件不存在，建议再检查一下所有的代码细节和所有的配置文件是否完整。是否还有细节错误。
> 
> 这都是数据集中的文件，您这边没有下载完整么？只要配置了数据FILE_PATH文件应该不会出错的

这个已解决。路径配置正确后，出现了这个问题
![image](https://github.com/user-attachments/assets/263b01a7-ade3-4064-8708-33f173c13a40)

2024-08-08 11:35 UTC, niushao12 commented
> > > ![image](https://private-user-images.githubusercontent.com/176906342/356197760-f1473022-3861-411b-9257-21182727bb6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTY1ODksIm5iZiI6MTcyMzExNjI4OSwicGF0aCI6Ii8xNzY5MDYzNDIvMzU2MTk3NzYwLWYxNDczMDIyLTM4NjEtNDExYi05MjU3LTIxMTgyNzI3YmI2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxMTI0NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Nzk3YTk4Yjc5MWY1YjQzMDQ0OGNiYmVkZDNmYjhiNjhhZWVhOWNiMmQ5OThkMGM1M2U5Zjk0NzQ3N2I4ZjMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PiGjDX8JVVFPUCxc1bHB8I5mNKnqCKx7YvsifNvcuDI) 优化的时候显示json文件不存在，建议再检查一下所有的代码细节和所有的配置文件是否完整。是否还有细节错误。
> > 
> > 
> > 这都是数据集中的文件，您这边没有下载完整么？只要配置了数据FILE_PATH文件应该不会出错的
> 
> 这个已解决。路径配置正确后，出现了这个问题 ![image](https://private-user-images.githubusercontent.com/176906342/356203671-263b01a7-ade3-4064-8708-33f173c13a40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTcxNDQsIm5iZiI6MTcyMzExNjg0NCwicGF0aCI6Ii8xNzY5MDYzNDIvMzU2MjAzNjcxLTI2M2IwMWE3LWFkZTMtNDA2NC04NzA4LTMzZjE3M2MxM2E0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxMTM0MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMGRmZjlkYTNiN2E2Y2JjOTM4YWJiNzBjZWIwZDI0Njc1ZWQ5YTgzZjMyNWI5Nzk1NzQzNjNhNWJiMjIyYjlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._ri_Q2d0NT24Wdfv72fi-7IbEd2sK5elZsqVvZ0necI)

这个您需要指定评估模型的路径，之前我在配置文件我指定配置了，上次修改的时候写成null了，需要这样指定EVAL.pretrained_model_path=

2024-08-08 11:35 UTC, HydrogenSulfate commented
> > > ![image](https://private-user-images.githubusercontent.com/176906342/356197760-f1473022-3861-411b-9257-21182727bb6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTY1ODksIm5iZiI6MTcyMzExNjI4OSwicGF0aCI6Ii8xNzY5MDYzNDIvMzU2MTk3NzYwLWYxNDczMDIyLTM4NjEtNDExYi05MjU3LTIxMTgyNzI3YmI2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxMTI0NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Nzk3YTk4Yjc5MWY1YjQzMDQ0OGNiYmVkZDNmYjhiNjhhZWVhOWNiMmQ5OThkMGM1M2U5Zjk0NzQ3N2I4ZjMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PiGjDX8JVVFPUCxc1bHB8I5mNKnqCKx7YvsifNvcuDI) 优化的时候显示json文件不存在，建议再检查一下所有的代码细节和所有的配置文件是否完整。是否还有细节错误。
> > 
> > 
> > 这都是数据集中的文件，您这边没有下载完整么？只要配置了数据FILE_PATH文件应该不会出错的
> 
> 这个已解决。路径配置正确后，出现了这个问题 ![image](https://private-user-images.githubusercontent.com/176906342/356203671-263b01a7-ade3-4064-8708-33f173c13a40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTcxMDgsIm5iZiI6MTcyMzExNjgwOCwicGF0aCI6Ii8xNzY5MDYzNDIvMzU2MjAzNjcxLTI2M2IwMWE3LWFkZTMtNDA2NC04NzA4LTMzZjE3M2MxM2E0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxMTMzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYjVlY2MzZDdjMGRlMWNhZjRjNTFkMTQ3NDM5NTMzNjUxZWE5OWY2ZmRlOGMxOWE5YTMyY2I2NWQyYThlODkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BJB31pNUTki3UXisN6y-qDWnzQ-_28athm-l8BcuTYM)

PaddleScience使用hydra管理启动命令，可以通过在执行的命令末尾加上：`EVAL.pretrained_model_path=xxx`覆写实际运行时的配置。

2024-08-08 11:36 UTC, niushao12 commented
> > > git commit前请安装pre-commit，否则code-style-check检查无法通过，`pre-commit run --files 你的文件夹路径` ![image](https://private-user-images.githubusercontent.com/23737287/356198622-13c03201-0fa0-48db-979a-ec43682f1acb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTY1ODksIm5iZiI6MTcyMzExNjI4OSwicGF0aCI6Ii8yMzczNzI4Ny8zNTYxOTg2MjItMTNjMDMyMDEtMGZhMC00OGRiLTk3OWEtZWM0MzY4MmYxYWNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDExMjQ0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5YWQ4NWYyZjY2YTRkNGVhMGM5ODhkOWE1NTM3NzM4ZmEzODUyODU1MmFlMmUzNTU5N2RmYWYyODU5ZGQwNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UrPFwUHHP3VUHGC9qH2HynytTtRt_jzujTtWOX6zaO8)
> > 
> > 
> > 我安装了这个包了，git commit的时候没有报错，不知道为什么会报错，我们这边服务其上链接github失败，代码是用我这边电脑上传的。
> 
> 可以确认一下pre-commit是否在git commit命令执行之前安装的，另外如果安装成功，git commit时会自动启动多项钩子检查，如果都通过的话（绿色pass）才能真正被commit，否则会自动修改有问题的文件（个别情况可能需要手动修改），然后需要手动add一下被修改的文件再次commit，重复这个过程直到全部pass通过。如果在commit之后安装的，也可以手动执行`pre-commit run --files 你的文件夹路径`，手动运行钩子检查。

是在上传之前安装的，我重新上传一下吧

2024-08-08 11:38 UTC, HydrogenSulfate commented
> > > > ![image](https://private-user-images.githubusercontent.com/176906342/356197760-f1473022-3861-411b-9257-21182727bb6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTY1ODksIm5iZiI6MTcyMzExNjI4OSwicGF0aCI6Ii8xNzY5MDYzNDIvMzU2MTk3NzYwLWYxNDczMDIyLTM4NjEtNDExYi05MjU3LTIxMTgyNzI3YmI2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxMTI0NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Nzk3YTk4Yjc5MWY1YjQzMDQ0OGNiYmVkZDNmYjhiNjhhZWVhOWNiMmQ5OThkMGM1M2U5Zjk0NzQ3N2I4ZjMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PiGjDX8JVVFPUCxc1bHB8I5mNKnqCKx7YvsifNvcuDI) 优化的时候显示json文件不存在，建议再检查一下所有的代码细节和所有的配置文件是否完整。是否还有细节错误。
> > > 
> > > 
> > > 这都是数据集中的文件，您这边没有下载完整么？只要配置了数据FILE_PATH文件应该不会出错的
> > 
> > 
> > 这个已解决。路径配置正确后，出现了这个问题 ![image](https://private-user-images.githubusercontent.com/176906342/356203671-263b01a7-ade3-4064-8708-33f173c13a40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTcxNDQsIm5iZiI6MTcyMzExNjg0NCwicGF0aCI6Ii8xNzY5MDYzNDIvMzU2MjAzNjcxLTI2M2IwMWE3LWFkZTMtNDA2NC04NzA4LTMzZjE3M2MxM2E0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxMTM0MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMGRmZjlkYTNiN2E2Y2JjOTM4YWJiNzBjZWIwZDI0Njc1ZWQ5YTgzZjMyNWI5Nzk1NzQzNjNhNWJiMjIyYjlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._ri_Q2d0NT24Wdfv72fi-7IbEd2sK5elZsqVvZ0necI)
> 
> 这个您需要指定评估模型的路径，之前我在配置文件我指定配置了，上次修改的时候写成null了，需要这样指定EVAL.pretrained_model_path=

可以顺便在文档开头给出的命令末尾补充一下

2024-08-08 11:39 UTC, niushao12 commented
> ![image](https://private-user-images.githubusercontent.com/176906342/356200478-81bbd281-4aae-4995-b549-e16903dcec55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTc0NDgsIm5iZiI6MTcyMzExNzE0OCwicGF0aCI6Ii8xNzY5MDYzNDIvMzU2MjAwNDc4LTgxYmJkMjgxLTRhYWUtNDk5NS1iNTQ5LWUxNjkwM2RjZWM1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxMTM5MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYmYyODM4ODM1ZDcyYmI1ZjZhY2U3NjllMjQ4NjUxNjU3MmViNDE1NTMwNzliZGUyN2U3MGU4NmY2ZDhiYTczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZvfekAaNT1Ip-6QuXAZufX30ZhgPKQwf2S70902Spqw) 文档这里也有点问题，代码行空着的 ![image](https://private-user-images.githubusercontent.com/176906342/356200864-a95a0987-5116-437a-9669-d5822f7b2f29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTc0NDgsIm5iZiI6MTcyMzExNzE0OCwicGF0aCI6Ii8xNzY5MDYzNDIvMzU2MjAwODY0LWE5NWEwOTg3LTUxMTYtNDM3YS05NjY5LWQ1ODIyZjdiMmYyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxMTM5MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MjBlNDZiYTMxZmU2MDNlYzMxZTllOTRlOWNmZDU3YmI2MTNmYjY4MmQ1ZDMxOTkyOWQzYjUyZDc4MTU5MDc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Uh33s--o0gBLr51QwUsGLc9uCfKP6HCbhd8DvG-TOWw) 海面温度模型 这里是不是打错字了

修复了，您看一下

2024-08-08 11:40 UTC, niushao12 commented
> > > > > ![image](https://private-user-images.githubusercontent.com/176906342/356197760-f1473022-3861-411b-9257-21182727bb6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTY1ODksIm5iZiI6MTcyMzExNjI4OSwicGF0aCI6Ii8xNzY5MDYzNDIvMzU2MTk3NzYwLWYxNDczMDIyLTM4NjEtNDExYi05MjU3LTIxMTgyNzI3YmI2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxMTI0NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Nzk3YTk4Yjc5MWY1YjQzMDQ0OGNiYmVkZDNmYjhiNjhhZWVhOWNiMmQ5OThkMGM1M2U5Zjk0NzQ3N2I4ZjMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PiGjDX8JVVFPUCxc1bHB8I5mNKnqCKx7YvsifNvcuDI) 优化的时候显示json文件不存在，建议再检查一下所有的代码细节和所有的配置文件是否完整。是否还有细节错误。
> > > > 
> > > > 
> > > > 这都是数据集中的文件，您这边没有下载完整么？只要配置了数据FILE_PATH文件应该不会出错的
> > > 
> > > 
> > > 这个已解决。路径配置正确后，出现了这个问题 ![image](https://private-user-images.githubusercontent.com/176906342/356203671-263b01a7-ade3-4064-8708-33f173c13a40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTcxNDQsIm5iZiI6MTcyMzExNjg0NCwicGF0aCI6Ii8xNzY5MDYzNDIvMzU2MjAzNjcxLTI2M2IwMWE3LWFkZTMtNDA2NC04NzA4LTMzZjE3M2MxM2E0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxMTM0MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMGRmZjlkYTNiN2E2Y2JjOTM4YWJiNzBjZWIwZDI0Njc1ZWQ5YTgzZjMyNWI5Nzk1NzQzNjNhNWJiMjIyYjlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._ri_Q2d0NT24Wdfv72fi-7IbEd2sK5elZsqVvZ0necI)
> > 
> > 
> > 这个您需要指定评估模型的路径，之前我在配置文件我指定配置了，上次修改的时候写成null了，需要这样指定EVAL.pretrained_model_path=
> 
> 可以顺便在文档开头给出的命令末尾补充一下

补充的时候我需要指定路径么？评估的时候涉及到的模型比较多

2024-08-08 11:46 UTC, HydrogenSulfate commented
> > > > > > ![image](https://private-user-images.githubusercontent.com/176906342/356197760-f1473022-3861-411b-9257-21182727bb6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTY1ODksIm5iZiI6MTcyMzExNjI4OSwicGF0aCI6Ii8xNzY5MDYzNDIvMzU2MTk3NzYwLWYxNDczMDIyLTM4NjEtNDExYi05MjU3LTIxMTgyNzI3YmI2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxMTI0NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Nzk3YTk4Yjc5MWY1YjQzMDQ0OGNiYmVkZDNmYjhiNjhhZWVhOWNiMmQ5OThkMGM1M2U5Zjk0NzQ3N2I4ZjMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PiGjDX8JVVFPUCxc1bHB8I5mNKnqCKx7YvsifNvcuDI) 优化的时候显示json文件不存在，建议再检查一下所有的代码细节和所有的配置文件是否完整。是否还有细节错误。
> > > > > 
> > > > > 
> > > > > 这都是数据集中的文件，您这边没有下载完整么？只要配置了数据FILE_PATH文件应该不会出错的
> > > > 
> > > > 
> > > > 这个已解决。路径配置正确后，出现了这个问题 ![image](https://private-user-images.githubusercontent.com/176906342/356203671-263b01a7-ade3-4064-8708-33f173c13a40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTcxNDQsIm5iZiI6MTcyMzExNjg0NCwicGF0aCI6Ii8xNzY5MDYzNDIvMzU2MjAzNjcxLTI2M2IwMWE3LWFkZTMtNDA2NC04NzA4LTMzZjE3M2MxM2E0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxMTM0MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMGRmZjlkYTNiN2E2Y2JjOTM4YWJiNzBjZWIwZDI0Njc1ZWQ5YTgzZjMyNWI5Nzk1NzQzNjNhNWJiMjIyYjlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._ri_Q2d0NT24Wdfv72fi-7IbEd2sK5elZsqVvZ0necI)
> > > 
> > > 
> > > 这个您需要指定评估模型的路径，之前我在配置文件我指定配置了，上次修改的时候写成null了，需要这样指定EVAL.pretrained_model_path=
> > 
> > 
> > 可以顺便在文档开头给出的命令末尾补充一下
> 
> 补充的时候我需要指定路径么？评估的时候涉及到的模型比较多

1. 这个路径可以是url或者是实际硬盘地址，可以参考其他案例的文档指定方式
2. 如果评估过程是独立的，即一个模型载入不同的参数文件评估，那可以复制上述命令改一下末尾的路径即可，如果是一次评估需要载入多个模型，那可以先保持现状，即只把这一个模型在命令行里指定，其它的写到代码中

2024-08-08 11:57 UTC, niushao12 commented
> > > > > > > ![image](https://private-user-images.githubusercontent.com/176906342/356197760-f1473022-3861-411b-9257-21182727bb6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTY1ODksIm5iZiI6MTcyMzExNjI4OSwicGF0aCI6Ii8xNzY5MDYzNDIvMzU2MTk3NzYwLWYxNDczMDIyLTM4NjEtNDExYi05MjU3LTIxMTgyNzI3YmI2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxMTI0NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Nzk3YTk4Yjc5MWY1YjQzMDQ0OGNiYmVkZDNmYjhiNjhhZWVhOWNiMmQ5OThkMGM1M2U5Zjk0NzQ3N2I4ZjMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PiGjDX8JVVFPUCxc1bHB8I5mNKnqCKx7YvsifNvcuDI) 优化的时候显示json文件不存在，建议再检查一下所有的代码细节和所有的配置文件是否完整。是否还有细节错误。
> > > > > > 
> > > > > > 
> > > > > > 这都是数据集中的文件，您这边没有下载完整么？只要配置了数据FILE_PATH文件应该不会出错的
> > > > > 
> > > > > 
> > > > > 这个已解决。路径配置正确后，出现了这个问题 ![image](https://private-user-images.githubusercontent.com/176906342/356203671-263b01a7-ade3-4064-8708-33f173c13a40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTcxNDQsIm5iZiI6MTcyMzExNjg0NCwicGF0aCI6Ii8xNzY5MDYzNDIvMzU2MjAzNjcxLTI2M2IwMWE3LWFkZTMtNDA2NC04NzA4LTMzZjE3M2MxM2E0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxMTM0MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMGRmZjlkYTNiN2E2Y2JjOTM4YWJiNzBjZWIwZDI0Njc1ZWQ5YTgzZjMyNWI5Nzk1NzQzNjNhNWJiMjIyYjlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._ri_Q2d0NT24Wdfv72fi-7IbEd2sK5elZsqVvZ0necI)
> > > > 
> > > > 
> > > > 这个您需要指定评估模型的路径，之前我在配置文件我指定配置了，上次修改的时候写成null了，需要这样指定EVAL.pretrained_model_path=
> > > 
> > > 
> > > 可以顺便在文档开头给出的命令末尾补充一下
> > 
> > 
> > 补充的时候我需要指定路径么？评估的时候涉及到的模型比较多
> 
> 1. 这个路径可以是url或者是实际硬盘地址，可以参考其他案例的文档指定方式
> 2. 如果评估过程是独立的，即一个模型载入不同的参数文件评估，那可以复制上述命令改一下末尾的路径即可，如果是一次评估需要载入多个模型，那可以先保持现状，即只把这一个模型在命令行里指定，其它的写到代码中

不是载入多个模型，是不同数据集模型不同，不同的优化方式模型也不同，我这边按照上传的模型修改了一下

2024-08-08 11:59 UTC, niushao12 commented
> > > > git commit前请安装pre-commit，否则code-style-check检查无法通过，`pre-commit run --files 你的文件夹路径` ![image](https://private-user-images.githubusercontent.com/23737287/356198622-13c03201-0fa0-48db-979a-ec43682f1acb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTY1ODksIm5iZiI6MTcyMzExNjI4OSwicGF0aCI6Ii8yMzczNzI4Ny8zNTYxOTg2MjItMTNjMDMyMDEtMGZhMC00OGRiLTk3OWEtZWM0MzY4MmYxYWNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDExMjQ0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5YWQ4NWYyZjY2YTRkNGVhMGM5ODhkOWE1NTM3NzM4ZmEzODUyODU1MmFlMmUzNTU5N2RmYWYyODU5ZGQwNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UrPFwUHHP3VUHGC9qH2HynytTtRt_jzujTtWOX6zaO8)
> > > 
> > > 
> > > 我安装了这个包了，git commit的时候没有报错，不知道为什么会报错，我们这边服务其上链接github失败，代码是用我这边电脑上传的。
> > 
> > 
> > 可以确认一下pre-commit是否在git commit命令执行之前安装的，另外如果安装成功，git commit时会自动启动多项钩子检查，如果都通过的话（绿色pass）才能真正被commit，否则会自动修改有问题的文件（个别情况可能需要手动修改），然后需要手动add一下被修改的文件再次commit，重复这个过程直到全部pass通过。如果在commit之后安装的，也可以手动执行`pre-commit run --files 你的文件夹路径`，手动运行钩子检查。
> 
> 是在上传之前安装的，我重新上传一下吧

这个怎么重新上传呢，新增一个PR么？

2024-08-08 12:08 UTC, HydrogenSulfate commented
> > > > > git commit前请安装pre-commit，否则code-style-check检查无法通过，`pre-commit run --files 你的文件夹路径` ![image](https://private-user-images.githubusercontent.com/23737287/356198622-13c03201-0fa0-48db-979a-ec43682f1acb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTY1ODksIm5iZiI6MTcyMzExNjI4OSwicGF0aCI6Ii8yMzczNzI4Ny8zNTYxOTg2MjItMTNjMDMyMDEtMGZhMC00OGRiLTk3OWEtZWM0MzY4MmYxYWNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDExMjQ0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5YWQ4NWYyZjY2YTRkNGVhMGM5ODhkOWE1NTM3NzM4ZmEzODUyODU1MmFlMmUzNTU5N2RmYWYyODU5ZGQwNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UrPFwUHHP3VUHGC9qH2HynytTtRt_jzujTtWOX6zaO8)
> > > > 
> > > > 
> > > > 我安装了这个包了，git commit的时候没有报错，不知道为什么会报错，我们这边服务其上链接github失败，代码是用我这边电脑上传的。
> > > 
> > > 
> > > 可以确认一下pre-commit是否在git commit命令执行之前安装的，另外如果安装成功，git commit时会自动启动多项钩子检查，如果都通过的话（绿色pass）才能真正被commit，否则会自动修改有问题的文件（个别情况可能需要手动修改），然后需要手动add一下被修改的文件再次commit，重复这个过程直到全部pass通过。如果在commit之后安装的，也可以手动执行`pre-commit run --files 你的文件夹路径`，手动运行钩子检查。
> > 
> > 
> > 是在上传之前安装的，我重新上传一下吧
> 
> 这个怎么重新上传呢，新增一个PR么？

没太理解，我没有提到需要重新上传什么额外的东西，不需要新增PR，pre-commit只是一个自动代码格式化工具，执行`pre-commit run --files 你的文件夹路径`后，某些文件可能会被这个工具修改代码格式（比如添加换行），修改了之后需要用户手动 git status -uno找到并add 这些文件，再commit，push上来

2024-08-08 12:29 UTC, HydrogenSulfate commented
train_moflow.py，mkdocs.yml两个文件好像还有点问题，可以用pre-commit单独跑一下

2024-08-08 12:38 UTC, niushao12 commented
> mkdocs

这两个文件检查的时报错了

![image](https://github.com/user-attachments/assets/3a543595-1049-4ce8-805c-6b33bc46d2d1)

2024-08-09 02:38 UTC, lxw123123 commented
![image](https://github.com/user-attachments/assets/a24be11b-849b-441c-95f8-0532b59ab204)
![截屏2024-08-09 10 36 26](https://github.com/user-attachments/assets/170155e0-5d7c-4515-beb3-1239ba5505e7)
![image](https://github.com/user-attachments/assets/7ad80f88-f9ec-4c73-ba30-38bfa7258efd)
文档多个代码的部分，添加了额外的信息，麻烦再检查一下

2024-08-09 03:04 UTC, lxw123123 commented
![image](https://github.com/user-attachments/assets/e3c541b7-c696-440a-933f-84ebfe4eff1f)
optimize_moflow.py 优化moflow这里还有问题

2024-08-09 07:22 UTC, niushao12 commented
> ![image](https://private-user-images.githubusercontent.com/176906342/356441532-a24be11b-849b-441c-95f8-0532b59ab204.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxODgzNjcsIm5iZiI6MTcyMzE4ODA2NywicGF0aCI6Ii8xNzY5MDYzNDIvMzU2NDQxNTMyLWEyNGJlMTFiLTg0OWItNDQxYy05NWY4LTA1MzJiNTlhYjIwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQwNzIxMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZmU4ZmRkNjlkOTBlZWZjNzg4NDFmMTRiYTMzY2NjYWJiYzNlOWEyYTZjY2U2ZTdmMDAxMzljYmFiNzRhM2Q2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.d9baadV7vEdN6eB1WXe9sHKFuABPHYLS0sI6vzZk-3I) 这里缺失代码 ![image](https://private-user-images.githubusercontent.com/176906342/356442146-49d312df-31b2-43cf-9b64-8d75c2f9ba32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxODgzNjcsIm5iZiI6MTcyMzE4ODA2NywicGF0aCI6Ii8xNzY5MDYzNDIvMzU2NDQyMTQ2LTQ5ZDMxMmRmLTMxYjItNDNjZi05YjY0LThkNzVjMmY5YmEzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQwNzIxMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDJjZmMzMzRjNGU4M2MxMzQzOGFkYWE5YTM1NzcwMmVjNjNkNzA1MGE5ZWRkMzA0Yjc2MjcwMDNlYzJhZmM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.heQt7ibpKhmXKTpNRam1CYHhjL2hUiT8fG-e6lI_7nU) 这里乱码了 ![截屏2024-08-09 10 36 26](https://private-user-images.githubusercontent.com/176906342/356441721-170155e0-5d7c-4515-beb3-1239ba5505e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxODgzNjcsIm5iZiI6MTcyMzE4ODA2NywicGF0aCI6Ii8xNzY5MDYzNDIvMzU2NDQxNzIxLTE3MDE1NWUwLTVkN2MtNDUxNS1iZWIzLTEyMzliYTU1MDVlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQwNzIxMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZmRkZTQyNjcxOTdiZTVlNTFhNWZkYmUyODNjYzhiZmMyMThhNGE1M2NiMjFmZWZhNDNhN2IzZjZmMTg2OGY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Cel3EIaklqLEv-J66uOnyNdrcHudh_smFBHcKwbCBqU) ![image](https://private-user-images.githubusercontent.com/176906342/356441869-7ad80f88-f9ec-4c73-ba30-38bfa7258efd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxODgzNjcsIm5iZiI6MTcyMzE4ODA2NywicGF0aCI6Ii8xNzY5MDYzNDIvMzU2NDQxODY5LTdhZDgwZjg4LWY5ZWMtNGM3My1iYTMwLTM4YmZhNzI1OGVmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQwNzIxMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YzljZGU4YmExN2E4Mjc3ODI2OTRhNGNjMzQ5M2Y5NDQ0MWVjYzA5MWIxMTMzZDQ3YjI4MmZkN2NlOTQyOGQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1RPLBsp5XAINF26OkCTTO8aS9Bbb2abAIJn3JZgniAk) 文档多个代码的部分，添加了额外的信息，麻烦再检查一下
> 
> 另外还想问一下，之前基于预训练的模型，我记得是会生成分子结构的，包括会有输出的图片，我在运行test_generate.py的时候，并没有看到生成的分子结构的输出
生成分子图片输出的话，您需要选择模式，有一个重构模式可以生成图片

2024-08-09 07:32 UTC, niushao12 commented
> ![image](https://private-user-images.githubusercontent.com/176906342/356446026-e3c541b7-c696-440a-933f-84ebfe4eff1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxODgzNjcsIm5iZiI6MTcyMzE4ODA2NywicGF0aCI6Ii8xNzY5MDYzNDIvMzU2NDQ2MDI2LWUzYzU0MWI3LWM2OTYtNDQwYS05MzNmLTg0ZWJmZTRlZmYxZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQwNzIxMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODllYjM3MWMyMjU2MDMwNDBmMjA2M2IxNmUzYTU1NzUwOTA2OThkODM4NzE4ZDg0ZDNhMTNmOGFlYmEzY2YxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ppkKoDGnoyRB2WQh8tvcatNlKx8U6pQBialeWbLHdzs) optimize_moflow.py 优化moflow这里还有问题

这个错误是将配置文件中的str换成int造成的，我这边修改一下吧

2024-08-09 07:42 UTC, niushao12 commented
> > ![image](https://private-user-images.githubusercontent.com/176906342/356446026-e3c541b7-c696-440a-933f-84ebfe4eff1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxODgzNjcsIm5iZiI6MTcyMzE4ODA2NywicGF0aCI6Ii8xNzY5MDYzNDIvMzU2NDQ2MDI2LWUzYzU0MWI3LWM2OTYtNDQwYS05MzNmLTg0ZWJmZTRlZmYxZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQwNzIxMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODllYjM3MWMyMjU2MDMwNDBmMjA2M2IxNmUzYTU1NzUwOTA2OThkODM4NzE4ZDg0ZDNhMTNmOGFlYmEzY2YxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ppkKoDGnoyRB2WQh8tvcatNlKx8U6pQBialeWbLHdzs) optimize_moflow.py 优化moflow这里还有问题
> 
> 这个错误是将配置文件中的str换成int造成的，我这边修改一下吧

已经修复了，将配置文件hidden参数修改成list就行

2024-08-09 07:56 UTC, niushao12 commented
> ![image](https://private-user-images.githubusercontent.com/176906342/356441532-a24be11b-849b-441c-95f8-0532b59ab204.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTAzNTEsIm5iZiI6MTcyMzE5MDA1MSwicGF0aCI6Ii8xNzY5MDYzNDIvMzU2NDQxNTMyLWEyNGJlMTFiLTg0OWItNDQxYy05NWY4LTA1MzJiNTlhYjIwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQwNzU0MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTRkODM5ZDQ5OGQxY2QxODg5YjBmYjA0NjFkNGZhNmY0MTA2Y2RmYWU3MDIwYzdiOTM5MjkxY2Y5NTE0ZTFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FxCpzuxKu-DhhlPGdVgIj50jp00CSRnkLbJserXYqC8) 这里缺失代码 ![image](https://private-user-images.githubusercontent.com/176906342/356442146-49d312df-31b2-43cf-9b64-8d75c2f9ba32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTAzNTEsIm5iZiI6MTcyMzE5MDA1MSwicGF0aCI6Ii8xNzY5MDYzNDIvMzU2NDQyMTQ2LTQ5ZDMxMmRmLTMxYjItNDNjZi05YjY0LThkNzVjMmY5YmEzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQwNzU0MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZmJlZDIxMmYyNWI4Nzk1NjEwNjRjOGIwOTVkYjk0NjgxYjdkZjAwNTNhOTA5MTI1NTU4MzNmZTA3YmE4ZTYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4H5im-B8W8ByDnyNbYAMa8kegCt4T2ERcwfRrwD3Mfc) 这里乱码了 ![截屏2024-08-09 10 36 26](https://private-user-images.githubusercontent.com/176906342/356441721-170155e0-5d7c-4515-beb3-1239ba5505e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTAzNTEsIm5iZiI6MTcyMzE5MDA1MSwicGF0aCI6Ii8xNzY5MDYzNDIvMzU2NDQxNzIxLTE3MDE1NWUwLTVkN2MtNDUxNS1iZWIzLTEyMzliYTU1MDVlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQwNzU0MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMmQ0MWVjYzJlMTczMTg2MTA0NTQ2OWZlZGY0NzczNWI4MTA3Y2RhNzIxNDI3MGM0NDQ5ZGU4YzUzYjExYjg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5Fbx4INUf7xUc-9jGglPIf_cMiSkyVX7M07NfTslXeY) ![image](https://private-user-images.githubusercontent.com/176906342/356441869-7ad80f88-f9ec-4c73-ba30-38bfa7258efd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTAzNTEsIm5iZiI6MTcyMzE5MDA1MSwicGF0aCI6Ii8xNzY5MDYzNDIvMzU2NDQxODY5LTdhZDgwZjg4LWY5ZWMtNGM3My1iYTMwLTM4YmZhNzI1OGVmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQwNzU0MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yN2IzNTUzYjliMWJjMjk5OGZjY2VlNDc4MGM3ZjRhNWYyMTJlOTFiMjU0ZWM3OWY2MmI4YWNhMDYxNmRiMWQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qTYlWVvGIKCfbtENfJWYbRPLc0dDXhidMRJx-0Ix1qM) 文档多个代码的部分，添加了额外的信息，麻烦再检查一下
> 
> 另外还想问一下，之前基于预训练的模型，我记得是会生成分子结构的，包括会有输出的图片，我在运行test_generate.py的时候，并没有看到生成的分子结构的输出

![image](https://github.com/user-attachments/assets/0c5e51c5-e3cf-4d92-9663-4caf85e43f1f)
这个公式乱码的我这边是正常的，是因为不支持这个字体么？
![image](https://github.com/user-attachments/assets/d78a989d-44a7-4089-aa43-9fa734bac9db)

2024-08-09 07:59 UTC, HydrogenSulfate commented
> > ![image](https://private-user-images.githubusercontent.com/176906342/356441532-a24be11b-849b-441c-95f8-0532b59ab204.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTAzNTEsIm5iZiI6MTcyMzE5MDA1MSwicGF0aCI6Ii8xNzY5MDYzNDIvMzU2NDQxNTMyLWEyNGJlMTFiLTg0OWItNDQxYy05NWY4LTA1MzJiNTlhYjIwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQwNzU0MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTRkODM5ZDQ5OGQxY2QxODg5YjBmYjA0NjFkNGZhNmY0MTA2Y2RmYWU3MDIwYzdiOTM5MjkxY2Y5NTE0ZTFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FxCpzuxKu-DhhlPGdVgIj50jp00CSRnkLbJserXYqC8) 这里缺失代码 ![image](https://private-user-images.githubusercontent.com/176906342/356442146-49d312df-31b2-43cf-9b64-8d75c2f9ba32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTAzNTEsIm5iZiI6MTcyMzE5MDA1MSwicGF0aCI6Ii8xNzY5MDYzNDIvMzU2NDQyMTQ2LTQ5ZDMxMmRmLTMxYjItNDNjZi05YjY0LThkNzVjMmY5YmEzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQwNzU0MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZmJlZDIxMmYyNWI4Nzk1NjEwNjRjOGIwOTVkYjk0NjgxYjdkZjAwNTNhOTA5MTI1NTU4MzNmZTA3YmE4ZTYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4H5im-B8W8ByDnyNbYAMa8kegCt4T2ERcwfRrwD3Mfc) 这里乱码了 ![截屏2024-08-09 10 36 26](https://private-user-images.githubusercontent.com/176906342/356441721-170155e0-5d7c-4515-beb3-1239ba5505e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTAzNTEsIm5iZiI6MTcyMzE5MDA1MSwicGF0aCI6Ii8xNzY5MDYzNDIvMzU2NDQxNzIxLTE3MDE1NWUwLTVkN2MtNDUxNS1iZWIzLTEyMzliYTU1MDVlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQwNzU0MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMmQ0MWVjYzJlMTczMTg2MTA0NTQ2OWZlZGY0NzczNWI4MTA3Y2RhNzIxNDI3MGM0NDQ5ZGU4YzUzYjExYjg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5Fbx4INUf7xUc-9jGglPIf_cMiSkyVX7M07NfTslXeY) ![image](https://private-user-images.githubusercontent.com/176906342/356441869-7ad80f88-f9ec-4c73-ba30-38bfa7258efd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTAzNTEsIm5iZiI6MTcyMzE5MDA1MSwicGF0aCI6Ii8xNzY5MDYzNDIvMzU2NDQxODY5LTdhZDgwZjg4LWY5ZWMtNGM3My1iYTMwLTM4YmZhNzI1OGVmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQwNzU0MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yN2IzNTUzYjliMWJjMjk5OGZjY2VlNDc4MGM3ZjRhNWYyMTJlOTFiMjU0ZWM3OWY2MmI4YWNhMDYxNmRiMWQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qTYlWVvGIKCfbtENfJWYbRPLc0dDXhidMRJx-0Ix1qM) 文档多个代码的部分，添加了额外的信息，麻烦再检查一下
> > 另外还想问一下，之前基于预训练的模型，我记得是会生成分子结构的，包括会有输出的图片，我在运行test_generate.py的时候，并没有看到生成的分子结构的输出
> 
> ![image](https://private-user-images.githubusercontent.com/53072633/356512791-0c5e51c5-e3cf-4d92-9663-4caf85e43f1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTA1MzksIm5iZiI6MTcyMzE5MDIzOSwicGF0aCI6Ii81MzA3MjYzMy8zNTY1MTI3OTEtMGM1ZTUxYzUtZTNjZi00ZDkyLTk2NjMtNGNhZjg1ZTQzZjFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDA3NTcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1YTYyYThmNTVkMDM1Y2E5M2M5NTc0NGU5Y2E5ODFkZGE0MWQ0MDM2M2E2NzdjMWZlNzQzZTdlN2UyNzNlNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AW6AWBBSaZWeSpbnT85C5DZQpj8PrZF844S-ExCFAqs) 这个公式乱码的我这边是正常的，是因为不支持这个字体么？ ![image](https://private-user-images.githubusercontent.com/53072633/356513283-d78a989d-44a7-4089-aa43-9fa734bac9db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTA1MzksIm5iZiI6MTcyMzE5MDIzOSwicGF0aCI6Ii81MzA3MjYzMy8zNTY1MTMyODMtZDc4YTk4OWQtNDRhNy00MDg5LWFhNDMtOWZhNzM0YmFjOWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDA3NTcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkY2Y5OTgwZDdjM2I0MjczMjcxOWY1YzAzMWQxYzY0NjdmYTYyOTYyMDE5NDc5NGZkZmVhMGU2MTZhMWVlOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FSgXKDDG2SLXkOrXDBGL8oTledUmou6z8jDcZSM6KZ8)

我们的文档使用katex语法，可能跟markdown的里的渲染结果有一定的区别，我看应该是吧 `$ P` 中间的空格删掉就行了，可以按照教程：https://paddlescience-docs.readthedocs.io/zh-cn/latest/zh/development/#3，预览下文档页面是否正确，

2024-08-09 08:35 UTC, niushao12 commented
> > > ![image](https://private-user-images.githubusercontent.com/176906342/356441532-a24be11b-849b-441c-95f8-0532b59ab204.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTAzNTEsIm5iZiI6MTcyMzE5MDA1MSwicGF0aCI6Ii8xNzY5MDYzNDIvMzU2NDQxNTMyLWEyNGJlMTFiLTg0OWItNDQxYy05NWY4LTA1MzJiNTlhYjIwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQwNzU0MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTRkODM5ZDQ5OGQxY2QxODg5YjBmYjA0NjFkNGZhNmY0MTA2Y2RmYWU3MDIwYzdiOTM5MjkxY2Y5NTE0ZTFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FxCpzuxKu-DhhlPGdVgIj50jp00CSRnkLbJserXYqC8) 这里缺失代码 ![image](https://private-user-images.githubusercontent.com/176906342/356442146-49d312df-31b2-43cf-9b64-8d75c2f9ba32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTAzNTEsIm5iZiI6MTcyMzE5MDA1MSwicGF0aCI6Ii8xNzY5MDYzNDIvMzU2NDQyMTQ2LTQ5ZDMxMmRmLTMxYjItNDNjZi05YjY0LThkNzVjMmY5YmEzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQwNzU0MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZmJlZDIxMmYyNWI4Nzk1NjEwNjRjOGIwOTVkYjk0NjgxYjdkZjAwNTNhOTA5MTI1NTU4MzNmZTA3YmE4ZTYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4H5im-B8W8ByDnyNbYAMa8kegCt4T2ERcwfRrwD3Mfc) 这里乱码了 ![截屏2024-08-09 10 36 26](https://private-user-images.githubusercontent.com/176906342/356441721-170155e0-5d7c-4515-beb3-1239ba5505e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTAzNTEsIm5iZiI6MTcyMzE5MDA1MSwicGF0aCI6Ii8xNzY5MDYzNDIvMzU2NDQxNzIxLTE3MDE1NWUwLTVkN2MtNDUxNS1iZWIzLTEyMzliYTU1MDVlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQwNzU0MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMmQ0MWVjYzJlMTczMTg2MTA0NTQ2OWZlZGY0NzczNWI4MTA3Y2RhNzIxNDI3MGM0NDQ5ZGU4YzUzYjExYjg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5Fbx4INUf7xUc-9jGglPIf_cMiSkyVX7M07NfTslXeY) ![image](https://private-user-images.githubusercontent.com/176906342/356441869-7ad80f88-f9ec-4c73-ba30-38bfa7258efd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTAzNTEsIm5iZiI6MTcyMzE5MDA1MSwicGF0aCI6Ii8xNzY5MDYzNDIvMzU2NDQxODY5LTdhZDgwZjg4LWY5ZWMtNGM3My1iYTMwLTM4YmZhNzI1OGVmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQwNzU0MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yN2IzNTUzYjliMWJjMjk5OGZjY2VlNDc4MGM3ZjRhNWYyMTJlOTFiMjU0ZWM3OWY2MmI4YWNhMDYxNmRiMWQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qTYlWVvGIKCfbtENfJWYbRPLc0dDXhidMRJx-0Ix1qM) 文档多个代码的部分，添加了额外的信息，麻烦再检查一下
> > > 另外还想问一下，之前基于预训练的模型，我记得是会生成分子结构的，包括会有输出的图片，我在运行test_generate.py的时候，并没有看到生成的分子结构的输出
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/53072633/356512791-0c5e51c5-e3cf-4d92-9663-4caf85e43f1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTA1MzksIm5iZiI6MTcyMzE5MDIzOSwicGF0aCI6Ii81MzA3MjYzMy8zNTY1MTI3OTEtMGM1ZTUxYzUtZTNjZi00ZDkyLTk2NjMtNGNhZjg1ZTQzZjFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDA3NTcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1YTYyYThmNTVkMDM1Y2E5M2M5NTc0NGU5Y2E5ODFkZGE0MWQ0MDM2M2E2NzdjMWZlNzQzZTdlN2UyNzNlNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AW6AWBBSaZWeSpbnT85C5DZQpj8PrZF844S-ExCFAqs) 这个公式乱码的我这边是正常的，是因为不支持这个字体么？ ![image](https://private-user-images.githubusercontent.com/53072633/356513283-d78a989d-44a7-4089-aa43-9fa734bac9db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTA1MzksIm5iZiI6MTcyMzE5MDIzOSwicGF0aCI6Ii81MzA3MjYzMy8zNTY1MTMyODMtZDc4YTk4OWQtNDRhNy00MDg5LWFhNDMtOWZhNzM0YmFjOWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDA3NTcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkY2Y5OTgwZDdjM2I0MjczMjcxOWY1YzAzMWQxYzY0NjdmYTYyOTYyMDE5NDc5NGZkZmVhMGU2MTZhMWVlOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FSgXKDDG2SLXkOrXDBGL8oTledUmou6z8jDcZSM6KZ8)
> 
> 我们的文档使用katex语法，可能跟markdown的里的渲染结果有一定的区别，我看应该是吧 `$ P` 中间的空格删掉就行了，可以按照教程：https://paddlescience-docs.readthedocs.io/zh-cn/latest/zh/development/#3，预览下文档页面是否正确，

修改后没有，我这边检查修改了所有文档问题，网页预览没有问题了

2024-08-10 00:16 UTC, HydrogenSulfate requested changes

2024-08-10 00:16 UTC, HydrogenSulfate commented on ppsci/arch/moflow_basic.py
> +            default_initializer=nn.initializer.ConstantInitializer(value=0.0),
ConstantInitializer-->Constant，请全局检查一下

2024-08-13 11:34 UTC, leeleolay commented
> > > > ![image](https://private-user-images.githubusercontent.com/176906342/356441532-a24be11b-849b-441c-95f8-0532b59ab204.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTAzNTEsIm5iZiI6MTcyMzE5MDA1MSwicGF0aCI6Ii8xNzY5MDYzNDIvMzU2NDQxNTMyLWEyNGJlMTFiLTg0OWItNDQxYy05NWY4LTA1MzJiNTlhYjIwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQwNzU0MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTRkODM5ZDQ5OGQxY2QxODg5YjBmYjA0NjFkNGZhNmY0MTA2Y2RmYWU3MDIwYzdiOTM5MjkxY2Y5NTE0ZTFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FxCpzuxKu-DhhlPGdVgIj50jp00CSRnkLbJserXYqC8) 这里缺失代码 ![image](https://private-user-images.githubusercontent.com/176906342/356442146-49d312df-31b2-43cf-9b64-8d75c2f9ba32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTAzNTEsIm5iZiI6MTcyMzE5MDA1MSwicGF0aCI6Ii8xNzY5MDYzNDIvMzU2NDQyMTQ2LTQ5ZDMxMmRmLTMxYjItNDNjZi05YjY0LThkNzVjMmY5YmEzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQwNzU0MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZmJlZDIxMmYyNWI4Nzk1NjEwNjRjOGIwOTVkYjk0NjgxYjdkZjAwNTNhOTA5MTI1NTU4MzNmZTA3YmE4ZTYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4H5im-B8W8ByDnyNbYAMa8kegCt4T2ERcwfRrwD3Mfc) 这里乱码了 ![截屏2024-08-09 10 36 26](https://private-user-images.githubusercontent.com/176906342/356441721-170155e0-5d7c-4515-beb3-1239ba5505e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTAzNTEsIm5iZiI6MTcyMzE5MDA1MSwicGF0aCI6Ii8xNzY5MDYzNDIvMzU2NDQxNzIxLTE3MDE1NWUwLTVkN2MtNDUxNS1iZWIzLTEyMzliYTU1MDVlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQwNzU0MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMmQ0MWVjYzJlMTczMTg2MTA0NTQ2OWZlZGY0NzczNWI4MTA3Y2RhNzIxNDI3MGM0NDQ5ZGU4YzUzYjExYjg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5Fbx4INUf7xUc-9jGglPIf_cMiSkyVX7M07NfTslXeY) ![image](https://private-user-images.githubusercontent.com/176906342/356441869-7ad80f88-f9ec-4c73-ba30-38bfa7258efd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTAzNTEsIm5iZiI6MTcyMzE5MDA1MSwicGF0aCI6Ii8xNzY5MDYzNDIvMzU2NDQxODY5LTdhZDgwZjg4LWY5ZWMtNGM3My1iYTMwLTM4YmZhNzI1OGVmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQwNzU0MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yN2IzNTUzYjliMWJjMjk5OGZjY2VlNDc4MGM3ZjRhNWYyMTJlOTFiMjU0ZWM3OWY2MmI4YWNhMDYxNmRiMWQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qTYlWVvGIKCfbtENfJWYbRPLc0dDXhidMRJx-0Ix1qM) 文档多个代码的部分，添加了额外的信息，麻烦再检查一下
> > > > 另外还想问一下，之前基于预训练的模型，我记得是会生成分子结构的，包括会有输出的图片，我在运行test_generate.py的时候，并没有看到生成的分子结构的输出
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/53072633/356512791-0c5e51c5-e3cf-4d92-9663-4caf85e43f1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTA1MzksIm5iZiI6MTcyMzE5MDIzOSwicGF0aCI6Ii81MzA3MjYzMy8zNTY1MTI3OTEtMGM1ZTUxYzUtZTNjZi00ZDkyLTk2NjMtNGNhZjg1ZTQzZjFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDA3NTcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1YTYyYThmNTVkMDM1Y2E5M2M5NTc0NGU5Y2E5ODFkZGE0MWQ0MDM2M2E2NzdjMWZlNzQzZTdlN2UyNzNlNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AW6AWBBSaZWeSpbnT85C5DZQpj8PrZF844S-ExCFAqs) 这个公式乱码的我这边是正常的，是因为不支持这个字体么？ ![image](https://private-user-images.githubusercontent.com/53072633/356513283-d78a989d-44a7-4089-aa43-9fa734bac9db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTA1MzksIm5iZiI6MTcyMzE5MDIzOSwicGF0aCI6Ii81MzA3MjYzMy8zNTY1MTMyODMtZDc4YTk4OWQtNDRhNy00MDg5LWFhNDMtOWZhNzM0YmFjOWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDA3NTcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkY2Y5OTgwZDdjM2I0MjczMjcxOWY1YzAzMWQxYzY0NjdmYTYyOTYyMDE5NDc5NGZkZmVhMGU2MTZhMWVlOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FSgXKDDG2SLXkOrXDBGL8oTledUmou6z8jDcZSM6KZ8)
> > 
> > 
> > 我们的文档使用katex语法，可能跟markdown的里的渲染结果有一定的区别，我看应该是吧 `$ P` 中间的空格删掉就行了，可以按照教程：[https://paddlescience-docs.readthedocs.io/zh-cn/latest/zh/development/#3，预览下文档页面是否正确，](https://paddlescience-docs.readthedocs.io/zh-cn/latest/zh/development/#3%EF%BC%8C%E9%A2%84%E8%A7%88%E4%B8%8B%E6%96%87%E6%A1%A3%E9%A1%B5%E9%9D%A2%E6%98%AF%E5%90%A6%E6%AD%A3%E7%A1%AE%EF%BC%8C)
> 
> 修改后没有，我这边检查修改了所有文档问题，网页预览没有问题了，要是需要生成分子照片的话，EVAL_mode参数选择nter2point或者Intergrid可以可视化显示图片或者pdf

辛苦在文档里标注说明一下

2024-08-13 11:44 UTC, HydrogenSulfate commented
> [![CLA assistant check](https://camo.githubusercontent.com/fbf2b4a56b8f8dacb3fb4f7f3cf7877b8c27f9cfee8546ff24c8df94facca0f6/68747470733a2f2f636c612d617373697374616e742e696f2f70756c6c2f62616467652f6e6f745f7369676e6564)](https://cla-assistant.io/PaddlePaddle/PaddleScience?pullRequest=962) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleScience?pullRequest=962) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleScience?pullRequest=962) it.

@niushao12 签署一下CLA协议

2024-08-16 05:47 UTC, leeleolay commented
<img width="813" alt="image" src="https://github.com/user-attachments/assets/7c481653-e78c-46f0-802e-4129f01eb1b2">


<img width="921" alt="image" src="https://github.com/user-attachments/assets/2bb510a6-d994-4416-9508-aa4c0745768b">
运行这条命令会报错，辛苦再看一下吧python test_generate.py data_name=qm9 EVAL_mode=Inter2point EVAL.pretrained_model_path=https://paddle-org.bj.bcebos.com/paddlescience/models/MoFlow/qm9/qed_pretrained.pdparams

2024-08-16 08:22 UTC, niushao12 commented
> qed_pretrained
这个应该是预训练模型的问题，上传模型的时候一个qm9的数据集我上传了两个，我不知道qed_pretrained是使用qed_model修改的，还是latest修改的， 如果是后者是不会报错的，文档中的说明修改了。

2024-08-16 08:45 UTC, HydrogenSulfate commented
> > qed_pretrained
> > 这个应该是预训练模型的问题，上传模型的时候一个qm9的数据集我上传了两个，我不知道qed_pretrained是使用qed_model修改的，还是latest修改的， 如果是后者是不会报错的，文档中的说明修改了。

qm9，zinc250k这两个数据集的区别是什么呢，zinc250k文件夹下是有两个模型参数文件，这两个都需要还是有一个是多余的？
![Uploading image.png…]()

2024-08-19 01:16 UTC, niushao12 commented
> > > qed_pretrained
> > > 这个应该是预训练模型的问题，上传模型的时候一个qm9的数据集我上传了两个，我不知道qed_pretrained是使用qed_model修改的，还是latest修改的， 如果是后者是不会报错的，文档中的说明修改了。
> 
> qm9，zinc250k这两个数据集的区别是什么呢，zinc250k文件夹下是有两个模型参数文件，这两个都需要还是有一个是多余的？ ![image](https://private-user-images.githubusercontent.com/23737287/358525254-0e1e0a87-366c-4c58-b955-459ff9423509.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwMjk3NjgsIm5iZiI6MTcyNDAyOTQ2OCwicGF0aCI6Ii8yMzczNzI4Ny8zNTg1MjUyNTQtMGUxZTBhODctMzY2Yy00YzU4LWI5NTUtNDU5ZmY5NDIzNTA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDAxMDQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlOWVlYWU1MzhhZWFkZjBmMGY1YjhiYjVjZDkzZjdkMzE0ZGU3YzhmNThiZTFhYWE5ZGUwMGQyMmFkYzRiZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TzEbPhYq170JG4itEe_lNft92PmYe-1yW6TmbjpwAzE)



> > > qed_pretrained
> > > 这个应该是预训练模型的问题，上传模型的时候一个qm9的数据集我上传了两个，我不知道qed_pretrained是使用qed_model修改的，还是latest修改的， 如果是后者是不会报错的，文档中的说明修改了。
> 
> qm9，zinc250k这两个数据集的区别是什么呢，zinc250k文件夹下是有两个模型参数文件，这两个都需要还是有一个是多余的？ ![image](https://private-user-images.githubusercontent.com/23737287/358525254-0e1e0a87-366c-4c58-b955-459ff9423509.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwMjk3NjgsIm5iZiI6MTcyNDAyOTQ2OCwicGF0aCI6Ii8yMzczNzI4Ny8zNTg1MjUyNTQtMGUxZTBhODctMzY2Yy00YzU4LWI5NTUtNDU5ZmY5NDIzNTA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDAxMDQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlOWVlYWU1MzhhZWFkZjBmMGY1YjhiYjVjZDkzZjdkMzE0ZGU3YzhmNThiZTFhYWE5ZGUwMGQyMmFkYzRiZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TzEbPhYq170JG4itEe_lNft92PmYe-1yW6TmbjpwAzE)

这两个数据集都是小分子数据集，是两个不同的化学结构数据集，用于药物设计和发现，QM9和Zinc250k都具有分子结结构信息，两个主要区别是分子特性参数不同，因此处理的时候也不相同。M9数据集更加专注于药物设计和材料科学，而Zinc250k数据集更加专注于高通量化学合成和小分子结构优化。qed_model.pdparams是optimize_moflow.py中增加优化网络MLP重新训练了一个模型，是基于latest.pdparams增加了MLP网络参数，训练的速度很快。latest.pdparams才是预训练模型。

2024-08-19 02:45 UTC, HydrogenSulfate commented on examples/moflow/optimize_moflow.py
> +    ppsci.utils.save_load.load_pretrain(model, path=cfg.EVAL.pretrained_model_path)
```suggestion
    ppsci.utils.save_load.load_pretrain(model, path=cfg.TRAIN.pretrained_model_path)
```

2024-08-19 02:45 UTC, HydrogenSulfate commented on docs/zh/examples/moflow.md
> +    python optimize_moflow.py data_name=zinc250k  EVAL.pretrained_model_path=https://paddle-org.bj.bcebos.com/paddlescience/models/MoFlow/zinc250k/zinc250k_pretrained.pdparams
```suggestion
    python optimize_moflow.py data_name=zinc250k  TRAIN.pretrained_model_path=https://paddle-org.bj.bcebos.com/paddlescience/models/MoFlow/zinc250k/zinc250k_pretrained.pdparams
```

2024-08-19 07:25 UTC, leeleolay commented
我这里使用原先的预训练模型进行评估是没有问题的。 建议在docs/zh/examples/moflow.md文件里，添加模型推理评估命令的四种模式的说明（Reconstruct/Random/Inter2point/Intergrid），以及在该文档里添加好两个数据集QM9和Zinc250k各自对应的预训练模型，以及优化后的模型。另外想问一下，优化后产生的qed模型，在推理阶段中的哪些模式是可以使用的？这部分的解释说明也可以添加在moflow.md里。@niushao12
以上问题修改完后建议可以合入repo。@HydrogenSulfate

2024-08-19 08:13 UTC, niushao12 commented
> 我这里使用原先的预训练模型进行评估是没有问题的。 建议在docs/zh/examples/moflow.md文件里，添加模型推理评估命令的四种模式的说明（Reconstruct/Random/Inter2point/Intergrid），以及在该文档里添加好两个数据集QM9和Zinc250k各自对应的预训练模型，以及优化后的模型。另外想问一下，优化后产生的qed模型，在推理阶段中的哪些模式是可以使用的？这部分的解释说明也可以添加在moflow.md里。@niushao12 以上问题修改完后建议可以合入repo。@HydrogenSulfate

说明已经在docs/zh/examples/moflow.md中添加，参数文件中也添加了，优化模型除了qed模型，还有plogp模型，也增加了相关说明，首次运行优化程序的产生qed模型或者plogp模型，在第二次运行的时候将对优化后的模型进行评估。即在优化模型训练完成之后再运行优化程序的时候使用。

2024-08-19 08:33 UTC, leeleolay commented
> > 我这里使用原先的预训练模型进行评估是没有问题的。 建议在docs/zh/examples/moflow.md文件里，添加模型推理评估命令的四种模式的说明（Reconstruct/Random/Inter2point/Intergrid），以及在该文档里添加好两个数据集QM9和Zinc250k各自对应的预训练模型，以及优化后的模型。另外想问一下，优化后产生的qed模型，在推理阶段中的哪些模式是可以使用的？这部分的解释说明也可以添加在moflow.md里。@niushao12 以上问题修改完后建议可以合入repo。@HydrogenSulfate
> 
> 说明已经在docs/zh/examples/moflow.md中添加，参数文件中也添加了，优化模型除了qed模型，还有plogp模型，也增加了相关说明，首次运行优化程序的产生qed模型或者plogp模型，在第二次运行的时候将对优化后的模型进行评估。即在优化模型训练完成之后再运行优化程序的时候使用。
<img width="1439" alt="image" src="https://github.com/user-attachments/assets/3f273bd1-2640-4f83-8ddb-6aac2a1ea2b9">
运行test_generate.py时的warning麻烦再修改一下吧。另外优化后的plogp这个模型是否有上传？

2024-08-19 08:50 UTC, niushao12 commented
> > > 我这里使用原先的预训练模型进行评估是没有问题的。 建议在docs/zh/examples/moflow.md文件里，添加模型推理评估命令的四种模式的说明（Reconstruct/Random/Inter2point/Intergrid），以及在该文档里添加好两个数据集QM9和Zinc250k各自对应的预训练模型，以及优化后的模型。另外想问一下，优化后产生的qed模型，在推理阶段中的哪些模式是可以使用的？这部分的解释说明也可以添加在moflow.md里。@niushao12 以上问题修改完后建议可以合入repo。@HydrogenSulfate
> > 
> > 
> > 说明已经在docs/zh/examples/moflow.md中添加，参数文件中也添加了，优化模型除了qed模型，还有plogp模型，也增加了相关说明，首次运行优化程序的产生qed模型或者plogp模型，在第二次运行的时候将对优化后的模型进行评估。即在优化模型训练完成之后再运行优化程序的时候使用。
> 
> <img alt="image" width="1439" src="https://private-user-images.githubusercontent.com/50223303/359035649-3f273bd1-2640-4f83-8ddb-6aac2a1ea2b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNTY3ODksIm5iZiI6MTcyNDA1NjQ4OSwicGF0aCI6Ii81MDIyMzMwMy8zNTkwMzU2NDktM2YyNzNiZDEtMjY0MC00ZjgzLThkZGItNmFhYzJhMWVhMmI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDA4MzQ0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkMzQyMDRlY2IyN2NhY2MwNTBmMmEyNGUwNzcwZjIxM2I4YmNlNGQ5NDcxMDIwMTgxYTY2NDYzNTI3M2VmZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TxDOVeQtPgafRyj2dcFU-XRb3LJvRddzc9gLtzgOqdk"> 运行test_generate.py时的warning麻烦再修改一下吧。另外优化后的plogp这个模型是否有上传？

qed模型和plogp模型不是运行test_generate.py的时候用的，是在运行

> > > 我这里使用原先的预训练模型进行评估是没有问题的。 建议在docs/zh/examples/moflow.md文件里，添加模型推理评估命令的四种模式的说明（Reconstruct/Random/Inter2point/Intergrid），以及在该文档里添加好两个数据集QM9和Zinc250k各自对应的预训练模型，以及优化后的模型。另外想问一下，优化后产生的qed模型，在推理阶段中的哪些模式是可以使用的？这部分的解释说明也可以添加在moflow.md里。@niushao12 以上问题修改完后建议可以合入repo。@HydrogenSulfate
> > 
> > 
> > 说明已经在docs/zh/examples/moflow.md中添加，参数文件中也添加了，优化模型除了qed模型，还有plogp模型，也增加了相关说明，首次运行优化程序的产生qed模型或者plogp模型，在第二次运行的时候将对优化后的模型进行评估。即在优化模型训练完成之后再运行优化程序的时候使用。
> 
> <img alt="image" width="1439" src="https://private-user-images.githubusercontent.com/50223303/359035649-3f273bd1-2640-4f83-8ddb-6aac2a1ea2b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNTY3ODksIm5iZiI6MTcyNDA1NjQ4OSwicGF0aCI6Ii81MDIyMzMwMy8zNTkwMzU2NDktM2YyNzNiZDEtMjY0MC00ZjgzLThkZGItNmFhYzJhMWVhMmI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDA4MzQ0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkMzQyMDRlY2IyN2NhY2MwNTBmMmEyNGUwNzcwZjIxM2I4YmNlNGQ5NDcxMDIwMTgxYTY2NDYzNTI3M2VmZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TxDOVeQtPgafRyj2dcFU-XRb3LJvRddzc9gLtzgOqdk"> 运行test_generate.py时的warning麻烦再修改一下吧。另外优化后的plogp这个模型是否有上传？



> > > 我这里使用原先的预训练模型进行评估是没有问题的。 建议在docs/zh/examples/moflow.md文件里，添加模型推理评估命令的四种模式的说明（Reconstruct/Random/Inter2point/Intergrid），以及在该文档里添加好两个数据集QM9和Zinc250k各自对应的预训练模型，以及优化后的模型。另外想问一下，优化后产生的qed模型，在推理阶段中的哪些模式是可以使用的？这部分的解释说明也可以添加在moflow.md里。@niushao12 以上问题修改完后建议可以合入repo。@HydrogenSulfate
> > 
> > 
> > 说明已经在docs/zh/examples/moflow.md中添加，参数文件中也添加了，优化模型除了qed模型，还有plogp模型，也增加了相关说明，首次运行优化程序的产生qed模型或者plogp模型，在第二次运行的时候将对优化后的模型进行评估。即在优化模型训练完成之后再运行优化程序的时候使用。
> 
> <img alt="image" width="1439" src="https://private-user-images.githubusercontent.com/50223303/359035649-3f273bd1-2640-4f83-8ddb-6aac2a1ea2b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNTY5NDYsIm5iZiI6MTcyNDA1NjY0NiwicGF0aCI6Ii81MDIyMzMwMy8zNTkwMzU2NDktM2YyNzNiZDEtMjY0MC00ZjgzLThkZGItNmFhYzJhMWVhMmI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDA4MzcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwMzg1ZWI3MDJlZjhiMDk1MDY3MGU2ZTIwZTBiMWYwNmI2MGM1ZWUzZDgzM2E2ZWZkNmZlZjliZjA5OWFkOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iwOnIjd5QCpPs8xIWsTg7QaS_DsJtQEwmU7-KbwHjJE"> 运行test_generate.py时的warning麻烦再修改一下吧。另外优化后的plogp这个模型是否有上传？

optimize_moflow.pyoptimize_moflow.py

> > > 我这里使用原先的预训练模型进行评估是没有问题的。 建议在docs/zh/examples/moflow.md文件里，添加模型推理评估命令的四种模式的说明（Reconstruct/Random/Inter2point/Intergrid），以及在该文档里添加好两个数据集QM9和Zinc250k各自对应的预训练模型，以及优化后的模型。另外想问一下，优化后产生的qed模型，在推理阶段中的哪些模式是可以使用的？这部分的解释说明也可以添加在moflow.md里。@niushao12 以上问题修改完后建议可以合入repo。@HydrogenSulfate
> > 
> > 
> > 说明已经在docs/zh/examples/moflow.md中添加，参数文件中也添加了，优化模型除了qed模型，还有plogp模型，也增加了相关说明，首次运行优化程序的产生qed模型或者plogp模型，在第二次运行的时候将对优化后的模型进行评估。即在优化模型训练完成之后再运行优化程序的时候使用。
> 
> <img alt="image" width="1439" src="https://private-user-images.githubusercontent.com/50223303/359035649-3f273bd1-2640-4f83-8ddb-6aac2a1ea2b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNTY5NzUsIm5iZiI6MTcyNDA1NjY3NSwicGF0aCI6Ii81MDIyMzMwMy8zNTkwMzU2NDktM2YyNzNiZDEtMjY0MC00ZjgzLThkZGItNmFhYzJhMWVhMmI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDA4Mzc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNjhmYTJlMzhiOWFkNjdhMjRhMGFkNjc1NWQ2Y2QxYjRlNDdkZGU1ZGQ3ZDFhMzZlYWQwZDNhNDc4OGYwNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VCFSrL_YZhvCZJzddh_gJORpbZ33Y8aR4aTN7yzo8iU"> 运行test_generate.py时的warning麻烦再修改一下吧。另外优化后的plogp这个模型是否有上传？

这个还是模型报错的，预训练模型我这边修改不了，optimize_moflow.py运行的时候会对预训练模型进行优化，选择qed和plogp模式就行，第二次运行optimize_moflow.py就能加载优化后的模型，我这边不建议在上传优化模型了，优化模型不到五分钟就优化训练完成了，没有必要再上传吧，之前上传的我建议删除了，这样保证都是预训练模型不会出现模型混用的报错。

2024-08-20 07:06 UTC, HydrogenSulfate approved these changes
LGTM

2024-08-20 07:06 UTC, merged

2024-08-21 03:59 UTC, luotao1 commented
hi, @niushao12 
- 非常感谢你对飞桨的贡献，我们正在运营一个PFCC组织，会通过定期分享技术知识与发布开发者主导任务的形式持续为飞桨做贡献，详情可见 https://github.com/luotao1 主页说明。
- 如果你对PFCC有兴趣，请发送邮件至 [ext_paddle_oss@baidu.com](mailto:ext_paddle_oss@baidu.com)，我们会邀请你加入~