velocitygan demo1
PaddlePaddle/PaddleScience pull request #981
Opened 2024-08-26 05:06 UTC by 9zdq

### PR types

New features
### PR changes

Docs
### Describe

增加了一个新的example, velocityGAN。

2024-08-26 05:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleScience?pullRequest=981) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleScience?pullRequest=981) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleScience?pullRequest=981) it.</sub>

2024-08-26 07:45 UTC, HydrogenSulfate requested changes
感谢提交PR，以下是代码方面的review意见

2024-08-26 07:45 UTC, HydrogenSulfate commented on examples/velocityGAN/conf/velocityGAN.yaml
> +    subdir: ./
```suggestion
defaults:
  - ppsci_default
  - TRAIN: train_default
  - TRAIN/ema: ema_default
  - TRAIN/swa: swa_default
  - EVAL: eval_default
  - INFER: infer_default
  - hydra/job/config/override_dirname/exclude_keys: exclude_keys_default
  - _self_

hydra:
  run:
    # dynamic output directory according to running time and override name
    dir: outputs_VIV/${now:%Y-%m-%d}/${now:%H-%M-%S}/${hydra.job.override_dirname} #
  job:
    name: ${mode} # name of logfile
    chdir: false # keep current working directory unchanged
  sweep:
    # output directory for multirun
    dir: ${hydra.run.dir}
    subdir: ./

```

2024-08-26 07:45 UTC, HydrogenSulfate commented on examples/velocityGAN/conf/velocityGAN.yaml
请将配置文件中出现的多个连续换行删除至保留一个即可

2024-08-26 07:45 UTC, HydrogenSulfate commented on docs/zh/examples/velocity_gan.md
请将文档中的多个连续换行删除至保留一个即可

2024-08-26 07:45 UTC, HydrogenSulfate commented on docs/zh/examples/velocity_gan.md
> +![image-20240825160034203](VelocityGAN/image-20240825160034203.png)
这个图片可以上传到本PR里吗，我下载过来上传到bce上

2024-08-26 07:45 UTC, HydrogenSulfate commented on docs/zh/examples/velocity_gan.md
> +|            | MAE: 0.0669<br>PSNR: 0.0947<br>SSIM: 0.8511 |
预训练模型同样可以上传到PR里，我下载后上传到bce上再贴到这个PR中

2024-08-26 07:45 UTC, HydrogenSulfate commented on docs/zh/examples/velocity_gan.md
> +
在预训练模型表格的上方补充一下模型的训练命令，以及基于预训练模型的精度评估命令吧，如下所示：
![image](https://github.com/user-attachments/assets/7c4d4f9b-182e-4b51-bff9-3ca589ccbe20)

2024-08-26 07:45 UTC, HydrogenSulfate commented on docs/zh/examples/velocity_gan.md
> +```
这类代码建议使用如下固定代码引用格式，这样文档在渲染的时候会直接引用vlocitygan.py里的指定代码块，否则需要维护两份代码。https://github.com/PaddlePaddle/PaddleScience/blob/12a3f26b815eb74c1518c2d83db358b423238ba0/docs/zh/examples/allen_cahn.md?plain=1#L94-L100

这个修改工作可以在代码review完成的最后进行，减少代码格式改动而频繁修改代码块起始终止位置

2024-08-26 07:45 UTC, HydrogenSulfate commented on docs/zh/examples/velocity_gan.md
> +![](VelocityGAN.assets/V_6_0.jpg)
同理，图片上传到这个PR里

2024-08-26 07:45 UTC, HydrogenSulfate commented on examples/velocityGAN/conf/velocityGAN.yaml
配置文件内每一行的末尾冗余的井号"#"可以删除

2024-08-26 07:45 UTC, HydrogenSulfate commented on examples/velocityGAN/flatvel_a_train.txt
是否可以改为相对路径？假设当前代码运行时所在路径为`examples/velocityGAN/`

2024-08-26 07:45 UTC, HydrogenSulfate commented on examples/velocityGAN/flatvel_a_val.txt
同理，是否可以改为相对路径

2024-08-26 07:45 UTC, HydrogenSulfate commented on examples/velocityGAN/functions.py
> +class MinMaxNormalize(object):
python3的类已经不需要手动从object继承，可以删除

```suggestion
class MinMaxNormalize:

```

2024-08-26 07:45 UTC, HydrogenSulfate commented on examples/velocityGAN/functions.py
> +class LogTransform(object):
同理删除
```suggestion
class LogTransform:

```

2024-08-26 07:45 UTC, HydrogenSulfate commented on examples/velocityGAN/functions.py
> +    return (vid - 0.5) * 2 if scale == 2 else vid
如果这个函数只有对应类内用到了，可以移动到类内，作为类方法

2024-08-26 07:45 UTC, HydrogenSulfate commented on examples/velocityGAN/functions.py
> +    return np.log1p(np.abs(k * data) + c) * np.sign(data)
如果这个函数只有对应类内用到了，可以移动到类内，作为类方法

2024-08-26 07:45 UTC, HydrogenSulfate commented on examples/velocityGAN/functions.py
> +            ),
在paddle里如果grad_outputs是全1的，则可以省略不写。

2024-08-26 07:45 UTC, HydrogenSulfate commented on examples/velocityGAN/functions.py
> +
函数名下方的多余空行可以删除

2024-08-26 07:45 UTC, HydrogenSulfate commented on examples/velocityGAN/velocityGAN.py
> +        },
shuffle和drop_last都是False时，sampler字段可以删除

2024-08-26 07:45 UTC, HydrogenSulfate commented on examples/velocityGAN/velocityGAN.py
> +        "use_shared_memory": True,  # True的时候出现错误
如果设置use_shared_memory=True会出现报错的话，麻烦把报错信息贴到本PR里，我们内部看一下具体原因

2024-08-26 07:45 UTC, HydrogenSulfate commented on examples/velocityGAN/velocityGAN.py
> +    solver.eval()
```suggestion
    # initialize solver
    solver = ppsci.solver.Solver(
        model=model_gen,
        validator=validator_dict,
        cfg=cfg,
    )
    solver.eval()

```

2024-08-26 07:45 UTC, HydrogenSulfate commented on examples/velocityGAN/velocityGAN.py
> +
配置文件开头加上defaults字段后可以删除这段代码

2024-08-26 07:45 UTC, HydrogenSulfate commented on examples/velocityGAN/velocityGAN.py
> +    paddle.save(model_gen.state_dict(), "model_gen.pdparams")
```suggestion
    paddle.save(model_gen.state_dict(), os.path.join(cfg.output_dir, "model_gen.pdparams"))

```

2024-08-26 07:45 UTC, HydrogenSulfate commented on ppsci/data/dataset/fwi_dataset.py
> +        transform_data|label: transformation applied to data or label
docstring有固定书写格式，这里分开写transform_data和transform_label，跟实际参数名保持一致

2024-08-26 07:45 UTC, HydrogenSulfate commented on ppsci/data/dataset/fwi_dataset.py
> +        file_size: # of samples in each npy file
句子开头大写

2024-08-26 07:47 UTC, HydrogenSulfate requested changes

2024-08-26 07:47 UTC, HydrogenSulfate commented on examples/velocityGAN/velocityGAN.py
typo: constraient --> constraint，请全文检查一下。

2024-08-26 07:49 UTC, HydrogenSulfate commented
@9zdq 提交代码前可以拉一下最新分支然后合并一下解决冲突

2024-09-19 08:47 UTC, 9zdq commented
感谢您提供的review建议，我已经修改好并提交了。

以下是对提交内容的补充：

- `velocity_gan.md`文档重新整理了一遍
  - 图片位于`examples/velocityGAN/velocity_gan.assets`
  - 预训练权重位于`examples/velocityGAN/velocitygan_pretrained.pdparams`
- `examples/velocityGAN/FWIOpenData`中的目录是用来存储数据集的
- 由于一份数据集包含多个文件，为了方便读取数据，这里将所有路径（相对路径）打包成一个文本文件，存储于`examples/velocityGAN/anno_files`
- `yaml`配置文件添加了`default`字段，并增加了更多的参数配置
- 规范了`examples/velocityGAN/velocityGAN.py`的参数调用
- `examples/velocityGAN`中的`functions.py`文件添加了注释，并规范了代码格式
- `fwi_dataset.py`修改了参数`weight`的处理逻辑（相当于不用这个参数了）；`weight`（各项损失的权重）在`functions.py`中的`class GenFuncs/DisFuncs `中调用

2024-09-20 03:45 UTC, HydrogenSulfate requested changes

2024-09-20 03:45 UTC, HydrogenSulfate commented on examples/velocityGAN/conf/velocityGAN.yaml
> +    drop_last: false
这个可以删掉吧，eval的sampler一般不会去更改，所以没有必要写到配置文件里

2024-09-20 03:45 UTC, HydrogenSulfate commented on docs/zh/examples/velocity_gan.md
> +|            | MAE: 0.0669<br>PSNR: 0.0947<br>SSIM: 0.8511 |
这里叫PSNR，但是文末叫RMSE，应该是RMSE吧？SSIM能到0.85，PSNR不太可能只有0.09？

2024-09-20 03:45 UTC, HydrogenSulfate commented on docs/zh/examples/velocity_gan.md
> +<a href="https://aistudio.baidu.com/projectdetail/7927786" class="md-button md-button--primary" style>AI Studio快速体验</a>
AIStudio链接注释掉

2024-09-20 03:56 UTC, HydrogenSulfate requested changes
`velocity_gan.assets`和`.pdparams`文件已经上传，可以把图片和权重文件从PR里删掉了。
https://paddle-org.bj.bcebos.com/paddlescience/docs/velocitygan/data.png
https://paddle-org.bj.bcebos.com/paddlescience/docs/velocitygan/fault_family.png
https://paddle-org.bj.bcebos.com/paddlescience/docs/velocitygan/flatvel_a_1.png
https://paddle-org.bj.bcebos.com/paddlescience/docs/velocitygan/flatvel_a_2.png
https://paddle-org.bj.bcebos.com/paddlescience/docs/velocitygan/sample.png
https://paddle-org.bj.bcebos.com/paddlescience/docs/velocitygan/vel_family.png
https://paddle-org.bj.bcebos.com/paddlescience/docs/velocitygan/velocityGAN.png
https://paddle-org.bj.bcebos.com/paddlescience/models/velocitygan/velocitygan_pretrained.pdparams

2024-09-20 03:56 UTC, HydrogenSulfate commented on ppsci/arch/velocitygan.py
> +class VelocityGenerator(base.Arch):
把VelocityGenerator和VelocityDiscriminator加到arch/__init__.py里

2024-09-20 09:15 UTC, 9zdq commented on examples/velocityGAN/conf/velocityGAN.yaml
> +    drop_last: false
嗯嗯，我已经删掉了，这两个参数的在代码中的调用也去掉了。

2024-09-20 09:15 UTC, 9zdq commented on docs/zh/examples/velocity_gan.md
> +|            | MAE: 0.0669<br>PSNR: 0.0947<br>SSIM: 0.8511 |
是的，是RMSE，我这里搞错了。（已修改）

2024-09-20 09:16 UTC, 9zdq commented on docs/zh/examples/velocity_gan.md
> +<a href="https://aistudio.baidu.com/projectdetail/7927786" class="md-button md-button--primary" style>AI Studio快速体验</a>
好的，已经删掉了。

2024-09-20 09:17 UTC, 9zdq commented on ppsci/arch/velocitygan.py
> +class VelocityGenerator(base.Arch):
好的，已经添加进去了。
并且把FWIDataset添加到对应__init__.py了。

2024-09-25 12:23 UTC, HydrogenSulfate approved these changes
LGTM

2024-09-25 12:24 UTC, merged

2024-09-27 10:19 UTC, luotao1 commented
hi, @zhudequan9 
- 非常感谢你对飞桨的贡献，我们正在运营一个PFCC组织，会通过定期分享技术知识与发布开发者主导任务的形式持续为飞桨做贡献，详情可见 https://github.com/luotao1 主页说明。
- 如果你对PFCC有兴趣，请发送邮件至 [ext_paddle_oss@baidu.com](mailto:ext_paddle_oss@baidu.com)，我们会邀请你加入~